Repository OCA/account-invoicing, pull requests merged in 2019-03, with the labels that each got.

#504 [ADD] purchase_invoice_no_zero_lines: avoid zero quantity lines in ac…
  purchase_invoicing_no_zero_line/__init__.py
  purchase_invoicing_no_zero_line/__manifest__.py
  purchase_invoicing_no_zero_line/i18n/es.po
  purchase_invoicing_no_zero_line/models/__init__.py
  purchase_invoicing_no_zero_line/models/account_invoice.py
  purchase_invoicing_no_zero_line/models/account_journal.py
  purchase_invoicing_no_zero_line/static/description/icon.png
  purchase_invoicing_no_zero_line/static/description/icon.svg
  purchase_invoicing_no_zero_line/views/account_view.xml
Labels: approved

#452 [12.0] [MIG] account_invoice_search_by_reference
  account_invoice_search_by_reference/README.rst
  account_invoice_search_by_reference/__init__.py
  account_invoice_search_by_reference/__manifest__.py
  account_invoice_search_by_reference/i18n/account_invoice_search_by_reference.pot
  account_invoice_search_by_reference/i18n/ar.po
  account_invoice_search_by_reference/i18n/bg.po
  account_invoice_search_by_reference/i18n/bs.po
  account_invoice_search_by_reference/i18n/ca.po
  account_invoice_search_by_reference/i18n/cs.po
  account_invoice_search_by_reference/i18n/de.po
  account_invoice_search_by_reference/i18n/el_GR.po
  account_invoice_search_by_reference/i18n/en_GB.po
  account_invoice_search_by_reference/i18n/es.po
  account_invoice_search_by_reference/i18n/es_CR.po
  account_invoice_search_by_reference/i18n/es_EC.po
  account_invoice_search_by_reference/i18n/es_ES.po
  account_invoice_search_by_reference/i18n/es_MX.po
  account_invoice_search_by_reference/i18n/es_PE.po
  account_invoice_search_by_reference/i18n/et.po
  account_invoice_search_by_reference/i18n/fi.po
  account_invoice_search_by_reference/i18n/fr.po
  account_invoice_search_by_reference/i18n/fr_CA.po
  account_invoice_search_by_reference/i18n/fr_CH.po
  account_invoice_search_by_reference/i18n/gl.po
  account_invoice_search_by_reference/i18n/hr.po
  account_invoice_search_by_reference/i18n/hr_HR.po
  account_invoice_search_by_reference/i18n/hu.po
  account_invoice_search_by_reference/i18n/id.po
  account_invoice_search_by_reference/i18n/it.po
  account_invoice_search_by_reference/i18n/ja.po
  account_invoice_search_by_reference/i18n/lt.po
  account_invoice_search_by_reference/i18n/mk.po
  account_invoice_search_by_reference/i18n/mn.po
  account_invoice_search_by_reference/i18n/nb.po
  account_invoice_search_by_reference/i18n/nb_NO.po
  account_invoice_search_by_reference/i18n/nl.po
  account_invoice_search_by_reference/i18n/nl_BE.po
  account_invoice_search_by_reference/i18n/nl_NL.po
  account_invoice_search_by_reference/i18n/pl.po
  account_invoice_search_by_reference/i18n/pt.po
  account_invoice_search_by_reference/i18n/pt_BR.po
  account_invoice_search_by_reference/i18n/pt_PT.po
  account_invoice_search_by_reference/i18n/ro.po
  account_invoice_search_by_reference/i18n/ru.po
  account_invoice_search_by_reference/i18n/sk_SK.po
  account_invoice_search_by_reference/i18n/sl.po
  account_invoice_search_by_reference/i18n/sv.po
  account_invoice_search_by_reference/i18n/th.po
  account_invoice_search_by_reference/i18n/tr.po
  account_invoice_search_by_reference/i18n/tr_TR.po
  account_invoice_search_by_reference/i18n/zh_CN.po
  account_invoice_search_by_reference/i18n/zh_TW.po
  account_invoice_search_by_reference/model/__init__.py
  account_invoice_search_by_reference/model/account_invoice.py
  account_invoice_search_by_reference/tests/__init__.py
  account_invoice_search_by_reference/tests/test_account_invoice_search_by_reference.py
Labels: approved

#465 [12.0] [MIG] account_invoice_fiscal_position_update
  account_invoice_fiscal_position_update/README.rst
  account_invoice_fiscal_position_update/__init__.py
  account_invoice_fiscal_position_update/__manifest__.py
  account_invoice_fiscal_position_update/i18n/account_invoice_fiscal_position_update.pot
  account_invoice_fiscal_position_update/i18n/ar.po
  account_invoice_fiscal_position_update/i18n/bg.po
  account_invoice_fiscal_position_update/i18n/bs.po
  account_invoice_fiscal_position_update/i18n/ca.po
  account_invoice_fiscal_position_update/i18n/cs.po
  account_invoice_fiscal_position_update/i18n/de.po
  account_invoice_fiscal_position_update/i18n/el_GR.po
  account_invoice_fiscal_position_update/i18n/en_GB.po
  account_invoice_fiscal_position_update/i18n/es.po
  account_invoice_fiscal_position_update/i18n/es_CR.po
  account_invoice_fiscal_position_update/i18n/es_EC.po
  account_invoice_fiscal_position_update/i18n/es_ES.po
  account_invoice_fiscal_position_update/i18n/es_MX.po
  account_invoice_fiscal_position_update/i18n/es_PE.po
  account_invoice_fiscal_position_update/i18n/et.po
  account_invoice_fiscal_position_update/i18n/fi.po
  account_invoice_fiscal_position_update/i18n/fr.po
  account_invoice_fiscal_position_update/i18n/fr_CA.po
  account_invoice_fiscal_position_update/i18n/fr_CH.po
  account_invoice_fiscal_position_update/i18n/gl.po
  account_invoice_fiscal_position_update/i18n/hr.po
  account_invoice_fiscal_position_update/i18n/hr_HR.po
  account_invoice_fiscal_position_update/i18n/hu.po
  account_invoice_fiscal_position_update/i18n/id.po
  account_invoice_fiscal_position_update/i18n/it.po
  account_invoice_fiscal_position_update/i18n/ja.po
  account_invoice_fiscal_position_update/i18n/lt.po
  account_invoice_fiscal_position_update/i18n/mk.po
  account_invoice_fiscal_position_update/i18n/mn.po
  account_invoice_fiscal_position_update/i18n/nb.po
  account_invoice_fiscal_position_update/i18n/nb_NO.po
  account_invoice_fiscal_position_update/i18n/nl.po
  account_invoice_fiscal_position_update/i18n/nl_BE.po
  account_invoice_fiscal_position_update/i18n/nl_NL.po
  account_invoice_fiscal_position_update/i18n/pl.po
  account_invoice_fiscal_position_update/i18n/pt.po
  account_invoice_fiscal_position_update/i18n/pt_BR.po
  account_invoice_fiscal_position_update/i18n/pt_PT.po
  account_invoice_fiscal_position_update/i18n/ro.po
  account_invoice_fiscal_position_update/i18n/ru.po
  account_invoice_fiscal_position_update/i18n/sk_SK.po
  account_invoice_fiscal_position_update/i18n/sl.po
  account_invoice_fiscal_position_update/i18n/sv.po
  account_invoice_fiscal_position_update/i18n/th.po
  account_invoice_fiscal_position_update/i18n/tr.po
  account_invoice_fiscal_position_update/i18n/tr_TR.po
  account_invoice_fiscal_position_update/i18n/zh_CN.po
  account_invoice_fiscal_position_update/i18n/zh_TW.po
  account_invoice_fiscal_position_update/models/__init__.py
  account_invoice_fiscal_position_update/models/account_invoice.py
  account_invoice_fiscal_position_update/readme/CONTRIBUTORS.rst
  account_invoice_fiscal_position_update/readme/DESCRIPTION.rst
  account_invoice_fiscal_position_update/readme/USAGE.rst
  account_invoice_fiscal_position_update/static/description/index.html
  account_invoice_fiscal_position_update/tests/__init__.py
  account_invoice_fiscal_position_update/tests/test_inv_fiscal_pos_update.py
Labels: needs review

#386 [IMP] account_invoice_merge: refactor invoice merging
  account_invoice_merge/__manifest__.py
  account_invoice_merge/models/__init__.py
  account_invoice_merge/models/account_invoice.py
  account_invoice_merge/models/account_invoice_line.py
  account_invoice_merge/tests/test_account_invoice_merge.py
Labels: approved

#371 [MIG][10.0]product_supplierinfo_for_customer_invoice
  product_customer_code_invoice/__init__.py
  product_customer_code_invoice/__manifest__.py
  product_customer_code_invoice/account_invoice.py
  product_customer_code_invoice/account_invoice_view.xml
  product_supplierinfo_for_customer_invoice/README.rst
  product_supplierinfo_for_customer_invoice/__init__.py
  product_supplierinfo_for_customer_invoice/__manifest__.py
  product_supplierinfo_for_customer_invoice/i18n/it.po
  product_supplierinfo_for_customer_invoice/i18n/product_supplierinfo_for_customer_invoice.pot
  product_supplierinfo_for_customer_invoice/models/__init__.py
  product_supplierinfo_for_customer_invoice/models/account_invoice.py
  product_supplierinfo_for_customer_invoice/views/account_invoice_view.xml
Labels: approved, needs review

#500 [10.0][FIX] account_invoice_triple_discount: Fix rounding
  account_invoice_triple_discount/__manifest__.py
  account_invoice_triple_discount/models/account_invoice.py
  account_invoice_triple_discount/tests/test_invoice_triple_discount.py
Labels: approved, ready to merge

#516 [11.0][FIX] account_payment_term_extension: Load data demo to fix test
  account_payment_term_extension/demo/account_demo.xml
Labels: approved
