Repository OCA/account-invoicing, pull requests merged in 2019-08, with the labels that each got.

#573 [FIX] bad display on invoices form
  account_invoice_pricelist/views/account_invoice_view.xml
Labels: approved, needs review

#568 [ADD] account_brand
  account_brand/README.rst
  account_brand/__init__.py
  account_brand/__manifest__.py
  account_brand/models/__init__.py
  account_brand/models/account_invoice.py
  account_brand/readme/CONFIGURE.rst
  account_brand/readme/CONTRIBUTORS.rst
  account_brand/readme/CREDITS.rst
  account_brand/readme/DESCRIPTION.rst
  account_brand/readme/USAGE.rst
  account_brand/static/description/icon.png
  account_brand/views/account_invoice.xml
  oca_dependencies.txt
Labels: approved, enhancement, needs review

#582 [UPD] Travis.yml
  .travis.yml
Labels: approved
