Repository OCA/account-invoicing, pull requests merged in 2019-01, with the labels that each got.

#473 [11.0][FIX] purchase_stock_picking_return_invoicing: Change buggy compute code
  purchase_stock_picking_return_invoicing/models/purchase_order.py
Labels: approved, needs review

#434 [12.0][MIG] account_invoice_force_number
  account_invoice_force_number/README.rst
  account_invoice_force_number/__init__.py
  account_invoice_force_number/__manifest__.py
  account_invoice_force_number/i18n/account_invoice_force_number.pot
  account_invoice_force_number/i18n/ar.po
  account_invoice_force_number/i18n/bg.po
  account_invoice_force_number/i18n/bs.po
  account_invoice_force_number/i18n/ca.po
  account_invoice_force_number/i18n/cs.po
  account_invoice_force_number/i18n/de.po
  account_invoice_force_number/i18n/el_GR.po
  account_invoice_force_number/i18n/en_GB.po
  account_invoice_force_number/i18n/es.po
  account_invoice_force_number/i18n/es_CR.po
  account_invoice_force_number/i18n/es_EC.po
  account_invoice_force_number/i18n/es_MX.po
  account_invoice_force_number/i18n/et.po
  account_invoice_force_number/i18n/fi.po
  account_invoice_force_number/i18n/fr.po
  account_invoice_force_number/i18n/fr_CH.po
  account_invoice_force_number/i18n/gl.po
  account_invoice_force_number/i18n/hr.po
  account_invoice_force_number/i18n/hr_HR.po
  account_invoice_force_number/i18n/id.po
  account_invoice_force_number/i18n/it.po
  account_invoice_force_number/i18n/ja.po
  account_invoice_force_number/i18n/lt.po
  account_invoice_force_number/i18n/mk.po
  account_invoice_force_number/i18n/mn.po
  account_invoice_force_number/i18n/nb_NO.po
  account_invoice_force_number/i18n/nl.po
  account_invoice_force_number/i18n/nl_BE.po
  account_invoice_force_number/i18n/pl.po
  account_invoice_force_number/i18n/pt.po
  account_invoice_force_number/i18n/pt_BR.po
  account_invoice_force_number/i18n/pt_PT.po
  account_invoice_force_number/i18n/ro.po
  account_invoice_force_number/i18n/ru.po
  account_invoice_force_number/i18n/sk_SK.po
  account_invoice_force_number/i18n/sl.po
  account_invoice_force_number/i18n/sv.po
  account_invoice_force_number/i18n/th.po
  account_invoice_force_number/i18n/tr.po
  account_invoice_force_number/i18n/tr_TR.po
  account_invoice_force_number/i18n/zh_CN.po
  account_invoice_force_number/i18n/zh_TW.po
  account_invoice_force_number/readme/CONFIGURE.rst
  account_invoice_force_number/readme/CONTRIBUTORS.rst
  account_invoice_force_number/readme/DESCRIPTION.rst
  account_invoice_force_number/readme/USAGE.rst
  account_invoice_force_number/security/security.xml
  account_invoice_force_number/static/description/icon.png
  account_invoice_force_number/static/description/index.html
  account_invoice_force_number/tests/__init__.py
  account_invoice_force_number/tests/test_account_force_number.py
  account_invoice_force_number/views/account_invoice_view.xml
Labels: approved, needs review, ready to merge

#482 [10.0] account_invoice_pricelist: FIX broken invoice views
  account_invoice_pricelist/views/account_invoice_view.xml
Labels: approved

#490 [12.0] [MIG] account_invoice_triple_discount
  account_invoice_triple_discount/README.rst
  account_invoice_triple_discount/__init__.py
  account_invoice_triple_discount/__manifest__.py
  account_invoice_triple_discount/i18n/account_invoice_triple_discount.pot
  account_invoice_triple_discount/i18n/ar.po
  account_invoice_triple_discount/i18n/bg.po
  account_invoice_triple_discount/i18n/bs.po
  account_invoice_triple_discount/i18n/ca.po
  account_invoice_triple_discount/i18n/cs.po
  account_invoice_triple_discount/i18n/de.po
  account_invoice_triple_discount/i18n/el_GR.po
  account_invoice_triple_discount/i18n/en_GB.po
  account_invoice_triple_discount/i18n/es.po
  account_invoice_triple_discount/i18n/es_CR.po
  account_invoice_triple_discount/i18n/es_EC.po
  account_invoice_triple_discount/i18n/es_ES.po
  account_invoice_triple_discount/i18n/es_MX.po
  account_invoice_triple_discount/i18n/et.po
  account_invoice_triple_discount/i18n/fi.po
  account_invoice_triple_discount/i18n/fr.po
  account_invoice_triple_discount/i18n/fr_CA.po
  account_invoice_triple_discount/i18n/fr_CH.po
  account_invoice_triple_discount/i18n/gl.po
  account_invoice_triple_discount/i18n/hr.po
  account_invoice_triple_discount/i18n/hr_HR.po
  account_invoice_triple_discount/i18n/hu.po
  account_invoice_triple_discount/i18n/id.po
  account_invoice_triple_discount/i18n/it.po
  account_invoice_triple_discount/i18n/ja.po
  account_invoice_triple_discount/i18n/lt.po
  account_invoice_triple_discount/i18n/mk.po
  account_invoice_triple_discount/i18n/mn.po
  account_invoice_triple_discount/i18n/nb.po
  account_invoice_triple_discount/i18n/nb_NO.po
  account_invoice_triple_discount/i18n/nl.po
  account_invoice_triple_discount/i18n/nl_BE.po
  account_invoice_triple_discount/i18n/nl_NL.po
  account_invoice_triple_discount/i18n/pl.po
  account_invoice_triple_discount/i18n/pt.po
  account_invoice_triple_discount/i18n/pt_BR.po
  account_invoice_triple_discount/i18n/pt_PT.po
  account_invoice_triple_discount/i18n/ro.po
  account_invoice_triple_discount/i18n/ru.po
  account_invoice_triple_discount/i18n/sk_SK.po
  account_invoice_triple_discount/i18n/sl.po
  account_invoice_triple_discount/i18n/sv.po
  account_invoice_triple_discount/i18n/th.po
  account_invoice_triple_discount/i18n/tr.po
  account_invoice_triple_discount/i18n/tr_TR.po
  account_invoice_triple_discount/i18n/zh_CN.po
  account_invoice_triple_discount/i18n/zh_TW.po
  account_invoice_triple_discount/models/__init__.py
  account_invoice_triple_discount/models/account_invoice.py
  account_invoice_triple_discount/tests/__init__.py
  account_invoice_triple_discount/tests/test_invoice_triple_discount.py
  account_invoice_triple_discount/views/account_invoice_view.xml
Labels: approved
