Repository OCA/account-invoicing, pull requests merged in 2019-09, with the labels that each got.

#588 [11.0][ADD] sale_order_invoicing_queued: Enqueue sales order invoicing
  oca_dependencies.txt
  sale_order_invoicing_queued/README.rst
  sale_order_invoicing_queued/__init__.py
  sale_order_invoicing_queued/__manifest__.py
  sale_order_invoicing_queued/i18n/es.po
  sale_order_invoicing_queued/i18n/sale_order_invoicing_queued.pot
  sale_order_invoicing_queued/models/__init__.py
  sale_order_invoicing_queued/models/queue_job.py
  sale_order_invoicing_queued/models/sale_order.py
  sale_order_invoicing_queued/readme/CONFIGURE.rst
  sale_order_invoicing_queued/readme/CONTRIBUTORS.rst
  sale_order_invoicing_queued/readme/DESCRIPTION.rst
  sale_order_invoicing_queued/readme/INSTALL.rst
  sale_order_invoicing_queued/readme/ROADMAP.rst
  sale_order_invoicing_queued/readme/USAGE.rst
  sale_order_invoicing_queued/static/description/index.html
  sale_order_invoicing_queued/tests/__init__.py
  sale_order_invoicing_queued/tests/test_sale_order_invoicing_queued.py
  sale_order_invoicing_queued/views/queue_job_views.xml
  sale_order_invoicing_queued/views/sale_order_views.xml
  sale_order_invoicing_queued/wizards/__init__.py
  sale_order_invoicing_queued/wizards/sale_advance_payment_inv.py
  sale_order_invoicing_queued/wizards/sale_advance_payment_inv_views.xml
Labels: approved, needs review

#590 [IMP] account_triple_discount: add inheritable method
  account_invoice_triple_discount/models/account_invoice.py
Labels: approved

#591 [12.0][RMV] - Remove account_brand module …
  account_brand/README.rst
  account_brand/__init__.py
  account_brand/__manifest__.py
  account_brand/i18n/account_brand.pot
  account_brand/models/__init__.py
  account_brand/models/account_invoice.py
  account_brand/readme/CONFIGURE.rst
  account_brand/readme/CONTRIBUTORS.rst
  account_brand/readme/CREDITS.rst
  account_brand/readme/DESCRIPTION.rst
  account_brand/readme/USAGE.rst
  account_brand/static/description/icon.png
  account_brand/static/description/index.html
  account_brand/views/account_invoice.xml
  setup/_metapackage/setup.py
  setup/account_brand/odoo/addons/account_brand
  setup/account_brand/setup.py
Labels: approved, merged 🎉

#593 [IMP] *_queued: Remove `cancel` method + use same user
  account_invoice_validation_queued/models/__init__.py
  account_invoice_validation_queued/models/account_invoice.py
  account_invoice_validation_queued/models/queue_job.py
  account_invoice_validation_queued/tests/test_account_invoice_validation_queued.py
  account_invoice_validation_queued/views/queue_job_views.xml
  account_invoice_validation_queued/wizards/account_invoice_confirm.py
  sale_order_invoicing_queued/models/__init__.py
  sale_order_invoicing_queued/models/queue_job.py
  sale_order_invoicing_queued/tests/test_sale_order_invoicing_queued.py
  sale_order_invoicing_queued/views/queue_job_views.xml
  sale_order_invoicing_queued/wizards/sale_advance_payment_inv.py
Labels: approved

#594 [11.0][FIX] purchase_stock_picking_return_invoicing: Trigger returned qty computation on move qty change
  purchase_stock_picking_return_invoicing/models/purchase_order.py
Labels: approved
