Repository OCA/account-invoicing, pull requests merged in 2020-10, with the labels that each got.

#790 [13.0][UPD] Eficent -> ForgeFlow
  account_invoice_fixed_discount/README.rst
  account_invoice_fixed_discount/__manifest__.py
  account_invoice_fixed_discount/models/account_move.py
  account_invoice_fixed_discount/readme/CONTRIBUTORS.rst
  account_invoice_fixed_discount/reports/report_account_invoice.xml
  account_invoice_fixed_discount/static/description/index.html
  account_invoice_fixed_discount/views/account_move_view.xml
  account_invoice_search_by_reference/README.rst
  account_move_tier_validation/tests/common.py
  account_move_tier_validation/tests/test_tier_validation.py
  account_move_tier_validation/tests/tier_validation_tester.py
Labels: approved, bot is merging ⏳, ready to merge

#789 [13.0] [FIX] account_move_tier_validation fix RecursionError
  account_move_tier_validation/models/account_move.py
Labels: approved, bot is merging ⏳, ready to merge

#781 [12.0][ADD] account_portal_hide_invoice module
  account_portal_hide_invoice/README.rst
  account_portal_hide_invoice/__init__.py
  account_portal_hide_invoice/__manifest__.py
  account_portal_hide_invoice/readme/CONTRIBUTORS.rst
  account_portal_hide_invoice/readme/CREDITS.rst
  account_portal_hide_invoice/readme/DESCRIPTION.rst
  account_portal_hide_invoice/views/account_portal_templates.xml
Labels: bot is merging ⏳

#797 [FIX][12.0] account_global_discount: sale order templates compatibility
  account_global_discount/models/account_invoice.py
Labels: approved, bot is merging ⏳

#688 [12.0][MIG] account_invoice_refund_line_selection
  account_invoice_refund_line_selection/README.rst
  account_invoice_refund_line_selection/__init__.py
  account_invoice_refund_line_selection/__manifest__.py
  account_invoice_refund_line_selection/i18n/account_invoice_refund_line_selection.pot
  account_invoice_refund_line_selection/i18n/de.po
  account_invoice_refund_line_selection/i18n/es.po
  account_invoice_refund_line_selection/models/__init__.py
  account_invoice_refund_line_selection/models/account_invoice.py
  account_invoice_refund_line_selection/readme/CONTRIBUTORS.rst
  account_invoice_refund_line_selection/readme/DESCRIPTION.rst
  account_invoice_refund_line_selection/readme/USAGE.rst
  account_invoice_refund_line_selection/static/description/icon.png
  account_invoice_refund_line_selection/tests/__init__.py
  account_invoice_refund_line_selection/tests/test_refund_line.py
  account_invoice_refund_line_selection/wizards/__init__.py
  account_invoice_refund_line_selection/wizards/account_invoice_refund.py
  account_invoice_refund_line_selection/wizards/account_invoice_refund_view.xml
Labels: approved, bot is merging ⏳, ready to merge

#799 [12.0] FIX workflow used after v11.0
  account_invoice_supplierinfo_update/wizard/wizard_update_invoice_supplierinfo.py
Labels: approved, bot is merging ⏳

#801 [12.0][FIX] account_invoice_pricelist: Remove wrong super
  account_invoice_pricelist/models/account_invoice.py
Labels: approved, bot is merging ⏳
