Repository OCA/account-invoicing, pull requests merged in 2020-06, with the labels that each got.

#723 [12.0][FIX] too generic xpath expr
  account_invoice_refund_reason/views/account_invoice_view.xml
Labels: approved, bot is merging ⏳, ready to merge

#708 [12.0][IMP] stock_picking_invoicing set name from moves instead of product
  stock_picking_invoicing/views/stock_picking.xml
  stock_picking_invoicing/wizards/stock_invoice_onshipping.py
Labels: bot is merging ⏳

#726 [12.0][FIX] account_payment_term_extension: bad use of precision_digits vs precision_rounding
  account_payment_term_extension/models/account_payment_term.py
  account_payment_term_extension/tests/test_payment_term.py
Labels: approved, bot is merging ⏳, ready to merge

#739 [11.0][FIX] account_payment_term_extension: bad use of precision_digits vs precision_rounding
  account_payment_term_extension/models/account_payment_term.py
Labels: approved, bot is merging ⏳

#740 [10.0][FIX] account_payment_term_extension: bad use of precision_digits vs precision_rounding
  account_payment_term_extension/models/account_payment_term.py
Labels: approved, bot is merging ⏳, ready to merge
