Repository OCA/account-invoicing, pull requests merged in 2020-03, with the labels that each got.

#680 [12.0][IMP] sale_order_invoicing_queued: Make it compatible with grouping criteria
  sale_order_invoicing_queued/wizards/sale_advance_payment_inv.py
Labels: approved, ready to merge

#683 [13.0] sale_order_invoicing_*: Use core hook
  sale_order_invoicing_grouping_criteria/README.rst
  sale_order_invoicing_grouping_criteria/i18n/es.po
  sale_order_invoicing_grouping_criteria/i18n/sale_order_invoicing_grouping_criteria.pot
  sale_order_invoicing_grouping_criteria/models/sale_invoicing_grouping_criteria.py
  sale_order_invoicing_grouping_criteria/models/sale_order.py
  sale_order_invoicing_grouping_criteria/readme/CONFIGURE.rst
  sale_order_invoicing_grouping_criteria/readme/DESCRIPTION.rst
  sale_order_invoicing_grouping_criteria/readme/INSTALL.rst
  sale_order_invoicing_grouping_criteria/static/description/index.html
  sale_order_invoicing_grouping_criteria/views/res_config_settings_views.xml
  sale_order_invoicing_queued/README.rst
  sale_order_invoicing_queued/readme/INSTALL.rst
  sale_order_invoicing_queued/readme/ROADMAP.rst
  sale_order_invoicing_queued/static/description/index.html
  sale_order_invoicing_queued/wizards/sale_advance_payment_inv.py
Labels: approved

#662 [ADD]account_invoice_tier_validation v11
  account_invoice_tier_validation/README.rst
  account_invoice_tier_validation/__init__.py
  account_invoice_tier_validation/__manifest__.py
  account_invoice_tier_validation/demo/account_invoice_tier_definition.xml
  account_invoice_tier_validation/models/__init__.py
  account_invoice_tier_validation/models/account_invoice.py
  account_invoice_tier_validation/models/tier_definition.py
  account_invoice_tier_validation/readme/CONFIGURE.rst
  account_invoice_tier_validation/readme/CONTRIBUTORS.rst
  account_invoice_tier_validation/readme/DESCRIPTION.rst
  account_invoice_tier_validation/readme/USAGE.rst
  account_invoice_tier_validation/static/description/icon.png
  account_invoice_tier_validation/static/description/index.html
  account_invoice_tier_validation/tests/__init__.py
  account_invoice_tier_validation/tests/test_account_invoice_tier_validation.py
  account_invoice_tier_validation/views/account_invoice_view.xml
Labels: approved, ready to merge

#559 [12.0][ADD] account_debitnote
  account_debitnote/README.rst
  account_debitnote/__init__.py
  account_debitnote/__manifest__.py
  account_debitnote/models/__init__.py
  account_debitnote/models/account.py
  account_debitnote/models/account_invoice.py
  account_debitnote/models/account_move.py
  account_debitnote/models/ir_sequence.py
  account_debitnote/readme/CONFIGURE.rst
  account_debitnote/readme/CONTRIBUTORS.rst
  account_debitnote/readme/DESCRIPTION.rst
  account_debitnote/readme/USAGE.rst
  account_debitnote/static/description/index.html
  account_debitnote/tests/__init__.py
  account_debitnote/tests/test_account_debitnote.py
  account_debitnote/views/account_invoice_view.xml
  account_debitnote/views/account_view.xml
  account_debitnote/wizard/__init__.py
  account_debitnote/wizard/account_invoice_debitnote.py
  account_debitnote/wizard/account_invoice_debitnote_view.xml
Labels: approved, ready to merge

#674 [ADD] 13.0 account_move_tier_validation
  account_move_tier_validation/README.rst
  account_move_tier_validation/__init__.py
  account_move_tier_validation/__manifest__.py
  account_move_tier_validation/models/__init__.py
  account_move_tier_validation/models/account_move.py
  account_move_tier_validation/models/tier_definition.py
  account_move_tier_validation/readme/CONFIGURE.rst
  account_move_tier_validation/readme/CONTRIBUTORS.rst
  account_move_tier_validation/readme/DESCRIPTION.rst
  account_move_tier_validation/readme/INSTALL.rst
  account_move_tier_validation/readme/USAGE.rst
  account_move_tier_validation/static/description/index.html
  account_move_tier_validation/tests/__init__.py
  account_move_tier_validation/tests/common.py
  account_move_tier_validation/tests/test_tier_validation.py
  account_move_tier_validation/tests/tier_validation_tester.py
  account_move_tier_validation/views/account_move_view.xml
  oca_dependencies.txt
Labels: approved, ready to merge

#571 [IMP] account_invoice_rounding: remove overriding methods of account.tax
  account_invoice_rounding/README.rst
  account_invoice_rounding/models/account.py
Labels: approved, needs review, ready to merge

#651 [13.0][MIG] account_invoice_search_by_reference
  account_invoice_search_by_reference/README.rst
  account_invoice_search_by_reference/__init__.py
  account_invoice_search_by_reference/__manifest__.py
  account_invoice_search_by_reference/i18n/account_invoice_search_by_reference.pot
  account_invoice_search_by_reference/i18n/ar.po
  account_invoice_search_by_reference/i18n/bg.po
  account_invoice_search_by_reference/i18n/bs.po
  account_invoice_search_by_reference/i18n/ca.po
  account_invoice_search_by_reference/i18n/cs.po
  account_invoice_search_by_reference/i18n/de.po
  account_invoice_search_by_reference/i18n/el_GR.po
  account_invoice_search_by_reference/i18n/en_GB.po
  account_invoice_search_by_reference/i18n/es.po
  account_invoice_search_by_reference/i18n/es_CR.po
  account_invoice_search_by_reference/i18n/es_EC.po
  account_invoice_search_by_reference/i18n/es_ES.po
  account_invoice_search_by_reference/i18n/es_MX.po
  account_invoice_search_by_reference/i18n/es_PE.po
  account_invoice_search_by_reference/i18n/et.po
  account_invoice_search_by_reference/i18n/fi.po
  account_invoice_search_by_reference/i18n/fr.po
  account_invoice_search_by_reference/i18n/fr_CA.po
  account_invoice_search_by_reference/i18n/fr_CH.po
  account_invoice_search_by_reference/i18n/gl.po
  account_invoice_search_by_reference/i18n/hr.po
  account_invoice_search_by_reference/i18n/hr_HR.po
  account_invoice_search_by_reference/i18n/hu.po
  account_invoice_search_by_reference/i18n/id.po
  account_invoice_search_by_reference/i18n/it.po
  account_invoice_search_by_reference/i18n/ja.po
  account_invoice_search_by_reference/i18n/lt.po
  account_invoice_search_by_reference/i18n/mk.po
  account_invoice_search_by_reference/i18n/mn.po
  account_invoice_search_by_reference/i18n/nb.po
  account_invoice_search_by_reference/i18n/nb_NO.po
  account_invoice_search_by_reference/i18n/nl.po
  account_invoice_search_by_reference/i18n/nl_BE.po
  account_invoice_search_by_reference/i18n/nl_NL.po
  account_invoice_search_by_reference/i18n/pl.po
  account_invoice_search_by_reference/i18n/pt.po
  account_invoice_search_by_reference/i18n/pt_BR.po
  account_invoice_search_by_reference/i18n/pt_PT.po
  account_invoice_search_by_reference/i18n/ro.po
  account_invoice_search_by_reference/i18n/ru.po
  account_invoice_search_by_reference/i18n/sk_SK.po
  account_invoice_search_by_reference/i18n/sl.po
  account_invoice_search_by_reference/i18n/sv.po
  account_invoice_search_by_reference/i18n/th.po
  account_invoice_search_by_reference/i18n/tr.po
  account_invoice_search_by_reference/i18n/tr_TR.po
  account_invoice_search_by_reference/i18n/zh_CN.po
  account_invoice_search_by_reference/i18n/zh_TW.po
  account_invoice_search_by_reference/models/__init__.py
  account_invoice_search_by_reference/models/account_move.py
  account_invoice_search_by_reference/static/description/icon.png
  account_invoice_search_by_reference/tests/__init__.py
  account_invoice_search_by_reference/tests/test_account_invoice_search_by_reference.py
Labels: approved, ready to merge

#647 [13.0][MIG] account_invoice_force_number
  account_invoice_force_number/README.rst
  account_invoice_force_number/__init__.py
  account_invoice_force_number/__manifest__.py
  account_invoice_force_number/i18n/account_invoice_force_number.pot
  account_invoice_force_number/i18n/ar.po
  account_invoice_force_number/i18n/bg.po
  account_invoice_force_number/i18n/bs.po
  account_invoice_force_number/i18n/ca.po
  account_invoice_force_number/i18n/cs.po
  account_invoice_force_number/i18n/de.po
  account_invoice_force_number/i18n/el_GR.po
  account_invoice_force_number/i18n/en_GB.po
  account_invoice_force_number/i18n/es.po
  account_invoice_force_number/i18n/es_CR.po
  account_invoice_force_number/i18n/es_EC.po
  account_invoice_force_number/i18n/es_MX.po
  account_invoice_force_number/i18n/et.po
  account_invoice_force_number/i18n/fi.po
  account_invoice_force_number/i18n/fr.po
  account_invoice_force_number/i18n/fr_CH.po
  account_invoice_force_number/i18n/gl.po
  account_invoice_force_number/i18n/hr.po
  account_invoice_force_number/i18n/hr_HR.po
  account_invoice_force_number/i18n/id.po
  account_invoice_force_number/i18n/it.po
  account_invoice_force_number/i18n/ja.po
  account_invoice_force_number/i18n/lt.po
  account_invoice_force_number/i18n/mk.po
  account_invoice_force_number/i18n/mn.po
  account_invoice_force_number/i18n/nb_NO.po
  account_invoice_force_number/i18n/nl.po
  account_invoice_force_number/i18n/nl_BE.po
  account_invoice_force_number/i18n/pl.po
  account_invoice_force_number/i18n/pt.po
  account_invoice_force_number/i18n/pt_BR.po
  account_invoice_force_number/i18n/pt_PT.po
  account_invoice_force_number/i18n/ro.po
  account_invoice_force_number/i18n/ru.po
  account_invoice_force_number/i18n/sk_SK.po
  account_invoice_force_number/i18n/sl.po
  account_invoice_force_number/i18n/sv.po
  account_invoice_force_number/i18n/th.po
  account_invoice_force_number/i18n/tr.po
  account_invoice_force_number/i18n/tr_TR.po
  account_invoice_force_number/i18n/zh_CN.po
  account_invoice_force_number/i18n/zh_TW.po
  account_invoice_force_number/models/__init__.py
  account_invoice_force_number/models/account_move.py
  account_invoice_force_number/readme/CONFIGURE.rst
  account_invoice_force_number/readme/CONTRIBUTORS.rst
  account_invoice_force_number/readme/DESCRIPTION.rst
  account_invoice_force_number/readme/USAGE.rst
  account_invoice_force_number/security/security.xml
  account_invoice_force_number/static/description/icon.png
  account_invoice_force_number/static/description/index.html
  account_invoice_force_number/tests/__init__.py
  account_invoice_force_number/tests/test_account_force_number.py
  account_invoice_force_number/views/account_move_view.xml
  setup/account_invoice_force_number/odoo/addons/account_invoice_force_number
  setup/account_invoice_force_number/setup.py
Labels: approved, ready to merge

#689 [FIX] account_invoice_date_due: Small fixes to the initial version
  account_invoice_date_due/README.rst
  account_invoice_date_due/__manifest__.py
  account_invoice_date_due/security/security.xml
  account_invoice_date_due/wizards/__init__.py
Labels: approved, ready to merge

#523 [12.0][ADD] account_billing
  account_billing/README.rst
  account_billing/__init__.py
  account_billing/__manifest__.py
  account_billing/data/account_billing_sequence.xml
  account_billing/data/account_invoice.xml
  account_billing/models/__init__.py
  account_billing/models/account_billing.py
  account_billing/models/account_invoice.py
  account_billing/readme/CONTRIBUTORS.rst
  account_billing/readme/DESCRIPTION.rst
  account_billing/readme/USAGE.rst
  account_billing/report/report.xml
  account_billing/report/report_billing.xml
  account_billing/security/ir.model.access.csv
  account_billing/static/description/index.html
  account_billing/static/src/img/icon.png
  account_billing/tests/__init__.py
  account_billing/tests/test_account_billing.py
  account_billing/views/account_billing.xml
  account_billing/views/account_invoice_view.xml
Labels: approved, merged 🎉, ready to merge
