Repository OCA/account-invoicing, pull requests merged in 2020-04, with the labels that each got.

#440 [10.0] account_invoice_transmit_method: use base_view_inheritance_extension
  account_invoice_transmit_method/__manifest__.py
  account_invoice_transmit_method/views/partner.xml
  oca_dependencies.txt
Labels: needs review

#566 [12.0][MIG] Module stock_picking_invoicing
  oca_dependencies.txt
  stock_picking_invoicing/README.rst
  stock_picking_invoicing/__init__.py
  stock_picking_invoicing/__manifest__.py
  stock_picking_invoicing/demo/stock_picking_demo.xml
  stock_picking_invoicing/i18n/fr.po
  stock_picking_invoicing/i18n/sl.po
  stock_picking_invoicing/i18n/stock_picking_invoicing.pot
  stock_picking_invoicing/models/__init__.py
  stock_picking_invoicing/models/account_invoice.py
  stock_picking_invoicing/models/stock_invoice_state_mixin.py
  stock_picking_invoicing/models/stock_move.py
  stock_picking_invoicing/models/stock_picking.py
  stock_picking_invoicing/models/stock_picking_type.py
  stock_picking_invoicing/readme/CONTRIBUTORS.rst
  stock_picking_invoicing/readme/DESCRIPTION.rst
  stock_picking_invoicing/readme/HISTORY.rst
  stock_picking_invoicing/readme/INSTALL.rst
  stock_picking_invoicing/readme/USAGE.rst
  stock_picking_invoicing/static/description/icon.png
  stock_picking_invoicing/static/description/index.html
  stock_picking_invoicing/tests/__init__.py
  stock_picking_invoicing/tests/test_picking_invoicing.py
  stock_picking_invoicing/views/stock_move.xml
  stock_picking_invoicing/views/stock_picking.xml
  stock_picking_invoicing/views/stock_picking_type.xml
  stock_picking_invoicing/wizards/__init__.py
  stock_picking_invoicing/wizards/stock_invoice_onshipping.py
  stock_picking_invoicing/wizards/stock_invoice_onshipping_view.xml
Labels: bot is merging ⏳

#707 [12.0][ENH] account_menu_invoice_refund, remove payment netting feature
  account_menu_invoice_refund/__init__.py
  account_menu_invoice_refund/__manifest__.py
  account_menu_invoice_refund/hooks.py
  account_menu_invoice_refund/readme/DESCRIPTION.rst
  account_menu_invoice_refund/readme/USAGE.rst
  account_menu_invoice_refund/tests/__init__.py
  account_menu_invoice_refund/tests/test_pay_net_invoice_refund.py
Labels: bot is merging ⏳

#665 [FIX] sale_order_invoicing_grouping_criteria: Error accessing partners
  sale_order_invoicing_grouping_criteria/views/res_partner_views.xml
Labels: approved, bot is merging ⏳, ready to merge
