Repository OCA/account-invoicing, pull requests merged in 2020-07, with the labels that each got.

#753 [FIX] account_invoice_refund_link: Fix foreignkey exception when a credit note invoice has done from sale order.
  account_invoice_refund_link/__init__.py
  account_invoice_refund_link/models/account_move.py
  account_invoice_refund_link/wizards/__init__.py
  account_invoice_refund_link/wizards/account_move_reversal.py
Labels: approved, bot is merging ⏳

#744 [13.0][ADD] account_invoice_section_sale_order
  account_invoice_section_sale_order/__init__.py
  account_invoice_section_sale_order/__manifest__.py
  account_invoice_section_sale_order/models/__init__.py
  account_invoice_section_sale_order/models/sale_order.py
  account_invoice_section_sale_order/readme/CONTRIBUTORS.rst
  account_invoice_section_sale_order/readme/DESCRIPTION.rst
  account_invoice_section_sale_order/tests/__init__.py
  account_invoice_section_sale_order/tests/test_invoice_group_by_sale_order.py
Labels: bot is merging ⏳

#745 [11.0][FIX] account_global_discount: link line taxes to discount move line
  account_global_discount/README.rst
  account_global_discount/__manifest__.py
  account_global_discount/migrations/11.0.2.0.0/post-migration.py
  account_global_discount/migrations/11.0.2.0.0/pre-migration.py
  account_global_discount/models/account_invoice.py
  account_global_discount/models/account_move_line.py
  account_global_discount/readme/ROADMAP.rst
  account_global_discount/tests/test_global_discount.py
  account_global_discount/views/account_invoice_views.xml
Labels: bot is merging ⏳

#748 [12.0][MIG] account_global_discount: Migration to 12.0
  account_global_discount/README.rst
  account_global_discount/__init__.py
  account_global_discount/__manifest__.py
  account_global_discount/i18n/.empty
  account_global_discount/i18n/account_global_discount.pot
  account_global_discount/i18n/es.po
  account_global_discount/migrations/11.0.2.0.0/post-migration.py
  account_global_discount/migrations/11.0.2.0.0/pre-migration.py
  account_global_discount/models/__init__.py
  account_global_discount/models/account_invoice.py
  account_global_discount/models/account_move_line.py
  account_global_discount/models/global_discount.py
  account_global_discount/readme/CONTRIBUTORS.rst
  account_global_discount/readme/DESCRIPTION.rst
  account_global_discount/readme/ROADMAP.rst
  account_global_discount/readme/USAGE.rst
  account_global_discount/security/ir.model.access.csv
  account_global_discount/security/security.xml
  account_global_discount/static/description/icon.png
  account_global_discount/static/description/icon.svg
  account_global_discount/static/description/index.html
  account_global_discount/tests/__init__.py
  account_global_discount/tests/test_global_discount.py
  account_global_discount/views/account_invoice_views.xml
  account_global_discount/views/global_discount_views.xml
  account_global_discount/views/report_account_invoice.xml
  oca_dependencies.txt
Labels: approved, bot is merging ⏳

#746 [12.0][ADD] account invoice supplier date
  account_invoice_supplier_date/README.rst
  account_invoice_supplier_date/__init__.py
  account_invoice_supplier_date/__manifest__.py
  account_invoice_supplier_date/readme/CONTRIBUTORS.rst
  account_invoice_supplier_date/readme/DESCRIPTION.rst
  account_invoice_supplier_date/readme/USAGE.rst
  account_invoice_supplier_date/static/description/icon.png
  account_invoice_supplier_date/static/description/index.html
  account_invoice_supplier_date/views/account.xml
  setup/account_invoice_supplier_date/odoo/addons/account_invoice_supplier_date
  setup/account_invoice_supplier_date/setup.py
Labels: approved, bot is merging ⏳, ready to merge

#732 [IMP][8.0] account_invoice_merge: Make the function to get draft invoices overridable, since some…
  account_invoice_merge/models/account_invoice.py
  account_invoice_merge/wizard/invoice_merge.py
Labels: approved, ready to merge

#669 [FIX] uom onchange of account invoice line in account_invoice_pricelist
  account_invoice_pricelist/models/account_invoice.py
Labels: approved, bot is merging ⏳, ready to merge

#698 [13.0][ADD] account_invoice_warn_message
  account_invoice_warn_message/README.rst
  account_invoice_warn_message/__init__.py
  account_invoice_warn_message/__manifest__.py
  account_invoice_warn_message/models/__init__.py
  account_invoice_warn_message/models/account_move.py
  account_invoice_warn_message/readme/CONTRIBUTORS.rst
  account_invoice_warn_message/readme/DESCRIPTION.rst
  account_invoice_warn_message/static/description/icon.png
  account_invoice_warn_message/static/description/index.html
  account_invoice_warn_message/tests/__init__.py
  account_invoice_warn_message/tests/test_account_invoice_warn_message.py
  account_invoice_warn_message/views/account_move_views.xml
  setup/account_invoice_warn_message/odoo/addons/account_invoice_warn_message
  setup/account_invoice_warn_message/setup.py
Labels: approved, bot is merging ⏳

#660 [12.0] [MIG] account group invoice line
  account_group_invoice_line/README.rst
  account_group_invoice_line/__init__.py
  account_group_invoice_line/__manifest__.py
  account_group_invoice_line/i18n/account_group_invoice_line.pot
  account_group_invoice_line/i18n/ar.po
  account_group_invoice_line/i18n/bg.po
  account_group_invoice_line/i18n/bs.po
  account_group_invoice_line/i18n/ca.po
  account_group_invoice_line/i18n/cs.po
  account_group_invoice_line/i18n/de.po
  account_group_invoice_line/i18n/el_GR.po
  account_group_invoice_line/i18n/en_GB.po
  account_group_invoice_line/i18n/es.po
  account_group_invoice_line/i18n/es_CR.po
  account_group_invoice_line/i18n/es_EC.po
  account_group_invoice_line/i18n/es_ES.po
  account_group_invoice_line/i18n/es_MX.po
  account_group_invoice_line/i18n/es_PE.po
  account_group_invoice_line/i18n/et.po
  account_group_invoice_line/i18n/fi.po
  account_group_invoice_line/i18n/fr.po
  account_group_invoice_line/i18n/fr_CA.po
  account_group_invoice_line/i18n/fr_CH.po
  account_group_invoice_line/i18n/gl.po
  account_group_invoice_line/i18n/hr.po
  account_group_invoice_line/i18n/hr_HR.po
  account_group_invoice_line/i18n/hu.po
  account_group_invoice_line/i18n/id.po
  account_group_invoice_line/i18n/it.po
  account_group_invoice_line/i18n/ja.po
  account_group_invoice_line/i18n/lt.po
  account_group_invoice_line/i18n/mk.po
  account_group_invoice_line/i18n/mn.po
  account_group_invoice_line/i18n/nb.po
  account_group_invoice_line/i18n/nb_NO.po
  account_group_invoice_line/i18n/nl.po
  account_group_invoice_line/i18n/nl_BE.po
  account_group_invoice_line/i18n/nl_NL.po
  account_group_invoice_line/i18n/pl.po
  account_group_invoice_line/i18n/pt.po
  account_group_invoice_line/i18n/pt_BR.po
  account_group_invoice_line/i18n/pt_PT.po
  account_group_invoice_line/i18n/ro.po
  account_group_invoice_line/i18n/ru.po
  account_group_invoice_line/i18n/sk_SK.po
  account_group_invoice_line/i18n/sl.po
  account_group_invoice_line/i18n/sv.po
  account_group_invoice_line/i18n/th.po
  account_group_invoice_line/i18n/tr.po
  account_group_invoice_line/i18n/tr_TR.po
  account_group_invoice_line/i18n/zh_CN.po
  account_group_invoice_line/i18n/zh_TW.po
  account_group_invoice_line/models/__init__.py
  account_group_invoice_line/models/account_invoice.py
  account_group_invoice_line/models/account_journal.py
  account_group_invoice_line/static/description/icon.png
  account_group_invoice_line/views/account_journal.xml
Labels: approved, bot is merging ⏳, ready to merge

#764 [FIX] website key in account_invoice_warn_message
  account_invoice_warn_message/__manifest__.py
Labels: bot is merging ⏳
