Repository OCA/account-invoicing, pull requests merged in 2020-05, with the labels that each got.

#696 [13.0][MIG] account_invoice_validation_queued : Migration to 13.0
  account_invoice_validation_queued/README.rst
  account_invoice_validation_queued/__init__.py
  account_invoice_validation_queued/__manifest__.py
  account_invoice_validation_queued/i18n/account_invoice_validation_queued.pot
  account_invoice_validation_queued/i18n/es.po
  account_invoice_validation_queued/models/__init__.py
  account_invoice_validation_queued/models/account_move.py
  account_invoice_validation_queued/readme/CONFIGURE.rst
  account_invoice_validation_queued/readme/CONTRIBUTORS.rst
  account_invoice_validation_queued/readme/DESCRIPTION.rst
  account_invoice_validation_queued/readme/INSTALL.rst
  account_invoice_validation_queued/readme/ROADMAP.rst
  account_invoice_validation_queued/readme/USAGE.rst
  account_invoice_validation_queued/static/description/icon.png
  account_invoice_validation_queued/static/description/index.html
  account_invoice_validation_queued/tests/__init__.py
  account_invoice_validation_queued/tests/test_account_invoice_validation_queued.py
  account_invoice_validation_queued/views/account_invoice_views.xml
  account_invoice_validation_queued/views/queue_job_views.xml
  account_invoice_validation_queued/wizards/__init__.py
  account_invoice_validation_queued/wizards/validate_account_move.py
  account_invoice_validation_queued/wizards/validate_account_move_view.xml
  setup/account_invoice_validation_queued/odoo/addons/account_invoice_validation_queued
  setup/account_invoice_validation_queued/setup.py
Labels: bot is merging ⏳

#694 [12.0][ADD] - substitution rules for transmit method
  account_invoice_transmit_method_substitution_rule/README.rst
  account_invoice_transmit_method_substitution_rule/__init__.py
  account_invoice_transmit_method_substitution_rule/__manifest__.py
  account_invoice_transmit_method_substitution_rule/demo/transmit_method_substitution_rule.xml
  account_invoice_transmit_method_substitution_rule/models/__init__.py
  account_invoice_transmit_method_substitution_rule/models/account_invoice.py
  account_invoice_transmit_method_substitution_rule/models/transmit_method_substitution_rule.py
  account_invoice_transmit_method_substitution_rule/readme/CONTRIBUTORS.rst
  account_invoice_transmit_method_substitution_rule/readme/DESCRIPTION.rst
  account_invoice_transmit_method_substitution_rule/readme/USAGE.rst
  account_invoice_transmit_method_substitution_rule/security/transmit_method_substitution_rule.xml
  account_invoice_transmit_method_substitution_rule/static/description/icon.png
  account_invoice_transmit_method_substitution_rule/static/description/index.html
  account_invoice_transmit_method_substitution_rule/tests/__init__.py
  account_invoice_transmit_method_substitution_rule/tests/test_account_invoice_transmit_method_substitution_rule.py
  account_invoice_transmit_method_substitution_rule/views/transmit_method_substitution_rule.xml
  setup/account_invoice_transmit_method_substitution_rule/odoo/addons/account_invoice_transmit_method_substitution_rule
  setup/account_invoice_transmit_method_substitution_rule/setup.py
Labels: approved, bot is merging ⏳, ready to merge

#717 [FIX] account_invoice_change_currency: Rounding price_unit & tax amou…
  account_invoice_change_currency/models/account_change_currency.py
Labels: approved, bot is merging ⏳
