Repository OCA/account-invoicing, pull requests merged in 2020-12, with the labels that each got.

#815 [13.0][MIG] account_global_discount: Migration to 13.0
  account_global_discount/README.rst
  account_global_discount/__init__.py
  account_global_discount/__manifest__.py
  account_global_discount/i18n/.empty
  account_global_discount/i18n/account_global_discount.pot
  account_global_discount/i18n/es.po
  account_global_discount/i18n/pt.po
  account_global_discount/migrations/13.0.1.0.0/post-migration.py
  account_global_discount/migrations/13.0.1.0.0/pre-migration.py
  account_global_discount/models/__init__.py
  account_global_discount/models/account_move.py
  account_global_discount/models/global_discount.py
  account_global_discount/readme/CONFIGURE.rst
  account_global_discount/readme/CONTRIBUTORS.rst
  account_global_discount/readme/DESCRIPTION.rst
  account_global_discount/readme/ROADMAP.rst
  account_global_discount/readme/USAGE.rst
  account_global_discount/security/ir.model.access.csv
  account_global_discount/security/security.xml
  account_global_discount/static/description/icon.png
  account_global_discount/static/description/icon.svg
  account_global_discount/static/description/index.html
  account_global_discount/tests/__init__.py
  account_global_discount/tests/test_global_discount.py
  account_global_discount/views/account_invoice_views.xml
  account_global_discount/views/global_discount_views.xml
  account_global_discount/views/report_account_invoice.xml
  oca_dependencies.txt
  setup/account_global_discount/odoo/addons/account_global_discount
  setup/account_global_discount/setup.py
Labels: approved, bot is merging ⏳, ready to merge

#819 [FIX] account_invoice_fiscal_position_update: filter on invoice lines without display_type
  account_invoice_fiscal_position_update/models/account_invoice.py
Labels: approved, bot is merging ⏳

#814 [13.0] [FIX] account_invoice_supplier_ref_unique: do not display field on journal entry
  account_invoice_supplier_ref_unique/views/account_move.xml
Labels: approved, bot is merging ⏳, ready to merge

#830 [IMP] account_global_discount: security group
  account_global_discount/migrations/11.0.2.0.0/post-migration.py
  account_global_discount/migrations/11.0.2.0.0/pre-migration.py
  account_global_discount/migrations/12.0.2.0.0/post-migration.py
  account_global_discount/models/account_invoice.py
  account_global_discount/views/account_invoice_views.xml
  account_global_discount/views/global_discount_views.xml
Labels: approved, bot is merging ⏳

#840 [FIX] account_global_discount: duplicated label
  account_global_discount/models/account_invoice.py
  account_global_discount/views/account_invoice_views.xml
Labels: bot is merging ⏳

#841 [13.0][FIX] account_global_discount: wrong tax move line discounts on invoice post
  account_global_discount/models/account_move.py
Labels: approved, bot is merging ⏳
