Repository OCA/account-invoicing, pull requests merged in 2021-03, with the labels that each got.

#812 [14.0][MIG] account_billing
  account_billing/README.rst
  account_billing/__init__.py
  account_billing/__manifest__.py
  account_billing/data/account_billing_sequence.xml
  account_billing/data/account_move.xml
  account_billing/i18n/account_billing.pot
  account_billing/models/__init__.py
  account_billing/models/account_billing.py
  account_billing/models/account_move.py
  account_billing/readme/CONTRIBUTORS.rst
  account_billing/readme/DESCRIPTION.rst
  account_billing/readme/USAGE.rst
  account_billing/report/report.xml
  account_billing/report/report_billing.xml
  account_billing/security/ir.model.access.csv
  account_billing/static/description/icon.png
  account_billing/static/description/index.html
  account_billing/static/src/img/icon.png
  account_billing/tests/__init__.py
  account_billing/tests/test_account_billing.py
  account_billing/views/account_billing_views.xml
  account_billing/views/account_move_views.xml
  setup/account_billing/odoo/addons/account_billing
  setup/account_billing/setup.py
Labels: approved, bot is merging ⏳, ready to merge

#875 [13.0][FIX] account_invoice_pricelist, fix test currency rate
  account_invoice_pricelist/tests/test_account_move_pricelist.py
Labels: bot is merging ⏳

#879 [MIG][14.0] account_invoice_search_by_reference: Migration to 14.0
  account_invoice_search_by_reference/README.rst
  account_invoice_search_by_reference/__init__.py
  account_invoice_search_by_reference/__manifest__.py
  account_invoice_search_by_reference/i18n/account_invoice_search_by_reference.pot
  account_invoice_search_by_reference/i18n/ar.po
  account_invoice_search_by_reference/i18n/bg.po
  account_invoice_search_by_reference/i18n/bs.po
  account_invoice_search_by_reference/i18n/ca.po
  account_invoice_search_by_reference/i18n/cs.po
  account_invoice_search_by_reference/i18n/de.po
  account_invoice_search_by_reference/i18n/el_GR.po
  account_invoice_search_by_reference/i18n/en_GB.po
  account_invoice_search_by_reference/i18n/es.po
  account_invoice_search_by_reference/i18n/es_CR.po
  account_invoice_search_by_reference/i18n/es_EC.po
  account_invoice_search_by_reference/i18n/es_ES.po
  account_invoice_search_by_reference/i18n/es_MX.po
  account_invoice_search_by_reference/i18n/es_PE.po
  account_invoice_search_by_reference/i18n/et.po
  account_invoice_search_by_reference/i18n/fi.po
  account_invoice_search_by_reference/i18n/fr.po
  account_invoice_search_by_reference/i18n/fr_CA.po
  account_invoice_search_by_reference/i18n/fr_CH.po
  account_invoice_search_by_reference/i18n/gl.po
  account_invoice_search_by_reference/i18n/hr.po
  account_invoice_search_by_reference/i18n/hr_HR.po
  account_invoice_search_by_reference/i18n/hu.po
  account_invoice_search_by_reference/i18n/id.po
  account_invoice_search_by_reference/i18n/it.po
  account_invoice_search_by_reference/i18n/ja.po
  account_invoice_search_by_reference/i18n/lt.po
  account_invoice_search_by_reference/i18n/mk.po
  account_invoice_search_by_reference/i18n/mn.po
  account_invoice_search_by_reference/i18n/nb.po
  account_invoice_search_by_reference/i18n/nb_NO.po
  account_invoice_search_by_reference/i18n/nl.po
  account_invoice_search_by_reference/i18n/nl_BE.po
  account_invoice_search_by_reference/i18n/nl_NL.po
  account_invoice_search_by_reference/i18n/pl.po
  account_invoice_search_by_reference/i18n/pt.po
  account_invoice_search_by_reference/i18n/pt_BR.po
  account_invoice_search_by_reference/i18n/pt_PT.po
  account_invoice_search_by_reference/i18n/ro.po
  account_invoice_search_by_reference/i18n/ru.po
  account_invoice_search_by_reference/i18n/sk_SK.po
  account_invoice_search_by_reference/i18n/sl.po
  account_invoice_search_by_reference/i18n/sv.po
  account_invoice_search_by_reference/i18n/th.po
  account_invoice_search_by_reference/i18n/tr.po
  account_invoice_search_by_reference/i18n/tr_TR.po
  account_invoice_search_by_reference/i18n/zh_CN.po
  account_invoice_search_by_reference/i18n/zh_TW.po
  account_invoice_search_by_reference/models/__init__.py
  account_invoice_search_by_reference/models/account_move.py
  account_invoice_search_by_reference/static/description/icon.png
  account_invoice_search_by_reference/tests/__init__.py
  account_invoice_search_by_reference/tests/test_account_invoice_search_by_reference.py
  setup/account_invoice_search_by_reference/odoo/addons/account_invoice_search_by_reference
  setup/account_invoice_search_by_reference/setup.py
Labels: approved, bot is merging ⏳, ready to merge

#889 [13.0][FIX] account_global_discount + account_billing: Fix tests
  account_billing/tests/test_account_billing.py
  account_global_discount/tests/test_global_discount.py
Labels: bot is merging ⏳

#893 [13.0][FIX] account_billing: Prevent error in tests related to sale journal not exist
  account_billing/tests/test_account_billing.py
Labels: approved, bot is merging ⏳

#894 Copy invoice state in backorders and extra stock move in pickings
  stock_picking_invoicing/models/stock_move.py
  stock_picking_invoicing/models/stock_picking.py
  stock_picking_invoicing/tests/test_picking_invoicing.py
Labels: approved, bot is merging ⏳

#896 [12.0][IMP+FIX] Return Picking Invocing Process and mapping Invoice Type
  stock_picking_invoicing/__manifest__.py
  stock_picking_invoicing/tests/test_picking_invoicing.py
  stock_picking_invoicing/wizards/__init__.py
  stock_picking_invoicing/wizards/stock_invoice_onshipping.py
  stock_picking_invoicing/wizards/stock_return_picking.py
  stock_picking_invoicing/wizards/stock_return_picking_view.xml
Labels: approved, bot is merging ⏳

#899 [12.0][FIX] Mapping Invoice Type - stock_picking_invoicing
  stock_picking_invoicing/tests/test_picking_invoicing.py
  stock_picking_invoicing/wizards/stock_invoice_onshipping.py
Labels: approved, bot is merging ⏳

#902 [12.0][FIX] remove from invoice lines with no quantity
  purchase_batch_invoicing/README.rst
  purchase_batch_invoicing/__init__.py
  purchase_batch_invoicing/models/__init__.py
  purchase_batch_invoicing/models/account_invoice.py
  purchase_batch_invoicing/readme/CONTRIBUTORS.rst
  purchase_batch_invoicing/readme/DESCRIPTION.rst
  purchase_batch_invoicing/static/description/index.html
  purchase_batch_invoicing/tests/test_invoicing.py
  purchase_batch_invoicing/wizards/purchase_batch_invoicing.py
  purchase_batch_invoicing/wizards/purchase_batch_invoicing_view.xml
Labels: approved, bot is merging ⏳
