Repository OCA/account-invoicing, pull requests merged in 2021-12, with the labels that each got.

#1048 [14.0] account_invoice_section_sale_order fix create_invoice
  account_invoice_section_sale_order/models/sale_order.py
Labels: bot is merging ⏳

#813 [FIX] Do not recalculate price if no product is set
  account_invoice_pricelist/models/account_move.py
Labels: bot is merging ⏳

#1046 [FIX] account_invoice_supplierinfo_update: rounding
  account_invoice_supplierinfo_update/models/account_invoice_line.py
Labels: approved, bot is merging ⏳

#412 [FIX] Store invoice currency on the supplierinfo
  .travis.yml
  account_invoice_supplierinfo_update/tests/test_account_invoice_supplierinfo_update.py
  account_invoice_supplierinfo_update/wizard/wizard_update_invoice_supplierinfo.py
  account_invoice_supplierinfo_update/wizard/wizard_update_invoice_supplierinfo_line.py
Labels: bot is merging ⏳

#1042 [14.0][ADD] account_move_propagate_ref
  account_move_propagate_ref/__init__.py
  account_move_propagate_ref/__manifest__.py
  account_move_propagate_ref/models/__init__.py
  account_move_propagate_ref/models/account_move.py
  account_move_propagate_ref/readme/CONTRIBUTORS.rst
  account_move_propagate_ref/readme/DESCRIPTION.rst
  account_move_propagate_ref/static/description/icon.png
  account_move_propagate_ref/tests/__init__.py
  account_move_propagate_ref/tests/test_propagate_ref.py
  account_move_propagate_ref/wizard/__init__.py
  account_move_propagate_ref/wizard/account_move_reversal.py
  setup/account_move_propagate_ref/odoo/addons/account_move_propagate_ref
  setup/account_move_propagate_ref/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#1052 [14.0] Fix _create_invoice on sale_order_invoicing_grouping_criteria
  sale_order_invoicing_grouping_criteria/models/sale_order.py
Labels: approved, bot is merging ⏳

#986 [13.0][IMP] purchase_batch_invoicing: improve wizard tree view
  purchase_batch_invoicing/readme/CONTRIBUTORS.rst
  purchase_batch_invoicing/views/purchase_order_view.xml
  purchase_batch_invoicing/wizards/purchase_batch_invoicing_view.xml
Labels: approved, ready to merge, bot is merging ⏳

#918 [FIX] account_invoice_merge: compatibility with account_invoice_margin module (OCA/margin-analysis repository)
  account_invoice_merge/models/account_invoice.py
Labels: bot is merging ⏳

#992 [13.0][FIX] purchase_stock_picking_return_invoicing: some fixes
  purchase_stock_picking_return_invoicing/__manifest__.py
  purchase_stock_picking_return_invoicing/models/account_invoice.py
  purchase_stock_picking_return_invoicing/models/purchase_order.py
  purchase_stock_picking_return_invoicing/readme/CONTRIBUTORS.rst
  purchase_stock_picking_return_invoicing/tests/test_purchase_stock_picking_return_invoicing.py
  purchase_stock_picking_return_invoicing/views/purchase_view.xml
Labels: bot is merging ⏳

#993 [12.0][FIX] purchase_stock_picking_return_invoicing: some fixes
  purchase_stock_picking_return_invoicing/__manifest__.py
  purchase_stock_picking_return_invoicing/models/purchase_order.py
  purchase_stock_picking_return_invoicing/views/purchase_view.xml
Labels: bot is merging ⏳

#1055 [14.0][FIX] account_invoice_payment_retention: compute_amount on payment wizard
  account_invoice_payment_retention/models/__init__.py
  account_invoice_payment_retention/wizard/__init__.py
  account_invoice_payment_retention/wizard/account_payment_register.py
Labels: bot is merging ⏳

#1054 [14.0][MIG] sale_order_invoicing_queued: Migration to 14.0
  sale_order_invoicing_queued/README.rst
  sale_order_invoicing_queued/__init__.py
  sale_order_invoicing_queued/__manifest__.py
  sale_order_invoicing_queued/data/job_queue.xml
  sale_order_invoicing_queued/i18n/es.po
  sale_order_invoicing_queued/i18n/sale_order_invoicing_queued.pot
  sale_order_invoicing_queued/i18n/zh_CN.po
  sale_order_invoicing_queued/models/__init__.py
  sale_order_invoicing_queued/models/sale_order.py
  sale_order_invoicing_queued/readme/CONFIGURE.rst
  sale_order_invoicing_queued/readme/CONTRIBUTORS.rst
  sale_order_invoicing_queued/readme/DESCRIPTION.rst
  sale_order_invoicing_queued/readme/INSTALL.rst
  sale_order_invoicing_queued/readme/USAGE.rst
  sale_order_invoicing_queued/static/description/icon.png
  sale_order_invoicing_queued/static/description/index.html
  sale_order_invoicing_queued/tests/__init__.py
  sale_order_invoicing_queued/tests/test_sale_order_invoicing_queued.py
  sale_order_invoicing_queued/views/queue_job_views.xml
  sale_order_invoicing_queued/views/sale_order_views.xml
  sale_order_invoicing_queued/wizards/__init__.py
  sale_order_invoicing_queued/wizards/sale_advance_payment_inv.py
  sale_order_invoicing_queued/wizards/sale_advance_payment_inv_views.xml
  setup/sale_order_invoicing_queued/odoo/addons/sale_order_invoicing_queued
  setup/sale_order_invoicing_queued/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#1068 [FIX] account_invoice_refund_link: Fix development_status
  account_invoice_refund_link/__manifest__.py
Labels: bot is merging ⏳
