Repository OCA/account-invoicing, pull requests merged in 2021-11, with the labels that each got.

#1027 [FIX] account_invoice_supplier_self_invoice: Set ref as self_invoice_number
  account_invoice_supplier_self_invoice/__manifest__.py
  account_invoice_supplier_self_invoice/migrations/13.0.1.1.1/post-migration.py
  account_invoice_supplier_self_invoice/models/account_move.py
Labels: approved, ready to merge, bot is merging ⏳

#595 [10.0][ADD] account_invoice_merge - making make_key() generic
  account_invoice_merge/models/account_invoice.py
Labels: approved, bot is merging ⏳

#1030 [14.0][FIX] account_invoice_check_total FR translation
  account_invoice_check_total/i18n/fr.po
Labels: approved, bot is merging ⏳

#928 [FIX] account_invoice_fiscal_position_update: Mark to recompute line for taxes when change fpos
  account_invoice_fiscal_position_update/models/account_invoice.py
  account_invoice_pricelist/tests/test_account_move_pricelist.py
Labels: approved, ready to merge, bot is merging ⏳

#1017 [IMP] add a hook to get ordered invoice lines (Forward port)
  account_invoice_section_sale_order/models/sale_order.py
Labels: approved, ready to merge, bot is merging ⏳

#1011 [12.0][IMP] account_invoice_tier_validation: add more filters to search view
  account_invoice_tier_validation/views/account_invoice_view.xml
Labels: approved, ready to merge, bot is merging ⏳

#1034 [IMP] account_invoice_refund_line_selection: Add view for search
  account_invoice_refund_line_selection/wizards/account_move_reversal_view.xml
Labels: approved, bot is merging ⏳

#1014 [14.0][MIG] Module stock_picking_invoicing
  stock_picking_invoicing/README.rst
  stock_picking_invoicing/__init__.py
  stock_picking_invoicing/__manifest__.py
  stock_picking_invoicing/demo/stock_picking_demo.xml
  stock_picking_invoicing/i18n/de.po
  stock_picking_invoicing/i18n/es.po
  stock_picking_invoicing/i18n/fr.po
  stock_picking_invoicing/i18n/pt_BR.po
  stock_picking_invoicing/i18n/sl.po
  stock_picking_invoicing/i18n/stock_picking_invoicing.pot
  stock_picking_invoicing/models/__init__.py
  stock_picking_invoicing/models/account_move.py
  stock_picking_invoicing/models/stock_invoice_state_mixin.py
  stock_picking_invoicing/models/stock_move.py
  stock_picking_invoicing/models/stock_picking.py
  stock_picking_invoicing/models/stock_picking_type.py
  stock_picking_invoicing/readme/CONTRIBUTORS.rst
  stock_picking_invoicing/readme/DESCRIPTION.rst
  stock_picking_invoicing/readme/HISTORY.rst
  stock_picking_invoicing/readme/INSTALL.rst
  stock_picking_invoicing/readme/USAGE.rst
  stock_picking_invoicing/security/ir.model.access.csv
  stock_picking_invoicing/static/description/icon.png
  stock_picking_invoicing/static/description/index.html
  stock_picking_invoicing/tests/__init__.py
  stock_picking_invoicing/tests/test_picking_invoicing.py
  stock_picking_invoicing/views/stock_move.xml
  stock_picking_invoicing/views/stock_picking.xml
  stock_picking_invoicing/views/stock_picking_type.xml
  stock_picking_invoicing/wizards/__init__.py
  stock_picking_invoicing/wizards/stock_invoice_onshipping.py
  stock_picking_invoicing/wizards/stock_invoice_onshipping_view.xml
  stock_picking_invoicing/wizards/stock_return_picking.py
  stock_picking_invoicing/wizards/stock_return_picking_view.xml
Labels: approved, ready to merge, bot is merging ⏳

#1031 [ADD] account_invoice_refund_reinvoice
  account_invoice_refund_reinvoice/README.rst
  account_invoice_refund_reinvoice/__init__.py
  account_invoice_refund_reinvoice/__manifest__.py
  account_invoice_refund_reinvoice/models/__init__.py
  account_invoice_refund_reinvoice/models/account_move.py
  account_invoice_refund_reinvoice/readme/CONTRIBUTORS.rst
  account_invoice_refund_reinvoice/readme/DESCRIPTION.rst
  account_invoice_refund_reinvoice/readme/USAGE.rst
  account_invoice_refund_reinvoice/static/description/icon.png
  account_invoice_refund_reinvoice/static/description/index.html
  account_invoice_refund_reinvoice/tests/__init__.py
  account_invoice_refund_reinvoice/tests/test_refund_invoice.py
  account_invoice_refund_reinvoice/views/account_move.xml
  setup/account_invoice_refund_reinvoice/odoo/addons/account_invoice_refund_reinvoice
  setup/account_invoice_refund_reinvoice/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#1036 [FIX] account_invoice_triple_discount: Developer Mode was required to use discounts
  account_invoice_triple_discount/views/account_move.xml
Labels: approved, bot is merging ⏳

#1021 [14.0][ADD] account_move_line_accounting_description
  account_move_line_accounting_description/__init__.py
  account_move_line_accounting_description/__manifest__.py
  account_move_line_accounting_description/models/__init__.py
  account_move_line_accounting_description/models/account_move.py
  account_move_line_accounting_description/models/product.py
  account_move_line_accounting_description/readme/CONTRIBUTORS.rst
  account_move_line_accounting_description/readme/DESCRIPTION.rst
  account_move_line_accounting_description/reports/invoice.xml
  account_move_line_accounting_description/tests/__init__.py
  account_move_line_accounting_description/tests/test_account_move_line_description.py
  account_move_line_accounting_description/views/account_move.xml
  account_move_line_accounting_description/views/product_template.xml
  account_move_line_accounting_description_purchase/__init__.py
  account_move_line_accounting_description_purchase/__manifest__.py
  account_move_line_accounting_description_purchase/models/__init__.py
  account_move_line_accounting_description_purchase/models/purchase_order.py
  account_move_line_accounting_description_purchase/readme/CONTRIBUTORS.rst
  account_move_line_accounting_description_purchase/readme/DESCRIPTION.rst
  account_move_line_accounting_description_purchase/tests/__init__.py
  account_move_line_accounting_description_purchase/tests/test_purchase_order_description.py
  account_move_line_accounting_description_sale/__init__.py
  account_move_line_accounting_description_sale/__manifest__.py
  account_move_line_accounting_description_sale/models/__init__.py
  account_move_line_accounting_description_sale/models/sale_order.py
  account_move_line_accounting_description_sale/readme/CONTRIBUTORS.rst
  account_move_line_accounting_description_sale/readme/DESCRIPTION.rst
  account_move_line_accounting_description_sale/tests/__init__.py
  account_move_line_accounting_description_sale/tests/test_sale_description.py
  setup/account_move_line_accounting_description/odoo/addons/account_move_line_accounting_description
  setup/account_move_line_accounting_description/setup.py
  setup/account_move_line_accounting_description_purchase/odoo/addons/account_move_line_accounting_description_purchase
  setup/account_move_line_accounting_description_purchase/setup.py
  setup/account_move_line_accounting_description_sale/odoo/addons/account_move_line_accounting_description_sale
  setup/account_move_line_accounting_description_sale/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#1039 [14.0][FW] account_move_tier_validation: multiple ports from 13.0
  account_move_tier_validation/views/account_move_view.xml
Labels: approved, ready to merge, bot is merging ⏳

#942 [REM] account_invoice_rounding: remove useless prints
  account_invoice_rounding/tests/test_invoice_rounding.py
Labels: approved

#935 [13.0][FIX] account_invoice_warn_message, calculation when parent has message but partner not
  account_invoice_warn_message/models/account_move.py
  account_invoice_warn_message/tests/test_account_invoice_warn_message.py
Labels: approved, ready to merge, bot is merging ⏳

#1009 [14.0][MIG] account_move_exception
  account_move_exception/README.rst
  account_move_exception/__init__.py
  account_move_exception/__manifest__.py
  account_move_exception/data/account_exception_data.xml
  account_move_exception/i18n/account_move_exception.pot
  account_move_exception/init_hook.py
  account_move_exception/models/__init__.py
  account_move_exception/models/account_move.py
  account_move_exception/models/account_move_line.py
  account_move_exception/models/exception_rule.py
  account_move_exception/readme/CONTRIBUTORS.rst
  account_move_exception/readme/DESCRIPTION.rst
  account_move_exception/readme/USAGE.rst
  account_move_exception/security/ir.model.access.csv
  account_move_exception/static/description/icon.png
  account_move_exception/static/description/index.html
  account_move_exception/tests/__init__.py
  account_move_exception/tests/test_account_exception.py
  account_move_exception/views/account_view.xml
  account_move_exception/wizard/__init__.py
  account_move_exception/wizard/account_exception_confirm.py
  account_move_exception/wizard/account_exception_confirm_view.xml
  setup/account_move_exception/odoo/addons/account_move_exception
  setup/account_move_exception/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#451 [10.0][ADD] account_invoice_date_required
  account_invoice_date_required/README.rst
  account_invoice_date_required/__init__.py
  account_invoice_date_required/__manifest__.py
  account_invoice_date_required/models/__init__.py
  account_invoice_date_required/models/account_config_settings.py
  account_invoice_date_required/models/account_invoice.py
  account_invoice_date_required/models/res_company.py
  account_invoice_date_required/readme/CONFIGURE.rst
  account_invoice_date_required/readme/CONTRIBUTORS.rst
  account_invoice_date_required/readme/DESCRIPTION.rst
  account_invoice_date_required/readme/USAGE.rst
  account_invoice_date_required/static/description/icon.png
  account_invoice_date_required/static/description/index.html
  account_invoice_date_required/tests/__init__.py
  account_invoice_date_required/tests/test_account_invoice.py
  account_invoice_date_required/views/account_config_settings.xml
  setup/account_invoice_date_required/odoo/__init__.py
  setup/account_invoice_date_required/odoo/addons/__init__.py
  setup/account_invoice_date_required/odoo/addons/account_invoice_date_required
  setup/account_invoice_date_required/setup.py
Labels: work in progress, approved, bot is merging ⏳

#806 [13.0] [FIX] account_invoice_check_total: validation error format
  account_invoice_check_total/i18n/account_invoice_check_total.pot
  account_invoice_check_total/i18n/fr.po
  account_invoice_check_total/models/account_move.py
Labels: approved, ready to merge, bot is merging ⏳

#1038 [UPD] account_move_line_accounting_description FR translation
  account_move_line_accounting_description/i18n/fr.po
  account_move_line_accounting_description/views/account_move.xml
Labels: approved, ready to merge, bot is merging ⏳

#750 [MIG] account_invoice_alternate_payer: Migration to 12.0
  account_invoice_alternate_payer/README.rst
  account_invoice_alternate_payer/__init__.py
  account_invoice_alternate_payer/__manifest__.py
  account_invoice_alternate_payer/i18n/account_invoice_alternate_payer.pot
  account_invoice_alternate_payer/models/__init__.py
  account_invoice_alternate_payer/models/account_invoice.py
  account_invoice_alternate_payer/models/account_payment.py
  account_invoice_alternate_payer/readme/CONTRIBUTORS.rst
  account_invoice_alternate_payer/readme/DESCRIPTION.rst
  account_invoice_alternate_payer/readme/USAGE.rst
  account_invoice_alternate_payer/static/description/icon.png
  account_invoice_alternate_payer/static/description/index.html
  account_invoice_alternate_payer/tests/__init__.py
  account_invoice_alternate_payer/tests/test_account_invoice.py
  account_invoice_alternate_payer/views/account_invoice_views.xml
Labels: approved, ready to merge, bot is merging ⏳

#1037 [14.0][IMP] acount_invoice_refund_link: add index
  account_invoice_refund_link/models/__init__.py
  account_invoice_refund_link/models/account_move.py
  account_invoice_refund_link/models/account_move_line.py
Labels: approved, ready to merge, bot is merging ⏳

#1015 [14.0][MIG] account_invoice_partner from 10.0
  account_invoice_partner/README.rst
  account_invoice_partner/__init__.py
  account_invoice_partner/__manifest__.py
  account_invoice_partner/i18n/account_invoice_partner.pot
  account_invoice_partner/i18n/ar.po
  account_invoice_partner/i18n/bg.po
  account_invoice_partner/i18n/bs.po
  account_invoice_partner/i18n/ca.po
  account_invoice_partner/i18n/cs.po
  account_invoice_partner/i18n/de.po
  account_invoice_partner/i18n/el_GR.po
  account_invoice_partner/i18n/en_GB.po
  account_invoice_partner/i18n/es.po
  account_invoice_partner/i18n/es_CR.po
  account_invoice_partner/i18n/es_EC.po
  account_invoice_partner/i18n/es_ES.po
  account_invoice_partner/i18n/es_MX.po
  account_invoice_partner/i18n/es_PE.po
  account_invoice_partner/i18n/et.po
  account_invoice_partner/i18n/fi.po
  account_invoice_partner/i18n/fr.po
  account_invoice_partner/i18n/fr_CA.po
  account_invoice_partner/i18n/fr_CH.po
  account_invoice_partner/i18n/gl.po
  account_invoice_partner/i18n/hr.po
  account_invoice_partner/i18n/hr_HR.po
  account_invoice_partner/i18n/hu.po
  account_invoice_partner/i18n/id.po
  account_invoice_partner/i18n/it.po
  account_invoice_partner/i18n/ja.po
  account_invoice_partner/i18n/lt.po
  account_invoice_partner/i18n/mk.po
  account_invoice_partner/i18n/mn.po
  account_invoice_partner/i18n/nb.po
  account_invoice_partner/i18n/nb_NO.po
  account_invoice_partner/i18n/nl.po
  account_invoice_partner/i18n/nl_BE.po
  account_invoice_partner/i18n/nl_NL.po
  account_invoice_partner/i18n/pl.po
  account_invoice_partner/i18n/pt.po
  account_invoice_partner/i18n/pt_BR.po
  account_invoice_partner/i18n/pt_PT.po
  account_invoice_partner/i18n/ro.po
  account_invoice_partner/i18n/ru.po
  account_invoice_partner/i18n/sk_SK.po
  account_invoice_partner/i18n/sl.po
  account_invoice_partner/i18n/sv.po
  account_invoice_partner/i18n/th.po
  account_invoice_partner/i18n/tr.po
  account_invoice_partner/i18n/tr_TR.po
  account_invoice_partner/i18n/zh_CN.po
  account_invoice_partner/i18n/zh_TW.po
  account_invoice_partner/models/__init__.py
  account_invoice_partner/models/account_move.py
  account_invoice_partner/static/description/icon.png
  account_invoice_partner/tests/__init__.py
  account_invoice_partner/tests/test_account_invoice_partner.py
  setup/account_invoice_partner/odoo/addons/account_invoice_partner
  setup/account_invoice_partner/setup.py
Labels: approved, bot is merging ⏳

#985 [14.0][ADD] account_mail_autosubscribe
  account_mail_autosubscribe/__init__.py
  account_mail_autosubscribe/__manifest__.py
  account_mail_autosubscribe/data/mail_autosubscribe.xml
  account_mail_autosubscribe/readme/CONFIGURE.rst
  account_mail_autosubscribe/readme/CONTRIBUTORS.rst
  account_mail_autosubscribe/readme/DESCRIPTION.rst
  setup/account_mail_autosubscribe/odoo/addons/account_mail_autosubscribe
  setup/account_mail_autosubscribe/setup.py
Labels: bot is merging ⏳
