Repository OCA/account-invoicing, pull requests merged in 2021-04, with the labels that each got.

#895 [13.0][MIG+IMP] account_invoice_date_due: Migration to 13.0 and refactor
  account_invoice_date_due/README.rst
  account_invoice_date_due/__init__.py
  account_invoice_date_due/__manifest__.py
  account_invoice_date_due/i18n/account_invoice_date_due.pot
  account_invoice_date_due/i18n/de.po
  account_invoice_date_due/i18n/es.po
  account_invoice_date_due/models/__init__.py
  account_invoice_date_due/models/account_move.py
  account_invoice_date_due/readme/CONFIGURE.rst
  account_invoice_date_due/readme/CONTRIBUTORS.rst
  account_invoice_date_due/readme/DESCRIPTION.rst
  account_invoice_date_due/readme/USAGE.rst
  account_invoice_date_due/security/security.xml
  account_invoice_date_due/static/description/icon.png
  account_invoice_date_due/static/description/index.html
  account_invoice_date_due/tests/__init__.py
  account_invoice_date_due/tests/test_account_invoice_date_due.py
  account_invoice_date_due/views/account_move_date_due.xml
  setup/account_invoice_date_due/odoo/addons/account_invoice_date_due
  setup/account_invoice_date_due/setup.py
Labels: approved, bot is merging ⏳, ready to merge

#910 [13.0][fix][account_billing] fixes failing tests
  account_billing/tests/test_account_billing.py
Labels: bot is merging ⏳

#909 [13.0][imp][account_move_tier_validation] Adds new filters
  account_move_tier_validation/views/account_move_view.xml
Labels: approved, bot is merging ⏳

#891 [13.0][IMP] add addons table
  README.md
Labels: approved, bot is merging ⏳, ready to merge

#911 [14.0][fix][account_billing] fixes failing tests
  account_billing/tests/test_account_billing.py
Labels: bot is merging ⏳

#907 [13.0] [FIX] account_invoice_fiscal_position_update: recompute the taxes after changed
  account_invoice_fiscal_position_update/models/account_invoice.py
Labels: approved, bot is merging ⏳, ready to merge

#908 [14.0][MIG] account_invoice_date_due: Migration to 14.0
  account_billing/tests/test_account_billing.py
  account_invoice_date_due/README.rst
  account_invoice_date_due/__init__.py
  account_invoice_date_due/__manifest__.py
  account_invoice_date_due/i18n/account_invoice_date_due.pot
  account_invoice_date_due/i18n/de.po
  account_invoice_date_due/i18n/es.po
  account_invoice_date_due/models/__init__.py
  account_invoice_date_due/models/account_move.py
  account_invoice_date_due/readme/CONFIGURE.rst
  account_invoice_date_due/readme/CONTRIBUTORS.rst
  account_invoice_date_due/readme/DESCRIPTION.rst
  account_invoice_date_due/readme/USAGE.rst
  account_invoice_date_due/security/security.xml
  account_invoice_date_due/static/description/icon.png
  account_invoice_date_due/static/description/index.html
  account_invoice_date_due/tests/__init__.py
  account_invoice_date_due/tests/test_account_invoice_date_due.py
  account_invoice_date_due/views/account_move_date_due.xml
  setup/account_invoice_date_due/odoo/addons/account_invoice_date_due
  setup/account_invoice_date_due/setup.py
Labels: bot is merging ⏳

#890 [12.0][IMP] add addons table and fix translate status
  README.md
Labels: approved, bot is merging ⏳, ready to merge

#916 [account_move_tier_validation][fix] fixes search 'Validation Not Started'
  account_move_tier_validation/views/account_move_view.xml
Labels: approved, bot is merging ⏳

#678 [MIG][13.0] stock_picking_return_refund_option: Migration to v13.0
  setup/stock_picking_return_refund_option/.eggs/README.txt
  setup/stock_picking_return_refund_option/odoo/addons/stock_picking_return_refund_option
  setup/stock_picking_return_refund_option/setup.py
  stock_picking_return_refund_option/README.rst
  stock_picking_return_refund_option/__init__.py
  stock_picking_return_refund_option/__manifest__.py
  stock_picking_return_refund_option/i18n/es.po
  stock_picking_return_refund_option/i18n/stock_picking_return_refund_option.pot
  stock_picking_return_refund_option/models/__init__.py
  stock_picking_return_refund_option/models/stock_move.py
  stock_picking_return_refund_option/models/stock_picking.py
  stock_picking_return_refund_option/readme/CONTRIBUTORS.rst
  stock_picking_return_refund_option/readme/DESCRIPTION.rst
  stock_picking_return_refund_option/readme/INSTALL.rst
  stock_picking_return_refund_option/readme/USAGE.rst
  stock_picking_return_refund_option/static/description/icon.png
  stock_picking_return_refund_option/static/description/index.html
  stock_picking_return_refund_option/tests/__init__.py
  stock_picking_return_refund_option/tests/test_stock_picking_return_refund_options.py
  stock_picking_return_refund_option/views/stock_picking_view.xml
Labels: bot is merging ⏳

#845 [MIG][14.0] account_invoice_force_number
  account_invoice_force_number/README.rst
  account_invoice_force_number/__init__.py
  account_invoice_force_number/__manifest__.py
  account_invoice_force_number/i18n/account_invoice_force_number.pot
  account_invoice_force_number/i18n/ar.po
  account_invoice_force_number/i18n/bg.po
  account_invoice_force_number/i18n/bs.po
  account_invoice_force_number/i18n/ca.po
  account_invoice_force_number/i18n/cs.po
  account_invoice_force_number/i18n/de.po
  account_invoice_force_number/i18n/el_GR.po
  account_invoice_force_number/i18n/en_GB.po
  account_invoice_force_number/i18n/es.po
  account_invoice_force_number/i18n/es_CR.po
  account_invoice_force_number/i18n/es_EC.po
  account_invoice_force_number/i18n/es_MX.po
  account_invoice_force_number/i18n/et.po
  account_invoice_force_number/i18n/fi.po
  account_invoice_force_number/i18n/fr.po
  account_invoice_force_number/i18n/fr_CH.po
  account_invoice_force_number/i18n/gl.po
  account_invoice_force_number/i18n/hr.po
  account_invoice_force_number/i18n/hr_HR.po
  account_invoice_force_number/i18n/id.po
  account_invoice_force_number/i18n/it.po
  account_invoice_force_number/i18n/ja.po
  account_invoice_force_number/i18n/lt.po
  account_invoice_force_number/i18n/mk.po
  account_invoice_force_number/i18n/mn.po
  account_invoice_force_number/i18n/nb_NO.po
  account_invoice_force_number/i18n/nl.po
  account_invoice_force_number/i18n/nl_BE.po
  account_invoice_force_number/i18n/pl.po
  account_invoice_force_number/i18n/pt.po
  account_invoice_force_number/i18n/pt_BR.po
  account_invoice_force_number/i18n/pt_PT.po
  account_invoice_force_number/i18n/ro.po
  account_invoice_force_number/i18n/ru.po
  account_invoice_force_number/i18n/sk_SK.po
  account_invoice_force_number/i18n/sl.po
  account_invoice_force_number/i18n/sv.po
  account_invoice_force_number/i18n/th.po
  account_invoice_force_number/i18n/tr.po
  account_invoice_force_number/i18n/tr_TR.po
  account_invoice_force_number/i18n/zh_CN.po
  account_invoice_force_number/i18n/zh_TW.po
  account_invoice_force_number/models/__init__.py
  account_invoice_force_number/models/account_move.py
  account_invoice_force_number/readme/CONFIGURE.rst
  account_invoice_force_number/readme/CONTRIBUTORS.rst
  account_invoice_force_number/readme/DESCRIPTION.rst
  account_invoice_force_number/readme/USAGE.rst
  account_invoice_force_number/security/security.xml
  account_invoice_force_number/static/description/icon.png
  account_invoice_force_number/static/description/index.html
  account_invoice_force_number/tests/__init__.py
  account_invoice_force_number/tests/test_account_force_number.py
  account_invoice_force_number/views/account_move_view.xml
  setup/account_invoice_force_number/odoo/addons/account_invoice_force_number
  setup/account_invoice_force_number/setup.py
Labels: approved, bot is merging ⏳

#884 [13.0][ADD] account_move_exception & account_move_post_block
  account_move_exception/__init__.py
  account_move_exception/__manifest__.py
  account_move_exception/data/account_exception_data.xml
  account_move_exception/init_hook.py
  account_move_exception/models/__init__.py
  account_move_exception/models/account_move.py
  account_move_exception/models/account_move_line.py
  account_move_exception/models/exception_rule.py
  account_move_exception/readme/CONTRIBUTORS.rst
  account_move_exception/readme/DESCRIPTION.rst
  account_move_exception/readme/USAGE.rst
  account_move_exception/static/description/icon.png
  account_move_exception/tests/__init__.py
  account_move_exception/tests/test_account_exception.py
  account_move_exception/views/account_view.xml
  account_move_exception/wizard/__init__.py
  account_move_exception/wizard/account_exception_confirm.py
  account_move_exception/wizard/account_exception_confirm_view.xml
  account_move_post_block/__init__.py
  account_move_post_block/__manifest__.py
  account_move_post_block/data/account_exception_data.xml
  account_move_post_block/models/__init__.py
  account_move_post_block/models/account_move.py
  account_move_post_block/models/account_post_block_reason.py
  account_move_post_block/readme/CONFIGURE.rst
  account_move_post_block/readme/CONTRIBUTORS.rst
  account_move_post_block/readme/DESCRIPTION.rst
  account_move_post_block/readme/USAGE.rst
  account_move_post_block/security/account_move_post_block_security.xml
  account_move_post_block/security/ir.model.access.csv
  account_move_post_block/static/description/icon.png
  account_move_post_block/tests/__init__.py
  account_move_post_block/tests/test_account_move_post_block.py
  account_move_post_block/tests/test_am_post_block_reason.py
  account_move_post_block/views/account_move_view.xml
  account_move_post_block/views/account_post_block_reason_view.xml
  account_move_post_block/wizard/__init__.py
  account_move_post_block/wizard/account_exception_confirm.py
Labels: approved, bot is merging ⏳, ready to merge

#853 [14.0][MIG] account_move_tier_validation
  account_move_tier_validation/README.rst
  account_move_tier_validation/__init__.py
  account_move_tier_validation/__manifest__.py
  account_move_tier_validation/i18n/account_move_tier_validation.pot
  account_move_tier_validation/i18n/zh_CN.po
  account_move_tier_validation/models/__init__.py
  account_move_tier_validation/models/account_move.py
  account_move_tier_validation/models/tier_definition.py
  account_move_tier_validation/readme/CONFIGURE.rst
  account_move_tier_validation/readme/CONTRIBUTORS.rst
  account_move_tier_validation/readme/DESCRIPTION.rst
  account_move_tier_validation/readme/INSTALL.rst
  account_move_tier_validation/readme/USAGE.rst
  account_move_tier_validation/static/description/icon.png
  account_move_tier_validation/static/description/index.html
  account_move_tier_validation/tests/__init__.py
  account_move_tier_validation/tests/common.py
  account_move_tier_validation/tests/test_tier_validation.py
  account_move_tier_validation/tests/tier_validation_tester.py
  account_move_tier_validation/views/account_move_view.xml
  setup/account_move_tier_validation/odoo/addons/account_move_tier_validation
  setup/account_move_tier_validation/setup.py
Labels: approved, bot is merging ⏳, ready to merge
