Repository OCA/account-invoicing, pull requests merged in 2021-06, with the labels that each got.

#947 [FIX] account_invoice_supplier_self_invoice: fix migration script from 12 to 13
  account_invoice_supplier_self_invoice/migrations/13.0.1.0.0/post-migration.py
  account_invoice_supplier_self_invoice/models/account_move.py
  account_invoice_supplier_self_invoice/readme/USAGE.rst
  account_invoice_supplier_self_invoice/views/report_self_invoice.xml
  account_invoice_supplier_self_invoice/views/res_partner_views.xml
Labels: approved, bot is merging ⏳, ready to merge

#956 [FIX] purchase_stock_picking_return_invoicing: consider context properly
  purchase_stock_picking_return_invoicing/models/purchase_order.py
Labels: bot is merging ⏳

#957 [13.0][account_move_tier_validation][fix] filter Validation Not Started is not working correctly
  account_move_tier_validation/views/account_move_view.xml
Labels: approved, bot is merging ⏳

#912 [13.0] [FIX] account_invoice_fiscal_position_update: Filter only lines without comments or notes.
  account_invoice_fiscal_position_update/models/account_invoice.py
  account_invoice_pricelist/tests/test_account_move_pricelist.py
Labels: approved, bot is merging ⏳, ready to merge

#961 [13.0][FIX] account_global_discount: Prevent error when add more taxes in multi-lines from invoices when global discount is empty
  account_global_discount/models/account_move.py
Labels: approved, bot is merging ⏳
