Repository OCA/account-invoicing, pull requests merged in 2021-05, with the labels that each got.

#926 [FIX] account_invoice_refund_link: index origin_line_id
  account_invoice_refund_link/models/account_move.py
Labels: approved, bot is merging ⏳

#925 [ADD] account_tax_group_widget_base_amount: New module
  account_tax_group_widget_base_amount/README.rst
  account_tax_group_widget_base_amount/__init__.py
  account_tax_group_widget_base_amount/__manifest__.py
  account_tax_group_widget_base_amount/i18n/account_tax_group_widget_base_amount.pot
  account_tax_group_widget_base_amount/i18n/es.po
  account_tax_group_widget_base_amount/readme/CONTRIBUTORS.rst
  account_tax_group_widget_base_amount/readme/DESCRIPTION.rst
  account_tax_group_widget_base_amount/readme/ROADMAP.rst
  account_tax_group_widget_base_amount/static/description/account_tax_group_widget_base_amount.png
  account_tax_group_widget_base_amount/static/description/icon.png
  account_tax_group_widget_base_amount/static/description/index.html
  account_tax_group_widget_base_amount/static/src/xml/tax_group.xml
  setup/account_tax_group_widget_base_amount/odoo/addons/account_tax_group_widget_base_amount
  setup/account_tax_group_widget_base_amount/setup.py
Labels: approved, bot is merging ⏳

#922 [11.0] Fix No update cron data purchase_batch_invoicing
  purchase_batch_invoicing/data/ir_cron_data.xml
Labels: bot is merging ⏳

#930 13.0 mig account invoice tax note
  account_invoice_tax_note/README.rst
  account_invoice_tax_note/__init__.py
  account_invoice_tax_note/__manifest__.py
  account_invoice_tax_note/i18n/account_invoice_tax_note.pot
  account_invoice_tax_note/i18n/de.po
  account_invoice_tax_note/i18n/fr.po
  account_invoice_tax_note/models/__init__.py
  account_invoice_tax_note/models/account_move.py
  account_invoice_tax_note/models/account_tax_group.py
  account_invoice_tax_note/readme/CONTRIBUTORS.rst
  account_invoice_tax_note/readme/DESCRIPTION.rst
  account_invoice_tax_note/readme/USAGE.rst
  account_invoice_tax_note/reports/report_invoice_document.xml
  account_invoice_tax_note/static/description/icon.png
  account_invoice_tax_note/static/description/index.html
  account_invoice_tax_note/tests/__init__.py
  account_invoice_tax_note/tests/test_account_invoice.py
Labels: bot is merging ⏳

#838 [MIG] account_invoice_section_sale_order: Migration to 14.0
  account_invoice_section_sale_order/README.rst
  account_invoice_section_sale_order/__init__.py
  account_invoice_section_sale_order/__manifest__.py
  account_invoice_section_sale_order/i18n/account_invoice_section_sale_order.pot
  account_invoice_section_sale_order/models/__init__.py
  account_invoice_section_sale_order/models/sale_order.py
  account_invoice_section_sale_order/readme/CONTRIBUTORS.rst
  account_invoice_section_sale_order/readme/CREDITS.rst
  account_invoice_section_sale_order/readme/DESCRIPTION.rst
  account_invoice_section_sale_order/static/description/icon.png
  account_invoice_section_sale_order/static/description/index.html
  account_invoice_section_sale_order/tests/__init__.py
  account_invoice_section_sale_order/tests/test_invoice_group_by_sale_order.py
Labels: bot is merging ⏳

#923 [13.0][FIX] purchase_batch_invoicing: Remove from invoice lines with no quantity
  purchase_batch_invoicing/README.rst
  purchase_batch_invoicing/__init__.py
  purchase_batch_invoicing/models/__init__.py
  purchase_batch_invoicing/models/account_move.py
  purchase_batch_invoicing/readme/CONTRIBUTORS.rst
  purchase_batch_invoicing/readme/DESCRIPTION.rst
  purchase_batch_invoicing/static/description/index.html
  purchase_batch_invoicing/tests/test_invoicing.py
  purchase_batch_invoicing/wizards/purchase_batch_invoicing.py
  purchase_batch_invoicing/wizards/purchase_batch_invoicing_view.xml
Labels: bot is merging ⏳

#921 [13.0][ADD] account_invoice_tree_currency
  account_invoice_tree_currency/__init__.py
  account_invoice_tree_currency/__manifest__.py
  account_invoice_tree_currency/readme/CONTRIBUTORS.rst
  account_invoice_tree_currency/readme/DESCRIPTION.rst
  account_invoice_tree_currency/static/description/icon.png
  account_invoice_tree_currency/views/account_move_view.xml
Labels: approved, bot is merging ⏳, ready to merge

#933 [13.0][FIX] account_move_post_block:
  account_move_post_block/views/account_move_view.xml
  account_move_post_block/views/account_post_block_reason_view.xml
Labels: approved, bot is merging ⏳

#936 [13.0][IMP]account_move_exception&account_move_post_block
  account_move_exception/views/account_view.xml
  account_move_post_block/data/account_exception_data.xml
Labels: approved, bot is merging ⏳

#944 [13.0][FIX] sale_order_invoicing_grouping_criteria:
  sale_order_invoicing_grouping_criteria/models/sale_order.py
  sale_order_invoicing_grouping_criteria/tests/test_sale_order_invoicing_group_criteria.py
Labels: approved, bot is merging ⏳, ready to merge
