Repository OCA/account-invoicing, pull requests merged in 2021-07, with the labels that each got.

#954 [MIG] account_invoice_refund_line_selection: Migration to 13.0
  account_invoice_refund_line_selection/README.rst
  account_invoice_refund_line_selection/__init__.py
  account_invoice_refund_line_selection/__manifest__.py
  account_invoice_refund_line_selection/i18n/account_invoice_refund_line_selection.pot
  account_invoice_refund_line_selection/i18n/de.po
  account_invoice_refund_line_selection/i18n/es.po
  account_invoice_refund_line_selection/readme/CONTRIBUTORS.rst
  account_invoice_refund_line_selection/readme/DESCRIPTION.rst
  account_invoice_refund_line_selection/readme/USAGE.rst
  account_invoice_refund_line_selection/static/description/icon.png
  account_invoice_refund_line_selection/static/description/index.html
  account_invoice_refund_line_selection/tests/__init__.py
  account_invoice_refund_line_selection/tests/test_refund_line.py
  account_invoice_refund_line_selection/wizards/__init__.py
  account_invoice_refund_line_selection/wizards/account_move_reversal.py
  account_invoice_refund_line_selection/wizards/account_move_reversal_view.xml
  setup/account_invoice_refund_line_selection/odoo/addons/account_invoice_refund_line_selection
  setup/account_invoice_refund_line_selection/setup.py
Labels: approved, bot is merging ⏳, ready to merge

#969 [12.0][IMP] stock_picking_invoicing: add action_invoice_draft method
  stock_picking_invoicing/models/account_invoice.py
Labels: approved, bot is merging ⏳

#960 [13.0][ADD] sale_line_refund_to_invoice_qty
  sale_line_refund_to_invoice_qty/README.rst
  sale_line_refund_to_invoice_qty/__init__.py
  sale_line_refund_to_invoice_qty/__manifest__.py
  sale_line_refund_to_invoice_qty/models/__init__.py
  sale_line_refund_to_invoice_qty/models/account.py
  sale_line_refund_to_invoice_qty/models/sale.py
  sale_line_refund_to_invoice_qty/readme/CONTRIBUTORS.rst
  sale_line_refund_to_invoice_qty/readme/DESCRIPTION.rst
  sale_line_refund_to_invoice_qty/readme/USAGE.rst
  sale_line_refund_to_invoice_qty/static/description/icon.png
  sale_line_refund_to_invoice_qty/static/description/index.html
  sale_line_refund_to_invoice_qty/tests/__init__.py
  sale_line_refund_to_invoice_qty/tests/test_sale_line_refund_to_invoice_qty.py
  sale_line_refund_to_invoice_qty/views/account_move_views.xml
  sale_line_refund_to_invoice_qty/views/sale_order_views.xml
  sale_line_refund_to_invoice_qty/wizards/__init__.py
  sale_line_refund_to_invoice_qty/wizards/account_move_reversal.py
  sale_line_refund_to_invoice_qty/wizards/account_move_reversal_view.xml
  setup/sale_line_refund_to_invoice_qty/odoo/addons/sale_line_refund_to_invoice_qty
  setup/sale_line_refund_to_invoice_qty/setup.py
Labels: approved, bot is merging ⏳, ready to merge

#871 [12.0][MIG] account_invoice_tier_validation
  account_invoice_tier_validation/README.rst
  account_invoice_tier_validation/__init__.py
  account_invoice_tier_validation/__manifest__.py
  account_invoice_tier_validation/demo/account_invoice_tier_definition.xml
  account_invoice_tier_validation/i18n/account_invoice_tier_validation.pot
  account_invoice_tier_validation/models/__init__.py
  account_invoice_tier_validation/models/account_invoice.py
  account_invoice_tier_validation/models/tier_definition.py
  account_invoice_tier_validation/readme/CONFIGURE.rst
  account_invoice_tier_validation/readme/CONTRIBUTORS.rst
  account_invoice_tier_validation/readme/DESCRIPTION.rst
  account_invoice_tier_validation/readme/USAGE.rst
  account_invoice_tier_validation/static/description/icon.png
  account_invoice_tier_validation/static/description/index.html
  account_invoice_tier_validation/tests/__init__.py
  account_invoice_tier_validation/tests/test_account_invoice_tier_validation.py
  account_invoice_tier_validation/views/account_invoice_view.xml
  oca_dependencies.txt
Labels: approved, bot is merging ⏳, ready to merge

#967 [13.0][FIX+REF] account_global_discount: Include taxes in global discount move lines
  account_global_discount/__manifest__.py
  account_global_discount/migrations/13.0.2.0.0/post-migration.py
  account_global_discount/models/account_move.py
  account_global_discount/readme/ROADMAP.rst
  account_global_discount/tests/test_global_discount.py
  account_global_discount/views/account_invoice_views.xml
Labels: approved, bot is merging ⏳, ready to merge

#820 [14.0][ADD] account_invoice_payment_retention
  account_invoice_payment_retention/README.rst
  account_invoice_payment_retention/__init__.py
  account_invoice_payment_retention/__manifest__.py
  account_invoice_payment_retention/models/__init__.py
  account_invoice_payment_retention/models/account_move.py
  account_invoice_payment_retention/models/account_payment.py
  account_invoice_payment_retention/models/res_company.py
  account_invoice_payment_retention/models/res_config_settings.py
  account_invoice_payment_retention/readme/CONFIGURE.rst
  account_invoice_payment_retention/readme/CONTRIBUTORS.rst
  account_invoice_payment_retention/readme/DESCRIPTION.rst
  account_invoice_payment_retention/readme/USAGE.rst
  account_invoice_payment_retention/security/security.xml
  account_invoice_payment_retention/static/description/index.html
  account_invoice_payment_retention/tests/__init__.py
  account_invoice_payment_retention/tests/test_invoice_payment_retention.py
  account_invoice_payment_retention/views/account_move_views.xml
  account_invoice_payment_retention/views/res_config_settings_views.xml
  account_invoice_payment_retention/wizard/account_payment_register_views.xml
Labels: approved, bot is merging ⏳, ready to merge

#976 [13.0][FIX] account_invoice_tax_required: Restore multi-record support in action_post
  account_invoice_tax_required/models/account_move.py
Labels: bot is merging ⏳

#978 [13.0][FIX] account_invoice_date_due: restore multi-record handling in write()
  account_invoice_date_due/models/account_move.py
Labels: bot is merging ⏳

#974 [13.0][MIG/REF] product_supplierinfo_for_customer_invoice
  oca_dependencies.txt
  product_supplierinfo_for_customer_invoice/README.rst
  product_supplierinfo_for_customer_invoice/__init__.py
  product_supplierinfo_for_customer_invoice/__manifest__.py
  product_supplierinfo_for_customer_invoice/i18n/de.po
  product_supplierinfo_for_customer_invoice/i18n/es.po
  product_supplierinfo_for_customer_invoice/i18n/it.po
  product_supplierinfo_for_customer_invoice/i18n/product_supplierinfo_for_customer_invoice.pot
  product_supplierinfo_for_customer_invoice/i18n/pt.po
  product_supplierinfo_for_customer_invoice/i18n/pt_BR.po
  product_supplierinfo_for_customer_invoice/models/__init__.py
  product_supplierinfo_for_customer_invoice/models/account_move_line.py
  product_supplierinfo_for_customer_invoice/readme/CONTRIBUTORS.rst
  product_supplierinfo_for_customer_invoice/readme/DESCRIPTION.rst
  product_supplierinfo_for_customer_invoice/static/description/icon.png
  product_supplierinfo_for_customer_invoice/static/description/index.html
  product_supplierinfo_for_customer_invoice/tests/__init__.py
  product_supplierinfo_for_customer_invoice/tests/test_product_supplierinfo_for_customer_invoice.py
  product_supplierinfo_for_customer_invoice/views/account_move_view.xml
  setup/product_supplierinfo_for_customer_invoice/odoo/addons/product_supplierinfo_for_customer_invoice
  setup/product_supplierinfo_for_customer_invoice/setup.py
Labels: approved, bot is merging ⏳, ready to merge

#975 [14.0][ADD] account_move_original_partner
  account_move_original_partner/__init__.py
  account_move_original_partner/__manifest__.py
  account_move_original_partner/hooks.py
  account_move_original_partner/models/__init__.py
  account_move_original_partner/models/account_move.py
  account_move_original_partner/readme/CONTRIBUTORS.rst
  account_move_original_partner/readme/CREDITS.rst
  account_move_original_partner/readme/DESCRIPTION.rst
  account_move_original_partner/static/description/icon.png
  account_move_original_partner/views/account_move.xml
  setup/account_move_original_partner/odoo/addons/account_move_original_partner
  setup/account_move_original_partner/setup.py
Labels: approved, bot is merging ⏳, ready to merge
