Repository OCA/account-invoicing, pull requests merged in 2022-10, with the labels that each got.

#1262 [14.0][FIX] account_receipt_print: delete replace label date
  account_receipt_print/views/report_receipt.xml
Labels: bot is merging ⏳

#472 [11.0][add][account_invoice_supplier_self_invoice_tax_note]
  account_invoice_supplier_self_invoice_tax_note/README.rst
  account_invoice_supplier_self_invoice_tax_note/__init__.py
  account_invoice_supplier_self_invoice_tax_note/__manifest__.py
  account_invoice_supplier_self_invoice_tax_note/readme/CONTRIBUTORS.rst
  account_invoice_supplier_self_invoice_tax_note/readme/DESCRIPTION.rst
  account_invoice_supplier_self_invoice_tax_note/readme/INSTALL.rst
  account_invoice_supplier_self_invoice_tax_note/static/description/icon.png
  account_invoice_supplier_self_invoice_tax_note/static/description/index.html
  account_invoice_supplier_self_invoice_tax_note/views/report_self_invoice.xml
Labels: needs fixing, approved, ready to merge, bot is merging ⏳

#1256 [14.0] [FIX] account_invoice_triple_discount: Fix precision when compute discount
  account_invoice_triple_discount/models/account_move.py
  account_invoice_triple_discount/tests/test_invoice_triple_discount.py
Labels: approved, ready to merge, bot is merging ⏳

#1258 [16][MIG] account invoice blocking: Migration to 16.0
  account_invoice_blocking/README.rst
  account_invoice_blocking/__init__.py
  account_invoice_blocking/__manifest__.py
  account_invoice_blocking/i18n/account_invoice_blocking.pot
  account_invoice_blocking/i18n/de.po
  account_invoice_blocking/i18n/es.po
  account_invoice_blocking/i18n/hr.po
  account_invoice_blocking/i18n/nl.po
  account_invoice_blocking/i18n/pt.po
  account_invoice_blocking/i18n/pt_BR.po
  account_invoice_blocking/models/__init__.py
  account_invoice_blocking/models/account_move.py
  account_invoice_blocking/readme/CONTRIBUTORS.rst
  account_invoice_blocking/readme/DESCRIPTION.rst
  account_invoice_blocking/readme/ROADMAP.rst
  account_invoice_blocking/readme/USAGE.rst
  account_invoice_blocking/static/description/icon.png
  account_invoice_blocking/static/description/index.html
  account_invoice_blocking/tests/__init__.py
  account_invoice_blocking/tests/test_account_move_blocking.py
  account_invoice_blocking/views/account_move.xml
  setup/account_invoice_blocking/odoo/addons/account_invoice_blocking
  setup/account_invoice_blocking/setup.py
Labels: approved, ready to merge

#1268 [13.0][MIG] account invoice refund reason: Migration to 13
  account_invoice_refund_reason/README.rst
  account_invoice_refund_reason/__init__.py
  account_invoice_refund_reason/__manifest__.py
  account_invoice_refund_reason/data/account.invoice.refund.reason.csv
  account_invoice_refund_reason/i18n/account_invoice_refund_reason.pot
  account_invoice_refund_reason/i18n/de.po
  account_invoice_refund_reason/i18n/es.po
  account_invoice_refund_reason/i18n/hr.po
  account_invoice_refund_reason/models/__init__.py
  account_invoice_refund_reason/models/account_invoice_refund_reason.py
  account_invoice_refund_reason/models/account_move.py
  account_invoice_refund_reason/readme/CONFIGURE.rst
  account_invoice_refund_reason/readme/CONTRIBUTORS.rst
  account_invoice_refund_reason/readme/DESCRIPTION.rst
  account_invoice_refund_reason/readme/USAGE.rst
  account_invoice_refund_reason/security/ir.model.access.csv
  account_invoice_refund_reason/static/description/icon.png
  account_invoice_refund_reason/static/description/index.html
  account_invoice_refund_reason/tests/__init__.py
  account_invoice_refund_reason/tests/test_account_invoice_refund_reason.py
  account_invoice_refund_reason/views/account_invoice_refund_reason_view.xml
  account_invoice_refund_reason/views/account_move_view.xml
  account_invoice_refund_reason/wizard/__init__.py
  account_invoice_refund_reason/wizard/account_move_reversal.py
  account_invoice_refund_reason/wizard/account_move_reversal_view.xml
  setup/account_invoice_refund_reason/odoo/addons/account_invoice_refund_reason
  setup/account_invoice_refund_reason/setup.py
Labels: approved, bot is merging ⏳

#1270 [13.0][IMP] account_invoice_refund_reason: active and description fields
  account_invoice_refund_reason/models/account_invoice_refund_reason.py
  account_invoice_refund_reason/views/account_invoice_refund_reason_view.xml
Labels: approved, bot is merging ⏳

#1265 [15.0][mig] account_invoice_blocking
  account_invoice_blocking/README.rst
  account_invoice_blocking/__init__.py
  account_invoice_blocking/__manifest__.py
  account_invoice_blocking/i18n/account_invoice_blocking.pot
  account_invoice_blocking/i18n/de.po
  account_invoice_blocking/i18n/es.po
  account_invoice_blocking/i18n/hr.po
  account_invoice_blocking/i18n/nl.po
  account_invoice_blocking/i18n/pt.po
  account_invoice_blocking/i18n/pt_BR.po
  account_invoice_blocking/models/__init__.py
  account_invoice_blocking/models/account_move.py
  account_invoice_blocking/readme/CONTRIBUTORS.rst
  account_invoice_blocking/readme/DESCRIPTION.rst
  account_invoice_blocking/readme/ROADMAP.rst
  account_invoice_blocking/readme/USAGE.rst
  account_invoice_blocking/static/description/icon.png
  account_invoice_blocking/static/description/index.html
  account_invoice_blocking/tests/__init__.py
  account_invoice_blocking/tests/test_account_move_blocking.py
  account_invoice_blocking/views/account_move.xml
  setup/account_invoice_blocking/odoo/addons/account_invoice_blocking
  setup/account_invoice_blocking/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#1275 [15.0][ADD] portal_account_personal_data_only: display only own invoices in portal
  portal_account_personal_data_only/README.rst
  portal_account_personal_data_only/__init__.py
  portal_account_personal_data_only/__manifest__.py
  portal_account_personal_data_only/hooks.py
  portal_account_personal_data_only/readme/CONTRIBUTORS.rst
  portal_account_personal_data_only/readme/DESCRIPTION.rst
  portal_account_personal_data_only/readme/USAGE.rst
  portal_account_personal_data_only/security/security.xml
  portal_account_personal_data_only/static/description/icon.png
  portal_account_personal_data_only/static/description/index.html
  portal_account_personal_data_only/tests/__init__.py
  portal_account_personal_data_only/tests/test_partner_access.py
  setup/portal_account_personal_data_only/odoo/addons/portal_account_personal_data_only
  setup/portal_account_personal_data_only/setup.py
Labels: needs review, approved, bot is merging ⏳

#1273 [14.0][MIG] account_invoice_refund_reason
  account_invoice_refund_reason/README.rst
  account_invoice_refund_reason/__init__.py
  account_invoice_refund_reason/__manifest__.py
  account_invoice_refund_reason/data/account.move.refund.reason.csv
  account_invoice_refund_reason/i18n/account_invoice_refund_reason.pot
  account_invoice_refund_reason/i18n/de.po
  account_invoice_refund_reason/i18n/es.po
  account_invoice_refund_reason/i18n/hr.po
  account_invoice_refund_reason/migrations/14.0.1.0.0/pre-migration.py
  account_invoice_refund_reason/models/__init__.py
  account_invoice_refund_reason/models/account_move.py
  account_invoice_refund_reason/models/account_move_refund_reason.py
  account_invoice_refund_reason/readme/CONFIGURE.rst
  account_invoice_refund_reason/readme/CONTRIBUTORS.rst
  account_invoice_refund_reason/readme/DESCRIPTION.rst
  account_invoice_refund_reason/readme/USAGE.rst
  account_invoice_refund_reason/security/ir.model.access.csv
  account_invoice_refund_reason/static/description/icon.png
  account_invoice_refund_reason/static/description/index.html
  account_invoice_refund_reason/tests/__init__.py
  account_invoice_refund_reason/tests/test_account_invoice_refund_reason.py
  account_invoice_refund_reason/views/account_move_refund_reason_view.xml
  account_invoice_refund_reason/views/account_move_view.xml
  account_invoice_refund_reason/wizard/__init__.py
  account_invoice_refund_reason/wizard/account_move_reversal.py
  account_invoice_refund_reason/wizard/account_move_reversal_view.xml
  setup/account_invoice_refund_reason/odoo/addons/account_invoice_refund_reason
  setup/account_invoice_refund_reason/setup.py
Labels: approved, ready to merge, bot is merging ⏳
