Repository OCA/account-invoicing, pull requests merged in 2022-04, with the labels that each got.

#1085 [MIG] account_invoice_blocking: Migration to 14.0
  account_invoice_blocking/README.rst
  account_invoice_blocking/__init__.py
  account_invoice_blocking/__manifest__.py
  account_invoice_blocking/i18n/account_invoice_blocking.pot
  account_invoice_blocking/i18n/de.po
  account_invoice_blocking/i18n/es.po
  account_invoice_blocking/i18n/hr.po
  account_invoice_blocking/i18n/nl.po
  account_invoice_blocking/i18n/pt.po
  account_invoice_blocking/i18n/pt_BR.po
  account_invoice_blocking/models/__init__.py
  account_invoice_blocking/models/account_move.py
  account_invoice_blocking/readme/CONTRIBUTORS.rst
  account_invoice_blocking/readme/DESCRIPTION.rst
  account_invoice_blocking/readme/ROADMAP.rst
  account_invoice_blocking/readme/USAGE.rst
  account_invoice_blocking/static/description/icon.png
  account_invoice_blocking/static/description/index.html
  account_invoice_blocking/tests/__init__.py
  account_invoice_blocking/tests/test_account_move_blocking.py
  account_invoice_blocking/views/account_move.xml
  setup/account_invoice_blocking/odoo/addons/account_invoice_blocking
  setup/account_invoice_blocking/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#1129 [14.0][FIX] account_billing: minor fixes
  account_billing/models/account_move.py
  account_billing/security/ir.model.access.csv
Labels: bot is merging ⏳

#1128 [13.0][FIX] account_billing: minor fixes
  account_billing/models/account_move.py
  account_billing/security/ir.model.access.csv
  account_billing/tests/test_account_billing.py
Labels: approved, bot is merging ⏳

#1130 Added copier from template
  .copier-answers.yml
  .eslintrc.yml
  .github/workflows/pre-commit.yml
  .github/workflows/test.yml
  .pre-commit-config.yaml
  .pre-commit-config.yaml.rej
  .travis.yml
  README.md
  account_move_post_block/__manifest__.py
  account_move_tier_validation_approver/__manifest__.py
Labels: approved

#1131 [FIX] account_invoice_refund_line_selection: Business fields were missing
  account_invoice_refund_line_selection/wizards/account_move_reversal.py
Labels: approved, bot is merging ⏳

#1125 [14.0][REF] account_invoice_payment_retention
  account_invoice_payment_retention/models/account_move.py
Labels: approved, bot is merging ⏳

#1141 [14.0][FIX] account_invoice_fiscal_position_update: fix tests
  account_invoice_blocking/tests/test_account_move_blocking.py
  account_invoice_fiscal_position_update/tests/test_inv_fiscal_pos_update.py
  account_invoice_force_number/tests/test_account_force_number.py
  account_invoice_refund_line_selection/tests/test_refund_line.py
  account_invoice_tax_required/tests/test_account_move_tax_required.py
  account_move_propagate_ref/tests/test_propagate_ref.py
Labels: needs review, approved, bot is merging ⏳

#1058 [14.0][FIX] account_invoice_payment_retention, return retention with …
  account_invoice_payment_retention/models/account_move.py
Labels: approved, bot is merging ⏳
