Repository OCA/account-invoicing, pull requests merged in 2022-02, with the labels that each got.

#1091 [14.0][FIX] stock_picking_invoicing: fix access right issues when using actions
  stock_picking_invoicing/wizards/stock_invoice_onshipping.py
Labels: approved, bot is merging ⏳

#1016 [12.0][FIX] account_invoice_pricelist: Use right date context
  account_invoice_pricelist/models/account_invoice.py
Labels: approved, bot is merging ⏳

#570 [12.0] account_invoice_transmit_method: use base_view_inheritance_extension
  account_invoice_transmit_method/__manifest__.py
  account_invoice_transmit_method/views/partner.xml
  oca_dependencies.txt
Labels: bot is merging ⏳

#1102 [14.0][FIX][BUG] Get the current company should be made with self.env.company
  stock_picking_invoicing/models/stock_move.py
  stock_picking_invoicing/wizards/stock_invoice_onshipping.py
Labels: approved, bot is merging ⏳

#1095 [13.0][FIX][BUG] Get the current company should be made with self.env.company
  stock_picking_invoicing/models/stock_move.py
  stock_picking_invoicing/wizards/stock_invoice_onshipping.py
Labels: approved, ready to merge, bot is merging ⏳

#990 [14.0][MIG] account_global_discount
  account_global_discount/README.rst
  account_global_discount/__init__.py
  account_global_discount/__manifest__.py
  account_global_discount/i18n/.empty
  account_global_discount/i18n/account_global_discount.pot
  account_global_discount/i18n/es.po
  account_global_discount/i18n/nl_NL.po
  account_global_discount/i18n/pt.po
  account_global_discount/models/__init__.py
  account_global_discount/models/account_move.py
  account_global_discount/models/global_discount.py
  account_global_discount/readme/CONFIGURE.rst
  account_global_discount/readme/CONTRIBUTORS.rst
  account_global_discount/readme/DESCRIPTION.rst
  account_global_discount/readme/ROADMAP.rst
  account_global_discount/readme/USAGE.rst
  account_global_discount/report/__init__.py
  account_global_discount/report/account_invoice_report.py
  account_global_discount/security/ir.model.access.csv
  account_global_discount/security/security.xml
  account_global_discount/static/description/icon.png
  account_global_discount/static/description/icon.svg
  account_global_discount/static/description/index.html
  account_global_discount/tests/__init__.py
  account_global_discount/tests/test_global_discount.py
  account_global_discount/views/account_invoice_views.xml
  account_global_discount/views/global_discount_views.xml
  account_global_discount/views/report_account_invoice.xml
  setup/account_global_discount/odoo/addons/account_global_discount
  setup/account_global_discount/setup.py
Labels: bot is merging ⏳

#1043 [15.0][MIG] account_invoice_tree_currency: Migration to 15.0
  account_invoice_refund_link/__manifest__.py
  account_invoice_tree_currency/README.rst
  account_invoice_tree_currency/__init__.py
  account_invoice_tree_currency/__manifest__.py
  account_invoice_tree_currency/i18n/account_invoice_tree_currency.pot
  account_invoice_tree_currency/readme/CONTRIBUTORS.rst
  account_invoice_tree_currency/readme/DESCRIPTION.rst
  account_invoice_tree_currency/static/description/icon.png
  account_invoice_tree_currency/static/description/index.html
  account_invoice_tree_currency/views/account_move_view.xml
  setup/account_invoice_tree_currency/odoo/addons/account_invoice_tree_currency
  setup/account_invoice_tree_currency/setup.py
Labels: approved, bot is merging ⏳

#1044 [15.0][MIG] account_invoice_date_due: Migration to 15.0
  account_invoice_date_due/README.rst
  account_invoice_date_due/__init__.py
  account_invoice_date_due/__manifest__.py
  account_invoice_date_due/i18n/account_invoice_date_due.pot
  account_invoice_date_due/i18n/de.po
  account_invoice_date_due/i18n/es.po
  account_invoice_date_due/i18n/fr.po
  account_invoice_date_due/i18n/fr_FR.po
  account_invoice_date_due/models/__init__.py
  account_invoice_date_due/models/account_move.py
  account_invoice_date_due/readme/CONFIGURE.rst
  account_invoice_date_due/readme/CONTRIBUTORS.rst
  account_invoice_date_due/readme/DESCRIPTION.rst
  account_invoice_date_due/readme/USAGE.rst
  account_invoice_date_due/security/security.xml
  account_invoice_date_due/static/description/icon.png
  account_invoice_date_due/static/description/index.html
  account_invoice_date_due/tests/__init__.py
  account_invoice_date_due/tests/test_account_invoice_date_due.py
  account_invoice_date_due/views/account_move_date_due.xml
  setup/account_invoice_date_due/odoo/addons/account_invoice_date_due
  setup/account_invoice_date_due/setup.py
Labels: approved, bot is merging ⏳
