Repository OCA/account-invoicing, pull requests merged in 2022-05, with the labels that each got.

#1149 Updated from template
  .copier-answers.yml
  .github/workflows/test.yml
  .pylintrc
  .pylintrc-mandatory
  .travis.yml
  README.md
Labels: approved, bot is merging ⏳

#1065 [14.0][FIX] account_invoice_transmit_method: fix partner form view inheritance
  account_invoice_transmit_method/views/partner.xml
Labels: bot is merging ⏳

#1104 [MIG] account_invoice_change_currency: Migration to 14.0
  account_invoice_change_currency/README.rst
  account_invoice_change_currency/__init__.py
  account_invoice_change_currency/__manifest__.py
  account_invoice_change_currency/i18n/account_invoice_change_currency.pot
  account_invoice_change_currency/i18n/de.po
  account_invoice_change_currency/i18n/es.po
  account_invoice_change_currency/i18n/es_MX.po
  account_invoice_change_currency/i18n/hr.po
  account_invoice_change_currency/models/__init__.py
  account_invoice_change_currency/models/account_move.py
  account_invoice_change_currency/models/account_move_line.py
  account_invoice_change_currency/models/res_currency.py
  account_invoice_change_currency/readme/CONFIGURE.rst
  account_invoice_change_currency/readme/CONTRIBUTORS.rst
  account_invoice_change_currency/readme/DESCRIPTION.rst
  account_invoice_change_currency/readme/USAGE.rst
  account_invoice_change_currency/static/description/icon.png
  account_invoice_change_currency/static/description/index.html
  account_invoice_change_currency/tests/__init__.py
  account_invoice_change_currency/tests/test_account_invoice_change_currency.py
  account_invoice_change_currency/views/account_move_views.xml
  setup/account_invoice_change_currency/odoo/addons/account_invoice_change_currency
  setup/account_invoice_change_currency/setup.py
Labels: needs review, approved, ready to merge

#1161 [MIG] account_invoice_change_currency: Migration to 15.0
  account_invoice_change_currency/README.rst
  account_invoice_change_currency/__init__.py
  account_invoice_change_currency/__manifest__.py
  account_invoice_change_currency/i18n/account_invoice_change_currency.pot
  account_invoice_change_currency/i18n/de.po
  account_invoice_change_currency/i18n/es.po
  account_invoice_change_currency/i18n/es_MX.po
  account_invoice_change_currency/i18n/hr.po
  account_invoice_change_currency/models/__init__.py
  account_invoice_change_currency/models/account_move.py
  account_invoice_change_currency/models/account_move_line.py
  account_invoice_change_currency/models/res_currency.py
  account_invoice_change_currency/readme/CONFIGURE.rst
  account_invoice_change_currency/readme/CONTRIBUTORS.rst
  account_invoice_change_currency/readme/DESCRIPTION.rst
  account_invoice_change_currency/readme/USAGE.rst
  account_invoice_change_currency/static/description/icon.png
  account_invoice_change_currency/static/description/index.html
  account_invoice_change_currency/tests/__init__.py
  account_invoice_change_currency/tests/test_account_invoice_change_currency.py
  account_invoice_change_currency/views/account_move_views.xml
  setup/account_invoice_change_currency/odoo/addons/account_invoice_change_currency
  setup/account_invoice_change_currency/setup.py
Labels: approved
