Repository OCA/account-invoicing, pull requests merged in 2022-06, with the labels that each got.

#542 [11.0][FIX] Bug account_invoice_reimbursable multi currency
  account_invoice_reimbursable/README.rst
  account_invoice_reimbursable/__manifest__.py
  account_invoice_reimbursable/models/account_invoice.py
  account_invoice_reimbursable/readme/CONTRIBUTORS.rst
  account_invoice_reimbursable/readme/DESCRIPTION.rst
  account_invoice_reimbursable/readme/ROADMAP.rst
  account_invoice_reimbursable/readme/USAGE.rst
  account_invoice_reimbursable/static/description/index.html
  account_invoice_reimbursable/tests/test_reimbursable.py
Labels: approved, ready to merge, bot is merging ⏳

#1175 [14.0][FIX] account_invoice_line_description: unbalanced invoice error in test
  account_invoice_line_description/tests/test_account_invoice_line_description.py
Labels: bot is merging ⏳

#1183 [13.0][IMP] stock_picking_return_refund_option: Make tests resilient
  account_invoice_line_description/tests/test_account_invoice_line_description.py
  stock_picking_return_refund_option/tests/test_stock_picking_return_refund_options.py
Labels: bot is merging ⏳

#1184 [13.0][IMP] stock_picking_return_refund_option: More resilience in tests
  stock_picking_return_refund_option/tests/test_stock_picking_return_refund_options.py
Labels: bot is merging ⏳

#1180 [IMP] account_invoice_change_currency: Speed up module installation.
  account_invoice_change_currency/__init__.py
  account_invoice_change_currency/__manifest__.py
  account_invoice_change_currency/hooks.py
Labels: bot is merging ⏳

#1191 [15.0][FIX] account_invoice_fiscal_position_update: avoid error in tests (greenify repo)
  account_invoice_fiscal_position_update/tests/test_inv_fiscal_pos_update.py
Labels: approved, bot is merging ⏳

#1167 [15.0] [FIX] AccessError
  sale_order_invoicing_grouping_criteria/models/sale_order.py
  sale_order_invoicing_grouping_criteria/tests/test_sale_order_invoicing_group_criteria.py
Labels: approved, bot is merging ⏳
