Repository OCA/account-invoicing, pull requests merged in 2022-01, with the labels that each got.

#987 [14.0][MIG]account_invoice_fixed_discount
  account_invoice_fixed_discount/README.rst
  account_invoice_fixed_discount/__init__.py
  account_invoice_fixed_discount/__manifest__.py
  account_invoice_fixed_discount/i18n/account_invoice_fixed_discount.pot
  account_invoice_fixed_discount/i18n/de.po
  account_invoice_fixed_discount/i18n/es.po
  account_invoice_fixed_discount/models/__init__.py
  account_invoice_fixed_discount/models/account_move.py
  account_invoice_fixed_discount/readme/CONTRIBUTORS.rst
  account_invoice_fixed_discount/readme/DESCRIPTION.rst
  account_invoice_fixed_discount/readme/INSTALL.rst
  account_invoice_fixed_discount/readme/ROADMAP.rst
  account_invoice_fixed_discount/readme/USAGE.rst
  account_invoice_fixed_discount/reports/report_account_invoice.xml
  account_invoice_fixed_discount/static/description/icon.png
  account_invoice_fixed_discount/static/description/index.html
  account_invoice_fixed_discount/tests/__init__.py
  account_invoice_fixed_discount/tests/test_account_fixed_discount.py
  account_invoice_fixed_discount/views/account_move_view.xml
  setup/account_invoice_fixed_discount/odoo/addons/account_invoice_fixed_discount
  setup/account_invoice_fixed_discount/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#1050 [14.0][IMP] account_invoice_section_sale_order: custom section name and refactor
  account_invoice_section_sale_order/__manifest__.py
  account_invoice_section_sale_order/models/__init__.py
  account_invoice_section_sale_order/models/account_move.py
  account_invoice_section_sale_order/models/res_company.py
  account_invoice_section_sale_order/models/res_config_settings.py
  account_invoice_section_sale_order/models/res_partner.py
  account_invoice_section_sale_order/models/sale_order.py
  account_invoice_section_sale_order/readme/CONFIGURATION.rst
  account_invoice_section_sale_order/readme/CONTRIBUTORS.rst
  account_invoice_section_sale_order/readme/DESCRIPTION.rst
  account_invoice_section_sale_order/security/res_groups.xml
  account_invoice_section_sale_order/tests/test_invoice_group_by_sale_order.py
  account_invoice_section_sale_order/views/res_config_settings.xml
  account_invoice_section_sale_order/views/res_partner.xml
Labels: approved, ready to merge, bot is merging ⏳

#1077 [13.0][MIG] account_invoice_line_description: Migration to 13.0
  account_invoice_line_description/README.rst
  account_invoice_line_description/__init__.py
  account_invoice_line_description/__manifest__.py
  account_invoice_line_description/i18n/account_invoice_line_description.pot
  account_invoice_line_description/i18n/ar.po
  account_invoice_line_description/i18n/bs.po
  account_invoice_line_description/i18n/ca.po
  account_invoice_line_description/i18n/cs.po
  account_invoice_line_description/i18n/de.po
  account_invoice_line_description/i18n/en_GB.po
  account_invoice_line_description/i18n/es.po
  account_invoice_line_description/i18n/es_CR.po
  account_invoice_line_description/i18n/es_EC.po
  account_invoice_line_description/i18n/es_ES.po
  account_invoice_line_description/i18n/es_MX.po
  account_invoice_line_description/i18n/et.po
  account_invoice_line_description/i18n/fr.po
  account_invoice_line_description/i18n/fr_CH.po
  account_invoice_line_description/i18n/hr.po
  account_invoice_line_description/i18n/hr_HR.po
  account_invoice_line_description/i18n/hu.po
  account_invoice_line_description/i18n/it.po
  account_invoice_line_description/i18n/ja.po
  account_invoice_line_description/i18n/lt.po
  account_invoice_line_description/i18n/mk.po
  account_invoice_line_description/i18n/mn.po
  account_invoice_line_description/i18n/nb.po
  account_invoice_line_description/i18n/nl.po
  account_invoice_line_description/i18n/nl_BE.po
  account_invoice_line_description/i18n/nl_NL.po
  account_invoice_line_description/i18n/pt.po
  account_invoice_line_description/i18n/pt_BR.po
  account_invoice_line_description/i18n/pt_PT.po
  account_invoice_line_description/i18n/ro.po
  account_invoice_line_description/i18n/ru.po
  account_invoice_line_description/i18n/sl.po
  account_invoice_line_description/i18n/sv.po
  account_invoice_line_description/i18n/tr.po
  account_invoice_line_description/i18n/tr_TR.po
  account_invoice_line_description/i18n/zh_CN.po
  account_invoice_line_description/i18n/zh_TW.po
  account_invoice_line_description/models/__init__.py
  account_invoice_line_description/models/account_move.py
  account_invoice_line_description/readme/CONFIGURE.rst
  account_invoice_line_description/readme/CONTRIBUTORS.rst
  account_invoice_line_description/readme/DESCRIPTION.rst
  account_invoice_line_description/security/account_security.xml
  account_invoice_line_description/static/description/icon.png
  account_invoice_line_description/static/description/index.html
  account_invoice_line_description/tests/__init__.py
  account_invoice_line_description/tests/test_account_invoice_line_description.py
  account_invoice_line_description/wizards/__init__.py
  account_invoice_line_description/wizards/res_config.py
  account_invoice_line_description/wizards/res_config_view.xml
  account_invoice_show_currency_rate/tests/test_account_move.py
  setup/account_invoice_line_description/odoo/addons/account_invoice_line_description
  setup/account_invoice_line_description/setup.py
Labels: bot is merging ⏳

#1078 [14.0][MIG] account_invoice_line_description: Migration to 14.0
  account_invoice_line_description/README.rst
  account_invoice_line_description/__init__.py
  account_invoice_line_description/__manifest__.py
  account_invoice_line_description/i18n/account_invoice_line_description.pot
  account_invoice_line_description/i18n/ar.po
  account_invoice_line_description/i18n/bs.po
  account_invoice_line_description/i18n/ca.po
  account_invoice_line_description/i18n/cs.po
  account_invoice_line_description/i18n/de.po
  account_invoice_line_description/i18n/en_GB.po
  account_invoice_line_description/i18n/es.po
  account_invoice_line_description/i18n/es_CR.po
  account_invoice_line_description/i18n/es_EC.po
  account_invoice_line_description/i18n/es_ES.po
  account_invoice_line_description/i18n/es_MX.po
  account_invoice_line_description/i18n/et.po
  account_invoice_line_description/i18n/fr.po
  account_invoice_line_description/i18n/fr_CH.po
  account_invoice_line_description/i18n/hr.po
  account_invoice_line_description/i18n/hr_HR.po
  account_invoice_line_description/i18n/hu.po
  account_invoice_line_description/i18n/it.po
  account_invoice_line_description/i18n/ja.po
  account_invoice_line_description/i18n/lt.po
  account_invoice_line_description/i18n/mk.po
  account_invoice_line_description/i18n/mn.po
  account_invoice_line_description/i18n/nb.po
  account_invoice_line_description/i18n/nl.po
  account_invoice_line_description/i18n/nl_BE.po
  account_invoice_line_description/i18n/nl_NL.po
  account_invoice_line_description/i18n/pt.po
  account_invoice_line_description/i18n/pt_BR.po
  account_invoice_line_description/i18n/pt_PT.po
  account_invoice_line_description/i18n/ro.po
  account_invoice_line_description/i18n/ru.po
  account_invoice_line_description/i18n/sl.po
  account_invoice_line_description/i18n/sv.po
  account_invoice_line_description/i18n/tr.po
  account_invoice_line_description/i18n/tr_TR.po
  account_invoice_line_description/i18n/zh_CN.po
  account_invoice_line_description/i18n/zh_TW.po
  account_invoice_line_description/models/__init__.py
  account_invoice_line_description/models/account_move.py
  account_invoice_line_description/readme/CONFIGURE.rst
  account_invoice_line_description/readme/CONTRIBUTORS.rst
  account_invoice_line_description/readme/DESCRIPTION.rst
  account_invoice_line_description/security/account_security.xml
  account_invoice_line_description/static/description/icon.png
  account_invoice_line_description/static/description/index.html
  account_invoice_line_description/tests/__init__.py
  account_invoice_line_description/tests/test_account_invoice_line_description.py
  account_invoice_line_description/wizards/__init__.py
  account_invoice_line_description/wizards/res_config.py
  account_invoice_line_description/wizards/res_config_view.xml
  setup/account_invoice_line_description/odoo/addons/account_invoice_line_description
  setup/account_invoice_line_description/setup.py
Labels: approved, bot is merging ⏳

#874 [FIX] account_invoice_supplier_self_invoice: Fix report
  account_invoice_supplier_self_invoice/models/account_invoice.py
  account_invoice_supplier_self_invoice/views/report_self_invoice.xml
Labels: approved, ready to merge, bot is merging ⏳

#1081 [13.0][FIX] account_invoice_show_currency_rate: Round currency_rate_amount to avoid many decimal places
  account_invoice_show_currency_rate/models/account_move.py
  test-requirements.txt
Labels: bot is merging ⏳

#1080 [MIG] account_invoice_refund_line_selection: Migration to 14.0
  account_invoice_refund_line_selection/README.rst
  account_invoice_refund_line_selection/__init__.py
  account_invoice_refund_line_selection/__manifest__.py
  account_invoice_refund_line_selection/i18n/account_invoice_refund_line_selection.pot
  account_invoice_refund_line_selection/i18n/de.po
  account_invoice_refund_line_selection/i18n/es.po
  account_invoice_refund_line_selection/readme/CONTRIBUTORS.rst
  account_invoice_refund_line_selection/readme/DESCRIPTION.rst
  account_invoice_refund_line_selection/readme/USAGE.rst
  account_invoice_refund_line_selection/static/description/icon.png
  account_invoice_refund_line_selection/static/description/index.html
  account_invoice_refund_line_selection/tests/__init__.py
  account_invoice_refund_line_selection/tests/test_refund_line.py
  account_invoice_refund_line_selection/wizards/__init__.py
  account_invoice_refund_line_selection/wizards/account_move_reversal.py
  account_invoice_refund_line_selection/wizards/account_move_reversal_view.xml
  setup/account_invoice_refund_line_selection/odoo/addons/account_invoice_refund_line_selection
  setup/account_invoice_refund_line_selection/setup.py
Labels: approved, bot is merging ⏳

#953 [MIG] account_invoice_blocking: Migration to 13.0
  account_invoice_blocking/README.rst
  account_invoice_blocking/__init__.py
  account_invoice_blocking/__manifest__.py
  account_invoice_blocking/i18n/account_invoice_blocking.pot
  account_invoice_blocking/i18n/de.po
  account_invoice_blocking/i18n/es.po
  account_invoice_blocking/i18n/hr.po
  account_invoice_blocking/i18n/nl.po
  account_invoice_blocking/i18n/pt.po
  account_invoice_blocking/i18n/pt_BR.po
  account_invoice_blocking/models/__init__.py
  account_invoice_blocking/models/account_move.py
  account_invoice_blocking/readme/CONTRIBUTORS.rst
  account_invoice_blocking/readme/DESCRIPTION.rst
  account_invoice_blocking/readme/ROADMAP.rst
  account_invoice_blocking/readme/USAGE.rst
  account_invoice_blocking/static/description/icon.png
  account_invoice_blocking/static/description/index.html
  account_invoice_blocking/tests/__init__.py
  account_invoice_blocking/tests/test_account_move_blocking.py
  account_invoice_blocking/views/account_move.xml
  setup/account_invoice_blocking/odoo/addons/account_invoice_blocking
  setup/account_invoice_blocking/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#959 [MIG] account_invoice_alternate_payer: Migration to 13.0
  account_invoice_alternate_payer/README.rst
  account_invoice_alternate_payer/__init__.py
  account_invoice_alternate_payer/__manifest__.py
  account_invoice_alternate_payer/i18n/account_invoice_alternate_payer.pot
  account_invoice_alternate_payer/migrations/13.0.1.0.0/post-migration.py
  account_invoice_alternate_payer/models/__init__.py
  account_invoice_alternate_payer/models/account_move.py
  account_invoice_alternate_payer/models/account_payment.py
  account_invoice_alternate_payer/readme/CONTRIBUTORS.rst
  account_invoice_alternate_payer/readme/DESCRIPTION.rst
  account_invoice_alternate_payer/readme/USAGE.rst
  account_invoice_alternate_payer/static/description/icon.png
  account_invoice_alternate_payer/static/description/index.html
  account_invoice_alternate_payer/tests/__init__.py
  account_invoice_alternate_payer/tests/test_account_invoice.py
  account_invoice_alternate_payer/views/account_move_views.xml
  setup/account_invoice_alternate_payer/odoo/addons/account_invoice_alternate_payer
  setup/account_invoice_alternate_payer/setup.py
Labels: approved, bot is merging ⏳

#1073 [MIG] account_invoice_tax_note: Migration to 14.0
  account_invoice_tax_note/README.rst
  account_invoice_tax_note/__init__.py
  account_invoice_tax_note/__manifest__.py
  account_invoice_tax_note/i18n/account_invoice_tax_note.pot
  account_invoice_tax_note/i18n/de.po
  account_invoice_tax_note/i18n/fr.po
  account_invoice_tax_note/models/__init__.py
  account_invoice_tax_note/models/account_move.py
  account_invoice_tax_note/models/account_tax_group.py
  account_invoice_tax_note/readme/CONTRIBUTORS.rst
  account_invoice_tax_note/readme/DESCRIPTION.rst
  account_invoice_tax_note/readme/USAGE.rst
  account_invoice_tax_note/reports/report_invoice_document.xml
  account_invoice_tax_note/static/description/icon.png
  account_invoice_tax_note/static/description/index.html
  account_invoice_tax_note/tests/__init__.py
  account_invoice_tax_note/tests/test_account_invoice.py
  setup/account_invoice_tax_note/odoo/addons/account_invoice_tax_note
  setup/account_invoice_tax_note/setup.py
Labels: approved, ready to merge, bot is merging ⏳
