Repository OCA/account-invoicing, pull requests merged in 2022-07, with the labels that each got.

#1135 [FIX] account_invoice_section_sale: fix invoice total when using currency
  account_invoice_section_sale_order/models/sale_order.py
  account_invoice_section_sale_order/tests/test_invoice_group_by_sale_order.py
Labels: needs review, approved, ready to merge, bot is merging ⏳

#1196 [13.0][FIX] *: Change _recompute_tax_lines args according upstream
  account_global_discount/models/account_move.py
  account_invoice_fixed_discount/models/account_move.py
  account_invoice_triple_discount/models/account_move.py
Labels: bot is merging ⏳

#1197 [14.0][FIX] *: Change _recompute_tax_lines args according upstream
  account_global_discount/models/account_move.py
  account_invoice_fixed_discount/models/account_move.py
Labels: bot is merging ⏳

#1190 [15.0] [MIG] sale_line_refund_to_invoice_qty
  sale_line_refund_to_invoice_qty/README.rst
  sale_line_refund_to_invoice_qty/__init__.py
  sale_line_refund_to_invoice_qty/__manifest__.py
  sale_line_refund_to_invoice_qty/i18n/sale_line_refund_to_invoice_qty.pot
  sale_line_refund_to_invoice_qty/models/__init__.py
  sale_line_refund_to_invoice_qty/models/account.py
  sale_line_refund_to_invoice_qty/models/sale.py
  sale_line_refund_to_invoice_qty/readme/CONTRIBUTORS.rst
  sale_line_refund_to_invoice_qty/readme/DESCRIPTION.rst
  sale_line_refund_to_invoice_qty/readme/USAGE.rst
  sale_line_refund_to_invoice_qty/static/description/icon.png
  sale_line_refund_to_invoice_qty/static/description/index.html
  sale_line_refund_to_invoice_qty/tests/__init__.py
  sale_line_refund_to_invoice_qty/tests/test_sale_line_refund_to_invoice_qty.py
  sale_line_refund_to_invoice_qty/views/account_move_views.xml
  sale_line_refund_to_invoice_qty/views/sale_order_views.xml
  sale_line_refund_to_invoice_qty/wizards/__init__.py
  sale_line_refund_to_invoice_qty/wizards/account_move_reversal.py
  sale_line_refund_to_invoice_qty/wizards/account_move_reversal_view.xml
  setup/sale_line_refund_to_invoice_qty/odoo/addons/sale_line_refund_to_invoice_qty
  setup/sale_line_refund_to_invoice_qty/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#1132 [IMP] account_invoice_refund_line_selection: Line views
  account_invoice_refund_line_selection/__manifest__.py
  account_invoice_refund_line_selection/views/account_move_line_views.xml
  account_invoice_refund_line_selection/wizards/account_move_reversal_view.xml
Labels: approved, ready to merge, bot is merging ⏳

#1153 [MIG] account_invoice_refund_reinvoice: Migration to 14.0
  account_invoice_refund_reinvoice/README.rst
  account_invoice_refund_reinvoice/__init__.py
  account_invoice_refund_reinvoice/__manifest__.py
  account_invoice_refund_reinvoice/i18n/account_invoice_refund_reinvoice.pot
  account_invoice_refund_reinvoice/models/__init__.py
  account_invoice_refund_reinvoice/models/account_move.py
  account_invoice_refund_reinvoice/readme/CONTRIBUTORS.rst
  account_invoice_refund_reinvoice/readme/DESCRIPTION.rst
  account_invoice_refund_reinvoice/readme/USAGE.rst
  account_invoice_refund_reinvoice/static/description/icon.png
  account_invoice_refund_reinvoice/static/description/index.html
  account_invoice_refund_reinvoice/tests/__init__.py
  account_invoice_refund_reinvoice/tests/test_refund_invoice.py
  account_invoice_refund_reinvoice/views/account_move.xml
  setup/account_invoice_refund_reinvoice/odoo/addons/account_invoice_refund_reinvoice
  setup/account_invoice_refund_reinvoice/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#1143 [12.0][MIG] account_invoice_line_default_account
  account_invoice_line_default_account/README.rst
  account_invoice_line_default_account/__init__.py
  account_invoice_line_default_account/__manifest__.py
  account_invoice_line_default_account/i18n/account_invoice_line_default_account.pot
  account_invoice_line_default_account/i18n/fr.po
  account_invoice_line_default_account/i18n/it.po
  account_invoice_line_default_account/i18n/nl.po
  account_invoice_line_default_account/models/__init__.py
  account_invoice_line_default_account/models/account_invoice_line.py
  account_invoice_line_default_account/models/res_partner.py
  account_invoice_line_default_account/readme/CONTRIBUTORS.rst
  account_invoice_line_default_account/readme/DESCRIPTION.rst
  account_invoice_line_default_account/readme/ROADMAP.rst
  account_invoice_line_default_account/static/description/index.html
  account_invoice_line_default_account/tests/__init__.py
  account_invoice_line_default_account/tests/test_default_account.py
  account_invoice_line_default_account/views/res_partner.xml
  setup/account_invoice_line_default_account/odoo/addons/account_invoice_line_default_account
  setup/account_invoice_line_default_account/setup.py
Labels: needs review, approved, bot is merging ⏳

#1204 [15.0][MIG] stock_picking_return_refund_option: Migration to 15.0
  setup/stock_picking_return_refund_option/odoo/addons/stock_picking_return_refund_option
  setup/stock_picking_return_refund_option/setup.py
  stock_picking_return_refund_option/README.rst
  stock_picking_return_refund_option/__init__.py
  stock_picking_return_refund_option/__manifest__.py
  stock_picking_return_refund_option/i18n/es.po
  stock_picking_return_refund_option/i18n/stock_picking_return_refund_option.pot
  stock_picking_return_refund_option/models/__init__.py
  stock_picking_return_refund_option/models/stock_move.py
  stock_picking_return_refund_option/models/stock_picking.py
  stock_picking_return_refund_option/readme/CONTRIBUTORS.rst
  stock_picking_return_refund_option/readme/DESCRIPTION.rst
  stock_picking_return_refund_option/readme/INSTALL.rst
  stock_picking_return_refund_option/readme/USAGE.rst
  stock_picking_return_refund_option/static/description/icon.png
  stock_picking_return_refund_option/static/description/index.html
  stock_picking_return_refund_option/tests/__init__.py
  stock_picking_return_refund_option/tests/test_stock_picking_return_refund_options.py
  stock_picking_return_refund_option/views/stock_picking_view.xml
Labels: approved, bot is merging ⏳

#849 [14.0] [ADD] new module account_receipt_print
  account_receipt_print/README.rst
  account_receipt_print/__init__.py
  account_receipt_print/__manifest__.py
  account_receipt_print/i18n/account_receipt_print.pot
  account_receipt_print/i18n/it.po
  account_receipt_print/models/__init__.py
  account_receipt_print/models/ir_actions_report.py
  account_receipt_print/readme/CONFIGURE.rst
  account_receipt_print/readme/CONTRIBUTORS.rst
  account_receipt_print/readme/DESCRIPTION.rst
  account_receipt_print/static/description/index.html
  account_receipt_print/views/account_report.xml
  account_receipt_print/views/report_receipt.xml
  setup/account_receipt_print/odoo/addons/account_receipt_print
  setup/account_receipt_print/setup.py
Labels: bot is merging ⏳

#1206 [13.0][FIX] purchase_stock_picking_return_invoicing: qty_returned is not recomputed…
  purchase_stock_picking_return_invoicing/models/purchase_order.py
  purchase_stock_picking_return_invoicing/tests/test_purchase_stock_picking_return_invoicing.py
Labels: approved, bot is merging ⏳

#1208 [13.0][ADD] sale_invoicing_date_selection: New module to set invoice_date when user creates invoices from wizard
  sale_invoicing_date_selection/README.rst
  sale_invoicing_date_selection/__init__.py
  sale_invoicing_date_selection/__manifest__.py
  sale_invoicing_date_selection/i18n/es.po
  sale_invoicing_date_selection/i18n/sale_invoicing_date_selection.pot
  sale_invoicing_date_selection/readme/CONTRIBUTORS.rst
  sale_invoicing_date_selection/readme/DESCRIPTION.rst
  sale_invoicing_date_selection/readme/USAGE.rst
  sale_invoicing_date_selection/static/description/icon.png
  sale_invoicing_date_selection/static/description/index.html
  sale_invoicing_date_selection/tests/__init__.py
  sale_invoicing_date_selection/tests/test_sale_invoicing_date_selection.py
  sale_invoicing_date_selection/wizard/__init__.py
  sale_invoicing_date_selection/wizard/sale_advance_payment_inv.py
  sale_invoicing_date_selection/wizard/sale_make_invoice_advance_views.xml
  setup/sale_invoicing_date_selection/odoo/addons/sale_invoicing_date_selection
  setup/sale_invoicing_date_selection/setup.py
Labels: approved, bot is merging ⏳

#1203 [13.0][FIX] account_global_discount: leave amount_currency empty
  account_global_discount/models/account_move.py
Labels: approved, bot is merging ⏳
