Repository OCA/account-invoicing, pull requests merged in 2022-09, with the labels that each got.

#1072 15.0 mig account invoice section sale order
  account_invoice_section_sale_order/README.rst
  account_invoice_section_sale_order/__init__.py
  account_invoice_section_sale_order/__manifest__.py
  account_invoice_section_sale_order/i18n/account_invoice_section_sale_order.pot
  account_invoice_section_sale_order/models/__init__.py
  account_invoice_section_sale_order/models/sale_order.py
  account_invoice_section_sale_order/readme/CONTRIBUTORS.rst
  account_invoice_section_sale_order/readme/CREDITS.rst
  account_invoice_section_sale_order/readme/DESCRIPTION.rst
  account_invoice_section_sale_order/static/description/icon.png
  account_invoice_section_sale_order/static/description/index.html
  account_invoice_section_sale_order/tests/__init__.py
  account_invoice_section_sale_order/tests/test_invoice_group_by_sale_order.py
  setup/account_invoice_section_sale_order/odoo/addons/account_invoice_section_sale_order
  setup/account_invoice_section_sale_order/setup.py
Labels: approved, bot is merging ⏳

#1198 [15.0][MIG] account_move_post_block
  account_move_post_block/README.rst
  account_move_post_block/__init__.py
  account_move_post_block/__manifest__.py
  account_move_post_block/data/account_exception_data.xml
  account_move_post_block/i18n/account_move_post_block.pot
  account_move_post_block/models/__init__.py
  account_move_post_block/models/account_move.py
  account_move_post_block/models/account_post_block_reason.py
  account_move_post_block/readme/CONFIGURE.rst
  account_move_post_block/readme/CONTRIBUTORS.rst
  account_move_post_block/readme/DESCRIPTION.rst
  account_move_post_block/readme/USAGE.rst
  account_move_post_block/security/account_move_post_block_security.xml
  account_move_post_block/security/ir.model.access.csv
  account_move_post_block/static/description/icon.png
  account_move_post_block/static/description/index.html
  account_move_post_block/tests/__init__.py
  account_move_post_block/tests/test_account_move_post_block.py
  account_move_post_block/tests/test_am_post_block_reason.py
  account_move_post_block/views/account_move_view.xml
  account_move_post_block/views/account_post_block_reason_view.xml
  account_move_post_block/wizard/__init__.py
  account_move_post_block/wizard/account_exception_confirm.py
  setup/account_move_post_block/odoo/addons/account_move_post_block
  setup/account_move_post_block/setup.py
Labels: approved, bot is merging ⏳

#1237 [15.0][FIX] Greenify repo
  account_move_post_block/views/account_post_block_reason_view.xml
  sale_order_invoicing_grouping_criteria/tests/test_sale_order_invoicing_group_criteria.py
  stock_picking_return_refund_option/tests/test_stock_picking_return_refund_options.py
Labels: approved, bot is merging ⏳

#1229 [15.0][IMP] account_invoice_transmit_method add translate on name field transmit.method model
  account_invoice_transmit_method/models/transmit_method.py
Labels: approved, ready to merge, bot is merging ⏳

#1234 [14.0] [MIG] account_move_tier_validation_forward
  account_move_tier_validation_forward/README.rst
  account_move_tier_validation_forward/__init__.py
  account_move_tier_validation_forward/__manifest__.py
  account_move_tier_validation_forward/i18n/account_move_tier_validation_forward.pot
  account_move_tier_validation_forward/readme/CONFIGURE.rst
  account_move_tier_validation_forward/readme/CONTRIBUTORS.rst
  account_move_tier_validation_forward/readme/DESCRIPTION.rst
  account_move_tier_validation_forward/readme/INSTALL.rst
  account_move_tier_validation_forward/static/description/icon.png
  account_move_tier_validation_forward/static/description/index.html
  account_move_tier_validation_forward/views/account_move_view.xml
  setup/account_move_tier_validation_forward/odoo/addons/account_move_tier_validation_forward
  setup/account_move_tier_validation_forward/setup.py
Labels: approved, bot is merging ⏳

#1239 [15.0][IMP] account_move_tier_validation: add filter No Validation Requested
  account_move_tier_validation/__manifest__.py
  account_move_tier_validation/views/account_move_view.xml
Labels: approved, bot is merging ⏳

#1202 [15.0] [ADD] `account_invoice_payment_term_due_date`
  account_invoice_payment_term_date_due/README.rst
  account_invoice_payment_term_date_due/__init__.py
  account_invoice_payment_term_date_due/__manifest__.py
  account_invoice_payment_term_date_due/readme/CONTRIBUTORS.rst
  account_invoice_payment_term_date_due/readme/DESCRIPTION.rst
  account_invoice_payment_term_date_due/static/description/account-invoice-payment-term-due-date.png
  account_invoice_payment_term_date_due/views/account_move.xml
  setup/account_invoice_payment_term_date_due/odoo/addons/account_invoice_payment_term_date_due
  setup/account_invoice_payment_term_date_due/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#1238 [13.0][FIX] account_invoice_triple_discount: Calculate taxes correcly consi…
  account_invoice_triple_discount/models/account_move.py
  account_invoice_triple_discount/tests/test_invoice_triple_discount.py
Labels: bug, approved, bot is merging ⏳

#1235 [15.0] [MIG] account_move_tier_validation_forward
  account_move_tier_validation_forward/README.rst
  account_move_tier_validation_forward/__init__.py
  account_move_tier_validation_forward/__manifest__.py
  account_move_tier_validation_forward/i18n/account_move_tier_validation_forward.pot
  account_move_tier_validation_forward/readme/CONFIGURE.rst
  account_move_tier_validation_forward/readme/CONTRIBUTORS.rst
  account_move_tier_validation_forward/readme/DESCRIPTION.rst
  account_move_tier_validation_forward/readme/INSTALL.rst
  account_move_tier_validation_forward/static/description/icon.png
  account_move_tier_validation_forward/static/description/index.html
  account_move_tier_validation_forward/views/account_move_view.xml
  setup/account_move_tier_validation_forward/odoo/addons/account_move_tier_validation_forward
  setup/account_move_tier_validation_forward/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#1227 [15.0][IMP] account_invoice_transmit_method add active field transmit.method model
  account_invoice_transmit_method/data/transmit_method.xml
  account_invoice_transmit_method/models/transmit_method.py
  account_invoice_transmit_method/views/transmit_method.xml
Labels: approved, ready to merge, bot is merging ⏳

#1049 [14.0][MIG]account_move_post_block: Migration to 14.0
  account_move_post_block/README.rst
  account_move_post_block/__init__.py
  account_move_post_block/__manifest__.py
  account_move_post_block/data/account_exception_data.xml
  account_move_post_block/i18n/account_move_post_block.pot
  account_move_post_block/models/__init__.py
  account_move_post_block/models/account_move.py
  account_move_post_block/models/account_post_block_reason.py
  account_move_post_block/readme/CONFIGURE.rst
  account_move_post_block/readme/CONTRIBUTORS.rst
  account_move_post_block/readme/DESCRIPTION.rst
  account_move_post_block/readme/USAGE.rst
  account_move_post_block/security/account_move_post_block_security.xml
  account_move_post_block/security/ir.model.access.csv
  account_move_post_block/static/description/icon.png
  account_move_post_block/static/description/index.html
  account_move_post_block/tests/__init__.py
  account_move_post_block/tests/test_account_move_post_block.py
  account_move_post_block/tests/test_am_post_block_reason.py
  account_move_post_block/views/account_move_view.xml
  account_move_post_block/views/account_post_block_reason_view.xml
  account_move_post_block/wizard/__init__.py
  account_move_post_block/wizard/account_exception_confirm.py
  setup/account_move_post_block/odoo/addons/account_move_post_block
  setup/account_move_post_block/setup.py
Labels: approved, ready to merge, bot is merging ⏳
