Repository OCA/account-invoicing, pull requests merged in 2022-12, with the labels that each got.

#1297 [15.0][FIX] account_invoice_date_due: Fix tests. Compare fields with sudo user
  account_invoice_date_due/tests/test_account_invoice_date_due.py
Labels: approved, bot is merging ⏳

#1277 [14.0][ADD] account_refund_payment_term:
  account_refund_payment_term/README.rst
  account_refund_payment_term/__init__.py
  account_refund_payment_term/__manifest__.py
  account_refund_payment_term/i18n/account_refund_payment_term.pot
  account_refund_payment_term/i18n/fr.po
  account_refund_payment_term/models/__init__.py
  account_refund_payment_term/models/account_move.py
  account_refund_payment_term/models/partner.py
  account_refund_payment_term/readme/CONTRIBUTORS.rst
  account_refund_payment_term/readme/DESCRIPTION.rst
  account_refund_payment_term/readme/ROADMAP.rst
  account_refund_payment_term/readme/USAGE.rst
  account_refund_payment_term/static/description/index.html
  account_refund_payment_term/tests/__init__.py
  account_refund_payment_term/tests/test_refund_payment_term.py
  account_refund_payment_term/views/res_partner_view.xml
  setup/account_refund_payment_term/odoo/addons/account_refund_payment_term
  setup/account_refund_payment_term/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#1303 [FIX] account_invoice_supplier_self_invoice: Creation must be set with sudo
  account_invoice_supplier_self_invoice/models/res_partner.py
  account_invoice_supplier_self_invoice/tests/test_self_invoice.py
Labels: approved, bot is merging ⏳

#1305 [IMP] account_invoice_supplier_self_invoice: Allow to use a refund sequence
  account_invoice_supplier_self_invoice/models/account_move.py
  account_invoice_supplier_self_invoice/models/res_partner.py
  account_invoice_supplier_self_invoice/tests/test_self_invoice.py
  account_invoice_supplier_self_invoice/views/res_partner_views.xml
Labels: approved, bot is merging ⏳

#1304 [IMP] account_invoice_supplier_self_invoice: Apply improvements from 14
  account_invoice_supplier_self_invoice/README.rst
  account_invoice_supplier_self_invoice/__manifest__.py
  account_invoice_supplier_self_invoice/data/mail_template_data.xml
  account_invoice_supplier_self_invoice/i18n/account_invoice_supplier_self_invoice.pot
  account_invoice_supplier_self_invoice/i18n/es.po
  account_invoice_supplier_self_invoice/migrations/14.0.2.0.0/post-migration.py
  account_invoice_supplier_self_invoice/models/__init__.py
  account_invoice_supplier_self_invoice/models/account_move.py
  account_invoice_supplier_self_invoice/models/res_company.py
  account_invoice_supplier_self_invoice/models/res_config_settings.py
  account_invoice_supplier_self_invoice/models/res_partner.py
  account_invoice_supplier_self_invoice/readme/CONTRIBUTORS.rst
  account_invoice_supplier_self_invoice/readme/USAGE.rst
  account_invoice_supplier_self_invoice/static/description/index.html
  account_invoice_supplier_self_invoice/tests/test_self_invoice.py
  account_invoice_supplier_self_invoice/views/account_move_views.xml
  account_invoice_supplier_self_invoice/views/report_self_invoice.xml
  account_invoice_supplier_self_invoice/views/res_config_settings_views.xml
  account_invoice_supplier_self_invoice/views/res_partner_views.xml
Labels: approved, bot is merging ⏳

#1309 [FIX] [15.0] account_invoice_supplier_self_invoice: New partner billing prefix
  account_invoice_supplier_self_invoice/i18n/account_invoice_supplier_self_invoice.pot
  account_invoice_supplier_self_invoice/i18n/es.po
  account_invoice_supplier_self_invoice/models/res_partner.py
  account_invoice_supplier_self_invoice/readme/USAGE.rst
  account_invoice_supplier_self_invoice/views/account_move_views.xml
  account_invoice_supplier_self_invoice/views/report_self_invoice.xml
  account_invoice_supplier_self_invoice/views/res_partner_views.xml
Labels: needs review, approved, bot is merging ⏳

#1312 [14.0][UPD] copier & pre-commit
  .copier-answers.yml
  .github/workflows/pre-commit.yml
  .github/workflows/test.yml
Labels: bot is merging ⏳

#1315 [FIX] account_invoice_supplier_self_invoice: change the groups to view in order to use them without debug mode
  account_invoice_supplier_self_invoice/models/res_partner.py
  account_invoice_supplier_self_invoice/views/res_partner_views.xml
Labels: needs review, bot is merging ⏳

#1318 [14.0] account_invoice_supplier_self_invoice
  account_invoice_supplier_self_invoice/i18n/account_invoice_supplier_self_invoice.pot
  account_invoice_supplier_self_invoice/i18n/es.po
  account_invoice_supplier_self_invoice/models/res_partner.py
  account_invoice_supplier_self_invoice/readme/USAGE.rst
  account_invoice_supplier_self_invoice/views/account_move_views.xml
  account_invoice_supplier_self_invoice/views/report_self_invoice.xml
  account_invoice_supplier_self_invoice/views/res_partner_views.xml
Labels: needs review, approved, bot is merging ⏳

#1321 [12.0][UPD] copier
  .copier-answers.yml
  .github/workflows/pre-commit.yml
  .github/workflows/test.yml
  README.md
Labels: bot is merging ⏳

#1328 [13.0][UPD] repo template
  .copier-answers.yml
  .flake8
  .github/workflows/pre-commit.yml
  .github/workflows/test.yml
  .gitignore
  .pre-commit-config.yaml
  .pre-commit-config.yaml.rej
  .pylintrc
  .pylintrc-mandatory
  account_global_discount/__manifest__.py
  account_invoice_alternate_payer/__manifest__.py
  account_invoice_blocking/__manifest__.py
  account_invoice_line_sequence/__manifest__.py
  account_menu_invoice_refund/__manifest__.py
  account_move_tier_validation_approver/__manifest__.py
  purchase_batch_invoicing/__manifest__.py
  requirements.txt
  sale_timesheet_invoice_description/__manifest__.py
Labels: bot is merging ⏳

#1099 [13.0][IMP] account_invoice_check_picking_date: Change invoice date by accounting date
  account_invoice_check_picking_date/README.rst
  account_invoice_check_picking_date/__manifest__.py
  account_invoice_check_picking_date/i18n/account_invoice_check_picking_date.pot
  account_invoice_check_picking_date/i18n/es.po
  account_invoice_check_picking_date/models/account_move.py
  account_invoice_check_picking_date/readme/DESCRIPTION.rst
  account_invoice_check_picking_date/readme/USAGE.rst
  account_invoice_check_picking_date/static/description/index.html
  account_invoice_check_picking_date/wizards/invoice_stock_picking_date_wiz.py
  account_invoice_check_picking_date/wizards/invoice_stock_picking_date_wiz.xml
Labels: bot is merging ⏳
