Repository OCA/account-invoicing, pull requests merged in 2022-03, with the labels that each got.

#1110 [13.0][MIG] account_invoice_supplierinfo_update_discount: Migration to 13.0
  account_invoice_supplierinfo_update_discount/README.rst
  account_invoice_supplierinfo_update_discount/__init__.py
  account_invoice_supplierinfo_update_discount/__manifest__.py
  account_invoice_supplierinfo_update_discount/i18n/account_invoice_supplierinfo_update_discount.pot
  account_invoice_supplierinfo_update_discount/i18n/ar.po
  account_invoice_supplierinfo_update_discount/i18n/bs.po
  account_invoice_supplierinfo_update_discount/i18n/ca.po
  account_invoice_supplierinfo_update_discount/i18n/cs.po
  account_invoice_supplierinfo_update_discount/i18n/de.po
  account_invoice_supplierinfo_update_discount/i18n/en_GB.po
  account_invoice_supplierinfo_update_discount/i18n/es.po
  account_invoice_supplierinfo_update_discount/i18n/es_CR.po
  account_invoice_supplierinfo_update_discount/i18n/es_EC.po
  account_invoice_supplierinfo_update_discount/i18n/es_MX.po
  account_invoice_supplierinfo_update_discount/i18n/et.po
  account_invoice_supplierinfo_update_discount/i18n/fr.po
  account_invoice_supplierinfo_update_discount/i18n/fr_CH.po
  account_invoice_supplierinfo_update_discount/i18n/hr.po
  account_invoice_supplierinfo_update_discount/i18n/hu.po
  account_invoice_supplierinfo_update_discount/i18n/it.po
  account_invoice_supplierinfo_update_discount/i18n/ja.po
  account_invoice_supplierinfo_update_discount/i18n/lt.po
  account_invoice_supplierinfo_update_discount/i18n/mk.po
  account_invoice_supplierinfo_update_discount/i18n/mn.po
  account_invoice_supplierinfo_update_discount/i18n/nb.po
  account_invoice_supplierinfo_update_discount/i18n/nl.po
  account_invoice_supplierinfo_update_discount/i18n/nl_BE.po
  account_invoice_supplierinfo_update_discount/i18n/nl_NL.po
  account_invoice_supplierinfo_update_discount/i18n/pt.po
  account_invoice_supplierinfo_update_discount/i18n/pt_BR.po
  account_invoice_supplierinfo_update_discount/i18n/pt_PT.po
  account_invoice_supplierinfo_update_discount/i18n/ro.po
  account_invoice_supplierinfo_update_discount/i18n/ru.po
  account_invoice_supplierinfo_update_discount/i18n/sl.po
  account_invoice_supplierinfo_update_discount/i18n/sv.po
  account_invoice_supplierinfo_update_discount/i18n/tr.po
  account_invoice_supplierinfo_update_discount/i18n/tr_TR.po
  account_invoice_supplierinfo_update_discount/i18n/zh_CN.po
  account_invoice_supplierinfo_update_discount/i18n/zh_TW.po
  account_invoice_supplierinfo_update_discount/models/__init__.py
  account_invoice_supplierinfo_update_discount/models/account_move_line.py
  account_invoice_supplierinfo_update_discount/readme/CONTRIBUTORS.rst
  account_invoice_supplierinfo_update_discount/readme/DESCRIPTION.rst
  account_invoice_supplierinfo_update_discount/readme/ROADMAP.rst
  account_invoice_supplierinfo_update_discount/static/description/icon.png
  account_invoice_supplierinfo_update_discount/static/description/index.html
  account_invoice_supplierinfo_update_discount/tests/__init__.py
  account_invoice_supplierinfo_update_discount/tests/test_module.py
  account_invoice_supplierinfo_update_discount/wizard/__init__.py
  account_invoice_supplierinfo_update_discount/wizard/wizard_update_invoice_supplierinfo.xml
  account_invoice_supplierinfo_update_discount/wizard/wizard_update_invoice_supplierinfo_line.py
  setup/account_invoice_supplierinfo_update_discount/odoo/addons/account_invoice_supplierinfo_update_discount
  setup/account_invoice_supplierinfo_update_discount/setup.py
Labels: approved, bot is merging ⏳

#1115 [FIX] account_invoice_refund_line_selection: fixed view
  account_invoice_refund_line_selection/wizards/account_move_reversal_view.xml
Labels: approved, bot is merging ⏳

#1116 [13.0][MIG]purchase_invoicing_no_zero_line: Migration to 13.0
  purchase_invoicing_no_zero_line/README.rst
  purchase_invoicing_no_zero_line/__init__.py
  purchase_invoicing_no_zero_line/__manifest__.py
  purchase_invoicing_no_zero_line/i18n/de.po
  purchase_invoicing_no_zero_line/i18n/es.po
  purchase_invoicing_no_zero_line/i18n/purchase_invoicing_no_zero_line.pot
  purchase_invoicing_no_zero_line/models/__init__.py
  purchase_invoicing_no_zero_line/models/account_journal.py
  purchase_invoicing_no_zero_line/models/account_move.py
  purchase_invoicing_no_zero_line/readme/CONFIGURE.rst
  purchase_invoicing_no_zero_line/readme/CONTRIBUTORS.rst
  purchase_invoicing_no_zero_line/readme/DESCRIPTION.rst
  purchase_invoicing_no_zero_line/static/description/icon.png
  purchase_invoicing_no_zero_line/static/description/icon.svg
  purchase_invoicing_no_zero_line/static/description/index.html
  purchase_invoicing_no_zero_line/tests/__init__.py
  purchase_invoicing_no_zero_line/tests/test_purchase_invoicing_no_zero_line.py
  purchase_invoicing_no_zero_line/views/account_view.xml
  setup/purchase_invoicing_no_zero_line/odoo/addons/purchase_invoicing_no_zero_line
  setup/purchase_invoicing_no_zero_line/setup.py
Labels: approved, bot is merging ⏳

#843 [13.0][NEW][account_invoice_force_origin] New module to force invoice_origin field
  account_invoice_force_origin/README.rst
  account_invoice_force_origin/__init__.py
  account_invoice_force_origin/__manifest__.py
  account_invoice_force_origin/readme/CONFIGURE.rst
  account_invoice_force_origin/readme/CONTRIBUTORS.rst
  account_invoice_force_origin/readme/DESCRIPTION.rst
  account_invoice_force_origin/readme/USAGE.rst
  account_invoice_force_origin/security/security.xml
  account_invoice_force_origin/static/description/icon.png
  account_invoice_force_origin/static/description/index.html
  account_invoice_force_origin/views/account_move_view.xml
  setup/account_invoice_force_origin/odoo/addons/account_invoice_force_origin
  setup/account_invoice_force_origin/setup.py
Labels: bot is merging ⏳

#1120 [15.0][MIG] account_move_tier_validation
  account_move_tier_validation/README.rst
  account_move_tier_validation/__init__.py
  account_move_tier_validation/__manifest__.py
  account_move_tier_validation/i18n/account_move_tier_validation.pot
  account_move_tier_validation/i18n/ca.po
  account_move_tier_validation/i18n/es.po
  account_move_tier_validation/i18n/es_PA.po
  account_move_tier_validation/i18n/sv.po
  account_move_tier_validation/i18n/zh_CN.po
  account_move_tier_validation/models/__init__.py
  account_move_tier_validation/models/account_move.py
  account_move_tier_validation/models/tier_definition.py
  account_move_tier_validation/readme/CONFIGURE.rst
  account_move_tier_validation/readme/CONTRIBUTORS.rst
  account_move_tier_validation/readme/DESCRIPTION.rst
  account_move_tier_validation/readme/INSTALL.rst
  account_move_tier_validation/readme/USAGE.rst
  account_move_tier_validation/static/description/icon.png
  account_move_tier_validation/static/description/index.html
  account_move_tier_validation/tests/__init__.py
  account_move_tier_validation/tests/common.py
  account_move_tier_validation/tests/test_tier_validation.py
  account_move_tier_validation/tests/tier_validation_tester.py
  account_move_tier_validation/views/account_move_view.xml
Labels: approved, bot is merging ⏳

#1045 [14.0][MIG]sale_line_refund_to_invoice_qty: Migration to 14.0
  sale_line_refund_to_invoice_qty/README.rst
  sale_line_refund_to_invoice_qty/__init__.py
  sale_line_refund_to_invoice_qty/__manifest__.py
  sale_line_refund_to_invoice_qty/i18n/sale_line_refund_to_invoice_qty.pot
  sale_line_refund_to_invoice_qty/models/__init__.py
  sale_line_refund_to_invoice_qty/models/account.py
  sale_line_refund_to_invoice_qty/models/sale.py
  sale_line_refund_to_invoice_qty/readme/CONTRIBUTORS.rst
  sale_line_refund_to_invoice_qty/readme/DESCRIPTION.rst
  sale_line_refund_to_invoice_qty/readme/USAGE.rst
  sale_line_refund_to_invoice_qty/static/description/icon.png
  sale_line_refund_to_invoice_qty/static/description/index.html
  sale_line_refund_to_invoice_qty/tests/__init__.py
  sale_line_refund_to_invoice_qty/tests/test_sale_line_refund_to_invoice_qty.py
  sale_line_refund_to_invoice_qty/views/account_move_views.xml
  sale_line_refund_to_invoice_qty/views/sale_order_views.xml
  sale_line_refund_to_invoice_qty/wizards/__init__.py
  sale_line_refund_to_invoice_qty/wizards/account_move_reversal.py
  sale_line_refund_to_invoice_qty/wizards/account_move_reversal_view.xml
  setup/sale_line_refund_to_invoice_qty/odoo/addons/sale_line_refund_to_invoice_qty
  setup/sale_line_refund_to_invoice_qty/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#1114 [MIG] sale_order_invoicing_grouping_criteria: Migration to 15.0
  sale_order_invoicing_grouping_criteria/README.rst
  sale_order_invoicing_grouping_criteria/__init__.py
  sale_order_invoicing_grouping_criteria/__manifest__.py
  sale_order_invoicing_grouping_criteria/i18n/ca.po
  sale_order_invoicing_grouping_criteria/i18n/es.po
  sale_order_invoicing_grouping_criteria/i18n/sale_order_invoicing_grouping_criteria.pot
  sale_order_invoicing_grouping_criteria/models/__init__.py
  sale_order_invoicing_grouping_criteria/models/res_company.py
  sale_order_invoicing_grouping_criteria/models/res_config_settings.py
  sale_order_invoicing_grouping_criteria/models/res_partner.py
  sale_order_invoicing_grouping_criteria/models/sale_invoicing_grouping_criteria.py
  sale_order_invoicing_grouping_criteria/models/sale_order.py
  sale_order_invoicing_grouping_criteria/readme/CONFIGURE.rst
  sale_order_invoicing_grouping_criteria/readme/CONTRIBUTORS.rst
  sale_order_invoicing_grouping_criteria/readme/DESCRIPTION.rst
  sale_order_invoicing_grouping_criteria/readme/INSTALL.rst
  sale_order_invoicing_grouping_criteria/readme/USAGE.rst
  sale_order_invoicing_grouping_criteria/security/ir.model.access.csv
  sale_order_invoicing_grouping_criteria/static/description/icon.png
  sale_order_invoicing_grouping_criteria/static/description/index.html
  sale_order_invoicing_grouping_criteria/tests/__init__.py
  sale_order_invoicing_grouping_criteria/tests/test_sale_order_invoicing_group_criteria.py
  sale_order_invoicing_grouping_criteria/views/res_config_settings_views.xml
  sale_order_invoicing_grouping_criteria/views/res_partner_views.xml
  sale_order_invoicing_grouping_criteria/views/sale_invoicing_grouping_criteria_views.xml
  setup/sale_order_invoicing_grouping_criteria/odoo/addons/sale_order_invoicing_grouping_criteria
  setup/sale_order_invoicing_grouping_criteria/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#1119 [13.0][FIX] account_invoice_refund_line_selection, error singleton
  account_invoice_refund_line_selection/wizards/account_move_reversal.py
Labels: approved, ready to merge, bot is merging ⏳

#1123 {14.0}[PORT][FIX]{#1119}account_invoice_refund_line_selection, error singleton
  account_invoice_refund_line_selection/wizards/account_move_reversal.py
Labels: approved, bot is merging ⏳

#1124 [14.0] dotfiles update needs manual intervention
  .copier-answers.yml
  .eslintrc.yml
  .github/workflows/pre-commit.yml
  .pre-commit-config.yaml
  README.md
  account_billing/tests/test_account_billing.py
  account_invoice_fixed_discount/tests/test_account_fixed_discount.py
  account_invoice_payment_retention/models/account_move.py
  account_invoice_payment_retention/tests/test_invoice_payment_retention.py
  account_invoice_section_sale_order/tests/test_invoice_group_by_sale_order.py
  account_invoice_triple_discount/tests/test_invoice_triple_discount.py
  stock_picking_invoicing/views/stock_picking.xml
Labels: help wanted, needs review
