Repository OCA/account-invoicing, pull requests merged in 2023-08, with the labels that each got.

#1385 [16.0][MIG] Migration of module account_invoice_tree_currency
  account_invoice_tree_currency/README.rst
  account_invoice_tree_currency/__init__.py
  account_invoice_tree_currency/__manifest__.py
  account_invoice_tree_currency/i18n/account_invoice_tree_currency.pot
  account_invoice_tree_currency/i18n/ca.po
  account_invoice_tree_currency/readme/CONTRIBUTORS.rst
  account_invoice_tree_currency/readme/DESCRIPTION.rst
  account_invoice_tree_currency/static/description/icon.png
  account_invoice_tree_currency/static/description/index.html
  account_invoice_tree_currency/views/account_move_view.xml
  setup/account_invoice_tree_currency/odoo/addons/account_invoice_tree_currency
  setup/account_invoice_tree_currency/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#1521 [15.0][FIX+IMP] account_invoice_crm_tag: Proper line tag propagation + colors
  account_invoice_crm_tag/README.rst
  account_invoice_crm_tag/models/sale_order.py
  account_invoice_crm_tag/readme/CONTRIBUTORS.rst
  account_invoice_crm_tag/static/description/index.html
  account_invoice_crm_tag/views/account_invoice_views.xml
Labels: approved, bot is merging ⏳

#1461 [16.0][MIG] sale_line_refund_to_invoice_qty: Migration to 16.0
  sale_line_refund_to_invoice_qty/README.rst
  sale_line_refund_to_invoice_qty/__init__.py
  sale_line_refund_to_invoice_qty/__manifest__.py
  sale_line_refund_to_invoice_qty/i18n/es.po
  sale_line_refund_to_invoice_qty/i18n/sale_line_refund_to_invoice_qty.pot
  sale_line_refund_to_invoice_qty/models/__init__.py
  sale_line_refund_to_invoice_qty/models/account.py
  sale_line_refund_to_invoice_qty/models/sale.py
  sale_line_refund_to_invoice_qty/readme/CONTRIBUTORS.rst
  sale_line_refund_to_invoice_qty/readme/DESCRIPTION.rst
  sale_line_refund_to_invoice_qty/readme/USAGE.rst
  sale_line_refund_to_invoice_qty/static/description/icon.png
  sale_line_refund_to_invoice_qty/static/description/index.html
  sale_line_refund_to_invoice_qty/tests/__init__.py
  sale_line_refund_to_invoice_qty/tests/test_sale_line_refund_to_invoice_qty.py
  sale_line_refund_to_invoice_qty/views/account_move_views.xml
  sale_line_refund_to_invoice_qty/views/sale_order_views.xml
  sale_line_refund_to_invoice_qty/wizards/__init__.py
  sale_line_refund_to_invoice_qty/wizards/account_move_reversal.py
  sale_line_refund_to_invoice_qty/wizards/account_move_reversal_view.xml
  setup/sale_line_refund_to_invoice_qty/odoo/addons/sale_line_refund_to_invoice_qty
  setup/sale_line_refund_to_invoice_qty/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#1523 [13.0][IMP] account_invoice_refund_link: Make more reliable the linking
  account_invoice_refund_link/models/account_move.py
Labels: approved, bot is merging ⏳

#1526 [16.0][IMP] account_invoice_refund_link: Make more reliable the linking
  account_invoice_refund_link/__manifest__.py
  account_invoice_refund_link/models/account_move.py
  account_invoice_refund_link/models/account_move_line.py
  account_invoice_refund_link/tests/test_invoice_refund_link.py
Labels: needs review, approved, bot is merging ⏳

#1525 [15.0][IMP] account_invoice_refund_link: Make more reliable the linking
  account_invoice_refund_link/models/account_move.py
  account_invoice_refund_link/models/account_move_line.py
Labels: approved, bot is merging ⏳

#1524 [14.0][IMP] account_invoice_refund_link: Make more reliable the linking
  account_invoice_refund_link/models/account_move.py
  account_invoice_refund_link/models/account_move_line.py
Labels: approved, bot is merging ⏳

#1429 [14.0][IMP] account_invoice_mass_sending: use Odoo wizard and notification
  account_invoice_mass_sending/README.rst
  account_invoice_mass_sending/__init__.py
  account_invoice_mass_sending/__manifest__.py
  account_invoice_mass_sending/models/account_move.py
  account_invoice_mass_sending/readme/CONTRIBUTORS.rst
  account_invoice_mass_sending/readme/USAGE.rst
  account_invoice_mass_sending/static/description/index.html
  account_invoice_mass_sending/tests/test_account_invoice_mass_sending.py
  account_invoice_mass_sending/views/account_invoice_views.xml
  account_invoice_mass_sending/wizards/__init__.py
  account_invoice_mass_sending/wizards/account_invoice_send.py
  account_invoice_mass_sending/wizards/account_invoice_send.xml
Labels: approved, ready to merge, bot is merging ⏳

#1504 [15.0][ADD] account_move_search_line
  account_move_search_line/README.rst
  account_move_search_line/__init__.py
  account_move_search_line/__manifest__.py
  account_move_search_line/readme/DESCRIPTION.rst
  account_move_search_line/static/description/index.html
  account_move_search_line/views/account_move_views.xml
  setup/account_move_search_line/odoo/addons/account_move_search_line
  setup/account_move_search_line/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#1529 [16.0][MIG] account_invoice_mass_sending: Migration to 16.0
  account_invoice_mass_sending/README.rst
  account_invoice_mass_sending/__init__.py
  account_invoice_mass_sending/__manifest__.py
  account_invoice_mass_sending/i18n/account_invoice_mass_sending.pot
  account_invoice_mass_sending/i18n/es.po
  account_invoice_mass_sending/i18n/fr.po
  account_invoice_mass_sending/models/__init__.py
  account_invoice_mass_sending/models/account_move.py
  account_invoice_mass_sending/readme/CONFIGURE.rst
  account_invoice_mass_sending/readme/CONTRIBUTORS.rst
  account_invoice_mass_sending/readme/DESCRIPTION.rst
  account_invoice_mass_sending/readme/USAGE.rst
  account_invoice_mass_sending/static/description/icon.png
  account_invoice_mass_sending/static/description/index.html
  account_invoice_mass_sending/tests/__init__.py
  account_invoice_mass_sending/tests/test_account_invoice_mass_sending.py
  account_invoice_mass_sending/views/account_invoice_views.xml
  account_invoice_mass_sending/wizards/__init__.py
  account_invoice_mass_sending/wizards/account_invoice_send.py
  account_invoice_mass_sending/wizards/account_invoice_send.xml
  setup/account_invoice_mass_sending/odoo/addons/account_invoice_mass_sending
  setup/account_invoice_mass_sending/setup.py
Labels: approved, bot is merging ⏳

#1522 [16.0][MIG] account_invoice_show_currency_rate: Migration to 16.0
  account_invoice_show_currency_rate/README.rst
  account_invoice_show_currency_rate/__init__.py
  account_invoice_show_currency_rate/__manifest__.py
  account_invoice_show_currency_rate/i18n/account_invoice_show_currency_rate.pot
  account_invoice_show_currency_rate/i18n/es.po
  account_invoice_show_currency_rate/models/__init__.py
  account_invoice_show_currency_rate/models/account_move.py
  account_invoice_show_currency_rate/readme/CONFIGURE.rst
  account_invoice_show_currency_rate/readme/CONTRIBUTORS.rst
  account_invoice_show_currency_rate/readme/DESCRIPTION.rst
  account_invoice_show_currency_rate/readme/USAGE.rst
  account_invoice_show_currency_rate/static/description/icon.png
  account_invoice_show_currency_rate/static/description/index.html
  account_invoice_show_currency_rate/tests/__init__.py
  account_invoice_show_currency_rate/tests/test_account_move.py
  account_invoice_show_currency_rate/views/account_move_view.xml
  setup/account_invoice_show_currency_rate/odoo/addons/account_invoice_show_currency_rate
  setup/account_invoice_show_currency_rate/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#1351 [15.0] [MIG] account_invoice_discount_display_amount
  account_invoice_discount_display_amount/README.rst
  account_invoice_discount_display_amount/__init__.py
  account_invoice_discount_display_amount/__manifest__.py
  account_invoice_discount_display_amount/i18n/account_invoice_discount_display_amount.pot
  account_invoice_discount_display_amount/models/__init__.py
  account_invoice_discount_display_amount/models/account_move.py
  account_invoice_discount_display_amount/models/account_move_line.py
  account_invoice_discount_display_amount/readme/CONFIGURE.rst
  account_invoice_discount_display_amount/readme/CONTRIBUTORS.rst
  account_invoice_discount_display_amount/readme/DESCRIPTION.rst
  account_invoice_discount_display_amount/readme/USAGE.rst
  account_invoice_discount_display_amount/report/report_invoice.xml
  account_invoice_discount_display_amount/static/description/icon.png
  account_invoice_discount_display_amount/static/description/index.html
  account_invoice_discount_display_amount/tests/__init__.py
  account_invoice_discount_display_amount/tests/test_invoice_discount_display_amount.py
  account_invoice_discount_display_amount/views/account_move_views.xml
  setup/account_invoice_discount_display_amount/odoo/addons/account_invoice_discount_display_amount
  setup/account_invoice_discount_display_amount/setup.py
Labels: needs review, approved, bot is merging ⏳

#1531 [15.0][FIX] account_global_discount: Make tests resilient
  account_global_discount/tests/test_global_discount.py
Labels: bot is merging ⏳

#1536 [15.0][MIG] account_invoice_anglo_saxon_no_cogs_deferral
  account_invoice_anglo_saxon_no_cogs_deferral/README.rst
  account_invoice_anglo_saxon_no_cogs_deferral/__init__.py
  account_invoice_anglo_saxon_no_cogs_deferral/__manifest__.py
  account_invoice_anglo_saxon_no_cogs_deferral/i18n/account_invoice_anglo_saxon_no_cogs_deferral.pot
  account_invoice_anglo_saxon_no_cogs_deferral/i18n/de.po
  account_invoice_anglo_saxon_no_cogs_deferral/i18n/pt_BR.po
  account_invoice_anglo_saxon_no_cogs_deferral/models/__init__.py
  account_invoice_anglo_saxon_no_cogs_deferral/models/account_move.py
  account_invoice_anglo_saxon_no_cogs_deferral/readme/CONTRIBUTORS.rst
  account_invoice_anglo_saxon_no_cogs_deferral/readme/DESCRIPTION.rst
  account_invoice_anglo_saxon_no_cogs_deferral/readme/USAGE.rst
  account_invoice_anglo_saxon_no_cogs_deferral/static/description/icon.png
  account_invoice_anglo_saxon_no_cogs_deferral/static/description/index.html
  account_invoice_anglo_saxon_no_cogs_deferral/tests/__init__.py
  account_invoice_anglo_saxon_no_cogs_deferral/tests/test_account_invoice_anglo_saxon_no_cogs_deferral.py
  setup/account_invoice_anglo_saxon_no_cogs_deferral/odoo/addons/account_invoice_anglo_saxon_no_cogs_deferral
  setup/account_invoice_anglo_saxon_no_cogs_deferral/setup.py
Labels: approved, bot is merging ⏳
