Repository OCA/account-invoicing, pull requests merged in 2023-11, with the labels that each got.

#1575 [12.0][FIX] account_invoice_supplierinfo_update : update supplierinfo min_qty, based on new_min_quantity value on wizard line
  account_invoice_supplierinfo_update/tests/test_account_invoice_supplierinfo_update.py
  account_invoice_supplierinfo_update/wizard/wizard_update_invoice_supplierinfo_line.py
Labels: approved, ready to merge, bot is merging ⏳

#1574 [14.0][FIX] account_invoice_supplierinfo_update : update supplierinfo min_qty, based on new_min_quantity value on wizard line
  account_invoice_supplierinfo_update/tests/test_account_invoice_supplierinfo_update.py
  account_invoice_supplierinfo_update/wizard/wizard_update_invoice_supplierinfo_line.py
Labels: approved, ready to merge, bot is merging ⏳

#1288 [15.0][mig] account_invoice_payment_retention
  account_invoice_payment_retention/README.rst
  account_invoice_payment_retention/__init__.py
  account_invoice_payment_retention/__manifest__.py
  account_invoice_payment_retention/i18n/account_invoice_payment_retention.pot
  account_invoice_payment_retention/i18n/ca.po
  account_invoice_payment_retention/models/__init__.py
  account_invoice_payment_retention/models/account_move.py
  account_invoice_payment_retention/models/res_company.py
  account_invoice_payment_retention/models/res_config_settings.py
  account_invoice_payment_retention/readme/CONFIGURE.rst
  account_invoice_payment_retention/readme/CONTRIBUTORS.rst
  account_invoice_payment_retention/readme/DESCRIPTION.rst
  account_invoice_payment_retention/readme/USAGE.rst
  account_invoice_payment_retention/security/security.xml
  account_invoice_payment_retention/static/description/icon.png
  account_invoice_payment_retention/static/description/index.html
  account_invoice_payment_retention/tests/__init__.py
  account_invoice_payment_retention/tests/test_invoice_payment_retention.py
  account_invoice_payment_retention/views/account_move_views.xml
  account_invoice_payment_retention/views/res_config_settings_views.xml
  account_invoice_payment_retention/wizard/__init__.py
  account_invoice_payment_retention/wizard/account_payment_register.py
  account_invoice_payment_retention/wizard/account_payment_register_views.xml
  setup/account_invoice_payment_retention/odoo/addons/account_invoice_payment_retention
  setup/account_invoice_payment_retention/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#1592 [14.0] FIX account_invoice_triple_discount - _recompute_tax_lines involving only relevant lines: invoice_line_ids
  account_invoice_triple_discount/models/account_move.py
Labels: approved, ready to merge, bot is merging ⏳

#1364 [16.0][ADD] account_tax_one_vat
  account_tax_one_vat/README.rst
  account_tax_one_vat/__init__.py
  account_tax_one_vat/__manifest__.py
  account_tax_one_vat/i18n/account_tax_one_vat.pot
  account_tax_one_vat/i18n/fr_BE.po
  account_tax_one_vat/models/__init__.py
  account_tax_one_vat/models/account_move.py
  account_tax_one_vat/models/account_move_line.py
  account_tax_one_vat/models/account_tax.py
  account_tax_one_vat/models/account_tax_template.py
  account_tax_one_vat/models/one_vat_mixin.py
  account_tax_one_vat/models/product_template.py
  account_tax_one_vat/models/res_company.py
  account_tax_one_vat/models/res_config_settings.py
  account_tax_one_vat/readme/CONTRIBUTORS.rst
  account_tax_one_vat/readme/DESCRIPTION.rst
  account_tax_one_vat/readme/USAGE.rst
  account_tax_one_vat/static/description/index.html
  account_tax_one_vat/tests/__init__.py
  account_tax_one_vat/tests/common.py
  account_tax_one_vat/tests/test_account_tax_one_vat.py
  account_tax_one_vat/views/account_tax_views.xml
  account_tax_one_vat/views/res_config_settings_views.xml
  setup/account_tax_one_vat/odoo/addons/account_tax_one_vat
  setup/account_tax_one_vat/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#1448 [14.0][IMP] account_global_discount, added init hook to avoid memory issues on big database installation
  account_global_discount/__init__.py
  account_global_discount/__manifest__.py
  account_global_discount/hooks.py
Labels: approved, bot is merging ⏳

#1603 [14.0][FIX] account_invoice_refund_link: Proper tagging test with post_install
  account_invoice_refund_link/tests/test_invoice_refund_link.py
Labels: approved, ready to merge, bot is merging ⏳

#1598 [14.0][IMP] account_invoice_base_invoicing_mode: Adding shared methods and tests
  account_invoice_base_invoicing_mode/README.rst
  account_invoice_base_invoicing_mode/models/sale_order.py
  account_invoice_base_invoicing_mode/readme/CONTRIBUTORS.rst
  account_invoice_base_invoicing_mode/static/description/index.html
  account_invoice_base_invoicing_mode/tests/__init__.py
  account_invoice_base_invoicing_mode/tests/common.py
  account_invoice_base_invoicing_mode/tests/test_invoice_base_mode.py
  account_invoice_mode_at_shipping/README.rst
  account_invoice_mode_at_shipping/__manifest__.py
  account_invoice_mode_at_shipping/models/stock_picking.py
  account_invoice_mode_at_shipping/readme/CONTRIBUTORS.rst
  account_invoice_mode_at_shipping/static/description/index.html
  account_invoice_mode_at_shipping/tests/test_invoice_mode_at_shipping.py
  account_invoice_mode_monthly/README.rst
  account_invoice_mode_monthly/__init__.py
  account_invoice_mode_monthly/__manifest__.py
  account_invoice_mode_monthly/models/sale_order.py
  account_invoice_mode_monthly/readme/CONTRIBUTORS.rst
  account_invoice_mode_monthly/static/description/index.html
  account_invoice_mode_monthly/tests/test_invoice_mode_monthly.py
  account_invoice_mode_weekly/README.rst
  account_invoice_mode_weekly/__init__.py
  account_invoice_mode_weekly/__manifest__.py
  account_invoice_mode_weekly/models/sale_order.py
  account_invoice_mode_weekly/readme/CONTRIBUTORS.rst
  account_invoice_mode_weekly/static/description/index.html
  account_invoice_mode_weekly/tests/test_invoice_mode_weekly.py
  account_invoice_pricelist/README.rst
  account_invoice_pricelist/readme/CONTRIBUTORS.rst
  account_invoice_pricelist/static/description/index.html
  account_invoice_pricelist/tests/test_account_move_pricelist.py
Labels: approved, ready to merge, bot is merging ⏳

#1605 [14.0] [FIX] account_invoice_triple_discount: for in invoice_line_ids if exists, else on line_ids
  account_invoice_triple_discount/models/account_move.py
Labels: approved, bot is merging ⏳

#1606 [FIX] account_invoice_triple_discount: Discount rounding
  account_invoice_triple_discount/README.rst
  account_invoice_triple_discount/models/account_move.py
  account_invoice_triple_discount/models/account_move_line.py
  account_invoice_triple_discount/readme/CONTRIBUTORS.rst
  account_invoice_triple_discount/static/description/index.html
  account_invoice_triple_discount/tests/test_invoice_triple_discount.py
Labels: approved, ready to merge, bot is merging ⏳

#1618 [MIG] stock_picking_invoicing_incoterm: Migration to 14.0
  setup/stock_picking_invoicing_incoterm/odoo/addons/stock_picking_invoicing_incoterm
  setup/stock_picking_invoicing_incoterm/setup.py
  stock_picking_invoicing_incoterm/README.rst
  stock_picking_invoicing_incoterm/__init__.py
  stock_picking_invoicing_incoterm/__manifest__.py
  stock_picking_invoicing_incoterm/i18n/it.po
  stock_picking_invoicing_incoterm/models/__init__.py
  stock_picking_invoicing_incoterm/models/stock.py
  stock_picking_invoicing_incoterm/static/description/icon.png
  stock_picking_invoicing_incoterm/views/stock_picking_views.xml
Labels: needs review, bot is merging ⏳

#1486 [15.0][ADD] account_manual_currency
  account_manual_currency/README.rst
  account_manual_currency/__init__.py
  account_manual_currency/__manifest__.py
  account_manual_currency/data/decimal_data.xml
  account_manual_currency/models/__init__.py
  account_manual_currency/models/account_move.py
  account_manual_currency/readme/CONTRIBUTORS.rst
  account_manual_currency/readme/DESCRIPTION.rst
  account_manual_currency/readme/USAGE.rst
  account_manual_currency/static/description/icon.png
  account_manual_currency/static/description/index.html
  account_manual_currency/tests/__init__.py
  account_manual_currency/tests/test_account_manual_currency.py
  account_manual_currency/views/account_move_view.xml
  account_manual_currency/wizard/__init__.py
  account_manual_currency/wizard/account_payment_register.py
  setup/account_manual_currency/odoo/addons/account_manual_currency
  setup/account_manual_currency/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#1599 [14.0][ADD] account_invoice_mode_daily
  account_invoice_mode_daily/README.rst
  account_invoice_mode_daily/__init__.py
  account_invoice_mode_daily/__manifest__.py
  account_invoice_mode_daily/data/ir_cron.xml
  account_invoice_mode_daily/data/queue_job_data.xml
  account_invoice_mode_daily/i18n/account_invoice_mode_daily.pot
  account_invoice_mode_daily/models/__init__.py
  account_invoice_mode_daily/models/res_company.py
  account_invoice_mode_daily/models/res_config_settings.py
  account_invoice_mode_daily/models/res_partner.py
  account_invoice_mode_daily/models/sale_order.py
  account_invoice_mode_daily/readme/CONTRIBUTORS.rst
  account_invoice_mode_daily/readme/DESCRIPTION.rst
  account_invoice_mode_daily/static/description/icon.png
  account_invoice_mode_daily/static/description/index.html
  account_invoice_mode_daily/tests/__init__.py
  account_invoice_mode_daily/tests/test_invoice_mode_daily.py
  account_invoice_mode_daily/views/res_config_settings_views.xml
  setup/account_invoice_mode_daily/odoo/addons/account_invoice_mode_daily
  setup/account_invoice_mode_daily/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#1246 [14.0][FIX] account_invoice_check_total: Proper tagging of unittests
  account_invoice_check_total/tests/test_account_invoice.py
Labels: approved, ready to merge, bot is merging ⏳

#1465 [16.0][MIG] stock_picking_invoicing: Migration to 16.0
  setup/stock_picking_invoicing/odoo/addons/stock_picking_invoicing
  setup/stock_picking_invoicing/setup.py
  stock_picking_invoicing/README.rst
  stock_picking_invoicing/__init__.py
  stock_picking_invoicing/__manifest__.py
  stock_picking_invoicing/demo/stock_picking_demo.xml
  stock_picking_invoicing/i18n/ca.po
  stock_picking_invoicing/i18n/de.po
  stock_picking_invoicing/i18n/es.po
  stock_picking_invoicing/i18n/fr.po
  stock_picking_invoicing/i18n/pt_BR.po
  stock_picking_invoicing/i18n/sl.po
  stock_picking_invoicing/i18n/stock_picking_invoicing.pot
  stock_picking_invoicing/models/__init__.py
  stock_picking_invoicing/models/account_move.py
  stock_picking_invoicing/models/stock_invoice_state_mixin.py
  stock_picking_invoicing/models/stock_move.py
  stock_picking_invoicing/models/stock_picking.py
  stock_picking_invoicing/models/stock_picking_type.py
  stock_picking_invoicing/readme/CONTRIBUTORS.rst
  stock_picking_invoicing/readme/DESCRIPTION.rst
  stock_picking_invoicing/readme/HISTORY.rst
  stock_picking_invoicing/readme/INSTALL.rst
  stock_picking_invoicing/readme/USAGE.rst
  stock_picking_invoicing/security/ir.model.access.csv
  stock_picking_invoicing/static/description/icon.png
  stock_picking_invoicing/static/description/index.html
  stock_picking_invoicing/tests/__init__.py
  stock_picking_invoicing/tests/common.py
  stock_picking_invoicing/tests/test_picking_invoicing.py
  stock_picking_invoicing/views/stock_move_views.xml
  stock_picking_invoicing/views/stock_picking_type_views.xml
  stock_picking_invoicing/views/stock_picking_views.xml
  stock_picking_invoicing/wizards/__init__.py
  stock_picking_invoicing/wizards/stock_invoice_onshipping.py
  stock_picking_invoicing/wizards/stock_invoice_onshipping_view.xml
  stock_picking_invoicing/wizards/stock_return_picking.py
  stock_picking_invoicing/wizards/stock_return_picking_view.xml
Labels: approved, bot is merging ⏳
