Repository OCA/account-invoicing, pull requests merged in 2023-05, with the labels that each got.

#1458 [15.0][FIX] sale_timesheet_invoice_description: Fix tests according to qty_delivered compute change since
  sale_timesheet_invoice_description/tests/test_sale_timesheet_description.py
Labels: bot is merging ⏳

#1453 [16.0][FIX] account_invoice_merge: this commit fixes the incorrect link bet…
  account_invoice_merge/models/account_move.py
  account_invoice_merge/tests/test_account_invoice_merge.py
Labels: approved, bot is merging ⏳

#1433 [16.0][ADD] account_tax_change
  account_tax_change/README.rst
  account_tax_change/__init__.py
  account_tax_change/__manifest__.py
  account_tax_change/models/__init__.py
  account_tax_change/models/account_tax_change.py
  account_tax_change/readme/CONFIGURE.rst
  account_tax_change/readme/CONTRIBUTORS.rst
  account_tax_change/readme/DESCRIPTION.rst
  account_tax_change/readme/USAGE.rst
  account_tax_change/security/ir.model.access.csv
  account_tax_change/static/description/account_tax_change.png
  account_tax_change/static/description/apply_tax_changes_form.png
  account_tax_change/static/description/apply_tax_changes_menu.png
  account_tax_change/static/description/icon.png
  account_tax_change/static/description/index.html
  account_tax_change/tests/__init__.py
  account_tax_change/tests/common.py
  account_tax_change/tests/test_account_tax_change.py
  account_tax_change/views/account_tax_change.xml
  account_tax_change/wizards/__init__.py
  account_tax_change/wizards/account_move_apply_tax_change.py
  account_tax_change/wizards/account_move_apply_tax_change.xml
  setup/account_tax_change/odoo/addons/account_tax_change
  setup/account_tax_change/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#1443 [15.0][FIX] account_invoice_date_due: Singleton error when user set date due on more than one invoice
  account_invoice_date_due/README.rst
  account_invoice_date_due/models/account_move.py
  account_invoice_date_due/readme/CONTRIBUTORS.rst
  account_invoice_date_due/static/description/index.html
Labels: bot is merging ⏳

#1452 [15.0][MIG] stock_picking_invoicing: Migration to 15.0
  setup/stock_picking_invoicing/odoo/addons/stock_picking_invoicing
  setup/stock_picking_invoicing/setup.py
  stock_picking_invoicing/README.rst
  stock_picking_invoicing/__init__.py
  stock_picking_invoicing/__manifest__.py
  stock_picking_invoicing/demo/stock_picking_demo.xml
  stock_picking_invoicing/i18n/ca.po
  stock_picking_invoicing/i18n/de.po
  stock_picking_invoicing/i18n/es.po
  stock_picking_invoicing/i18n/fr.po
  stock_picking_invoicing/i18n/pt_BR.po
  stock_picking_invoicing/i18n/sl.po
  stock_picking_invoicing/i18n/stock_picking_invoicing.pot
  stock_picking_invoicing/models/__init__.py
  stock_picking_invoicing/models/account_move.py
  stock_picking_invoicing/models/stock_invoice_state_mixin.py
  stock_picking_invoicing/models/stock_move.py
  stock_picking_invoicing/models/stock_picking.py
  stock_picking_invoicing/models/stock_picking_type.py
  stock_picking_invoicing/readme/CONTRIBUTORS.rst
  stock_picking_invoicing/readme/DESCRIPTION.rst
  stock_picking_invoicing/readme/HISTORY.rst
  stock_picking_invoicing/readme/INSTALL.rst
  stock_picking_invoicing/readme/USAGE.rst
  stock_picking_invoicing/security/ir.model.access.csv
  stock_picking_invoicing/static/description/icon.png
  stock_picking_invoicing/static/description/index.html
  stock_picking_invoicing/tests/__init__.py
  stock_picking_invoicing/tests/test_picking_invoicing.py
  stock_picking_invoicing/views/stock_move.xml
  stock_picking_invoicing/views/stock_picking.xml
  stock_picking_invoicing/views/stock_picking_type.xml
  stock_picking_invoicing/wizards/__init__.py
  stock_picking_invoicing/wizards/stock_invoice_onshipping.py
  stock_picking_invoicing/wizards/stock_invoice_onshipping_view.xml
  stock_picking_invoicing/wizards/stock_return_picking.py
  stock_picking_invoicing/wizards/stock_return_picking_view.xml
Labels: approved, ready to merge, bot is merging ⏳

#1438 [15.0][ADD] account_invoice_clearing
  account_invoice_clearing/README.rst
  account_invoice_clearing/__init__.py
  account_invoice_clearing/__manifest__.py
  account_invoice_clearing/i18n/account_invoice_clearing.pot
  account_invoice_clearing/i18n/es.po
  account_invoice_clearing/models/__init__.py
  account_invoice_clearing/models/account_move.py
  account_invoice_clearing/readme/CONTRIBUTORS.rst
  account_invoice_clearing/readme/CREDITS.rst
  account_invoice_clearing/readme/DESCRIPTION.rst
  account_invoice_clearing/readme/ROADMAP.rst
  account_invoice_clearing/readme/USAGE.rst
  account_invoice_clearing/security/ir.model.access.csv
  account_invoice_clearing/static/description/icon.png
  account_invoice_clearing/tests/__init__.py
  account_invoice_clearing/tests/test_clearing_wizard.py
  account_invoice_clearing/views/account_move_view.xml
  account_invoice_clearing/wizards/__init__.py
  account_invoice_clearing/wizards/account_invoice_clearing_wizard.py
  account_invoice_clearing/wizards/account_invoice_clearing_wizard_views.xml
  setup/account_invoice_clearing/odoo/addons/account_invoice_clearing
  setup/account_invoice_clearing/setup.py
Labels: needs review, approved, bot is merging ⏳

#1464 [12.0][MIG] account_portal_invoice_search: Migration to 12.0
  account_portal_invoice_search/__init__.py
  account_portal_invoice_search/__manifest__.py
  account_portal_invoice_search/controllers/__init__.py
  account_portal_invoice_search/controllers/portal.py
  account_portal_invoice_search/models/__init__.py
  account_portal_invoice_search/models/account_move.py
  account_portal_invoice_search/readme/CONTRIBUTORS.rst
  account_portal_invoice_search/readme/DESCRIPTION.rst
  account_portal_invoice_search/readme/USAGE.rst
  account_portal_invoice_search/static/description/icon.png
  setup/account_portal_invoice_search/odoo/addons/account_portal_invoice_search
  setup/account_portal_invoice_search/setup.py
Labels: approved, bot is merging ⏳

#1261 [16.0][MIG] account_invoice_change_currency
  account_invoice_change_currency/README.rst
  account_invoice_change_currency/__init__.py
  account_invoice_change_currency/__manifest__.py
  account_invoice_change_currency/hooks.py
  account_invoice_change_currency/i18n/account_invoice_change_currency.pot
  account_invoice_change_currency/i18n/ca.po
  account_invoice_change_currency/i18n/de.po
  account_invoice_change_currency/i18n/es.po
  account_invoice_change_currency/i18n/es_MX.po
  account_invoice_change_currency/i18n/hr.po
  account_invoice_change_currency/models/__init__.py
  account_invoice_change_currency/models/account_move.py
  account_invoice_change_currency/models/account_move_line.py
  account_invoice_change_currency/models/res_currency.py
  account_invoice_change_currency/readme/CONFIGURE.rst
  account_invoice_change_currency/readme/CONTRIBUTORS.rst
  account_invoice_change_currency/readme/DESCRIPTION.rst
  account_invoice_change_currency/readme/USAGE.rst
  account_invoice_change_currency/static/description/icon.png
  account_invoice_change_currency/static/description/index.html
  account_invoice_change_currency/tests/__init__.py
  account_invoice_change_currency/tests/test_account_invoice_change_currency.py
  account_invoice_change_currency/views/account_move_views.xml
  setup/account_invoice_change_currency/odoo/addons/account_invoice_change_currency
  setup/account_invoice_change_currency/setup.py
Labels: approved, ready to merge, bot is merging ⏳
