Repository OCA/account-invoicing, pull requests merged in 2023-10, with the labels that each got.

#1566 [15.0][FIX] account_invoice_pricelist: Make tests resilient
  account_invoice_pricelist/tests/test_account_move_pricelist.py
Labels: bot is merging ⏳

#1576 [15.0] [IMP] improve tests performance
  account_invoice_date_due/tests/test_account_invoice_date_due.py
  account_invoice_mass_sending/tests/test_account_invoice_mass_sending.py
  account_invoice_refund_link/tests/test_invoice_refund_link.py
  account_invoice_tax_required/tests/test_account_move_tax_required.py
  account_invoice_transmit_method/tests/test_invoice_transmit_method.py
  purchase_stock_picking_return_invoicing/tests/test_purchase_stock_picking_return_invoicing.py
  sale_order_invoicing_grouping_criteria/tests/test_sale_order_invoicing_group_criteria.py
  stock_picking_return_refund_option/tests/test_stock_picking_return_refund_options.py
Labels: bot is merging ⏳

#1572 [16.0][MIG] account_invoice_crm_tag: Migration to version 16.0
  account_invoice_crm_tag/README.rst
  account_invoice_crm_tag/__init__.py
  account_invoice_crm_tag/__manifest__.py
  account_invoice_crm_tag/i18n/account_invoice_crm_tag.pot
  account_invoice_crm_tag/i18n/es.po
  account_invoice_crm_tag/models/__init__.py
  account_invoice_crm_tag/models/account_move.py
  account_invoice_crm_tag/models/sale_order.py
  account_invoice_crm_tag/readme/CONTRIBUTORS.rst
  account_invoice_crm_tag/readme/DESCRIPTION.rst
  account_invoice_crm_tag/readme/USAGE.rst
  account_invoice_crm_tag/report/__init__.py
  account_invoice_crm_tag/report/account_invoice_report.py
  account_invoice_crm_tag/report/account_invoice_report.xml
  account_invoice_crm_tag/static/description/icon.png
  account_invoice_crm_tag/static/description/index.html
  account_invoice_crm_tag/views/account_invoice_views.xml
  setup/account_invoice_crm_tag/odoo/addons/account_invoice_crm_tag
  setup/account_invoice_crm_tag/setup.py
Labels: approved, bot is merging ⏳

#1051 [14.0] Create module account_invoice_section_picking
  account_invoice_section_picking/README.rst
  account_invoice_section_picking/__init__.py
  account_invoice_section_picking/__manifest__.py
  account_invoice_section_picking/models/__init__.py
  account_invoice_section_picking/models/account_move_line.py
  account_invoice_section_picking/models/res_company.py
  account_invoice_section_picking/models/stock_picking.py
  account_invoice_section_picking/readme/CONTRIBUTORS.rst
  account_invoice_section_picking/readme/DESCRIPTION.rst
  account_invoice_section_picking/readme/ROADMAP.rst
  account_invoice_section_picking/tests/__init__.py
  account_invoice_section_picking/tests/common.py
  account_invoice_section_picking/tests/test_account_invoice_section_picking.py
  account_invoice_section_picking/tests/test_account_invoice_section_picking_backorder.py
  setup/account_invoice_section_picking/odoo/addons/account_invoice_section_picking
  setup/account_invoice_section_picking/setup.py
Labels: approved, bot is merging ⏳

#1403 [15.0][mig]-account_invoice_line_description
  account_invoice_line_description/README.rst
  account_invoice_line_description/__init__.py
  account_invoice_line_description/__manifest__.py
  account_invoice_line_description/i18n/account_invoice_line_description.pot
  account_invoice_line_description/i18n/ar.po
  account_invoice_line_description/i18n/bs.po
  account_invoice_line_description/i18n/ca.po
  account_invoice_line_description/i18n/cs.po
  account_invoice_line_description/i18n/de.po
  account_invoice_line_description/i18n/en_GB.po
  account_invoice_line_description/i18n/es.po
  account_invoice_line_description/i18n/es_CR.po
  account_invoice_line_description/i18n/es_EC.po
  account_invoice_line_description/i18n/es_ES.po
  account_invoice_line_description/i18n/es_MX.po
  account_invoice_line_description/i18n/et.po
  account_invoice_line_description/i18n/fr.po
  account_invoice_line_description/i18n/fr_CH.po
  account_invoice_line_description/i18n/hr.po
  account_invoice_line_description/i18n/hr_HR.po
  account_invoice_line_description/i18n/hu.po
  account_invoice_line_description/i18n/it.po
  account_invoice_line_description/i18n/ja.po
  account_invoice_line_description/i18n/lt.po
  account_invoice_line_description/i18n/mk.po
  account_invoice_line_description/i18n/mn.po
  account_invoice_line_description/i18n/nb.po
  account_invoice_line_description/i18n/nl.po
  account_invoice_line_description/i18n/nl_BE.po
  account_invoice_line_description/i18n/nl_NL.po
  account_invoice_line_description/i18n/pt.po
  account_invoice_line_description/i18n/pt_BR.po
  account_invoice_line_description/i18n/pt_PT.po
  account_invoice_line_description/i18n/ro.po
  account_invoice_line_description/i18n/ru.po
  account_invoice_line_description/i18n/sl.po
  account_invoice_line_description/i18n/sv.po
  account_invoice_line_description/i18n/tr.po
  account_invoice_line_description/i18n/tr_TR.po
  account_invoice_line_description/i18n/zh_CN.po
  account_invoice_line_description/i18n/zh_TW.po
  account_invoice_line_description/models/__init__.py
  account_invoice_line_description/models/account_move.py
  account_invoice_line_description/readme/CONFIGURE.rst
  account_invoice_line_description/readme/CONTRIBUTORS.rst
  account_invoice_line_description/readme/DESCRIPTION.rst
  account_invoice_line_description/security/account_security.xml
  account_invoice_line_description/static/description/icon.png
  account_invoice_line_description/static/description/index.html
  account_invoice_line_description/tests/__init__.py
  account_invoice_line_description/tests/test_account_invoice_line_description.py
  account_invoice_line_description/wizards/__init__.py
  account_invoice_line_description/wizards/res_config.py
  account_invoice_line_description/wizards/res_config_view.xml
  setup/account_invoice_line_description/odoo/addons/account_invoice_line_description
  setup/account_invoice_line_description/setup.py
Labels: needs review, approved, ready to merge, bot is merging ⏳

#1578 [16.0][ADD] account_invoice_refund_code
  account_invoice_refund_code/README.rst
  account_invoice_refund_code/__init__.py
  account_invoice_refund_code/__manifest__.py
  account_invoice_refund_code/models/__init__.py
  account_invoice_refund_code/models/account_journal.py
  account_invoice_refund_code/models/account_move.py
  account_invoice_refund_code/readme/CONTRIBUTORS.rst
  account_invoice_refund_code/readme/DESCRIPTION.rst
  account_invoice_refund_code/readme/USAGE.rst
  account_invoice_refund_code/static/description/index.html
  account_invoice_refund_code/tests/__init__.py
  account_invoice_refund_code/tests/test_refund_code.py
  account_invoice_refund_code/views/account_journal_views.xml
  setup/account_invoice_refund_code/odoo/addons/account_invoice_refund_code
  setup/account_invoice_refund_code/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#1589 [14.0] dotfiles update needs manual intervention
  .copier-answers.yml
  .eslintrc.yml
  .github/workflows/pre-commit.yml
  .github/workflows/test.yml
  .pre-commit-config.yaml
  account_billing/i18n/account_billing.pot
  account_invoice_base_invoicing_mode/data/queue_job_data.xml
  account_invoice_check_total/i18n/es_ES.po
  account_invoice_check_total/i18n/hr.po
  account_invoice_check_total/i18n/hr_HR.po
  account_invoice_check_total/i18n/nl_NL.po
  account_invoice_mode_monthly/data/queue_job_data.xml
  account_invoice_refund_line_selection/wizards/account_move_reversal_view.xml
  account_invoice_supplierinfo_update/wizard/wizard_update_invoice_supplierinfo.xml
  account_invoice_transmit_method/i18n/account_invoice_transmit_method.pot
  account_invoice_transmit_method/views/transmit_method.xml
  account_invoice_triple_discount/report/invoice.xml
  account_invoice_validation_queued/data/queue_job.xml
  account_move_line_accounting_description/reports/invoice.xml
  account_move_post_block/i18n/account_move_post_block.pot
  account_move_post_block/views/account_post_block_reason_view.xml
  account_move_tier_validation/i18n/account_move_tier_validation.pot
  account_move_tier_validation_approver/views/res_partner_views.xml
  account_receipt_print/views/account_report.xml
  account_receipt_print/views/report_receipt.xml
  accounting_partner_category/i18n/accounting_partner_category.pot
  accounting_partner_category/views/account_move.xml
  accounting_partner_category/views/account_partner_category.xml
  accounting_partner_category/views/partner_view.xml
  sale_line_refund_to_invoice_qty/views/account_move_views.xml
  sale_line_refund_to_invoice_qty/wizards/account_move_reversal_view.xml
  sale_order_invoicing_queued/data/job_queue.xml
Labels: needs review

#1591 [15.0][MIG]account_invoice_warn_message
  account_invoice_warn_message/README.rst
  account_invoice_warn_message/__init__.py
  account_invoice_warn_message/__manifest__.py
  account_invoice_warn_message/i18n/account_invoice_warn_message.pot
  account_invoice_warn_message/i18n/es.po
  account_invoice_warn_message/models/__init__.py
  account_invoice_warn_message/models/account_move.py
  account_invoice_warn_message/readme/CONTRIBUTORS.rst
  account_invoice_warn_message/readme/DESCRIPTION.rst
  account_invoice_warn_message/static/description/icon.png
  account_invoice_warn_message/static/description/index.html
  account_invoice_warn_message/tests/__init__.py
  account_invoice_warn_message/tests/test_account_invoice_warn_message.py
  account_invoice_warn_message/views/account_move_views.xml
  setup/account_invoice_warn_message/odoo/addons/account_invoice_warn_message
  setup/account_invoice_warn_message/setup.py
Labels: approved, bot is merging ⏳
