Repository OCA/account-invoicing, pull requests merged in 2023-01, with the labels that each got.

#1327 [13.0][FIX] sale_line_refund_to_invoice_qty: do not change invoiced qty
  sale_line_refund_to_invoice_qty/models/sale.py
  sale_line_refund_to_invoice_qty/readme/CONTRIBUTORS.rst
  sale_line_refund_to_invoice_qty/tests/test_sale_line_refund_to_invoice_qty.py
Labels: approved, ready to merge, bot is merging ⏳

#1333 [14.0][FW] sale_line_refund_to_invoice_qty: do not change invoiced qty
  sale_line_refund_to_invoice_qty/models/sale.py
  sale_line_refund_to_invoice_qty/readme/CONTRIBUTORS.rst
  sale_line_refund_to_invoice_qty/tests/test_sale_line_refund_to_invoice_qty.py
Labels: bot is merging ⏳

#1233 [14.0][FIX] account_invoice_alternate_payer, Set right partner on alternate invoices lines
  account_invoice_alternate_payer/models/account_move.py
  account_invoice_alternate_payer/tests/test_account_invoice.py
Labels: needs review, bot is merging ⏳

#1092 [MIG] account_invoice_pricelist_sale: Migration to 15.0
  account_invoice_pricelist_sale/README.rst
  account_invoice_pricelist_sale/__init__.py
  account_invoice_pricelist_sale/__manifest__.py
  account_invoice_pricelist_sale/i18n/account_invoice_pricelist_sale.pot
  account_invoice_pricelist_sale/i18n/ca.po
  account_invoice_pricelist_sale/i18n/de.po
  account_invoice_pricelist_sale/i18n/el_GR.po
  account_invoice_pricelist_sale/i18n/es.po
  account_invoice_pricelist_sale/i18n/es_ES.po
  account_invoice_pricelist_sale/i18n/es_VE.po
  account_invoice_pricelist_sale/i18n/fi.po
  account_invoice_pricelist_sale/i18n/fr.po
  account_invoice_pricelist_sale/i18n/hr.po
  account_invoice_pricelist_sale/i18n/hr_HR.po
  account_invoice_pricelist_sale/i18n/hu.po
  account_invoice_pricelist_sale/i18n/it.po
  account_invoice_pricelist_sale/i18n/nl.po
  account_invoice_pricelist_sale/i18n/nl_NL.po
  account_invoice_pricelist_sale/i18n/pt.po
  account_invoice_pricelist_sale/i18n/pt_BR.po
  account_invoice_pricelist_sale/i18n/ro.po
  account_invoice_pricelist_sale/i18n/sl.po
  account_invoice_pricelist_sale/i18n/tr.po
  account_invoice_pricelist_sale/i18n/tr_TR.po
  account_invoice_pricelist_sale/i18n/vi_VN.po
  account_invoice_pricelist_sale/i18n/zh_CN.po
  account_invoice_pricelist_sale/models/__init__.py
  account_invoice_pricelist_sale/models/sale_order.py
  account_invoice_pricelist_sale/readme/CONTRIBUTORS.rst
  account_invoice_pricelist_sale/readme/DESCRIPTION.rst
  account_invoice_pricelist_sale/readme/INSTALLATION.rst
  account_invoice_pricelist_sale/static/description/icon.png
  account_invoice_pricelist_sale/static/description/index.html
  account_invoice_pricelist_sale/tests/__init__.py
  account_invoice_pricelist_sale/tests/test_module.py
  setup/account_invoice_pricelist_sale/odoo/addons/account_invoice_pricelist_sale
  setup/account_invoice_pricelist_sale/setup.py
Labels: bot is merging ⏳

#1339 [15.0][FIX] sale_line_refund_to_invoice_qty: do not change invoiced qty
  sale_line_refund_to_invoice_qty/models/sale.py
  sale_line_refund_to_invoice_qty/readme/CONTRIBUTORS.rst
  sale_line_refund_to_invoice_qty/tests/test_sale_line_refund_to_invoice_qty.py
Labels: bot is merging ⏳

#1330 [13.0][ADD] product_form_account_move_line_link
  product_form_account_move_line_link/README.rst
  product_form_account_move_line_link/__init__.py
  product_form_account_move_line_link/__manifest__.py
  product_form_account_move_line_link/models/__init__.py
  product_form_account_move_line_link/models/product_product.py
  product_form_account_move_line_link/models/product_template.py
  product_form_account_move_line_link/readme/CONTRIBUTORS.rst
  product_form_account_move_line_link/readme/DESCRIPTION.rst
  product_form_account_move_line_link/readme/USAGE.rst
  product_form_account_move_line_link/static/description/icon.png
  product_form_account_move_line_link/views/account_move_line_views.xml
  product_form_account_move_line_link/views/product_product_views.xml
  product_form_account_move_line_link/views/product_template_views.xml
  setup/product_form_account_move_line_link/odoo/addons/product_form_account_move_line_link
  setup/product_form_account_move_line_link/setup.py
Labels: needs review, approved, bot is merging ⏳

#1341 [13.0][ADD] account_portal_invoice_search: New module to search invoices in portal
  account_portal_invoice_search/README.rst
  account_portal_invoice_search/__init__.py
  account_portal_invoice_search/__manifest__.py
  account_portal_invoice_search/controllers/__init__.py
  account_portal_invoice_search/controllers/portal.py
  account_portal_invoice_search/i18n/account_portal_invoice_search.pot
  account_portal_invoice_search/i18n/es.po
  account_portal_invoice_search/models/__init__.py
  account_portal_invoice_search/models/account_move.py
  account_portal_invoice_search/readme/CONTRIBUTORS.rst
  account_portal_invoice_search/readme/DESCRIPTION.rst
  account_portal_invoice_search/readme/USAGE.rst
  account_portal_invoice_search/static/description/index.html
  setup/account_portal_invoice_search/odoo/addons/account_portal_invoice_search
  setup/account_portal_invoice_search/setup.py
Labels: approved, bot is merging ⏳

#1343 [15.0] add account_block_payment
  README.md
  account_invoice_block_payment/README.md
  account_invoice_block_payment/__init__.py
  account_invoice_block_payment/__manifest__.py
  account_invoice_block_payment/i18n/account_invoice_block_payment.pot
  account_invoice_block_payment/i18n/de.po
  account_invoice_block_payment/i18n/fr.po
  account_invoice_block_payment/models/__init__.py
  account_invoice_block_payment/models/account_move.py
  account_invoice_block_payment/readme/CONTRIBUTORS.rst
  account_invoice_block_payment/readme/DESCRIPTION.rst
  account_invoice_block_payment/readme/USAGE.rst
  account_invoice_block_payment/tests/__init__.py
  account_invoice_block_payment/tests/test_account_block_payment.py
  account_invoice_block_payment/views/account_move.xml
  setup/account_invoice_block_payment/odoo/addons/account_invoice_block_payment
  setup/account_invoice_block_payment/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#1319 [IMP] account_invoice_supplier_self_invoice: Improve footer management
  account_invoice_supplier_self_invoice/models/res_partner.py
  account_invoice_supplier_self_invoice/tests/test_self_invoice.py
Labels: needs review, approved, bot is merging ⏳

#1352 [14.0][FIX] account_invoice_pricelist: Make tests resilient
  account_invoice_pricelist/tests/test_account_move_pricelist.py
Labels: approved, bot is merging ⏳

#1354 [15.0][FIX] account_invoice_pricelist: Make tests resilient
  account_invoice_pricelist/tests/test_account_move_pricelist.py
Labels: approved, bot is merging ⏳

#1355 [13.0][FIX] account_invoice_refund_reason: refund and new draft invoice
  account_invoice_refund_reason/wizard/account_move_reversal.py
Labels: approved, bot is merging ⏳

#1359 [FIX] account_invoice_supplier_self_invoice: Use country
  account_invoice_supplier_self_invoice/views/report_self_invoice.xml
Labels: needs review, approved, bot is merging ⏳

#1362 [15.0][FIX] copier & pre-commit
  .copier-answers.yml
  .github/workflows/pre-commit.yml
  .github/workflows/test.yml
  .pre-commit-config.yaml
Labels: bot is merging ⏳
