Repository OCA/account-invoicing, pull requests merged in 2023-03, with the labels that each got.

#1399 [16.0][FIX] account_invoice_refund_link - correct link creation
  account_invoice_refund_link/models/account_move.py
  account_invoice_refund_link/tests/test_invoice_refund_link.py
Labels: needs review, approved, bot is merging ⏳

#1401 [15.0][ADD] Account Receipt Send
  account_receipt_send/README.rst
  account_receipt_send/__init__.py
  account_receipt_send/__manifest__.py
  account_receipt_send/data/mail_template_data.xml
  account_receipt_send/models/__init__.py
  account_receipt_send/models/account_move.py
  account_receipt_send/readme/CONFIGURE.rst
  account_receipt_send/readme/CONTRIBUTORS.rst
  account_receipt_send/readme/DESCRIPTION.rst
  account_receipt_send/readme/USAGE.rst
  account_receipt_send/static/description/icon.png
  account_receipt_send/static/description/index.html
  account_receipt_send/tests/__init__.py
  account_receipt_send/tests/test_account_receipt.py
  account_receipt_send/views/account_move_views.xml
  setup/account_receipt_send/odoo/addons/account_receipt_send
  setup/account_receipt_send/setup.py
Labels: needs review, approved, bot is merging ⏳

#1398 [15.0][MIG] account_receipt_journal
  account_receipt_journal/README.rst
  account_receipt_journal/__init__.py
  account_receipt_journal/__manifest__.py
  account_receipt_journal/data/account_journal_data.xml
  account_receipt_journal/i18n/account_receipt_journal.pot
  account_receipt_journal/models/__init__.py
  account_receipt_journal/models/account_journal.py
  account_receipt_journal/models/account_move.py
  account_receipt_journal/readme/CONTRIBUTORS.rst
  account_receipt_journal/readme/DESCRIPTION.rst
  account_receipt_journal/readme/HISTORY.rst
  account_receipt_journal/static/description/icon.png
  account_receipt_journal/static/description/index.html
  account_receipt_journal/tests/__init__.py
  account_receipt_journal/tests/test_receipts.py
  account_receipt_journal/views/account_journal_views.xml
  requirements.txt
  setup/account_receipt_journal/odoo/addons/account_receipt_journal
  setup/account_receipt_journal/setup.py
Labels: needs review, approved, ready to merge, bot is merging ⏳

#1411 [15.0][MIG] account_portal_invoice_search: Migration to version 15.0
  account_portal_invoice_search/README.rst
  account_portal_invoice_search/__init__.py
  account_portal_invoice_search/__manifest__.py
  account_portal_invoice_search/controllers/__init__.py
  account_portal_invoice_search/controllers/portal.py
  account_portal_invoice_search/i18n/account_portal_invoice_search.pot
  account_portal_invoice_search/i18n/es.po
  account_portal_invoice_search/models/__init__.py
  account_portal_invoice_search/models/account_move.py
  account_portal_invoice_search/readme/CONTRIBUTORS.rst
  account_portal_invoice_search/readme/DESCRIPTION.rst
  account_portal_invoice_search/readme/USAGE.rst
  account_portal_invoice_search/static/description/icon.png
  account_portal_invoice_search/static/description/index.html
  setup/account_portal_invoice_search/odoo/addons/account_portal_invoice_search
  setup/account_portal_invoice_search/setup.py
Labels: approved, bot is merging ⏳

#1416 [15.0][MIG] sale_order_invoicing_qty_percentage: Migration to version 15.0
  sale_order_invoicing_qty_percentage/README.rst
  sale_order_invoicing_qty_percentage/__init__.py
  sale_order_invoicing_qty_percentage/__manifest__.py
  sale_order_invoicing_qty_percentage/i18n/es.po
  sale_order_invoicing_qty_percentage/i18n/sale_order_invoicing_qty_percentage.pot
  sale_order_invoicing_qty_percentage/models/__init__.py
  sale_order_invoicing_qty_percentage/models/sale_order.py
  sale_order_invoicing_qty_percentage/readme/CONTRIBUTORS.rst
  sale_order_invoicing_qty_percentage/readme/DESCRIPTION.rst
  sale_order_invoicing_qty_percentage/readme/ROADMAP.rst
  sale_order_invoicing_qty_percentage/readme/USAGE.rst
  sale_order_invoicing_qty_percentage/static/description/icon.png
  sale_order_invoicing_qty_percentage/static/description/index.html
  sale_order_invoicing_qty_percentage/tests/__init__.py
  sale_order_invoicing_qty_percentage/tests/test_sale_order_invoicing_qty_percentage.py
  sale_order_invoicing_qty_percentage/wizards/__init__.py
  sale_order_invoicing_qty_percentage/wizards/sale_advance_payment_inv.py
  sale_order_invoicing_qty_percentage/wizards/sale_advance_payment_inv_views.xml
  setup/sale_order_invoicing_qty_percentage/odoo/addons/sale_order_invoicing_qty_percentage
  setup/sale_order_invoicing_qty_percentage/setup.py
Labels: approved, bot is merging ⏳

#1181 [FIX] account_invoice_pricelist: float division by zero
  account_invoice_pricelist/models/account_move.py
  account_invoice_pricelist/tests/test_account_move_pricelist.py
Labels: approved, bot is merging ⏳

#1422 [13.0][FIX] account_invoice_supplierinfo_update: migration script
  account_invoice_supplierinfo_update/migrations/13.0.1.0.0/pre-migration.py
Labels: approved

#1282 [14.0] [MIG] account_invoice_mass_sending
  account_invoice_mass_sending/README.rst
  account_invoice_mass_sending/__init__.py
  account_invoice_mass_sending/__manifest__.py
  account_invoice_mass_sending/i18n/account_invoice_mass_sending.pot
  account_invoice_mass_sending/i18n/es.po
  account_invoice_mass_sending/i18n/fr.po
  account_invoice_mass_sending/models/__init__.py
  account_invoice_mass_sending/models/account_move.py
  account_invoice_mass_sending/readme/CONFIGURE.rst
  account_invoice_mass_sending/readme/CONTRIBUTORS.rst
  account_invoice_mass_sending/readme/DESCRIPTION.rst
  account_invoice_mass_sending/readme/USAGE.rst
  account_invoice_mass_sending/static/description/icon.png
  account_invoice_mass_sending/static/description/index.html
  account_invoice_mass_sending/tests/__init__.py
  account_invoice_mass_sending/tests/test_account_invoice_mass_sending.py
  account_invoice_mass_sending/views/account_invoice_views.xml
  setup/account_invoice_mass_sending/odoo/addons/account_invoice_mass_sending
  setup/account_invoice_mass_sending/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#1384 [14.0][ADD] sale_order_invoicing_qty_percentage
  account_invoice_section_sale_order/tests/test_invoice_group_by_sale_order.py
  sale_order_invoicing_qty_percentage/README.rst
  sale_order_invoicing_qty_percentage/__init__.py
  sale_order_invoicing_qty_percentage/__manifest__.py
  sale_order_invoicing_qty_percentage/i18n/es.po
  sale_order_invoicing_qty_percentage/i18n/sale_order_invoicing_qty_percentage.pot
  sale_order_invoicing_qty_percentage/models/__init__.py
  sale_order_invoicing_qty_percentage/models/sale_order.py
  sale_order_invoicing_qty_percentage/readme/CONTRIBUTORS.rst
  sale_order_invoicing_qty_percentage/readme/DESCRIPTION.rst
  sale_order_invoicing_qty_percentage/readme/ROADMAP.rst
  sale_order_invoicing_qty_percentage/readme/USAGE.rst
  sale_order_invoicing_qty_percentage/static/description/icon.png
  sale_order_invoicing_qty_percentage/static/description/index.html
  sale_order_invoicing_qty_percentage/tests/__init__.py
  sale_order_invoicing_qty_percentage/tests/test_sale_order_invoicing_qty_percentage.py
  sale_order_invoicing_qty_percentage/wizards/__init__.py
  sale_order_invoicing_qty_percentage/wizards/sale_advance_payment_inv.py
  sale_order_invoicing_qty_percentage/wizards/sale_advance_payment_inv_views.xml
  setup/sale_order_invoicing_qty_percentage/odoo/addons/sale_order_invoicing_qty_percentage
  setup/sale_order_invoicing_qty_percentage/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#1426 [15.0][FIX] account_invoice_payment_term_date_due: fix view conflict with ocr
  account_invoice_payment_term_date_due/views/account_move.xml
Labels: bot is merging ⏳

#1378 [FIX][16.0] account_invoice_triple_discount : Error when print reports
  account_invoice_triple_discount/models/__init__.py
  account_invoice_triple_discount/models/account_move.py
  account_invoice_triple_discount/report/invoice.xml
  account_invoice_triple_discount/tests/test_invoice_triple_discount.py
Labels: approved, ready to merge, bot is merging ⏳

#951 [ADD] new module account_invoice_recompute_tax, to reset tax lines on supplier invoices form view
  account_invoice_recompute_tax/README.rst
  account_invoice_recompute_tax/__init__.py
  account_invoice_recompute_tax/__manifest__.py
  account_invoice_recompute_tax/i18n/fr.po
  account_invoice_recompute_tax/models/__init__.py
  account_invoice_recompute_tax/models/account_invoice.py
  account_invoice_recompute_tax/readme/CONTRIBUTORS.rst
  account_invoice_recompute_tax/readme/DESCRIPTION.rst
  account_invoice_recompute_tax/readme/DEVELOP.rst
  account_invoice_recompute_tax/static/description/account_invoice_form.png
  account_invoice_recompute_tax/views/view_account_invoice.xml
  setup/account_invoice_recompute_tax/odoo/addons/account_invoice_recompute_tax
  setup/account_invoice_recompute_tax/setup.py
Labels: needs review, approved, bot is merging ⏳
