Repository OCA/account-invoicing, pull requests merged in 2023-02, with the labels that each got.

#1363 [FIX] account_invoice_supplier_self_invoice: account_fiscal_country_i…
  account_invoice_supplier_self_invoice/views/report_self_invoice.xml
Labels: approved, bot is merging ⏳

#1358 [15.0] [MIG] product_form_account_move_line_link
  product_form_account_move_line_link/README.rst
  product_form_account_move_line_link/__init__.py
  product_form_account_move_line_link/__manifest__.py
  product_form_account_move_line_link/i18n/product_form_account_move_line_link.pot
  product_form_account_move_line_link/models/__init__.py
  product_form_account_move_line_link/models/product_product.py
  product_form_account_move_line_link/models/product_template.py
  product_form_account_move_line_link/readme/CONTRIBUTORS.rst
  product_form_account_move_line_link/readme/DESCRIPTION.rst
  product_form_account_move_line_link/readme/USAGE.rst
  product_form_account_move_line_link/static/description/icon.png
  product_form_account_move_line_link/static/description/index.html
  product_form_account_move_line_link/views/account_move_line_views.xml
  product_form_account_move_line_link/views/product_product_views.xml
  product_form_account_move_line_link/views/product_template_views.xml
  setup/product_form_account_move_line_link/odoo/addons/product_form_account_move_line_link
  setup/product_form_account_move_line_link/setup.py
Labels: approved, bot is merging ⏳

#1260 [14.0] ADD account_receipt_journal: Define and use journals dedicated to receipts
  account_receipt_journal/__init__.py
  account_receipt_journal/__manifest__.py
  account_receipt_journal/data/account_journal_data.xml
  account_receipt_journal/models/__init__.py
  account_receipt_journal/models/account_journal.py
  account_receipt_journal/models/account_move.py
  account_receipt_journal/readme/CONTRIBUTORS.rst
  account_receipt_journal/readme/DESCRIPTION.rst
  account_receipt_journal/readme/HISTORY.rst
  account_receipt_journal/tests/__init__.py
  account_receipt_journal/tests/test_receipts.py
  account_receipt_journal/views/account_journal_views.xml
  requirements.txt
  setup/account_receipt_journal/odoo/addons/account_receipt_journal
  setup/account_receipt_journal/setup.py
Labels: approved, bot is merging ⏳

#1365 [FIX] account_invoice_supplier_self_invoice: Use a smaller logo
  account_invoice_supplier_self_invoice/views/report_self_invoice.xml
Labels: needs review, approved, bot is merging ⏳

#1210 [15.0][MIG] account_invoice_validation_queued
  account_invoice_validation_queued/README.rst
  account_invoice_validation_queued/__init__.py
  account_invoice_validation_queued/__manifest__.py
  account_invoice_validation_queued/data/queue_job.xml
  account_invoice_validation_queued/i18n/account_invoice_validation_queued.pot
  account_invoice_validation_queued/i18n/ca.po
  account_invoice_validation_queued/i18n/es.po
  account_invoice_validation_queued/models/__init__.py
  account_invoice_validation_queued/models/account_move.py
  account_invoice_validation_queued/readme/CONFIGURE.rst
  account_invoice_validation_queued/readme/CONTRIBUTORS.rst
  account_invoice_validation_queued/readme/DESCRIPTION.rst
  account_invoice_validation_queued/readme/INSTALL.rst
  account_invoice_validation_queued/readme/ROADMAP.rst
  account_invoice_validation_queued/readme/USAGE.rst
  account_invoice_validation_queued/static/description/icon.png
  account_invoice_validation_queued/static/description/index.html
  account_invoice_validation_queued/tests/__init__.py
  account_invoice_validation_queued/tests/test_account_invoice_validation_queued.py
  account_invoice_validation_queued/views/account_invoice_views.xml
  account_invoice_validation_queued/views/queue_job_views.xml
  account_invoice_validation_queued/wizards/__init__.py
  account_invoice_validation_queued/wizards/validate_account_move.py
  account_invoice_validation_queued/wizards/validate_account_move_view.xml
  setup/account_invoice_validation_queued/odoo/addons/account_invoice_validation_queued
  setup/account_invoice_validation_queued/setup.py
Labels: approved, bot is merging ⏳

#1163 [15.0][MIG] stock_picking_invoicing_incoterm
  setup/stock_picking_invoicing_incoterm/odoo/addons/stock_picking_invoicing_incoterm
  setup/stock_picking_invoicing_incoterm/setup.py
  stock_picking_invoicing_incoterm/README.rst
  stock_picking_invoicing_incoterm/__init__.py
  stock_picking_invoicing_incoterm/__manifest__.py
  stock_picking_invoicing_incoterm/i18n/it.po
  stock_picking_invoicing_incoterm/models/__init__.py
  stock_picking_invoicing_incoterm/models/stock.py
  stock_picking_invoicing_incoterm/static/description/icon.png
  stock_picking_invoicing_incoterm/views/stock_picking_views.xml
Labels: approved, ready to merge, bot is merging ⏳

#1168 [15.0][MIG] product_supplierinfo_for_customer_invoice
  product_supplierinfo_for_customer_invoice/README.rst
  product_supplierinfo_for_customer_invoice/__init__.py
  product_supplierinfo_for_customer_invoice/__manifest__.py
  product_supplierinfo_for_customer_invoice/i18n/ca.po
  product_supplierinfo_for_customer_invoice/i18n/de.po
  product_supplierinfo_for_customer_invoice/i18n/es.po
  product_supplierinfo_for_customer_invoice/i18n/it.po
  product_supplierinfo_for_customer_invoice/i18n/product_supplierinfo_for_customer_invoice.pot
  product_supplierinfo_for_customer_invoice/i18n/pt.po
  product_supplierinfo_for_customer_invoice/i18n/pt_BR.po
  product_supplierinfo_for_customer_invoice/models/__init__.py
  product_supplierinfo_for_customer_invoice/models/account_move_line.py
  product_supplierinfo_for_customer_invoice/readme/CONTRIBUTORS.rst
  product_supplierinfo_for_customer_invoice/readme/DESCRIPTION.rst
  product_supplierinfo_for_customer_invoice/static/description/icon.png
  product_supplierinfo_for_customer_invoice/static/description/index.html
  product_supplierinfo_for_customer_invoice/tests/__init__.py
  product_supplierinfo_for_customer_invoice/tests/test_product_supplierinfo_for_customer_invoice.py
  product_supplierinfo_for_customer_invoice/views/account_move_view.xml
  setup/product_supplierinfo_for_customer_invoice/odoo/addons/product_supplierinfo_for_customer_invoice
  setup/product_supplierinfo_for_customer_invoice/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#1366 [14.0][FIX][account_invoice_view_payment] account_move: fix read()[0]
  account_invoice_view_payment/models/account_move.py
Labels: approved, ready to merge, bot is merging ⏳

#1324 [15.0][MIG] account_invoice_refund_reason
  account_invoice_refund_reason/README.rst
  account_invoice_refund_reason/__init__.py
  account_invoice_refund_reason/__manifest__.py
  account_invoice_refund_reason/data/account.move.refund.reason.csv
  account_invoice_refund_reason/i18n/account_invoice_refund_reason.pot
  account_invoice_refund_reason/i18n/de.po
  account_invoice_refund_reason/i18n/es.po
  account_invoice_refund_reason/i18n/hr.po
  account_invoice_refund_reason/models/__init__.py
  account_invoice_refund_reason/models/account_move.py
  account_invoice_refund_reason/models/account_move_refund_reason.py
  account_invoice_refund_reason/readme/CONFIGURE.rst
  account_invoice_refund_reason/readme/CONTRIBUTORS.rst
  account_invoice_refund_reason/readme/DESCRIPTION.rst
  account_invoice_refund_reason/readme/USAGE.rst
  account_invoice_refund_reason/security/ir.model.access.csv
  account_invoice_refund_reason/static/description/icon.png
  account_invoice_refund_reason/static/description/index.html
  account_invoice_refund_reason/tests/__init__.py
  account_invoice_refund_reason/tests/test_account_invoice_refund_reason.py
  account_invoice_refund_reason/views/account_move_refund_reason_view.xml
  account_invoice_refund_reason/views/account_move_view.xml
  account_invoice_refund_reason/wizard/__init__.py
  account_invoice_refund_reason/wizard/account_move_reversal.py
  account_invoice_refund_reason/wizard/account_move_reversal_view.xml
  setup/account_invoice_refund_reason/odoo/addons/account_invoice_refund_reason
  setup/account_invoice_refund_reason/setup.py
Labels: needs review, approved, ready to merge, bot is merging ⏳

#1325 [16.0][MIG] account_menu_invoice_refund: Migration to 16.0
  account_menu_invoice_refund/README.rst
  account_menu_invoice_refund/__init__.py
  account_menu_invoice_refund/__manifest__.py
  account_menu_invoice_refund/i18n/account_menu_invoice_refund.pot
  account_menu_invoice_refund/i18n/de.po
  account_menu_invoice_refund/i18n/es.po
  account_menu_invoice_refund/i18n/hr.po
  account_menu_invoice_refund/i18n/pt.po
  account_menu_invoice_refund/readme/CONTRIBUTORS.rst
  account_menu_invoice_refund/readme/DESCRIPTION.rst
  account_menu_invoice_refund/static/description/icon.png
  account_menu_invoice_refund/static/description/index.html
  account_menu_invoice_refund/views/account_invoice_view.xml
  setup/account_menu_invoice_refund/odoo/addons/account_menu_invoice_refund
  setup/account_menu_invoice_refund/setup.py
Labels: needs review, approved, bot is merging ⏳

#1165 [14.0][ENH] account_invoice_payment_retention: add retention computation method
  account_invoice_payment_retention/models/account_move.py
  account_invoice_payment_retention/models/res_company.py
  account_invoice_payment_retention/models/res_config_settings.py
  account_invoice_payment_retention/tests/test_invoice_payment_retention.py
  account_invoice_payment_retention/views/account_move_views.xml
  account_invoice_payment_retention/views/res_config_settings_views.xml
Labels: approved, ready to merge, bot is merging ⏳

#1292 [14.0] [FIX] account_invoice_refund_line_selection: Business fields were missing
  account_invoice_refund_line_selection/wizards/account_move_reversal.py
Labels: approved, ready to merge, bot is merging ⏳

#1347 [14.0][MIG] account_menu_invoice_refund
  account_menu_invoice_refund/README.rst
  account_menu_invoice_refund/__init__.py
  account_menu_invoice_refund/__manifest__.py
  account_menu_invoice_refund/i18n/account_menu_invoice_refund.pot
  account_menu_invoice_refund/i18n/de.po
  account_menu_invoice_refund/i18n/es.po
  account_menu_invoice_refund/i18n/hr.po
  account_menu_invoice_refund/i18n/pt.po
  account_menu_invoice_refund/readme/CONTRIBUTORS.rst
  account_menu_invoice_refund/readme/DESCRIPTION.rst
  account_menu_invoice_refund/static/description/icon.png
  account_menu_invoice_refund/static/description/index.html
  account_menu_invoice_refund/views/account_invoice_view.xml
  setup/account_menu_invoice_refund/odoo/addons/account_menu_invoice_refund
  setup/account_menu_invoice_refund/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#1387 [13.0][FIX] account_portal_invoice_search: Pager URL must be based on invoices
  account_portal_invoice_search/controllers/portal.py
Labels: approved, bot is merging ⏳

#1272 [14.0][ADD] account_invoice_refund_reason_skip_anglo_saxon
  account_invoice_refund_reason_skip_anglo_saxon/README.rst
  account_invoice_refund_reason_skip_anglo_saxon/__init__.py
  account_invoice_refund_reason_skip_anglo_saxon/__manifest__.py
  account_invoice_refund_reason_skip_anglo_saxon/models/__init__.py
  account_invoice_refund_reason_skip_anglo_saxon/models/account_invoice_refund_reason.py
  account_invoice_refund_reason_skip_anglo_saxon/models/account_move.py
  account_invoice_refund_reason_skip_anglo_saxon/readme/CONFIGURE.rst
  account_invoice_refund_reason_skip_anglo_saxon/readme/CONTRIBUTORS.rst
  account_invoice_refund_reason_skip_anglo_saxon/readme/DESCRIPTION.rst
  account_invoice_refund_reason_skip_anglo_saxon/static/description/index.html
  account_invoice_refund_reason_skip_anglo_saxon/tests/__init__.py
  account_invoice_refund_reason_skip_anglo_saxon/tests/test_account_invoice_refund_reason_skip_anglo_saxon.py
  account_invoice_refund_reason_skip_anglo_saxon/views/account_invoice_refund_reason_view.xml
  sale_line_refund_to_invoice_qty_skip_anglo_saxon/README.rst
  sale_line_refund_to_invoice_qty_skip_anglo_saxon/__init__.py
  sale_line_refund_to_invoice_qty_skip_anglo_saxon/__manifest__.py
  sale_line_refund_to_invoice_qty_skip_anglo_saxon/readme/CONTRIBUTORS.rst
  sale_line_refund_to_invoice_qty_skip_anglo_saxon/readme/DESCRIPTION.rst
  sale_line_refund_to_invoice_qty_skip_anglo_saxon/static/description/index.html
  sale_line_refund_to_invoice_qty_skip_anglo_saxon/tests/__init__.py
  sale_line_refund_to_invoice_qty_skip_anglo_saxon/tests/test_sale_line_refund_to_invoice_qty_skip_anglo_saxon.py
  sale_line_refund_to_invoice_qty_skip_anglo_saxon/wizard/__init__.py
  sale_line_refund_to_invoice_qty_skip_anglo_saxon/wizard/account_move_reversal.py
  sale_line_refund_to_invoice_qty_skip_anglo_saxon/wizard/account_move_reversal_view.xml
  setup/account_invoice_refund_reason_skip_anglo_saxon/odoo/addons/account_invoice_refund_reason_skip_anglo_saxon
  setup/account_invoice_refund_reason_skip_anglo_saxon/setup.py
  setup/sale_line_refund_to_invoice_qty_skip_anglo_saxon/odoo/addons/sale_line_refund_to_invoice_qty_skip_anglo_saxon
  setup/sale_line_refund_to_invoice_qty_skip_anglo_saxon/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#1390 [15.0][MIG] sale_invoicing_date_selection: Migration to version 15.0
  sale_invoicing_date_selection/README.rst
  sale_invoicing_date_selection/__init__.py
  sale_invoicing_date_selection/__manifest__.py
  sale_invoicing_date_selection/i18n/es.po
  sale_invoicing_date_selection/i18n/sale_invoicing_date_selection.pot
  sale_invoicing_date_selection/readme/CONTRIBUTORS.rst
  sale_invoicing_date_selection/readme/DESCRIPTION.rst
  sale_invoicing_date_selection/readme/USAGE.rst
  sale_invoicing_date_selection/static/description/icon.png
  sale_invoicing_date_selection/static/description/index.html
  sale_invoicing_date_selection/tests/__init__.py
  sale_invoicing_date_selection/tests/test_sale_invoicing_date_selection.py
  sale_invoicing_date_selection/wizard/__init__.py
  sale_invoicing_date_selection/wizard/sale_advance_payment_inv.py
  sale_invoicing_date_selection/wizard/sale_make_invoice_advance_views.xml
  setup/sale_invoicing_date_selection/odoo/addons/sale_invoicing_date_selection
  setup/sale_invoicing_date_selection/setup.py
Labels: approved, bot is merging ⏳

#1391 [13.0][MIG] sale_order_invoicing_qty_percentage: Backport from 14.0
  sale_order_invoicing_qty_percentage/README.rst
  sale_order_invoicing_qty_percentage/__init__.py
  sale_order_invoicing_qty_percentage/__manifest__.py
  sale_order_invoicing_qty_percentage/i18n/es.po
  sale_order_invoicing_qty_percentage/i18n/sale_order_invoicing_qty_percentage.pot
  sale_order_invoicing_qty_percentage/models/__init__.py
  sale_order_invoicing_qty_percentage/models/sale_order.py
  sale_order_invoicing_qty_percentage/readme/CONTRIBUTORS.rst
  sale_order_invoicing_qty_percentage/readme/DESCRIPTION.rst
  sale_order_invoicing_qty_percentage/readme/ROADMAP.rst
  sale_order_invoicing_qty_percentage/readme/USAGE.rst
  sale_order_invoicing_qty_percentage/static/description/icon.png
  sale_order_invoicing_qty_percentage/static/description/index.html
  sale_order_invoicing_qty_percentage/tests/__init__.py
  sale_order_invoicing_qty_percentage/tests/test_sale_order_invoicing_qty_percentage.py
  sale_order_invoicing_qty_percentage/wizards/__init__.py
  sale_order_invoicing_qty_percentage/wizards/sale_advance_payment_inv.py
  sale_order_invoicing_qty_percentage/wizards/sale_advance_payment_inv_views.xml
  setup/sale_order_invoicing_qty_percentage/odoo/addons/sale_order_invoicing_qty_percentage
  setup/sale_order_invoicing_qty_percentage/setup.py
Labels: bot is merging ⏳

#1392 [13.0][IMP] account_invoice_refund_reason: add field filters
  account_invoice_refund_reason/views/account_invoice_refund_reason_view.xml
Labels: approved, bot is merging ⏳

#1395 [15.0][FW][IMP] account_invoice_refund_reason: add field filters
  account_invoice_refund_reason/views/account_move_refund_reason_view.xml
Labels: bot is merging ⏳

#1396 [FIX] account_invoice_line_sequence: enable the properties only on non test mode
  account_invoice_line_sequence/models/account_move.py
Labels: approved, bot is merging ⏳

#1394 [14.0][FW][IMP] account_invoice_refund_reason: add field filters
  account_invoice_refund_reason/views/account_move_refund_reason_view.xml
Labels: approved, bot is merging ⏳
