Repository OCA/account-invoicing, pull requests merged in 2023-09, with the labels that each got.

#1451 [16.0][MIG] account_invoice_section_sale_order
  account_invoice_section_sale_order/README.rst
  account_invoice_section_sale_order/__init__.py
  account_invoice_section_sale_order/__manifest__.py
  account_invoice_section_sale_order/i18n/account_invoice_section_sale_order.pot
  account_invoice_section_sale_order/models/__init__.py
  account_invoice_section_sale_order/models/sale_order.py
  account_invoice_section_sale_order/readme/CONTRIBUTORS.rst
  account_invoice_section_sale_order/readme/CREDITS.rst
  account_invoice_section_sale_order/readme/DESCRIPTION.rst
  account_invoice_section_sale_order/static/description/icon.png
  account_invoice_section_sale_order/static/description/index.html
  account_invoice_section_sale_order/tests/__init__.py
  account_invoice_section_sale_order/tests/test_invoice_group_by_sale_order.py
  setup/account_invoice_section_sale_order/odoo/addons/account_invoice_section_sale_order
  setup/account_invoice_section_sale_order/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#1301 [14.0][ADD] accounting_partner_category: utility module helping to filter invoices
  accounting_partner_category/README.rst
  accounting_partner_category/__init__.py
  accounting_partner_category/__manifest__.py
  accounting_partner_category/i18n/accounting_partner_category.pot
  accounting_partner_category/i18n/fr.po
  accounting_partner_category/models/__init__.py
  accounting_partner_category/models/account_move.py
  accounting_partner_category/models/accounting_partner_category.py
  accounting_partner_category/models/res_partner.py
  accounting_partner_category/readme/CONFIGURATION.rst
  accounting_partner_category/readme/CONTRIBUTORS.rst
  accounting_partner_category/readme/DESCRIPTION.rst
  accounting_partner_category/readme/USAGE.rst
  accounting_partner_category/security/ir.model.access.csv
  accounting_partner_category/static/description/accounting_partner_category.png
  accounting_partner_category/static/description/company_accounting_partner_category.png
  accounting_partner_category/static/description/filters_invoice_contains_tag1_accounting_partner_category.png
  accounting_partner_category/static/description/filters_invoice_contains_tag1_without_tags2_accounting_partner_category.png
  accounting_partner_category/static/description/filters_invoice_without_tags2_accounting_partner_category.png
  accounting_partner_category/static/description/index.html
  accounting_partner_category/static/description/invoice_with_accounting_partner_category.png
  accounting_partner_category/static/description/without_filters_accounting_partner_category.png
  accounting_partner_category/tests/__init__.py
  accounting_partner_category/tests/test_account_move.py
  accounting_partner_category/tests/test_accounting_partner_category.py
  accounting_partner_category/views/account_move.xml
  accounting_partner_category/views/account_partner_category.xml
  accounting_partner_category/views/partner_view.xml
  setup/accounting_partner_category/odoo/addons/accounting_partner_category
  setup/accounting_partner_category/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#1543 [15.0][MIG + IMP] account_invoice_mass_sending: Migration to v15 + Create a job channel to queue the jobs
  account_invoice_mass_sending/README.rst
  account_invoice_mass_sending/__init__.py
  account_invoice_mass_sending/__manifest__.py
  account_invoice_mass_sending/data/queue_job.xml
  account_invoice_mass_sending/i18n/account_invoice_mass_sending.pot
  account_invoice_mass_sending/i18n/es.po
  account_invoice_mass_sending/i18n/fr.po
  account_invoice_mass_sending/models/__init__.py
  account_invoice_mass_sending/models/account_move.py
  account_invoice_mass_sending/readme/CONFIGURE.rst
  account_invoice_mass_sending/readme/CONTRIBUTORS.rst
  account_invoice_mass_sending/readme/DESCRIPTION.rst
  account_invoice_mass_sending/readme/USAGE.rst
  account_invoice_mass_sending/static/description/icon.png
  account_invoice_mass_sending/static/description/index.html
  account_invoice_mass_sending/tests/__init__.py
  account_invoice_mass_sending/tests/test_account_invoice_mass_sending.py
  account_invoice_mass_sending/views/account_invoice_views.xml
  account_invoice_mass_sending/wizards/__init__.py
  account_invoice_mass_sending/wizards/account_invoice_send.py
  account_invoice_mass_sending/wizards/account_invoice_send.xml
  setup/account_invoice_mass_sending/odoo/addons/account_invoice_mass_sending
  setup/account_invoice_mass_sending/setup.py
Labels: approved, bot is merging ⏳

#1488 [16.0][MIG] account_invoice_fixed_discount: Migration to 16.0
  account_invoice_fixed_discount/README.rst
  account_invoice_fixed_discount/__init__.py
  account_invoice_fixed_discount/__manifest__.py
  account_invoice_fixed_discount/i18n/account_invoice_fixed_discount.pot
  account_invoice_fixed_discount/i18n/ca.po
  account_invoice_fixed_discount/i18n/de.po
  account_invoice_fixed_discount/i18n/es.po
  account_invoice_fixed_discount/models/__init__.py
  account_invoice_fixed_discount/models/account_move_line.py
  account_invoice_fixed_discount/models/account_tax.py
  account_invoice_fixed_discount/readme/CONTRIBUTORS.rst
  account_invoice_fixed_discount/readme/DESCRIPTION.rst
  account_invoice_fixed_discount/readme/INSTALL.rst
  account_invoice_fixed_discount/readme/USAGE.rst
  account_invoice_fixed_discount/reports/report_account_invoice.xml
  account_invoice_fixed_discount/security/res_groups.xml
  account_invoice_fixed_discount/static/description/icon.png
  account_invoice_fixed_discount/static/description/index.html
  account_invoice_fixed_discount/tests/__init__.py
  account_invoice_fixed_discount/tests/test_account_fixed_discount.py
  account_invoice_fixed_discount/views/account_move_view.xml
  setup/account_invoice_fixed_discount/odoo/addons/account_invoice_fixed_discount
  setup/account_invoice_fixed_discount/setup.py
Labels: needs review, bot is merging ⏳

#1547 [14.0][FIX] stock_picking_invoicing: demo product compatible with MRP module
  stock_picking_invoicing/demo/stock_picking_demo.xml
Labels: approved, bot is merging ⏳

#1546 [16.0][IMP] account_invoice_mass_sending: missing commits from 15
  account_invoice_mass_sending/README.rst
  account_invoice_mass_sending/__manifest__.py
  account_invoice_mass_sending/data/queue_job.xml
  account_invoice_mass_sending/models/account_move.py
  account_invoice_mass_sending/readme/CONFIGURE.rst
  account_invoice_mass_sending/readme/CONTRIBUTORS.rst
  account_invoice_mass_sending/static/description/index.html
  account_invoice_mass_sending/tests/test_account_invoice_mass_sending.py
Labels: approved, bot is merging ⏳

#1548 [14.0][FIX] stock_picking_invoicing: demo product compatible with MRP module.
  stock_picking_invoicing/demo/stock_picking_demo.xml
Labels: approved, bot is merging ⏳

#1441 [16.0][mig] account_invoice_force_number
  account_invoice_force_number/README.rst
  account_invoice_force_number/__init__.py
  account_invoice_force_number/__manifest__.py
  account_invoice_force_number/i18n/account_invoice_force_number.pot
  account_invoice_force_number/i18n/ar.po
  account_invoice_force_number/i18n/bg.po
  account_invoice_force_number/i18n/bs.po
  account_invoice_force_number/i18n/ca.po
  account_invoice_force_number/i18n/cs.po
  account_invoice_force_number/i18n/de.po
  account_invoice_force_number/i18n/el_GR.po
  account_invoice_force_number/i18n/en_GB.po
  account_invoice_force_number/i18n/es.po
  account_invoice_force_number/i18n/es_CR.po
  account_invoice_force_number/i18n/es_EC.po
  account_invoice_force_number/i18n/es_MX.po
  account_invoice_force_number/i18n/et.po
  account_invoice_force_number/i18n/fi.po
  account_invoice_force_number/i18n/fr.po
  account_invoice_force_number/i18n/fr_CH.po
  account_invoice_force_number/i18n/gl.po
  account_invoice_force_number/i18n/hr.po
  account_invoice_force_number/i18n/hr_HR.po
  account_invoice_force_number/i18n/id.po
  account_invoice_force_number/i18n/it.po
  account_invoice_force_number/i18n/ja.po
  account_invoice_force_number/i18n/lt.po
  account_invoice_force_number/i18n/mk.po
  account_invoice_force_number/i18n/mn.po
  account_invoice_force_number/i18n/nb_NO.po
  account_invoice_force_number/i18n/nl.po
  account_invoice_force_number/i18n/nl_BE.po
  account_invoice_force_number/i18n/pl.po
  account_invoice_force_number/i18n/pt.po
  account_invoice_force_number/i18n/pt_BR.po
  account_invoice_force_number/i18n/pt_PT.po
  account_invoice_force_number/i18n/ro.po
  account_invoice_force_number/i18n/ru.po
  account_invoice_force_number/i18n/sk_SK.po
  account_invoice_force_number/i18n/sl.po
  account_invoice_force_number/i18n/sv.po
  account_invoice_force_number/i18n/th.po
  account_invoice_force_number/i18n/tr.po
  account_invoice_force_number/i18n/tr_TR.po
  account_invoice_force_number/i18n/zh_CN.po
  account_invoice_force_number/i18n/zh_TW.po
  account_invoice_force_number/models/__init__.py
  account_invoice_force_number/models/account_move.py
  account_invoice_force_number/readme/CONFIGURE.rst
  account_invoice_force_number/readme/CONTRIBUTORS.rst
  account_invoice_force_number/readme/DESCRIPTION.rst
  account_invoice_force_number/readme/USAGE.rst
  account_invoice_force_number/security/security.xml
  account_invoice_force_number/static/description/icon.png
  account_invoice_force_number/static/description/index.html
  account_invoice_force_number/tests/__init__.py
  account_invoice_force_number/tests/test_account_force_number.py
  account_invoice_force_number/views/account_move_view.xml
  setup/account_invoice_force_number/odoo/addons/account_invoice_force_number
  setup/account_invoice_force_number/setup.py
Labels: bot is merging ⏳

#1560 [FIX] account_invoice_supplierinfo_update : make wizard working even if user is not member of the group 'uom.group_uom'.
  account_invoice_supplierinfo_update/wizard/wizard_update_invoice_supplierinfo.xml
Labels: bug, needs review, bot is merging ⏳

#1444 [16.0][MIG] account_invoice_supplierinfo_update_discount : Migration to 16.0
  account_invoice_supplierinfo_update_discount/README.rst
  account_invoice_supplierinfo_update_discount/__init__.py
  account_invoice_supplierinfo_update_discount/__manifest__.py
  account_invoice_supplierinfo_update_discount/i18n/account_invoice_supplierinfo_update_discount.pot
  account_invoice_supplierinfo_update_discount/i18n/ar.po
  account_invoice_supplierinfo_update_discount/i18n/bs.po
  account_invoice_supplierinfo_update_discount/i18n/ca.po
  account_invoice_supplierinfo_update_discount/i18n/cs.po
  account_invoice_supplierinfo_update_discount/i18n/de.po
  account_invoice_supplierinfo_update_discount/i18n/en_GB.po
  account_invoice_supplierinfo_update_discount/i18n/es.po
  account_invoice_supplierinfo_update_discount/i18n/es_CR.po
  account_invoice_supplierinfo_update_discount/i18n/es_EC.po
  account_invoice_supplierinfo_update_discount/i18n/es_MX.po
  account_invoice_supplierinfo_update_discount/i18n/et.po
  account_invoice_supplierinfo_update_discount/i18n/fr.po
  account_invoice_supplierinfo_update_discount/i18n/fr_CH.po
  account_invoice_supplierinfo_update_discount/i18n/hr.po
  account_invoice_supplierinfo_update_discount/i18n/hu.po
  account_invoice_supplierinfo_update_discount/i18n/it.po
  account_invoice_supplierinfo_update_discount/i18n/ja.po
  account_invoice_supplierinfo_update_discount/i18n/lt.po
  account_invoice_supplierinfo_update_discount/i18n/mk.po
  account_invoice_supplierinfo_update_discount/i18n/mn.po
  account_invoice_supplierinfo_update_discount/i18n/nb.po
  account_invoice_supplierinfo_update_discount/i18n/nl.po
  account_invoice_supplierinfo_update_discount/i18n/nl_BE.po
  account_invoice_supplierinfo_update_discount/i18n/nl_NL.po
  account_invoice_supplierinfo_update_discount/i18n/pt.po
  account_invoice_supplierinfo_update_discount/i18n/pt_BR.po
  account_invoice_supplierinfo_update_discount/i18n/pt_PT.po
  account_invoice_supplierinfo_update_discount/i18n/ro.po
  account_invoice_supplierinfo_update_discount/i18n/ru.po
  account_invoice_supplierinfo_update_discount/i18n/sl.po
  account_invoice_supplierinfo_update_discount/i18n/sv.po
  account_invoice_supplierinfo_update_discount/i18n/tr.po
  account_invoice_supplierinfo_update_discount/i18n/tr_TR.po
  account_invoice_supplierinfo_update_discount/i18n/zh_CN.po
  account_invoice_supplierinfo_update_discount/i18n/zh_TW.po
  account_invoice_supplierinfo_update_discount/models/__init__.py
  account_invoice_supplierinfo_update_discount/models/account_move_line.py
  account_invoice_supplierinfo_update_discount/readme/CONTRIBUTORS.rst
  account_invoice_supplierinfo_update_discount/readme/DESCRIPTION.rst
  account_invoice_supplierinfo_update_discount/readme/ROADMAP.rst
  account_invoice_supplierinfo_update_discount/static/description/icon.png
  account_invoice_supplierinfo_update_discount/static/description/index.html
  account_invoice_supplierinfo_update_discount/tests/__init__.py
  account_invoice_supplierinfo_update_discount/tests/test_module.py
  account_invoice_supplierinfo_update_discount/wizard/__init__.py
  account_invoice_supplierinfo_update_discount/wizard/wizard_update_invoice_supplierinfo.py
  account_invoice_supplierinfo_update_discount/wizard/wizard_update_invoice_supplierinfo.xml
  account_invoice_supplierinfo_update_discount/wizard/wizard_update_invoice_supplierinfo_line.py
  setup/account_invoice_supplierinfo_update_discount/odoo/addons/account_invoice_supplierinfo_update_discount
  setup/account_invoice_supplierinfo_update_discount/setup.py
Labels: approved, bot is merging ⏳
