Repository OCA/account-invoicing, pull requests merged in 2023-07, with the labels that each got.

#1373 [16.0][MIG] account_move_tier_validation to 16.0
  account_move_tier_validation/README.rst
  account_move_tier_validation/__init__.py
  account_move_tier_validation/__manifest__.py
  account_move_tier_validation/i18n/account_move_tier_validation.pot
  account_move_tier_validation/i18n/ca.po
  account_move_tier_validation/i18n/es.po
  account_move_tier_validation/i18n/es_PA.po
  account_move_tier_validation/i18n/sv.po
  account_move_tier_validation/i18n/zh_CN.po
  account_move_tier_validation/models/__init__.py
  account_move_tier_validation/models/account_move.py
  account_move_tier_validation/models/tier_definition.py
  account_move_tier_validation/readme/CONFIGURE.rst
  account_move_tier_validation/readme/CONTRIBUTORS.rst
  account_move_tier_validation/readme/DESCRIPTION.rst
  account_move_tier_validation/readme/INSTALL.rst
  account_move_tier_validation/readme/USAGE.rst
  account_move_tier_validation/static/description/icon.png
  account_move_tier_validation/static/description/index.html
  account_move_tier_validation/tests/__init__.py
  account_move_tier_validation/tests/test_tier_validation.py
  account_move_tier_validation/views/account_move_view.xml
  setup/account_move_tier_validation/odoo/addons/account_move_tier_validation
  setup/account_move_tier_validation/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#1482 [16.0][mig] account_tax_group_widget_base_amount: Migration to 16.0
  account_tax_group_widget_base_amount/README.rst
  account_tax_group_widget_base_amount/__init__.py
  account_tax_group_widget_base_amount/__manifest__.py
  account_tax_group_widget_base_amount/i18n/account_tax_group_widget_base_amount.pot
  account_tax_group_widget_base_amount/i18n/es.po
  account_tax_group_widget_base_amount/readme/CONTRIBUTORS.rst
  account_tax_group_widget_base_amount/readme/DESCRIPTION.rst
  account_tax_group_widget_base_amount/static/description/account_tax_group_widget_base_amount.png
  account_tax_group_widget_base_amount/static/description/icon.png
  account_tax_group_widget_base_amount/static/description/index.html
  account_tax_group_widget_base_amount/static/src/xml/tax_group.xml
  setup/account_tax_group_widget_base_amount/odoo/addons/account_tax_group_widget_base_amount
  setup/account_tax_group_widget_base_amount/setup.py
Labels: approved, bot is merging ⏳

#1322 [15.0][MIG] account_invoice_refund_line_selection
  account_invoice_refund_line_selection/README.rst
  account_invoice_refund_line_selection/__init__.py
  account_invoice_refund_line_selection/__manifest__.py
  account_invoice_refund_line_selection/i18n/account_invoice_refund_line_selection.pot
  account_invoice_refund_line_selection/i18n/ca.po
  account_invoice_refund_line_selection/i18n/de.po
  account_invoice_refund_line_selection/i18n/es.po
  account_invoice_refund_line_selection/i18n/nl.po
  account_invoice_refund_line_selection/readme/CONTRIBUTORS.rst
  account_invoice_refund_line_selection/readme/DESCRIPTION.rst
  account_invoice_refund_line_selection/readme/USAGE.rst
  account_invoice_refund_line_selection/static/description/icon.png
  account_invoice_refund_line_selection/static/description/index.html
  account_invoice_refund_line_selection/tests/__init__.py
  account_invoice_refund_line_selection/tests/test_refund_line.py
  account_invoice_refund_line_selection/wizards/__init__.py
  account_invoice_refund_line_selection/wizards/account_move_reversal.py
  account_invoice_refund_line_selection/wizards/account_move_reversal_view.xml
  setup/account_invoice_refund_line_selection/odoo/addons/account_invoice_refund_line_selection
  setup/account_invoice_refund_line_selection/setup.py
Labels: needs review, approved, ready to merge, bot is merging ⏳

#1509 [15.0][ADD] Add module account_invoice_crm_tag
  account_invoice_crm_tag/README.rst
  account_invoice_crm_tag/__init__.py
  account_invoice_crm_tag/__manifest__.py
  account_invoice_crm_tag/i18n/account_invoice_crm_tag.pot
  account_invoice_crm_tag/i18n/es.po
  account_invoice_crm_tag/models/__init__.py
  account_invoice_crm_tag/models/account_move.py
  account_invoice_crm_tag/models/sale_order.py
  account_invoice_crm_tag/readme/CONTRIBUTORS.rst
  account_invoice_crm_tag/readme/DESCRIPTION.rst
  account_invoice_crm_tag/readme/USAGE.rst
  account_invoice_crm_tag/report/__init__.py
  account_invoice_crm_tag/report/account_invoice_report.py
  account_invoice_crm_tag/report/account_invoice_report.xml
  account_invoice_crm_tag/static/description/index.html
  account_invoice_crm_tag/views/account_invoice_views.xml
  setup/account_invoice_crm_tag/odoo/addons/account_invoice_crm_tag
  setup/account_invoice_crm_tag/setup.py
Labels: bot is merging ⏳
