Repository OCA/account-invoicing, pull requests merged in 2023-04, with the labels that each got.

#1432 [15.0][IMP] account_invoice_check_picking_date: Change invoice date by accounting date
  account_invoice_check_picking_date/README.rst
  account_invoice_check_picking_date/__manifest__.py
  account_invoice_check_picking_date/i18n/account_invoice_check_picking_date.pot
  account_invoice_check_picking_date/i18n/es.po
  account_invoice_check_picking_date/models/account_move.py
  account_invoice_check_picking_date/readme/DESCRIPTION.rst
  account_invoice_check_picking_date/readme/USAGE.rst
  account_invoice_check_picking_date/static/description/index.html
  account_invoice_check_picking_date/wizards/invoice_stock_picking_date_wiz.py
  account_invoice_check_picking_date/wizards/invoice_stock_picking_date_wiz.xml
Labels: bot is merging ⏳

#1243 [15.0][MIG] account_invoice_base_invoicing_mode (renamed)
  partner_invoicing_mode/README.rst
  partner_invoicing_mode/__init__.py
  partner_invoicing_mode/__manifest__.py
  partner_invoicing_mode/data/queue_job_data.xml
  partner_invoicing_mode/models/__init__.py
  partner_invoicing_mode/models/account_invoice.py
  partner_invoicing_mode/models/queue_job.py
  partner_invoicing_mode/models/res_partner.py
  partner_invoicing_mode/models/sale_order.py
  partner_invoicing_mode/readme/CONTRIBUTORS.rst
  partner_invoicing_mode/readme/CREDITS.rst
  partner_invoicing_mode/readme/DESCRIPTION.rst
  partner_invoicing_mode/static/description/icon.png
  partner_invoicing_mode/static/description/index.html
  partner_invoicing_mode/views/res_partner.xml
  setup/partner_invoicing_mode/odoo/addons/partner_invoicing_mode
  setup/partner_invoicing_mode/setup.py
Labels: approved, bot is merging ⏳

#1440 [16.0][MIG] stock_picking_return_refund_option: Migration to version 16.0
  setup/stock_picking_return_refund_option/odoo/addons/stock_picking_return_refund_option
  setup/stock_picking_return_refund_option/setup.py
  stock_picking_return_refund_option/README.rst
  stock_picking_return_refund_option/__init__.py
  stock_picking_return_refund_option/__manifest__.py
  stock_picking_return_refund_option/i18n/ca.po
  stock_picking_return_refund_option/i18n/es.po
  stock_picking_return_refund_option/i18n/stock_picking_return_refund_option.pot
  stock_picking_return_refund_option/models/__init__.py
  stock_picking_return_refund_option/models/stock_move.py
  stock_picking_return_refund_option/models/stock_picking.py
  stock_picking_return_refund_option/readme/CONTRIBUTORS.rst
  stock_picking_return_refund_option/readme/DESCRIPTION.rst
  stock_picking_return_refund_option/readme/INSTALL.rst
  stock_picking_return_refund_option/readme/USAGE.rst
  stock_picking_return_refund_option/static/description/icon.png
  stock_picking_return_refund_option/static/description/index.html
  stock_picking_return_refund_option/tests/__init__.py
  stock_picking_return_refund_option/tests/test_stock_picking_return_refund_options.py
  stock_picking_return_refund_option/views/stock_picking_view.xml
Labels: approved, ready to merge, bot is merging ⏳

#1247 [MIG][15.0] account_invoicing_mode_at_shipping (renamed)
  partner_invoicing_mode_at_shipping/README.rst
  partner_invoicing_mode_at_shipping/__init__.py
  partner_invoicing_mode_at_shipping/__manifest__.py
  partner_invoicing_mode_at_shipping/data/queue_job_data.xml
  partner_invoicing_mode_at_shipping/models/__init__.py
  partner_invoicing_mode_at_shipping/models/res_partner.py
  partner_invoicing_mode_at_shipping/models/stock_move.py
  partner_invoicing_mode_at_shipping/models/stock_picking.py
  partner_invoicing_mode_at_shipping/readme/CONTRIBUTORS.rst
  partner_invoicing_mode_at_shipping/readme/CREDITS.rst
  partner_invoicing_mode_at_shipping/readme/DESCRIPTION.rst
  partner_invoicing_mode_at_shipping/static/description/icon.png
  partner_invoicing_mode_at_shipping/static/description/index.html
  partner_invoicing_mode_at_shipping/tests/__init__.py
  partner_invoicing_mode_at_shipping/tests/test_invoice_mode_at_shipping.py
  setup/partner_invoicing_mode_at_shipping/odoo/addons/partner_invoicing_mode_at_shipping
  setup/partner_invoicing_mode_at_shipping/setup.py
Labels: needs review, approved, bot is merging ⏳

#1295 [MIG] partner_invoicing_mode, partner_invoicing_mode_at_shipping, partner_invoicing_mode_monthly: Migration to 16.0
  partner_invoicing_mode/README.rst
  partner_invoicing_mode/__init__.py
  partner_invoicing_mode/__manifest__.py
  partner_invoicing_mode/data/queue_job_data.xml
  partner_invoicing_mode/models/__init__.py
  partner_invoicing_mode/models/account_invoice.py
  partner_invoicing_mode/models/queue_job.py
  partner_invoicing_mode/models/res_partner.py
  partner_invoicing_mode/models/sale_order.py
  partner_invoicing_mode/readme/CONTRIBUTORS.rst
  partner_invoicing_mode/readme/CREDITS.rst
  partner_invoicing_mode/readme/DESCRIPTION.rst
  partner_invoicing_mode/static/description/icon.png
  partner_invoicing_mode/static/description/index.html
  partner_invoicing_mode/tests/__init__.py
  partner_invoicing_mode/tests/test_invoice_mode.py
  partner_invoicing_mode/views/res_partner.xml
  partner_invoicing_mode_at_shipping/README.rst
  partner_invoicing_mode_at_shipping/__init__.py
  partner_invoicing_mode_at_shipping/__manifest__.py
  partner_invoicing_mode_at_shipping/data/queue_job_data.xml
  partner_invoicing_mode_at_shipping/models/__init__.py
  partner_invoicing_mode_at_shipping/models/res_partner.py
  partner_invoicing_mode_at_shipping/models/stock_move.py
  partner_invoicing_mode_at_shipping/models/stock_picking.py
  partner_invoicing_mode_at_shipping/readme/CONTRIBUTORS.rst
  partner_invoicing_mode_at_shipping/readme/CREDITS.rst
  partner_invoicing_mode_at_shipping/readme/DESCRIPTION.rst
  partner_invoicing_mode_at_shipping/static/description/icon.png
  partner_invoicing_mode_at_shipping/static/description/index.html
  partner_invoicing_mode_at_shipping/tests/__init__.py
  partner_invoicing_mode_at_shipping/tests/test_invoice_mode_at_shipping.py
  partner_invoicing_mode_monthly/README.rst
  partner_invoicing_mode_monthly/__init__.py
  partner_invoicing_mode_monthly/__manifest__.py
  partner_invoicing_mode_monthly/data/ir_cron.xml
  partner_invoicing_mode_monthly/data/queue_job_data.xml
  partner_invoicing_mode_monthly/models/__init__.py
  partner_invoicing_mode_monthly/models/res_company.py
  partner_invoicing_mode_monthly/models/res_config_settings.py
  partner_invoicing_mode_monthly/models/res_partner.py
  partner_invoicing_mode_monthly/models/sale_order.py
  partner_invoicing_mode_monthly/readme/CONTRIBUTORS.rst
  partner_invoicing_mode_monthly/readme/CREDITS.rst
  partner_invoicing_mode_monthly/readme/DESCRIPTION.rst
  partner_invoicing_mode_monthly/readme/INSTALL.rst
  partner_invoicing_mode_monthly/static/description/icon.png
  partner_invoicing_mode_monthly/static/description/index.html
  partner_invoicing_mode_monthly/tests/__init__.py
  partner_invoicing_mode_monthly/tests/test_invoice_mode_monthly.py
  partner_invoicing_mode_monthly/tests/test_invoice_mode_monthly_is_it_today.py
  partner_invoicing_mode_monthly/views/res_config_settings_views.xml
  setup/partner_invoicing_mode/odoo/addons/partner_invoicing_mode
  setup/partner_invoicing_mode/setup.py
  setup/partner_invoicing_mode_at_shipping/odoo/addons/partner_invoicing_mode_at_shipping
  setup/partner_invoicing_mode_at_shipping/setup.py
  setup/partner_invoicing_mode_monthly/odoo/addons/partner_invoicing_mode_monthly
  setup/partner_invoicing_mode_monthly/setup.py
Labels: needs review, approved, bot is merging ⏳
