Repository OCA/account-invoicing, pull requests merged in 2023-12, with the labels that each got.

#1612 [16.0][MIG] account_invoice_refund_reason: Migration to 16.0
  account_invoice_refund_reason/README.rst
  account_invoice_refund_reason/__init__.py
  account_invoice_refund_reason/__manifest__.py
  account_invoice_refund_reason/data/account.move.refund.reason.csv
  account_invoice_refund_reason/i18n/account_invoice_refund_reason.pot
  account_invoice_refund_reason/i18n/de.po
  account_invoice_refund_reason/i18n/es.po
  account_invoice_refund_reason/i18n/hr.po
  account_invoice_refund_reason/models/__init__.py
  account_invoice_refund_reason/models/account_move.py
  account_invoice_refund_reason/models/account_move_refund_reason.py
  account_invoice_refund_reason/readme/CONFIGURE.rst
  account_invoice_refund_reason/readme/CONTRIBUTORS.rst
  account_invoice_refund_reason/readme/DESCRIPTION.rst
  account_invoice_refund_reason/readme/USAGE.rst
  account_invoice_refund_reason/security/ir.model.access.csv
  account_invoice_refund_reason/static/description/icon.png
  account_invoice_refund_reason/static/description/index.html
  account_invoice_refund_reason/tests/__init__.py
  account_invoice_refund_reason/tests/test_account_invoice_refund_reason.py
  account_invoice_refund_reason/views/account_move_refund_reason_view.xml
  account_invoice_refund_reason/views/account_move_view.xml
  account_invoice_refund_reason/wizard/__init__.py
  account_invoice_refund_reason/wizard/account_move_reversal.py
  account_invoice_refund_reason/wizard/account_move_reversal_view.xml
  setup/account_invoice_refund_reason/odoo/addons/account_invoice_refund_reason
  setup/account_invoice_refund_reason/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#1625 [ADD] [15.0] account_invoice_discount_date: Early Payment Discount Date
  account_invoice_discount_date/README.rst
  account_invoice_discount_date/__init__.py
  account_invoice_discount_date/__manifest__.py
  account_invoice_discount_date/i18n/account_invoice_discount_date.pot
  account_invoice_discount_date/i18n/es.po
  account_invoice_discount_date/models/__init__.py
  account_invoice_discount_date/models/account_move.py
  account_invoice_discount_date/models/account_move_line.py
  account_invoice_discount_date/readme/CONTEXT.md
  account_invoice_discount_date/readme/CONTRIBUTORS.md
  account_invoice_discount_date/readme/DESCRIPTION.md
  account_invoice_discount_date/readme/ROADMAP.md
  account_invoice_discount_date/readme/USAGE.md
  account_invoice_discount_date/static/description/icon.png
  account_invoice_discount_date/static/description/index.html
  account_invoice_discount_date/tests/__init__.py
  account_invoice_discount_date/tests/test_account_invoice_discount_date.py
  account_invoice_discount_date/views/account_move_line_view.xml
  account_invoice_discount_date/views/account_move_view.xml
  setup/account_invoice_discount_date/odoo/addons/account_invoice_discount_date
  setup/account_invoice_discount_date/setup.py
Labels: needs review, approved, bot is merging ⏳

#1585 [16.0][MIG] product_form_account_move_line_link
  product_form_account_move_line_link/README.rst
  product_form_account_move_line_link/__init__.py
  product_form_account_move_line_link/__manifest__.py
  product_form_account_move_line_link/i18n/product_form_account_move_line_link.pot
  product_form_account_move_line_link/models/__init__.py
  product_form_account_move_line_link/models/product_product.py
  product_form_account_move_line_link/models/product_template.py
  product_form_account_move_line_link/readme/CONTRIBUTORS.rst
  product_form_account_move_line_link/readme/DESCRIPTION.rst
  product_form_account_move_line_link/readme/USAGE.rst
  product_form_account_move_line_link/static/description/icon.png
  product_form_account_move_line_link/static/description/index.html
  product_form_account_move_line_link/views/account_move_line_views.xml
  product_form_account_move_line_link/views/product_product_views.xml
  product_form_account_move_line_link/views/product_template_views.xml
  setup/product_form_account_move_line_link/odoo/addons/product_form_account_move_line_link
  setup/product_form_account_move_line_link/setup.py
Labels: approved, bot is merging ⏳

#1633 [UPD] Copier update
  .copier-answers.yml
  .gitignore
  .pre-commit-config.yaml
Labels: approved

#1635 [14.0][FIX] account_invoice_base_invoicing_mode: Test partner_invoice_id instead of partner_id
  account_invoice_base_invoicing_mode/models/sale_order.py
Labels: approved, bot is merging ⏳
