Repository OCA/account-invoicing, pull requests merged in 2023-06, with the labels that each got.

#1469 [16.0][IMP] account_receipt_journal: add USAGE file
  account_receipt_journal/readme/USAGE.rst
Labels: approved, bot is merging ⏳

#1468 [16.0][MIG] account receipt send: Migration to 16.0
  account_receipt_send/README.rst
  account_receipt_send/__init__.py
  account_receipt_send/__manifest__.py
  account_receipt_send/data/mail_template_data.xml
  account_receipt_send/i18n/account_receipt_send.pot
  account_receipt_send/models/__init__.py
  account_receipt_send/models/account_move.py
  account_receipt_send/readme/CONFIGURE.rst
  account_receipt_send/readme/CONTRIBUTORS.rst
  account_receipt_send/readme/DESCRIPTION.rst
  account_receipt_send/readme/USAGE.rst
  account_receipt_send/static/description/icon.png
  account_receipt_send/static/description/index.html
  account_receipt_send/tests/__init__.py
  account_receipt_send/tests/test_account_receipt.py
  account_receipt_send/views/account_move_views.xml
  setup/account_receipt_send/odoo/addons/account_receipt_send
  setup/account_receipt_send/setup.py
Labels: needs review, approved, bot is merging ⏳

#1300 [16.0][MIG] sale_order_invoicing_grouping_criteria
  sale_order_invoicing_grouping_criteria/README.rst
  sale_order_invoicing_grouping_criteria/__init__.py
  sale_order_invoicing_grouping_criteria/__manifest__.py
  sale_order_invoicing_grouping_criteria/i18n/ca.po
  sale_order_invoicing_grouping_criteria/i18n/es.po
  sale_order_invoicing_grouping_criteria/i18n/fr.po
  sale_order_invoicing_grouping_criteria/i18n/sale_order_invoicing_grouping_criteria.pot
  sale_order_invoicing_grouping_criteria/models/__init__.py
  sale_order_invoicing_grouping_criteria/models/res_company.py
  sale_order_invoicing_grouping_criteria/models/res_config_settings.py
  sale_order_invoicing_grouping_criteria/models/res_partner.py
  sale_order_invoicing_grouping_criteria/models/sale_invoicing_grouping_criteria.py
  sale_order_invoicing_grouping_criteria/models/sale_order.py
  sale_order_invoicing_grouping_criteria/readme/CONFIGURE.rst
  sale_order_invoicing_grouping_criteria/readme/CONTRIBUTORS.rst
  sale_order_invoicing_grouping_criteria/readme/DESCRIPTION.rst
  sale_order_invoicing_grouping_criteria/readme/USAGE.rst
  sale_order_invoicing_grouping_criteria/security/ir.model.access.csv
  sale_order_invoicing_grouping_criteria/static/description/icon.png
  sale_order_invoicing_grouping_criteria/static/description/index.html
  sale_order_invoicing_grouping_criteria/tests/__init__.py
  sale_order_invoicing_grouping_criteria/tests/test_sale_order_invoicing_group_criteria.py
  sale_order_invoicing_grouping_criteria/views/res_config_settings_views.xml
  sale_order_invoicing_grouping_criteria/views/res_partner_views.xml
  sale_order_invoicing_grouping_criteria/views/sale_invoicing_grouping_criteria_views.xml
  setup/sale_order_invoicing_grouping_criteria/odoo/addons/sale_order_invoicing_grouping_criteria
  setup/sale_order_invoicing_grouping_criteria/setup.py
Labels: needs review, approved, ready to merge, bot is merging ⏳

#1374 [16.0] [ADD] account_invoice_currency_taxes
  account_invoice_currency_taxes/README.rst
  account_invoice_currency_taxes/__init__.py
  account_invoice_currency_taxes/__manifest__.py
  account_invoice_currency_taxes/models/__init__.py
  account_invoice_currency_taxes/models/account_tax.py
  account_invoice_currency_taxes/readme/CONTRIBUTORS.rst
  account_invoice_currency_taxes/readme/DESCRIPTION.rst
  account_invoice_currency_taxes/readme/HISTORY.rst
  account_invoice_currency_taxes/readme/USAGE.rst
  account_invoice_currency_taxes/static/description/icon.png
  account_invoice_currency_taxes/static/description/out_invoice.jpg
  account_invoice_currency_taxes/tests/__init__.py
  account_invoice_currency_taxes/tests/test_account_tax.py
  account_invoice_currency_taxes/views/tax_groups_totals.xml
  setup/account_invoice_currency_taxes/odoo/addons/account_invoice_currency_taxes
  setup/account_invoice_currency_taxes/setup.py
Labels: needs review, approved, ready to merge, bot is merging ⏳

#1470 [15.0] FIX CI
  account_invoice_refund_reason/tests/test_account_invoice_refund_reason.py
  sale_timesheet_invoice_description/tests/test_sale_timesheet_description.py
Labels: approved, bot is merging ⏳

#1483 [15.0][FIX] account_invoice_clearing: sudo when reopening wizard
  account_invoice_clearing/wizards/account_invoice_clearing_wizard.py
Labels: bot is merging ⏳

#1170 [15.0][MIG] account_invoice_force_number
  account_invoice_force_number/README.rst
  account_invoice_force_number/__init__.py
  account_invoice_force_number/__manifest__.py
  account_invoice_force_number/i18n/account_invoice_force_number.pot
  account_invoice_force_number/i18n/ar.po
  account_invoice_force_number/i18n/bg.po
  account_invoice_force_number/i18n/bs.po
  account_invoice_force_number/i18n/ca.po
  account_invoice_force_number/i18n/cs.po
  account_invoice_force_number/i18n/de.po
  account_invoice_force_number/i18n/el_GR.po
  account_invoice_force_number/i18n/en_GB.po
  account_invoice_force_number/i18n/es.po
  account_invoice_force_number/i18n/es_CR.po
  account_invoice_force_number/i18n/es_EC.po
  account_invoice_force_number/i18n/es_MX.po
  account_invoice_force_number/i18n/et.po
  account_invoice_force_number/i18n/fi.po
  account_invoice_force_number/i18n/fr.po
  account_invoice_force_number/i18n/fr_CH.po
  account_invoice_force_number/i18n/gl.po
  account_invoice_force_number/i18n/hr.po
  account_invoice_force_number/i18n/hr_HR.po
  account_invoice_force_number/i18n/id.po
  account_invoice_force_number/i18n/it.po
  account_invoice_force_number/i18n/ja.po
  account_invoice_force_number/i18n/lt.po
  account_invoice_force_number/i18n/mk.po
  account_invoice_force_number/i18n/mn.po
  account_invoice_force_number/i18n/nb_NO.po
  account_invoice_force_number/i18n/nl.po
  account_invoice_force_number/i18n/nl_BE.po
  account_invoice_force_number/i18n/pl.po
  account_invoice_force_number/i18n/pt.po
  account_invoice_force_number/i18n/pt_BR.po
  account_invoice_force_number/i18n/pt_PT.po
  account_invoice_force_number/i18n/ro.po
  account_invoice_force_number/i18n/ru.po
  account_invoice_force_number/i18n/sk_SK.po
  account_invoice_force_number/i18n/sl.po
  account_invoice_force_number/i18n/sv.po
  account_invoice_force_number/i18n/th.po
  account_invoice_force_number/i18n/tr.po
  account_invoice_force_number/i18n/tr_TR.po
  account_invoice_force_number/i18n/zh_CN.po
  account_invoice_force_number/i18n/zh_TW.po
  account_invoice_force_number/models/__init__.py
  account_invoice_force_number/models/account_move.py
  account_invoice_force_number/readme/CONFIGURE.rst
  account_invoice_force_number/readme/CONTRIBUTORS.rst
  account_invoice_force_number/readme/DESCRIPTION.rst
  account_invoice_force_number/readme/USAGE.rst
  account_invoice_force_number/security/security.xml
  account_invoice_force_number/static/description/icon.png
  account_invoice_force_number/static/description/index.html
  account_invoice_force_number/tests/__init__.py
  account_invoice_force_number/tests/test_account_force_number.py
  account_invoice_force_number/views/account_move_view.xml
  setup/account_invoice_force_number/odoo/addons/account_invoice_force_number
  setup/account_invoice_force_number/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#1495 [15.0][MIG] account_invoice_restrict_linked_so: Migration to 15.0
  account_invoice_restrict_linked_so/README.rst
  account_invoice_restrict_linked_so/__init__.py
  account_invoice_restrict_linked_so/__manifest__.py
  account_invoice_restrict_linked_so/i18n/account_invoice_restrict_linked_so.pot
  account_invoice_restrict_linked_so/i18n/sl.po
  account_invoice_restrict_linked_so/readme/CONTRIBUTORS.rst
  account_invoice_restrict_linked_so/readme/DESCRIPTION.rst
  account_invoice_restrict_linked_so/readme/USAGE.rst
  account_invoice_restrict_linked_so/static/description/icon.png
  account_invoice_restrict_linked_so/static/description/index.html
  account_invoice_restrict_linked_so/views/account_move.xml
  setup/account_invoice_restrict_linked_so/odoo/addons/account_invoice_restrict_linked_so
  setup/account_invoice_restrict_linked_so/setup.py
Labels: approved, ready to merge, bot is merging ⏳
