Repository OCA/account-invoicing, pull requests merged in 2024-03, with the labels that each got.

#1551 [ADD] account_receipt_base
  account_receipt_base/README.rst
  account_receipt_base/__init__.py
  account_receipt_base/__manifest__.py
  account_receipt_base/i18n/it.po
  account_receipt_base/models/__init__.py
  account_receipt_base/models/account_fiscal_position.py
  account_receipt_base/models/account_move.py
  account_receipt_base/models/res_partner.py
  account_receipt_base/readme/CONFIGURE.rst
  account_receipt_base/readme/CONTRIBUTORS.rst
  account_receipt_base/readme/DESCRIPTION.rst
  account_receipt_base/reports/__init__.py
  account_receipt_base/reports/account_invoice_report.py
  account_receipt_base/reports/account_invoice_report_views.xml
  account_receipt_base/static/description/index.html
  account_receipt_base/tests/__init__.py
  account_receipt_base/tests/test_fiscal_position.py
  account_receipt_base/tests/test_partner.py
  account_receipt_base/tests/test_receipt.py
  account_receipt_base/views/account_fiscal_position_views.xml
  account_receipt_base/views/account_move_views.xml
  account_receipt_base/views/res_partner_views.xml
  setup/account_receipt_base/odoo/addons/account_receipt_base
  setup/account_receipt_base/setup.py
Labels: needs review, approved, ready to merge, bot is merging ⏳

#1267 [14.0] ADD account_receipt_sale
  account_receipt_sale/__init__.py
  account_receipt_sale/__manifest__.py
  account_receipt_sale/migrations/14.0.1.0.1/post-migrate.py
  account_receipt_sale/models/__init__.py
  account_receipt_sale/models/sale.py
  account_receipt_sale/readme/CONFIGURE.rst
  account_receipt_sale/readme/CONTRIBUTORS.rst
  account_receipt_sale/readme/DESCRIPTION.rst
  account_receipt_sale/readme/HISTORY.rst
  account_receipt_sale/tests/__init__.py
  account_receipt_sale/tests/test_receipts.py
  account_receipt_sale/views/sale_views.xml
  account_receipt_sale/wizard/__init__.py
  account_receipt_sale/wizard/sale_make_invoice.py
  setup/account_receipt_sale/odoo/addons/account_receipt_sale
  setup/account_receipt_sale/setup.py
Labels: needs review, approved, bot is merging ⏳

#1667 [17.0][MIG]account_invoice_fixed_discount: Migrated module to v17.0
  account_invoice_fixed_discount/README.rst
  account_invoice_fixed_discount/__init__.py
  account_invoice_fixed_discount/__manifest__.py
  account_invoice_fixed_discount/i18n/account_invoice_fixed_discount.pot
  account_invoice_fixed_discount/i18n/ca.po
  account_invoice_fixed_discount/i18n/de.po
  account_invoice_fixed_discount/i18n/es.po
  account_invoice_fixed_discount/i18n/pt_BR.po
  account_invoice_fixed_discount/models/__init__.py
  account_invoice_fixed_discount/models/account_move_line.py
  account_invoice_fixed_discount/models/account_tax.py
  account_invoice_fixed_discount/pyproject.toml
  account_invoice_fixed_discount/readme/CONTRIBUTORS.md
  account_invoice_fixed_discount/readme/DESCRIPTION.md
  account_invoice_fixed_discount/readme/INSTALL.md
  account_invoice_fixed_discount/readme/USAGE.md
  account_invoice_fixed_discount/reports/report_account_invoice.xml
  account_invoice_fixed_discount/security/res_groups.xml
  account_invoice_fixed_discount/static/description/icon.png
  account_invoice_fixed_discount/static/description/index.html
  account_invoice_fixed_discount/tests/__init__.py
  account_invoice_fixed_discount/tests/test_account_fixed_discount.py
  account_invoice_fixed_discount/views/account_move_view.xml
Labels: approved, bot is merging ⏳

#1679 [17.0][IMP]account_invoice_fixed_discount: Improved for contribution
  account_invoice_fixed_discount/README.rst
  account_invoice_fixed_discount/readme/CONTRIBUTORS.md
  account_invoice_fixed_discount/static/description/index.html
Labels: approved, bot is merging ⏳

#1568 [ADD][16.0][MIG] account_move_substate
  account_move_substate/README.rst
  account_move_substate/__init__.py
  account_move_substate/__manifest__.py
  account_move_substate/data/account_move_substate_data.xml
  account_move_substate/data/account_move_substate_mail_template_data.xml
  account_move_substate/demo/account_move_substate_demo.xml
  account_move_substate/models/__init__.py
  account_move_substate/models/account_move.py
  account_move_substate/readme/CONTRIBUTORS.rst
  account_move_substate/readme/DESCRIPTION.rst
  account_move_substate/readme/USAGE.rst
  account_move_substate/static/description/icon.png
  account_move_substate/static/description/index.html
  account_move_substate/tests/__init__.py
  account_move_substate/tests/test_account_move_substate.py
  account_move_substate/views/account_move_views.xml
  setup/account_move_substate/odoo/addons/account_move_substate
  setup/account_move_substate/setup.py
Labels: approved, bot is merging ⏳

#1681 [16.0][FIX] account_invoice_force_number: Assign forced number on mass vali…
  account_invoice_force_number/__manifest__.py
  account_invoice_force_number/models/account_move.py
  account_invoice_force_number/static/description/index.html
  account_invoice_force_number/tests/test_account_force_number.py
Labels: approved, ready to merge, bot is merging ⏳
