Repository OCA/account-invoicing, pull requests merged in 2024-11, with the labels that each got.

#1828 [15.0][FIX] account_invoice_view_payment: fix permissions issue when accessing to view payments from invoice
  account_invoice_view_payment/models/account_move.py
  account_invoice_view_payment/tests/test_account_invoice_view_payment.py
Labels: bot is merging ⏳

#1813 [16.0][ADD] stock_account_move_reset_to_draft: New module
  setup/stock_account_move_reset_to_draft/odoo/addons/stock_account_move_reset_to_draft
  setup/stock_account_move_reset_to_draft/setup.py
  stock_account_move_reset_to_draft/README.rst
  stock_account_move_reset_to_draft/__init__.py
  stock_account_move_reset_to_draft/__manifest__.py
  stock_account_move_reset_to_draft/i18n/es.po
  stock_account_move_reset_to_draft/i18n/stock_account_move_reset_to_draft.pot
  stock_account_move_reset_to_draft/models/__init__.py
  stock_account_move_reset_to_draft/models/account_move.py
  stock_account_move_reset_to_draft/readme/CONTEXT.rst
  stock_account_move_reset_to_draft/readme/CONTRIBUTORS.rst
  stock_account_move_reset_to_draft/readme/DESCRIPTION.rst
  stock_account_move_reset_to_draft/readme/USAGE.rst
  stock_account_move_reset_to_draft/static/description/icon.png
  stock_account_move_reset_to_draft/static/description/index.html
  stock_account_move_reset_to_draft/tests/__init__.py
  stock_account_move_reset_to_draft/tests/test_stock_account_move_reset_to_draft.py
Labels: approved, ready to merge, bot is merging ⏳

#1836 [13.0][FIX] account_invoice_show_currency_rate: use only debit from currency lines to get rate
  account_invoice_show_currency_rate/models/account_move.py
Labels: approved, bot is merging ⏳

#1837 [16.0][FW][FIX] account_invoice_show_currency_rate: use only debit from currency lines to get rate
  account_invoice_show_currency_rate/models/account_move.py
Labels: approved, bot is merging ⏳

#1829 [17.0][MIG] account_move_tier_validation
  account_move_tier_validation/README.rst
  account_move_tier_validation/__init__.py
  account_move_tier_validation/__manifest__.py
  account_move_tier_validation/i18n/account_move_tier_validation.pot
  account_move_tier_validation/i18n/ca.po
  account_move_tier_validation/i18n/es.po
  account_move_tier_validation/i18n/es_PA.po
  account_move_tier_validation/i18n/fr.po
  account_move_tier_validation/i18n/hr.po
  account_move_tier_validation/i18n/it.po
  account_move_tier_validation/i18n/sv.po
  account_move_tier_validation/i18n/zh_CN.po
  account_move_tier_validation/models/__init__.py
  account_move_tier_validation/models/account_move.py
  account_move_tier_validation/models/tier_definition.py
  account_move_tier_validation/pyproject.toml
  account_move_tier_validation/readme/CONFIGURE.md
  account_move_tier_validation/readme/CONTRIBUTORS.md
  account_move_tier_validation/readme/DESCRIPTION.md
  account_move_tier_validation/readme/INSTALL.md
  account_move_tier_validation/readme/USAGE.md
  account_move_tier_validation/static/description/icon.png
  account_move_tier_validation/static/description/index.html
  account_move_tier_validation/tests/__init__.py
  account_move_tier_validation/tests/test_tier_validation.py
  account_move_tier_validation/views/account_move_view.xml
Labels: approved, ready to merge, bot is merging ⏳

#1382 [14.0][ADD] account_invoice_auto_send_by_email
  account_invoice_auto_send_by_email/__init__.py
  account_invoice_auto_send_by_email/__manifest__.py
  account_invoice_auto_send_by_email/data/ir_cron.xml
  account_invoice_auto_send_by_email/models/__init__.py
  account_invoice_auto_send_by_email/models/account_invoice_send.py
  account_invoice_auto_send_by_email/models/account_move.py
  account_invoice_auto_send_by_email/readme/CONTRIBUTORS.rst
  account_invoice_auto_send_by_email/readme/DESCRIPTION.rst
  account_invoice_auto_send_by_email/tests/__init__.py
  account_invoice_auto_send_by_email/tests/test_account_invoice_auto_send_by_email.py
  setup/account_invoice_auto_send_by_email/odoo/addons/account_invoice_auto_send_by_email
  setup/account_invoice_auto_send_by_email/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#1841 [16.0][FIX] stock_account_move_reset_to_draft: Update the README
  stock_account_move_reset_to_draft/README.rst
  stock_account_move_reset_to_draft/readme/CONTEXT.rst
  stock_account_move_reset_to_draft/readme/DESCRIPTION.rst
  stock_account_move_reset_to_draft/readme/USAGE.rst
  stock_account_move_reset_to_draft/static/description/index.html
Labels: approved, bot is merging ⏳

#1839 [15.0][FIX] account_invoice_mass_sending: Users have extra notifications when the invoice has sent by the job
  account_invoice_mass_sending/models/account_move.py
  account_invoice_mass_sending/wizards/account_invoice_send.py
Labels: approved, bot is merging ⏳

#1843 [17.0][MIG] sale_order_invoicing_qty_percentage: Migration to 17.0
  sale_order_invoicing_qty_percentage/README.rst
  sale_order_invoicing_qty_percentage/__init__.py
  sale_order_invoicing_qty_percentage/__manifest__.py
  sale_order_invoicing_qty_percentage/i18n/es.po
  sale_order_invoicing_qty_percentage/i18n/it.po
  sale_order_invoicing_qty_percentage/i18n/sale_order_invoicing_qty_percentage.pot
  sale_order_invoicing_qty_percentage/models/__init__.py
  sale_order_invoicing_qty_percentage/models/sale_order.py
  sale_order_invoicing_qty_percentage/pyproject.toml
  sale_order_invoicing_qty_percentage/readme/CONTRIBUTORS.md
  sale_order_invoicing_qty_percentage/readme/DESCRIPTION.md
  sale_order_invoicing_qty_percentage/readme/ROADMAP.md
  sale_order_invoicing_qty_percentage/readme/USAGE.md
  sale_order_invoicing_qty_percentage/static/description/icon.png
  sale_order_invoicing_qty_percentage/static/description/index.html
  sale_order_invoicing_qty_percentage/tests/__init__.py
  sale_order_invoicing_qty_percentage/tests/test_sale_order_invoicing_qty_percentage.py
  sale_order_invoicing_qty_percentage/wizards/__init__.py
  sale_order_invoicing_qty_percentage/wizards/sale_advance_payment_inv.py
  sale_order_invoicing_qty_percentage/wizards/sale_advance_payment_inv_views.xml
Labels: approved, bot is merging ⏳

#1787 [17.0][MIG] portal_account_personal_data_only: Migration to 17.0
  portal_account_personal_data_only/README.rst
  portal_account_personal_data_only/__init__.py
  portal_account_personal_data_only/__manifest__.py
  portal_account_personal_data_only/hooks.py
  portal_account_personal_data_only/i18n/es.po
  portal_account_personal_data_only/i18n/it.po
  portal_account_personal_data_only/i18n/portal_account_personal_data_only.pot
  portal_account_personal_data_only/pyproject.toml
  portal_account_personal_data_only/readme/CONTRIBUTORS.md
  portal_account_personal_data_only/readme/DESCRIPTION.md
  portal_account_personal_data_only/readme/USAGE.md
  portal_account_personal_data_only/security/security.xml
  portal_account_personal_data_only/static/description/icon.png
  portal_account_personal_data_only/static/description/index.html
  portal_account_personal_data_only/tests/__init__.py
  portal_account_personal_data_only/tests/test_partner_access.py
Labels: approved, bot is merging ⏳

#1846 [16.0][FP] account_invoice_mass_sending: Users have extra notifications when the invoice has sent by the job
  account_invoice_mass_sending/models/account_move.py
  account_invoice_mass_sending/wizards/account_invoice_send.py
Labels: approved, bot is merging ⏳

#1819 [16.0][stock_picking_invoicing][FIX] stock_picking_invoicing:Stock Rule inv state - fwp 1782
  stock_picking_invoicing/models/__init__.py
  stock_picking_invoicing/models/stock_rule.py
Labels: approved, ready to merge, bot is merging ⏳

#1806 [17.0][FW] account_invoice_pricelist: Use setter for triple discount
  account_invoice_pricelist/models/account_move.py
Labels: bot is merging ⏳
