Repository OCA/account-invoicing, pull requests merged in 2024-12, with the labels that each got.

#1774 [IMP][14.0] account_invoice_section_sale_order: Fix read/write access
  account_invoice_section_sale_order/models/sale_order.py
  account_invoice_section_sale_order/tests/common.py
  account_invoice_section_sale_order/tests/test_access_rights.py
  account_invoice_section_sale_order/tests/test_invoice_group_by_sale_order.py
Labels: approved, ready to merge, bot is merging ⏳

#1862 [14.0] account_invoice_section_sale_order: fix access rights
  account_invoice_section_sale_order/models/sale_order.py
  account_invoice_section_sale_order/tests/__init__.py
Labels: approved, bot is merging ⏳

#1770 [14.0][FIX] account_invoice_section_sale_order check if line_ids exists
  account_invoice_section_sale_order/models/sale_order.py
Labels: approved, ready to merge, bot is merging ⏳

#1826 [15.0][MIG] sale_stock_picking_invoicing: Migration to 15.0
  sale_stock_picking_invoicing/README.rst
  sale_stock_picking_invoicing/__init__.py
  sale_stock_picking_invoicing/__manifest__.py
  sale_stock_picking_invoicing/demo/sale_order_demo.xml
  sale_stock_picking_invoicing/i18n/sale_stock_picking_invoicing.pot
  sale_stock_picking_invoicing/models/__init__.py
  sale_stock_picking_invoicing/models/res_company.py
  sale_stock_picking_invoicing/models/res_config_settings.py
  sale_stock_picking_invoicing/models/sale_order.py
  sale_stock_picking_invoicing/models/sale_order_line.py
  sale_stock_picking_invoicing/models/stock_move.py
  sale_stock_picking_invoicing/models/stock_picking.py
  sale_stock_picking_invoicing/readme/CONFIGURE.rst
  sale_stock_picking_invoicing/readme/CONTRIBUTORS.rst
  sale_stock_picking_invoicing/readme/CREDITS.rst
  sale_stock_picking_invoicing/readme/DESCRIPTION.rst
  sale_stock_picking_invoicing/readme/HISTORY.rst
  sale_stock_picking_invoicing/readme/INSTALL.rst
  sale_stock_picking_invoicing/readme/ROADMAP.rst
  sale_stock_picking_invoicing/readme/USAGE.rst
  sale_stock_picking_invoicing/static/description/icon.png
  sale_stock_picking_invoicing/static/description/index.html
  sale_stock_picking_invoicing/tests/__init__.py
  sale_stock_picking_invoicing/tests/test_sale_stock.py
  sale_stock_picking_invoicing/views/res_company_view.xml
  sale_stock_picking_invoicing/views/res_config_settings_view.xml
  sale_stock_picking_invoicing/wizards/__init__.py
  sale_stock_picking_invoicing/wizards/stock_invoice_onshipping.py
  sale_stock_picking_invoicing/wizards/stock_invoice_onshipping_view.xml
  setup/sale_stock_picking_invoicing/odoo/addons/sale_stock_picking_invoicing
  setup/sale_stock_picking_invoicing/setup.py
Labels: approved, bot is merging ⏳

#1856 [FIX] account_invoice_mass_sending: wrong channel name
  account_invoice_mass_sending/data/queue_job.xml
Labels: needs review, approved, ready to merge, bot is merging ⏳

#1538 [16.0][ADD] account_move_sent_usability
  account_move_sent_usability/README.rst
  account_move_sent_usability/__init__.py
  account_move_sent_usability/__manifest__.py
  account_move_sent_usability/readme/CONTRIBUTORS.rst
  account_move_sent_usability/readme/DESCRIPTION.rst
  account_move_sent_usability/static/description/icon.png
  account_move_sent_usability/static/description/index.html
  account_move_sent_usability/static/images/sent_filter.png
  account_move_sent_usability/static/images/sent_form.png
  account_move_sent_usability/views/account_move.xml
  setup/account_move_sent_usability/odoo/addons/account_move_sent_usability
  setup/account_move_sent_usability/setup.py
Labels: approved, ready to merge, bot is merging ⏳, stale

#1755 [16.0] [MIG] account_invoice_refund_reinvoice: Migration to 16.0
  account_invoice_refund_reinvoice/README.rst
  account_invoice_refund_reinvoice/__init__.py
  account_invoice_refund_reinvoice/__manifest__.py
  account_invoice_refund_reinvoice/i18n/account_invoice_refund_reinvoice.pot
  account_invoice_refund_reinvoice/models/__init__.py
  account_invoice_refund_reinvoice/models/account_move.py
  account_invoice_refund_reinvoice/readme/CONTRIBUTORS.rst
  account_invoice_refund_reinvoice/readme/DESCRIPTION.rst
  account_invoice_refund_reinvoice/readme/USAGE.rst
  account_invoice_refund_reinvoice/static/description/icon.png
  account_invoice_refund_reinvoice/static/description/index.html
  account_invoice_refund_reinvoice/tests/__init__.py
  account_invoice_refund_reinvoice/tests/test_refund_invoice.py
  account_invoice_refund_reinvoice/views/account_move.xml
  setup/account_invoice_refund_reinvoice/odoo/addons/account_invoice_refund_reinvoice
  setup/account_invoice_refund_reinvoice/setup.py
Labels: approved, bot is merging ⏳
