Repository OCA/account-invoicing, pull requests merged in 2024-05, with the labels that each got.

#1718 [17.0] dotfiles update needs manual intervention
  .copier-answers.yml
  .github/workflows/stale.yml
  .github/workflows/test.yml
  .pre-commit-config.yaml
  .ruff.toml
  account_invoice_fixed_discount/models/account_tax.py
Labels: help wanted, needs review, bot is merging ⏳

#1675 [17.0][MIG] account_invoice_warn_message
  account_invoice_warn_message/README.rst
  account_invoice_warn_message/__init__.py
  account_invoice_warn_message/__manifest__.py
  account_invoice_warn_message/i18n/account_invoice_warn_message.pot
  account_invoice_warn_message/i18n/es.po
  account_invoice_warn_message/models/__init__.py
  account_invoice_warn_message/models/account_move.py
  account_invoice_warn_message/pyproject.toml
  account_invoice_warn_message/readme/CONTRIBUTORS.md
  account_invoice_warn_message/readme/DESCRIPTION.md
  account_invoice_warn_message/static/description/icon.png
  account_invoice_warn_message/static/description/index.html
  account_invoice_warn_message/tests/__init__.py
  account_invoice_warn_message/tests/test_account_invoice_warn_message.py
  account_invoice_warn_message/views/account_move_views.xml
Labels: approved, ready to merge, bot is merging ⏳

#1499 [16.0][FIX] account_tax_change: fix tax changes wizard
  account_tax_change/wizards/account_move_apply_tax_change.py
Labels: approved, bot is merging ⏳

#1516 [FIX] account_tax_change: update chart_template_ref in test
  account_tax_change/tests/common.py
Labels: approved, ready to merge, bot is merging ⏳

#1558 [15.0][FIX] account_invoice_fixed_discount: Fix Division by zero error
  account_invoice_fixed_discount/models/account_move.py
Labels: approved, ready to merge, bot is merging ⏳

#1407 [15.0][MIG]account_invoice_alternate_payer : Migration to V15
  account_invoice_alternate_payer/README.rst
  account_invoice_alternate_payer/__init__.py
  account_invoice_alternate_payer/__manifest__.py
  account_invoice_alternate_payer/i18n/account_invoice_alternate_payer.pot
  account_invoice_alternate_payer/models/__init__.py
  account_invoice_alternate_payer/models/account_move.py
  account_invoice_alternate_payer/models/account_payment.py
  account_invoice_alternate_payer/readme/CONTRIBUTORS.rst
  account_invoice_alternate_payer/readme/DESCRIPTION.rst
  account_invoice_alternate_payer/readme/USAGE.rst
  account_invoice_alternate_payer/static/description/icon.png
  account_invoice_alternate_payer/static/description/index.html
  account_invoice_alternate_payer/tests/__init__.py
  account_invoice_alternate_payer/tests/test_account_invoice.py
  account_invoice_alternate_payer/views/account_move_views.xml
  setup/account_invoice_alternate_payer/odoo/addons/account_invoice_alternate_payer
  setup/account_invoice_alternate_payer/setup.py
Labels: approved, bot is merging ⏳

#1420 [ADD] account_invoice_line_complimentary
  account_invoice_change_currency/models/account_change_currency.py
  account_invoice_line_complimentary/README.rst
  account_invoice_line_complimentary/__init__.py
  account_invoice_line_complimentary/__manifest__.py
  account_invoice_line_complimentary/i18n/it.po
  account_invoice_line_complimentary/models/__init__.py
  account_invoice_line_complimentary/models/account_invoice.py
  account_invoice_line_complimentary/models/account_invoice_line.py
  account_invoice_line_complimentary/models/res_company.py
  account_invoice_line_complimentary/models/res_config_settings.py
  account_invoice_line_complimentary/readme/CONFIGURE.rst
  account_invoice_line_complimentary/readme/CONTRIBUTORS.rst
  account_invoice_line_complimentary/readme/DESCRIPTION.rst
  account_invoice_line_complimentary/readme/USAGE.rst
  account_invoice_line_complimentary/static/description/index.html
  account_invoice_line_complimentary/tests/__init__.py
  account_invoice_line_complimentary/tests/common.py
  account_invoice_line_complimentary/tests/test_complimentary.py
  account_invoice_line_complimentary/views/account_invoice_line_views.xml
  account_invoice_line_complimentary/views/account_invoice_views.xml
  account_invoice_line_complimentary/views/res_config_settings_views.xml
  setup/account_invoice_line_complimentary/odoo/addons/account_invoice_line_complimentary
  setup/account_invoice_line_complimentary/setup.py
Labels: approved, bot is merging ⏳

#1704 [ADD] [15.0] account_warn_option
  account_warn_option/README.rst
  account_warn_option/__init__.py
  account_warn_option/__manifest__.py
  account_warn_option/i18n/account_warn_option.pot
  account_warn_option/i18n/es.po
  account_warn_option/models/__init__.py
  account_warn_option/models/res_partner.py
  account_warn_option/models/warn_option.py
  account_warn_option/readme/CONTEXT.md
  account_warn_option/readme/CONTRIBUTORS.md
  account_warn_option/readme/DESCRIPTION.md
  account_warn_option/readme/USAGE.md
  account_warn_option/static/description/icon.png
  account_warn_option/static/description/index.html
  account_warn_option/tests/__init__.py
  account_warn_option/tests/test_warn_options.py
  account_warn_option/views/res_partner_views.xml
  setup/account_warn_option/odoo/addons/account_warn_option
  setup/account_warn_option/setup.py
Labels: needs review, approved, ready to merge, bot is merging ⏳

#1664 [16.0][FIX] account_invoice_triple_discount: Fix tax recompute on closed fiscal year
  account_invoice_triple_discount/README.rst
  account_invoice_triple_discount/models/account_move_line.py
  account_invoice_triple_discount/readme/CONTRIBUTORS.rst
  account_invoice_triple_discount/static/description/index.html
  account_invoice_triple_discount/tests/test_invoice_triple_discount.py
Labels: approved, bot is merging ⏳

#1710 [17.0][IMP] account_invoice_fixed_discount: avoid replace in xml
  account_invoice_fixed_discount/reports/report_account_invoice.xml
Labels: approved, bot is merging ⏳

#1724 [16.0][MIG] account_global_discount: Migration to 16.0
  account_global_discount/README.rst
  account_global_discount/__init__.py
  account_global_discount/__manifest__.py
  account_global_discount/hooks.py
  account_global_discount/i18n/.empty
  account_global_discount/i18n/account_global_discount.pot
  account_global_discount/i18n/es.po
  account_global_discount/i18n/it.po
  account_global_discount/i18n/nl_NL.po
  account_global_discount/i18n/pt.po
  account_global_discount/models/__init__.py
  account_global_discount/models/account_move.py
  account_global_discount/models/global_discount.py
  account_global_discount/readme/CONFIGURE.rst
  account_global_discount/readme/CONTRIBUTORS.rst
  account_global_discount/readme/DESCRIPTION.rst
  account_global_discount/readme/ROADMAP.rst
  account_global_discount/readme/USAGE.rst
  account_global_discount/report/__init__.py
  account_global_discount/report/account_invoice_report.py
  account_global_discount/security/ir.model.access.csv
  account_global_discount/security/security.xml
  account_global_discount/static/description/icon.png
  account_global_discount/static/description/icon.svg
  account_global_discount/static/description/index.html
  account_global_discount/tests/__init__.py
  account_global_discount/tests/test_global_discount.py
  account_global_discount/views/account_invoice_views.xml
  account_global_discount/views/global_discount_views.xml
  account_global_discount/views/report_account_invoice.xml
  setup/account_global_discount/odoo/addons/account_global_discount
  setup/account_global_discount/setup.py
Labels: bot is merging ⏳

#1381 [14.0][FIX] sale_line_refund_to_invoice_qty, fix default value on aml
  __init__.py
  sale_line_refund_to_invoice_qty/__manifest__.py
  sale_line_refund_to_invoice_qty/migrations/14.0.2.0.1/post-fix-old-field-value.py
  sale_line_refund_to_invoice_qty/models/account.py
Labels: approved, ready to merge, bot is merging ⏳

#1716 [16.0][IMP][FWD] account_move_substate: documentation
  account_move_substate/readme/DESCRIPTION.rst
Labels: approved, bot is merging ⏳

#1231 [15.0][MIG] account_portal_hide_invoice
  account_portal_hide_invoice/README.rst
  account_portal_hide_invoice/__init__.py
  account_portal_hide_invoice/__manifest__.py
  account_portal_hide_invoice/i18n/account_portal_hide_invoice.pot
  account_portal_hide_invoice/i18n/es.po
  account_portal_hide_invoice/readme/CONTRIBUTORS.rst
  account_portal_hide_invoice/readme/CREDITS.rst
  account_portal_hide_invoice/readme/DESCRIPTION.rst
  account_portal_hide_invoice/readme/ROADMAP.rst
  account_portal_hide_invoice/static/description/icon.png
  account_portal_hide_invoice/static/description/index.html
  account_portal_hide_invoice/views/account_portal_templates.xml
  setup/account_portal_hide_invoice/odoo/addons/account_portal_hide_invoice
  setup/account_portal_hide_invoice/setup.py
Labels: needs review, approved, bot is merging ⏳, stale

#1367 [16.0][ADD] account_tax_one_vat_purchase
  account_tax_one_vat_purchase/README.rst
  account_tax_one_vat_purchase/__init__.py
  account_tax_one_vat_purchase/__manifest__.py
  account_tax_one_vat_purchase/i18n/account_tax_one_vat_purchase.pot
  account_tax_one_vat_purchase/models/__init__.py
  account_tax_one_vat_purchase/models/purchase_order_line.py
  account_tax_one_vat_purchase/readme/CONTRIBUTORS.rst
  account_tax_one_vat_purchase/readme/DESCRIPTION.rst
  account_tax_one_vat_purchase/static/description/index.html
  account_tax_one_vat_purchase/tests/__init__.py
  account_tax_one_vat_purchase/tests/test_account_tax_one_vat_purchase.py
  setup/account_tax_one_vat_purchase/odoo/addons/account_tax_one_vat_purchase
  setup/account_tax_one_vat_purchase/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#1726 [14.0][REM] wrong init file
  __init__.py
Labels: bot is merging ⏳

#1623 [16.0][MIG] account_invoice_discount_display_amount: Migration to 16.0
  account_invoice_discount_display_amount/README.rst
  account_invoice_discount_display_amount/__init__.py
  account_invoice_discount_display_amount/__manifest__.py
  account_invoice_discount_display_amount/i18n/account_invoice_discount_display_amount.pot
  account_invoice_discount_display_amount/models/__init__.py
  account_invoice_discount_display_amount/models/account_move.py
  account_invoice_discount_display_amount/models/account_move_line.py
  account_invoice_discount_display_amount/readme/CONFIGURE.rst
  account_invoice_discount_display_amount/readme/CONTRIBUTORS.rst
  account_invoice_discount_display_amount/readme/DESCRIPTION.rst
  account_invoice_discount_display_amount/readme/USAGE.rst
  account_invoice_discount_display_amount/report/report_invoice.xml
  account_invoice_discount_display_amount/static/description/icon.png
  account_invoice_discount_display_amount/static/description/index.html
  account_invoice_discount_display_amount/tests/__init__.py
  account_invoice_discount_display_amount/tests/common.py
  account_invoice_discount_display_amount/tests/test_account_move.py
  account_invoice_discount_display_amount/tests/test_account_move_line.py
  account_invoice_discount_display_amount/tests/test_invoice_discount_display_amount.py
  account_invoice_discount_display_amount/views/account_move_views.xml
  setup/account_invoice_discount_display_amount/odoo/addons/account_invoice_discount_display_amount
  setup/account_invoice_discount_display_amount/setup.py
Labels: needs review, approved, migration, ready to merge, bot is merging ⏳

#1727 [16.0][FIX] account_invoice_pricelist: Make tests resilient
  account_invoice_pricelist/tests/test_account_move_pricelist.py
Labels: bot is merging ⏳

#1728 [15.0][FIX] account_portal_invoice_search: Define the correct parameters as well as account
  account_portal_invoice_search/controllers/portal.py
Labels: approved, bot is merging ⏳

#1730 [FIX] account_invoice_refund_link: Form view for refund invoices
  account_invoice_refund_link/views/account_invoice_view.xml
Labels: approved, bot is merging ⏳
