Repository OCA/account-invoicing, pull requests merged in 2024-06, with the labels that each got.

#1683 [ADD] account_move_auto_post_ref: propagate ref on recurrent invoices
  account_move_auto_post_ref/README.rst
  account_move_auto_post_ref/__init__.py
  account_move_auto_post_ref/__manifest__.py
  account_move_auto_post_ref/models/__init__.py
  account_move_auto_post_ref/models/account_move.py
  account_move_auto_post_ref/readme/CONTRIBUTORS.md
  account_move_auto_post_ref/readme/DESCRIPTION.md
  account_move_auto_post_ref/readme/USAGE.md
  account_move_auto_post_ref/static/description/icon.png
  account_move_auto_post_ref/static/description/index.html
  account_move_auto_post_ref/tests/__init__.py
  account_move_auto_post_ref/tests/test_invoice.py
  setup/account_move_auto_post_ref/odoo/addons/account_move_auto_post_ref
  setup/account_move_auto_post_ref/setup.py
Labels: needs review, approved, bot is merging ⏳

#1738 [16.0][IMP] account_invoice_show_currency_rate: optional show journal items rate
  account_invoice_show_currency_rate/views/account_move_view.xml
Labels: approved, bot is merging ⏳

#1580 [16.0][MIG] account_invoice_refund_reason_skip_anglo_saxon
  account_invoice_refund_reason_skip_anglo_saxon/README.rst
  account_invoice_refund_reason_skip_anglo_saxon/__init__.py
  account_invoice_refund_reason_skip_anglo_saxon/__manifest__.py
  account_invoice_refund_reason_skip_anglo_saxon/models/__init__.py
  account_invoice_refund_reason_skip_anglo_saxon/models/account_invoice_refund_reason.py
  account_invoice_refund_reason_skip_anglo_saxon/models/account_move.py
  account_invoice_refund_reason_skip_anglo_saxon/readme/CONFIGURE.rst
  account_invoice_refund_reason_skip_anglo_saxon/readme/CONTRIBUTORS.rst
  account_invoice_refund_reason_skip_anglo_saxon/readme/DESCRIPTION.rst
  account_invoice_refund_reason_skip_anglo_saxon/static/description/index.html
  account_invoice_refund_reason_skip_anglo_saxon/tests/__init__.py
  account_invoice_refund_reason_skip_anglo_saxon/tests/test_account_invoice_refund_reason_skip_anglo_saxon.py
  account_invoice_refund_reason_skip_anglo_saxon/views/account_invoice_refund_reason_view.xml
  setup/account_invoice_refund_reason_skip_anglo_saxon/odoo/addons/account_invoice_refund_reason_skip_anglo_saxon
  setup/account_invoice_refund_reason_skip_anglo_saxon/setup.py
Labels: bot is merging ⏳

#1739 [16.0][FIX] Several warnings in logs
  account_invoice_show_currency_rate/tests/test_account_move.py
  account_invoice_supplierinfo_update_triple_discount/wizard/wizard_update_invoice_supplierinfo_line.py
Labels: approved, ready to merge, bot is merging ⏳

#1725 [16.0][IMP] account_global_discount: exclude products from global disc
  account_global_discount/models/account_move.py
Labels: approved, bot is merging ⏳

#1741 [16.0] Replace 'Camptocamp SA' with 'Camptocamp'
  account_mail_autosubscribe/README.rst
  account_mail_autosubscribe/__manifest__.py
  account_mail_autosubscribe/static/description/index.html
Labels: bot is merging ⏳

#1628 [IMP] partner_invoicing_mode_at_shipping: Add grouping option per picking
  partner_invoicing_mode_at_shipping/README.rst
  partner_invoicing_mode_at_shipping/__init__.py
  partner_invoicing_mode_at_shipping/__manifest__.py
  partner_invoicing_mode_at_shipping/hooks.py
  partner_invoicing_mode_at_shipping/migrations/16.0.1.1.0/pre-migrate.py
  partner_invoicing_mode_at_shipping/models/__init__.py
  partner_invoicing_mode_at_shipping/models/res_partner.py
  partner_invoicing_mode_at_shipping/models/sale_order.py
  partner_invoicing_mode_at_shipping/models/stock_picking.py
  partner_invoicing_mode_at_shipping/readme/DESCRIPTION.rst
  partner_invoicing_mode_at_shipping/static/description/index.html
  partner_invoicing_mode_at_shipping/tests/__init__.py
  partner_invoicing_mode_at_shipping/tests/common.py
  partner_invoicing_mode_at_shipping/tests/test_invoice_mode_at_shipping.py
  partner_invoicing_mode_at_shipping/tests/test_invoice_mode_group_delivery.py
  partner_invoicing_mode_at_shipping/views/res_partner.xml
Labels: approved, ready to merge, bot is merging ⏳

#1539 [16.0][FIX] account_invoice_currency_taxes: get the company's currency through the record environment
  account_invoice_currency_taxes/models/account_tax.py
Labels: approved, bot is merging ⏳
