Repository OCA/account-invoicing, pull requests merged in 2024-02, with the labels that each got.

#1659 [15.0][IMP] account_invoice_tax_required: Add customer information to error message for missing taxes in invoice lines
  account_invoice_tax_required/i18n/account_invoice_tax_required.pot
  account_invoice_tax_required/i18n/ar.po
  account_invoice_tax_required/i18n/bg.po
  account_invoice_tax_required/i18n/bs.po
  account_invoice_tax_required/i18n/ca.po
  account_invoice_tax_required/i18n/cs.po
  account_invoice_tax_required/i18n/de.po
  account_invoice_tax_required/i18n/el_GR.po
  account_invoice_tax_required/i18n/en_GB.po
  account_invoice_tax_required/i18n/es.po
  account_invoice_tax_required/i18n/es_CR.po
  account_invoice_tax_required/i18n/es_EC.po
  account_invoice_tax_required/i18n/es_ES.po
  account_invoice_tax_required/i18n/es_MX.po
  account_invoice_tax_required/i18n/et.po
  account_invoice_tax_required/i18n/fi.po
  account_invoice_tax_required/i18n/fr.po
  account_invoice_tax_required/i18n/fr_CA.po
  account_invoice_tax_required/i18n/fr_CH.po
  account_invoice_tax_required/i18n/gl.po
  account_invoice_tax_required/i18n/hr.po
  account_invoice_tax_required/i18n/hr_HR.po
  account_invoice_tax_required/i18n/hu.po
  account_invoice_tax_required/i18n/id.po
  account_invoice_tax_required/i18n/it.po
  account_invoice_tax_required/i18n/ja.po
  account_invoice_tax_required/i18n/lt.po
  account_invoice_tax_required/i18n/mk.po
  account_invoice_tax_required/i18n/mn.po
  account_invoice_tax_required/i18n/nb.po
  account_invoice_tax_required/i18n/nb_NO.po
  account_invoice_tax_required/i18n/nl.po
  account_invoice_tax_required/i18n/nl_BE.po
  account_invoice_tax_required/i18n/nl_NL.po
  account_invoice_tax_required/i18n/pl.po
  account_invoice_tax_required/i18n/pt.po
  account_invoice_tax_required/i18n/pt_BR.po
  account_invoice_tax_required/i18n/pt_PT.po
  account_invoice_tax_required/i18n/ro.po
  account_invoice_tax_required/i18n/ru.po
  account_invoice_tax_required/i18n/sk_SK.po
  account_invoice_tax_required/i18n/sl.po
  account_invoice_tax_required/i18n/sv.po
  account_invoice_tax_required/i18n/th.po
  account_invoice_tax_required/i18n/tr.po
  account_invoice_tax_required/i18n/tr_TR.po
  account_invoice_tax_required/i18n/zh_CN.po
  account_invoice_tax_required/i18n/zh_TW.po
  account_invoice_tax_required/models/account_move.py
  account_invoice_tax_required/tests/test_account_move_tax_required.py
Labels: bot is merging ⏳

#1663 [16.0][IMP] account_invoice_tax_required: Improve error message for lack of tax
  account_invoice_tax_required/i18n/account_invoice_tax_required.pot
  account_invoice_tax_required/i18n/ar.po
  account_invoice_tax_required/i18n/bg.po
  account_invoice_tax_required/i18n/bs.po
  account_invoice_tax_required/i18n/ca.po
  account_invoice_tax_required/i18n/cs.po
  account_invoice_tax_required/i18n/de.po
  account_invoice_tax_required/i18n/el_GR.po
  account_invoice_tax_required/i18n/en_GB.po
  account_invoice_tax_required/i18n/es.po
  account_invoice_tax_required/i18n/es_CR.po
  account_invoice_tax_required/i18n/es_EC.po
  account_invoice_tax_required/i18n/es_ES.po
  account_invoice_tax_required/i18n/es_MX.po
  account_invoice_tax_required/i18n/et.po
  account_invoice_tax_required/i18n/fi.po
  account_invoice_tax_required/i18n/fr.po
  account_invoice_tax_required/i18n/fr_CA.po
  account_invoice_tax_required/i18n/fr_CH.po
  account_invoice_tax_required/i18n/gl.po
  account_invoice_tax_required/i18n/hr.po
  account_invoice_tax_required/i18n/hr_HR.po
  account_invoice_tax_required/i18n/hu.po
  account_invoice_tax_required/i18n/id.po
  account_invoice_tax_required/i18n/it.po
  account_invoice_tax_required/i18n/ja.po
  account_invoice_tax_required/i18n/lt.po
  account_invoice_tax_required/i18n/mk.po
  account_invoice_tax_required/i18n/mn.po
  account_invoice_tax_required/i18n/nb.po
  account_invoice_tax_required/i18n/nb_NO.po
  account_invoice_tax_required/i18n/nl.po
  account_invoice_tax_required/i18n/nl_BE.po
  account_invoice_tax_required/i18n/nl_NL.po
  account_invoice_tax_required/i18n/pl.po
  account_invoice_tax_required/i18n/pt.po
  account_invoice_tax_required/i18n/pt_BR.po
  account_invoice_tax_required/i18n/pt_PT.po
  account_invoice_tax_required/i18n/ro.po
  account_invoice_tax_required/i18n/ru.po
  account_invoice_tax_required/i18n/sk_SK.po
  account_invoice_tax_required/i18n/sl.po
  account_invoice_tax_required/i18n/sv.po
  account_invoice_tax_required/i18n/th.po
  account_invoice_tax_required/i18n/tr.po
  account_invoice_tax_required/i18n/tr_TR.po
  account_invoice_tax_required/i18n/zh_CN.po
  account_invoice_tax_required/i18n/zh_TW.po
  account_invoice_tax_required/models/account_move.py
  account_invoice_tax_required/tests/test_account_move_tax_required.py
Labels: approved, bot is merging ⏳

#1404 [IMP][12.0] account_invoice_supplierinfo_update : improve _is_correct_price function
  account_invoice_supplierinfo_update/models/account_invoice_line.py
  account_invoice_supplierinfo_update/tests/test_account_invoice_supplierinfo_update.py
  account_invoice_supplierinfo_update/wizard/wizard_update_invoice_supplierinfo.py
  account_invoice_supplierinfo_update/wizard/wizard_update_invoice_supplierinfo.xml
  account_invoice_supplierinfo_update/wizard/wizard_update_invoice_supplierinfo_line.py
Labels: approved, bot is merging ⏳

#1654 [16.0] mig account_invoice_default_code_column
  account_invoice_default_code_column/README.rst
  account_invoice_default_code_column/__init__.py
  account_invoice_default_code_column/__manifest__.py
  account_invoice_default_code_column/i18n/fr.po
  account_invoice_default_code_column/models/__init__.py
  account_invoice_default_code_column/models/account_move_line.py
  account_invoice_default_code_column/readme/CONTRIBUTORS.rst
  account_invoice_default_code_column/readme/DESCRIPTION.rst
  account_invoice_default_code_column/reports/report_account_invoice.xml
  account_invoice_default_code_column/static/description/1_without_module.png
  account_invoice_default_code_column/static/description/2_with_module.png
  account_invoice_default_code_column/static/description/icon.png
  account_invoice_default_code_column/static/description/index.html
  setup/account_invoice_default_code_column/odoo/addons/account_invoice_default_code_column
  setup/account_invoice_default_code_column/setup.py
Labels: approved, bot is merging ⏳

#1597 [16.0][MIG] account_invoice_payment_retention
  account_invoice_payment_retention/README.rst
  account_invoice_payment_retention/__init__.py
  account_invoice_payment_retention/__manifest__.py
  account_invoice_payment_retention/i18n/account_invoice_payment_retention.pot
  account_invoice_payment_retention/i18n/ca.po
  account_invoice_payment_retention/models/__init__.py
  account_invoice_payment_retention/models/account_move.py
  account_invoice_payment_retention/models/res_company.py
  account_invoice_payment_retention/models/res_config_settings.py
  account_invoice_payment_retention/readme/CONFIGURE.rst
  account_invoice_payment_retention/readme/CONTRIBUTORS.rst
  account_invoice_payment_retention/readme/DESCRIPTION.rst
  account_invoice_payment_retention/readme/USAGE.rst
  account_invoice_payment_retention/security/security.xml
  account_invoice_payment_retention/static/description/icon.png
  account_invoice_payment_retention/static/description/index.html
  account_invoice_payment_retention/tests/__init__.py
  account_invoice_payment_retention/tests/test_invoice_payment_retention.py
  account_invoice_payment_retention/views/account_move_views.xml
  account_invoice_payment_retention/views/res_config_settings_views.xml
  account_invoice_payment_retention/wizard/__init__.py
  account_invoice_payment_retention/wizard/account_payment_register.py
  account_invoice_payment_retention/wizard/account_payment_register_views.xml
  setup/account_invoice_payment_retention/odoo/addons/account_invoice_payment_retention
  setup/account_invoice_payment_retention/setup.py
Labels: approved, bot is merging ⏳

#1647 [15.0][ADD]account_invoice_custom_rounding: Custom taxes rounding method in invoices
  account_invoice_custom_rounding/README.rst
  account_invoice_custom_rounding/__init__.py
  account_invoice_custom_rounding/__manifest__.py
  account_invoice_custom_rounding/models/__init__.py
  account_invoice_custom_rounding/models/account_move.py
  account_invoice_custom_rounding/models/res_partner.py
  account_invoice_custom_rounding/readme/CONFIGURE.rst
  account_invoice_custom_rounding/readme/DESCRIPTION.rst
  account_invoice_custom_rounding/readme/USAGE.rst
  account_invoice_custom_rounding/static/description/icon.png
  account_invoice_custom_rounding/static/description/index.html
  account_invoice_custom_rounding/tests/__init__.py
  account_invoice_custom_rounding/tests/common.py
  account_invoice_custom_rounding/tests/test_account_invoice_custom_rounding.py
  account_invoice_custom_rounding/views/account_move_views.xml
  account_invoice_custom_rounding/views/partner_view.xml
  setup/account_invoice_custom_rounding/odoo/addons/account_invoice_custom_rounding
  setup/account_invoice_custom_rounding/setup.py
Labels: approved, bot is merging ⏳

#1616 [16.0][MIG] account-invoicing: account_invoice_tax_note
  README.md
  account_invoice_tax_note/README.rst
  account_invoice_tax_note/__init__.py
  account_invoice_tax_note/__manifest__.py
  account_invoice_tax_note/i18n/account_invoice_tax_note.pot
  account_invoice_tax_note/i18n/ca.po
  account_invoice_tax_note/i18n/de.po
  account_invoice_tax_note/i18n/es.po
  account_invoice_tax_note/i18n/fr.po
  account_invoice_tax_note/models/__init__.py
  account_invoice_tax_note/models/account_move.py
  account_invoice_tax_note/models/account_tax_group.py
  account_invoice_tax_note/readme/CONTRIBUTORS.rst
  account_invoice_tax_note/readme/DESCRIPTION.rst
  account_invoice_tax_note/readme/USAGE.rst
  account_invoice_tax_note/reports/report_invoice_document.xml
  account_invoice_tax_note/static/description/icon.png
  account_invoice_tax_note/static/description/index.html
  account_invoice_tax_note/tests/__init__.py
  account_invoice_tax_note/tests/test_account_invoice.py
  account_invoice_tax_note/views/account_tax_views.xml
  setup/account_invoice_tax_note/odoo/addons/account_invoice_tax_note
  setup/account_invoice_tax_note/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#1492 [16.0][MIG] account_invoice_alternate_payer
  account_invoice_alternate_payer/README.rst
  account_invoice_alternate_payer/__init__.py
  account_invoice_alternate_payer/__manifest__.py
  account_invoice_alternate_payer/i18n/account_invoice_alternate_payer.pot
  account_invoice_alternate_payer/i18n/es.po
  account_invoice_alternate_payer/models/__init__.py
  account_invoice_alternate_payer/models/account_move.py
  account_invoice_alternate_payer/models/account_payment.py
  account_invoice_alternate_payer/readme/CONTRIBUTORS.rst
  account_invoice_alternate_payer/readme/DESCRIPTION.rst
  account_invoice_alternate_payer/readme/USAGE.rst
  account_invoice_alternate_payer/static/description/icon.png
  account_invoice_alternate_payer/static/description/index.html
  account_invoice_alternate_payer/tests/__init__.py
  account_invoice_alternate_payer/tests/test_account_invoice.py
  account_invoice_alternate_payer/views/account_move_views.xml
  setup/account_invoice_alternate_payer/odoo/addons/account_invoice_alternate_payer
  setup/account_invoice_alternate_payer/setup.py
Labels: approved, ready to merge, bot is merging ⏳
