Repository OCA/account-invoicing, pull requests merged in 2024-07, with the labels that each got.

#1326 [15.0][ADD] purchase_order_invoicing_grouping_criteria: New module
  purchase_order_invoicing_grouping_criteria/README.rst
  purchase_order_invoicing_grouping_criteria/__init__.py
  purchase_order_invoicing_grouping_criteria/__manifest__.py
  purchase_order_invoicing_grouping_criteria/i18n/es.po
  purchase_order_invoicing_grouping_criteria/i18n/purchase_order_invoicing_grouping_criteria.pot
  purchase_order_invoicing_grouping_criteria/models/__init__.py
  purchase_order_invoicing_grouping_criteria/models/purchase_invoicing_grouping_criteria.py
  purchase_order_invoicing_grouping_criteria/models/purchase_order.py
  purchase_order_invoicing_grouping_criteria/models/res_company.py
  purchase_order_invoicing_grouping_criteria/models/res_config_settings.py
  purchase_order_invoicing_grouping_criteria/models/res_partner.py
  purchase_order_invoicing_grouping_criteria/readme/CONFIGURE.rst
  purchase_order_invoicing_grouping_criteria/readme/CONTRIBUTORS.rst
  purchase_order_invoicing_grouping_criteria/readme/DESCRIPTION.rst
  purchase_order_invoicing_grouping_criteria/readme/USAGE.rst
  purchase_order_invoicing_grouping_criteria/security/ir.model.access.csv
  purchase_order_invoicing_grouping_criteria/static/description/icon.png
  purchase_order_invoicing_grouping_criteria/static/description/index.html
  purchase_order_invoicing_grouping_criteria/tests/__init__.py
  purchase_order_invoicing_grouping_criteria/tests/test_purchase_order_invoicing_group_criteria.py
  purchase_order_invoicing_grouping_criteria/views/purchase_invoicing_grouping_criteria_views.xml
  purchase_order_invoicing_grouping_criteria/views/res_config_settings_views.xml
  purchase_order_invoicing_grouping_criteria/views/res_partner_views.xml
  setup/purchase_order_invoicing_grouping_criteria/odoo/addons/purchase_order_invoicing_grouping_criteria
  setup/purchase_order_invoicing_grouping_criteria/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#1323 [15.0][MIG] account_invoice_refund_reinvoice
  account_invoice_refund_reinvoice/README.rst
  account_invoice_refund_reinvoice/__init__.py
  account_invoice_refund_reinvoice/__manifest__.py
  account_invoice_refund_reinvoice/i18n/account_invoice_refund_reinvoice.pot
  account_invoice_refund_reinvoice/models/__init__.py
  account_invoice_refund_reinvoice/models/account_move.py
  account_invoice_refund_reinvoice/readme/CONTRIBUTORS.rst
  account_invoice_refund_reinvoice/readme/DESCRIPTION.rst
  account_invoice_refund_reinvoice/readme/USAGE.rst
  account_invoice_refund_reinvoice/static/description/icon.png
  account_invoice_refund_reinvoice/static/description/index.html
  account_invoice_refund_reinvoice/tests/__init__.py
  account_invoice_refund_reinvoice/tests/test_refund_invoice.py
  account_invoice_refund_reinvoice/views/account_move.xml
  setup/account_invoice_refund_reinvoice/odoo/addons/account_invoice_refund_reinvoice
  setup/account_invoice_refund_reinvoice/setup.py
Labels: needs review, approved, bot is merging ⏳, stale

#1754 [14.0][FIX] purchase_stock_picking_return_invoicing: Add digits="Product Unit of Measure" to qty_refunded + qty_returned fields
  purchase_stock_picking_return_invoicing/models/purchase_order.py
Labels: bot is merging ⏳

#1757 [15.0][FIX] purchase_stock_picking_return_invoicing: Add digits="Product Unit of Measure" to qty_refunded + qty_returned fields
  purchase_stock_picking_return_invoicing/models/purchase_order.py
Labels: bot is merging ⏳

#1758 [16.0][FIX] purchase_stock_picking_return_invoicing: Add digits="Product Unit of Measure" to qty_refunded + qty_returned fields
  purchase_stock_picking_return_invoicing/models/purchase_order.py
Labels: bot is merging ⏳

#1745 [16.0][ADD] account_invoice_recipient_bank_currency
  account_invoice_recipient_bank_currency/README.rst
  account_invoice_recipient_bank_currency/__init__.py
  account_invoice_recipient_bank_currency/__manifest__.py
  account_invoice_recipient_bank_currency/models/__init__.py
  account_invoice_recipient_bank_currency/models/account_move.py
  account_invoice_recipient_bank_currency/readme/CONTRIBUTORS.rst
  account_invoice_recipient_bank_currency/readme/DESCRIPTION.rst
  account_invoice_recipient_bank_currency/static/description/index.html
  account_invoice_recipient_bank_currency/tests/__init__.py
  account_invoice_recipient_bank_currency/tests/test_account_invoice_recipient_bank_currency.py
  setup/account_invoice_recipient_bank_currency/odoo/addons/account_invoice_recipient_bank_currency
  setup/account_invoice_recipient_bank_currency/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#1342 [13.0][ADD] account_portal_invoice_search_by_lot: New module to allow search invoices by lots at portal
  account_portal_invoice_search_by_lot/README.rst
  account_portal_invoice_search_by_lot/__init__.py
  account_portal_invoice_search_by_lot/__manifest__.py
  account_portal_invoice_search_by_lot/i18n/account_portal_invoice_search_by_lot.pot
  account_portal_invoice_search_by_lot/i18n/es.po
  account_portal_invoice_search_by_lot/models/__init__.py
  account_portal_invoice_search_by_lot/models/account_move.py
  account_portal_invoice_search_by_lot/readme/CONTRIBUTORS.rst
  account_portal_invoice_search_by_lot/readme/DESCRIPTION.rst
  account_portal_invoice_search_by_lot/readme/USAGE.rst
  account_portal_invoice_search_by_lot/static/description/index.html
  setup/account_portal_invoice_search_by_lot/odoo/addons/account_portal_invoice_search_by_lot
  setup/account_portal_invoice_search_by_lot/setup.py
Labels: approved, bot is merging ⏳, stale

#1752 [17.0] [MIG] sale_order_invoicing_grouping_criteria: Migration to 17.0
  sale_order_invoicing_grouping_criteria/README.rst
  sale_order_invoicing_grouping_criteria/__init__.py
  sale_order_invoicing_grouping_criteria/__manifest__.py
  sale_order_invoicing_grouping_criteria/i18n/ca.po
  sale_order_invoicing_grouping_criteria/i18n/de.po
  sale_order_invoicing_grouping_criteria/i18n/es.po
  sale_order_invoicing_grouping_criteria/i18n/fr.po
  sale_order_invoicing_grouping_criteria/i18n/it.po
  sale_order_invoicing_grouping_criteria/i18n/sale_order_invoicing_grouping_criteria.pot
  sale_order_invoicing_grouping_criteria/models/__init__.py
  sale_order_invoicing_grouping_criteria/models/res_company.py
  sale_order_invoicing_grouping_criteria/models/res_config_settings.py
  sale_order_invoicing_grouping_criteria/models/res_partner.py
  sale_order_invoicing_grouping_criteria/models/sale_invoicing_grouping_criteria.py
  sale_order_invoicing_grouping_criteria/models/sale_order.py
  sale_order_invoicing_grouping_criteria/pyproject.toml
  sale_order_invoicing_grouping_criteria/readme/CONFIGURE.md
  sale_order_invoicing_grouping_criteria/readme/CONTRIBUTORS.md
  sale_order_invoicing_grouping_criteria/readme/DESCRIPTION.md
  sale_order_invoicing_grouping_criteria/readme/USAGE.md
  sale_order_invoicing_grouping_criteria/security/ir.model.access.csv
  sale_order_invoicing_grouping_criteria/static/description/icon.png
  sale_order_invoicing_grouping_criteria/static/description/index.html
  sale_order_invoicing_grouping_criteria/tests/__init__.py
  sale_order_invoicing_grouping_criteria/tests/test_sale_order_invoicing_group_criteria.py
  sale_order_invoicing_grouping_criteria/views/res_config_settings_views.xml
  sale_order_invoicing_grouping_criteria/views/res_partner_views.xml
  sale_order_invoicing_grouping_criteria/views/sale_invoicing_grouping_criteria_views.xml
Labels: approved, bot is merging ⏳

#1357 [14.0][FIX] account_invoice_refund_reason: refund and new draft invoice
  account_invoice_refund_reason/wizard/account_move_reversal.py
Labels: bot is merging ⏳, stale

#1640 [17.0][MIG] account_invoice_section_sale_order: Migration to 17.0
  account_invoice_section_sale_order/README.rst
  account_invoice_section_sale_order/__init__.py
  account_invoice_section_sale_order/__manifest__.py
  account_invoice_section_sale_order/i18n/account_invoice_section_sale_order.pot
  account_invoice_section_sale_order/i18n/es.po
  account_invoice_section_sale_order/models/__init__.py
  account_invoice_section_sale_order/models/sale_order.py
  account_invoice_section_sale_order/pyproject.toml
  account_invoice_section_sale_order/readme/CONTRIBUTORS.md
  account_invoice_section_sale_order/readme/CREDITS.md
  account_invoice_section_sale_order/readme/DESCRIPTION.md
  account_invoice_section_sale_order/static/description/icon.png
  account_invoice_section_sale_order/static/description/index.html
  account_invoice_section_sale_order/tests/__init__.py
  account_invoice_section_sale_order/tests/test_invoice_group_by_sale_order.py
Labels: approved, ready to merge, bot is merging ⏳

#1744 [16.0][ADD] account_move_cancel_confirm
  account_move_cancel_confirm/README.rst
  account_move_cancel_confirm/__init__.py
  account_move_cancel_confirm/__manifest__.py
  account_move_cancel_confirm/model/__init__.py
  account_move_cancel_confirm/model/account_move.py
  account_move_cancel_confirm/model/account_payment.py
  account_move_cancel_confirm/readme/CONTRIBUTORS.rst
  account_move_cancel_confirm/readme/DESCRIPTION.rst
  account_move_cancel_confirm/static/description/icon.png
  account_move_cancel_confirm/static/description/index.html
  account_move_cancel_confirm/tests/__init__.py
  account_move_cancel_confirm/tests/test_account_move_cancel_confirm.py
  setup/account_move_cancel_confirm/odoo/addons/account_move_cancel_confirm
  setup/account_move_cancel_confirm/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#1767 [17.0][MIG] sale_invoicing_date_selection: Migration to version 17.0
  sale_invoicing_date_selection/README.rst
  sale_invoicing_date_selection/__init__.py
  sale_invoicing_date_selection/__manifest__.py
  sale_invoicing_date_selection/i18n/es.po
  sale_invoicing_date_selection/i18n/sale_invoicing_date_selection.pot
  sale_invoicing_date_selection/models/__init__.py
  sale_invoicing_date_selection/models/sale_order.py
  sale_invoicing_date_selection/pyproject.toml
  sale_invoicing_date_selection/readme/CONTRIBUTORS.md
  sale_invoicing_date_selection/readme/DESCRIPTION.md
  sale_invoicing_date_selection/readme/USAGE.md
  sale_invoicing_date_selection/static/description/icon.png
  sale_invoicing_date_selection/static/description/index.html
  sale_invoicing_date_selection/tests/__init__.py
  sale_invoicing_date_selection/tests/test_sale_invoicing_date_selection.py
  sale_invoicing_date_selection/wizard/__init__.py
  sale_invoicing_date_selection/wizard/sale_advance_payment_inv.py
  sale_invoicing_date_selection/wizard/sale_make_invoice_advance_views.xml
Labels: approved, ready to merge, bot is merging ⏳

#1682 [MIG] [17.0] account_invoice_blocking migration to 17.0
  account_invoice_blocking/README.rst
  account_invoice_blocking/__init__.py
  account_invoice_blocking/__manifest__.py
  account_invoice_blocking/i18n/account_invoice_blocking.pot
  account_invoice_blocking/i18n/de.po
  account_invoice_blocking/i18n/es.po
  account_invoice_blocking/i18n/hr.po
  account_invoice_blocking/i18n/it.po
  account_invoice_blocking/i18n/nl.po
  account_invoice_blocking/i18n/pt.po
  account_invoice_blocking/i18n/pt_BR.po
  account_invoice_blocking/models/__init__.py
  account_invoice_blocking/models/account_move.py
  account_invoice_blocking/pyproject.toml
  account_invoice_blocking/readme/CONTRIBUTORS.md
  account_invoice_blocking/readme/DESCRIPTION.md
  account_invoice_blocking/readme/ROADMAP.md
  account_invoice_blocking/readme/USAGE.md
  account_invoice_blocking/static/description/icon.png
  account_invoice_blocking/static/description/index.html
  account_invoice_blocking/tests/__init__.py
  account_invoice_blocking/tests/test_account_move_blocking.py
  account_invoice_blocking/views/account_move.xml
Labels: approved, bot is merging ⏳
