Repository OCA/account-invoicing, pull requests merged in 2024-01, with the labels that each got.

#1614 [FIX] account_invoice_fixed_discount: Check base_line type
  account_invoice_fixed_discount/models/account_tax.py
Labels: approved, ready to merge, bot is merging ⏳

#1636 [16.0][IMP] account_invoice_fixed_discount: Error on create expense
  account_invoice_fixed_discount/tests/test_account_fixed_discount.py
Labels: bot is merging ⏳

#1076 [13.0][FIX] account_invoice_pricelist: Avoid division by zero
  account_invoice_pricelist/models/account_move.py
Labels: approved, bot is merging ⏳

#1485 [16.0][FIX] account_invoice_pricelist: Avoid division by zero
  account_invoice_pricelist/models/account_move.py
Labels: needs review, approved, bot is merging ⏳

#1641 [15.0][FIX] account_invoice_pricelist: float division by zero
  account_invoice_pricelist/models/account_move.py
Labels: bot is merging ⏳

#1642 [15.0][FIX] account_invoice_tax_required: Don't bypass restriction on mass mass_validation
  account_invoice_tax_required/i18n/account_invoice_tax_required.pot
  account_invoice_tax_required/i18n/ar.po
  account_invoice_tax_required/i18n/bg.po
  account_invoice_tax_required/i18n/bs.po
  account_invoice_tax_required/i18n/ca.po
  account_invoice_tax_required/i18n/cs.po
  account_invoice_tax_required/i18n/de.po
  account_invoice_tax_required/i18n/el_GR.po
  account_invoice_tax_required/i18n/en_GB.po
  account_invoice_tax_required/i18n/es.po
  account_invoice_tax_required/i18n/es_CR.po
  account_invoice_tax_required/i18n/es_EC.po
  account_invoice_tax_required/i18n/es_ES.po
  account_invoice_tax_required/i18n/es_MX.po
  account_invoice_tax_required/i18n/et.po
  account_invoice_tax_required/i18n/fi.po
  account_invoice_tax_required/i18n/fr.po
  account_invoice_tax_required/i18n/fr_CA.po
  account_invoice_tax_required/i18n/fr_CH.po
  account_invoice_tax_required/i18n/gl.po
  account_invoice_tax_required/i18n/hr.po
  account_invoice_tax_required/i18n/hr_HR.po
  account_invoice_tax_required/i18n/hu.po
  account_invoice_tax_required/i18n/id.po
  account_invoice_tax_required/i18n/it.po
  account_invoice_tax_required/i18n/ja.po
  account_invoice_tax_required/i18n/lt.po
  account_invoice_tax_required/i18n/mk.po
  account_invoice_tax_required/i18n/mn.po
  account_invoice_tax_required/i18n/nb.po
  account_invoice_tax_required/i18n/nb_NO.po
  account_invoice_tax_required/i18n/nl.po
  account_invoice_tax_required/i18n/nl_BE.po
  account_invoice_tax_required/i18n/nl_NL.po
  account_invoice_tax_required/i18n/pl.po
  account_invoice_tax_required/i18n/pt.po
  account_invoice_tax_required/i18n/pt_BR.po
  account_invoice_tax_required/i18n/pt_PT.po
  account_invoice_tax_required/i18n/ro.po
  account_invoice_tax_required/i18n/ru.po
  account_invoice_tax_required/i18n/sk_SK.po
  account_invoice_tax_required/i18n/sl.po
  account_invoice_tax_required/i18n/sv.po
  account_invoice_tax_required/i18n/th.po
  account_invoice_tax_required/i18n/tr.po
  account_invoice_tax_required/i18n/tr_TR.po
  account_invoice_tax_required/i18n/zh_CN.po
  account_invoice_tax_required/i18n/zh_TW.po
  account_invoice_tax_required/models/account_move.py
  account_invoice_tax_required/tests/test_account_move_tax_required.py
Labels: approved, bot is merging ⏳

#1643 [16.0][IMP+FIX] account_invoice_tax_required: Don't bypass restriction on mass validation + better message
  account_invoice_tax_required/i18n/account_invoice_tax_required.pot
  account_invoice_tax_required/i18n/ar.po
  account_invoice_tax_required/i18n/bg.po
  account_invoice_tax_required/i18n/bs.po
  account_invoice_tax_required/i18n/ca.po
  account_invoice_tax_required/i18n/cs.po
  account_invoice_tax_required/i18n/de.po
  account_invoice_tax_required/i18n/el_GR.po
  account_invoice_tax_required/i18n/en_GB.po
  account_invoice_tax_required/i18n/es.po
  account_invoice_tax_required/i18n/es_CR.po
  account_invoice_tax_required/i18n/es_EC.po
  account_invoice_tax_required/i18n/es_ES.po
  account_invoice_tax_required/i18n/es_MX.po
  account_invoice_tax_required/i18n/et.po
  account_invoice_tax_required/i18n/fi.po
  account_invoice_tax_required/i18n/fr.po
  account_invoice_tax_required/i18n/fr_CA.po
  account_invoice_tax_required/i18n/fr_CH.po
  account_invoice_tax_required/i18n/gl.po
  account_invoice_tax_required/i18n/hr.po
  account_invoice_tax_required/i18n/hr_HR.po
  account_invoice_tax_required/i18n/hu.po
  account_invoice_tax_required/i18n/id.po
  account_invoice_tax_required/i18n/it.po
  account_invoice_tax_required/i18n/ja.po
  account_invoice_tax_required/i18n/lt.po
  account_invoice_tax_required/i18n/mk.po
  account_invoice_tax_required/i18n/mn.po
  account_invoice_tax_required/i18n/nb.po
  account_invoice_tax_required/i18n/nb_NO.po
  account_invoice_tax_required/i18n/nl.po
  account_invoice_tax_required/i18n/nl_BE.po
  account_invoice_tax_required/i18n/nl_NL.po
  account_invoice_tax_required/i18n/pl.po
  account_invoice_tax_required/i18n/pt.po
  account_invoice_tax_required/i18n/pt_BR.po
  account_invoice_tax_required/i18n/pt_PT.po
  account_invoice_tax_required/i18n/ro.po
  account_invoice_tax_required/i18n/ru.po
  account_invoice_tax_required/i18n/sk_SK.po
  account_invoice_tax_required/i18n/sl.po
  account_invoice_tax_required/i18n/sv.po
  account_invoice_tax_required/i18n/th.po
  account_invoice_tax_required/i18n/tr.po
  account_invoice_tax_required/i18n/tr_TR.po
  account_invoice_tax_required/i18n/zh_CN.po
  account_invoice_tax_required/i18n/zh_TW.po
  account_invoice_tax_required/models/account_move.py
  account_invoice_tax_required/tests/test_account_move_tax_required.py
Labels: approved, bot is merging ⏳

#1639 [16.0][MIG] sale_order_invoicing_qty_percentage: Migration to version 16.0
  sale_order_invoicing_qty_percentage/README.rst
  sale_order_invoicing_qty_percentage/__init__.py
  sale_order_invoicing_qty_percentage/__manifest__.py
  sale_order_invoicing_qty_percentage/i18n/es.po
  sale_order_invoicing_qty_percentage/i18n/sale_order_invoicing_qty_percentage.pot
  sale_order_invoicing_qty_percentage/models/__init__.py
  sale_order_invoicing_qty_percentage/models/sale_order.py
  sale_order_invoicing_qty_percentage/readme/CONTRIBUTORS.rst
  sale_order_invoicing_qty_percentage/readme/DESCRIPTION.rst
  sale_order_invoicing_qty_percentage/readme/ROADMAP.rst
  sale_order_invoicing_qty_percentage/readme/USAGE.rst
  sale_order_invoicing_qty_percentage/static/description/icon.png
  sale_order_invoicing_qty_percentage/static/description/index.html
  sale_order_invoicing_qty_percentage/tests/__init__.py
  sale_order_invoicing_qty_percentage/tests/test_sale_order_invoicing_qty_percentage.py
  sale_order_invoicing_qty_percentage/wizards/__init__.py
  sale_order_invoicing_qty_percentage/wizards/sale_advance_payment_inv.py
  sale_order_invoicing_qty_percentage/wizards/sale_advance_payment_inv_views.xml
  setup/sale_order_invoicing_qty_percentage/odoo/addons/sale_order_invoicing_qty_percentage
  setup/sale_order_invoicing_qty_percentage/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#1413 12.0 add account_invoice_supplierinfo_update_qty_multiplier
  account_invoice_supplierinfo_update_qty_multiplier/README.rst
  account_invoice_supplierinfo_update_qty_multiplier/__init__.py
  account_invoice_supplierinfo_update_qty_multiplier/__manifest__.py
  account_invoice_supplierinfo_update_qty_multiplier/i18n/fr.po
  account_invoice_supplierinfo_update_qty_multiplier/models/__init__.py
  account_invoice_supplierinfo_update_qty_multiplier/models/account_invoice_line.py
  account_invoice_supplierinfo_update_qty_multiplier/readme/DESCRIPTION.rst
  account_invoice_supplierinfo_update_qty_multiplier/tests/__init__.py
  account_invoice_supplierinfo_update_qty_multiplier/tests/test_module.py
  account_invoice_supplierinfo_update_qty_multiplier/wizard/__init__.py
  account_invoice_supplierinfo_update_qty_multiplier/wizard/wizard_update_invoice_supplierinfo.xml
  account_invoice_supplierinfo_update_qty_multiplier/wizard/wizard_update_invoice_supplierinfo_line.py
  setup/account_invoice_supplierinfo_update_qty_multiplier/odoo/addons/account_invoice_supplierinfo_update_qty_multiplier
  setup/account_invoice_supplierinfo_update_qty_multiplier/setup.py
Labels: needs review, approved, ready to merge, bot is merging ⏳

#1645 [13.0][IMP] account_invoice_warn_message: added full invoice types support
  account_invoice_warn_message/__manifest__.py
  account_invoice_warn_message/models/__init__.py
  account_invoice_warn_message/models/account_move.py
  account_invoice_warn_message/models/res_company.py
  account_invoice_warn_message/models/res_config_settings.py
  account_invoice_warn_message/readme/CONTRIBUTORS.rst
  account_invoice_warn_message/readme/DESCRIPTION.rst
  account_invoice_warn_message/views/res_config_settings_views.xml
Labels: approved, ready to merge, bot is merging ⏳

#1648 [15.0][IMP] account_invoice_triple_discount: only manage lines with discount2 or discount3
  account_invoice_triple_discount/models/account_move.py
  account_invoice_triple_discount/readme/CONTRIBUTORS.rst
Labels: approved, bot is merging ⏳

#1602 [16][MIG] purchase_invoicing_no_zero_line
  purchase_invoicing_no_zero_line/README.rst
  purchase_invoicing_no_zero_line/__init__.py
  purchase_invoicing_no_zero_line/__manifest__.py
  purchase_invoicing_no_zero_line/i18n/de.po
  purchase_invoicing_no_zero_line/i18n/es.po
  purchase_invoicing_no_zero_line/i18n/purchase_invoicing_no_zero_line.pot
  purchase_invoicing_no_zero_line/models/__init__.py
  purchase_invoicing_no_zero_line/models/account_journal.py
  purchase_invoicing_no_zero_line/models/account_move.py
  purchase_invoicing_no_zero_line/readme/CONFIGURE.rst
  purchase_invoicing_no_zero_line/readme/CONTRIBUTORS.rst
  purchase_invoicing_no_zero_line/readme/DESCRIPTION.rst
  purchase_invoicing_no_zero_line/static/description/icon.png
  purchase_invoicing_no_zero_line/static/description/icon.svg
  purchase_invoicing_no_zero_line/static/description/index.html
  purchase_invoicing_no_zero_line/tests/__init__.py
  purchase_invoicing_no_zero_line/tests/test_purchase_invoicing_no_zero_line.py
  purchase_invoicing_no_zero_line/views/account_view.xml
  setup/purchase_invoicing_no_zero_line/odoo/addons/purchase_invoicing_no_zero_line
  setup/purchase_invoicing_no_zero_line/setup.py
Labels: approved, bot is merging ⏳

#1445 [16.0] mig account_invoice_supplierinfo_update_triple_discount
  account_invoice_supplierinfo_update_triple_discount/README.rst
  account_invoice_supplierinfo_update_triple_discount/__init__.py
  account_invoice_supplierinfo_update_triple_discount/__manifest__.py
  account_invoice_supplierinfo_update_triple_discount/i18n/account_invoice_supplierinfo_update_triple_discount.pot
  account_invoice_supplierinfo_update_triple_discount/i18n/es.po
  account_invoice_supplierinfo_update_triple_discount/i18n/fr.po
  account_invoice_supplierinfo_update_triple_discount/i18n/it.po
  account_invoice_supplierinfo_update_triple_discount/models/__init__.py
  account_invoice_supplierinfo_update_triple_discount/models/account_move_line.py
  account_invoice_supplierinfo_update_triple_discount/readme/CONTRIBUTORS.rst
  account_invoice_supplierinfo_update_triple_discount/readme/DESCRIPTION.rst
  account_invoice_supplierinfo_update_triple_discount/static/description/icon.png
  account_invoice_supplierinfo_update_triple_discount/static/description/index.html
  account_invoice_supplierinfo_update_triple_discount/static/description/wizard_form.png
  account_invoice_supplierinfo_update_triple_discount/tests/__init__.py
  account_invoice_supplierinfo_update_triple_discount/tests/test_module.py
  account_invoice_supplierinfo_update_triple_discount/wizard/__init__.py
  account_invoice_supplierinfo_update_triple_discount/wizard/wizard_update_invoice_supplierinfo.py
  account_invoice_supplierinfo_update_triple_discount/wizard/wizard_update_invoice_supplierinfo.xml
  account_invoice_supplierinfo_update_triple_discount/wizard/wizard_update_invoice_supplierinfo_line.py
  setup/account_invoice_supplierinfo_update_triple_discount/odoo/addons/account_invoice_supplierinfo_update_triple_discount
  setup/account_invoice_supplierinfo_update_triple_discount/setup.py
Labels: approved, bot is merging ⏳

#1610 [ADD] new module account_invoice_uom_column
  account_invoice_uom_column/README.rst
  account_invoice_uom_column/__init__.py
  account_invoice_uom_column/__manifest__.py
  account_invoice_uom_column/i18n/fr.po
  account_invoice_uom_column/readme/CONTRIBUTORS.rst
  account_invoice_uom_column/readme/DESCRIPTION.rst
  account_invoice_uom_column/reports/report_account_invoice.xml
  account_invoice_uom_column/static/description/1_without_module.png
  account_invoice_uom_column/static/description/2_with_module.png
  setup/account_invoice_uom_column/odoo/addons/account_invoice_uom_column
  setup/account_invoice_uom_column/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#1601 [12.0] ADD account_invoice_default_code_column
  account_invoice_default_code_column/README.rst
  account_invoice_default_code_column/__init__.py
  account_invoice_default_code_column/__manifest__.py
  account_invoice_default_code_column/i18n/fr.po
  account_invoice_default_code_column/models/__init__.py
  account_invoice_default_code_column/models/account_invoice_line.py
  account_invoice_default_code_column/readme/CONTRIBUTORS.rst
  account_invoice_default_code_column/readme/DESCRIPTION.rst
  account_invoice_default_code_column/reports/report_account_invoice.xml
  account_invoice_default_code_column/static/description/1_without_module.png
  account_invoice_default_code_column/static/description/2_with_module.png
  setup/account_invoice_default_code_column/odoo/addons/account_invoice_default_code_column
  setup/account_invoice_default_code_column/setup.py
Labels: approved, bot is merging ⏳

#1147 [ADD] new module account_invoice_update_check to prevent to write on invoices lines of non draft invoices
  account_invoice_update_check/README.rst
  account_invoice_update_check/__init__.py
  account_invoice_update_check/__manifest__.py
  account_invoice_update_check/i18n/fr.po
  account_invoice_update_check/models/__init__.py
  account_invoice_update_check/models/account_invoice_line.py
  account_invoice_update_check/readme/CONTRIBUTORS.rst
  account_invoice_update_check/readme/DESCRIPTION.rst
  account_invoice_update_check/tests/__init__.py
  account_invoice_update_check/tests/test_module.py
  setup/account_invoice_update_check/odoo/addons/account_invoice_update_check
  setup/account_invoice_update_check/setup.py
Labels: needs review, approved, ready to merge, bot is merging ⏳
