Repository OCA/account-invoicing, pull requests merged in 2024-09, with the labels that each got.

#1733 [17.0][MIG] account_invoice_block_payment: Migration to 17.0
  account_invoice_block_payment/README.md
  account_invoice_block_payment/README.rst
  account_invoice_block_payment/__init__.py
  account_invoice_block_payment/__manifest__.py
  account_invoice_block_payment/i18n/account_invoice_block_payment.pot
  account_invoice_block_payment/i18n/de.po
  account_invoice_block_payment/i18n/fr.po
  account_invoice_block_payment/models/__init__.py
  account_invoice_block_payment/models/account_move.py
  account_invoice_block_payment/pyproject.toml
  account_invoice_block_payment/readme/CONTRIBUTORS.md
  account_invoice_block_payment/readme/DESCRIPTION.md
  account_invoice_block_payment/readme/USAGE.md
  account_invoice_block_payment/static/description/icon.png
  account_invoice_block_payment/static/description/index.html
  account_invoice_block_payment/tests/__init__.py
  account_invoice_block_payment/tests/test_account_block_payment.py
  account_invoice_block_payment/views/account_move.xml
Labels: approved, ready to merge, bot is merging ⏳

#1778 [14.0][MIG] account_invoice_block_payment
  account_invoice_block_payment/README.md
  account_invoice_block_payment/README.rst
  account_invoice_block_payment/__init__.py
  account_invoice_block_payment/__manifest__.py
  account_invoice_block_payment/i18n/account_invoice_block_payment.pot
  account_invoice_block_payment/i18n/de.po
  account_invoice_block_payment/i18n/fr.po
  account_invoice_block_payment/models/__init__.py
  account_invoice_block_payment/models/account_move.py
  account_invoice_block_payment/readme/CONTRIBUTORS.rst
  account_invoice_block_payment/readme/DESCRIPTION.rst
  account_invoice_block_payment/readme/USAGE.rst
  account_invoice_block_payment/static/description/icon.png
  account_invoice_block_payment/static/description/index.html
  account_invoice_block_payment/tests/__init__.py
  account_invoice_block_payment/tests/test_account_block_payment.py
  account_invoice_block_payment/views/account_move.xml
  setup/account_invoice_block_payment/odoo/addons/account_invoice_block_payment
  setup/account_invoice_block_payment/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#1734 [16.0][MIG] account_invoice_block_payment: Migration to 16.0
  account_invoice_block_payment/README.md
  account_invoice_block_payment/README.rst
  account_invoice_block_payment/__init__.py
  account_invoice_block_payment/__manifest__.py
  account_invoice_block_payment/i18n/account_invoice_block_payment.pot
  account_invoice_block_payment/i18n/de.po
  account_invoice_block_payment/i18n/fr.po
  account_invoice_block_payment/models/__init__.py
  account_invoice_block_payment/models/account_move.py
  account_invoice_block_payment/readme/CONTRIBUTORS.rst
  account_invoice_block_payment/readme/DESCRIPTION.rst
  account_invoice_block_payment/readme/USAGE.rst
  account_invoice_block_payment/static/description/icon.png
  account_invoice_block_payment/static/description/index.html
  account_invoice_block_payment/tests/__init__.py
  account_invoice_block_payment/tests/test_account_block_payment.py
  account_invoice_block_payment/views/account_move.xml
  setup/account_invoice_block_payment/odoo/addons/account_invoice_block_payment
  setup/account_invoice_block_payment/setup.py
Labels: bot is merging ⏳

#1783 [16.0][MIG] account_invoice_warn_message: Migration to 16.0
  account_invoice_warn_message/README.rst
  account_invoice_warn_message/__init__.py
  account_invoice_warn_message/__manifest__.py
  account_invoice_warn_message/i18n/account_invoice_warn_message.pot
  account_invoice_warn_message/i18n/es.po
  account_invoice_warn_message/i18n/it.po
  account_invoice_warn_message/models/__init__.py
  account_invoice_warn_message/models/account_move.py
  account_invoice_warn_message/pyproject.toml
  account_invoice_warn_message/readme/CONTRIBUTORS.md
  account_invoice_warn_message/readme/DESCRIPTION.md
  account_invoice_warn_message/static/description/icon.png
  account_invoice_warn_message/static/description/index.html
  account_invoice_warn_message/tests/__init__.py
  account_invoice_warn_message/tests/test_account_invoice_warn_message.py
  account_invoice_warn_message/views/account_move_views.xml
  setup/account_invoice_warn_message/odoo/addons/account_invoice_warn_message
  setup/account_invoice_warn_message/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#1703 [16.0][FIX] account_move_tier_validation: Pass context to allow confirming moves with tier validation
  account_move_tier_validation/models/account_move.py
  account_move_tier_validation/tests/test_tier_validation.py
Labels: approved, ready to merge, bot is merging ⏳

#1791 [15.0][ADD] sale_order_whole_delivered_invoiceability: Add new module
  sale_order_whole_delivered_invoiceability/README.rst
  sale_order_whole_delivered_invoiceability/__init__.py
  sale_order_whole_delivered_invoiceability/__manifest__.py
  sale_order_whole_delivered_invoiceability/i18n/es.po
  sale_order_whole_delivered_invoiceability/i18n/sale_order_whole_delivered_invoiceability.pot
  sale_order_whole_delivered_invoiceability/models/__init__.py
  sale_order_whole_delivered_invoiceability/models/res_partner.py
  sale_order_whole_delivered_invoiceability/models/sale_order.py
  sale_order_whole_delivered_invoiceability/readme/CONFIGURE.rst
  sale_order_whole_delivered_invoiceability/readme/CONTRIBUTORS.rst
  sale_order_whole_delivered_invoiceability/readme/DESCRIPTION.rst
  sale_order_whole_delivered_invoiceability/readme/USAGE.rst
  sale_order_whole_delivered_invoiceability/static/description/icon.png
  sale_order_whole_delivered_invoiceability/static/description/index.html
  sale_order_whole_delivered_invoiceability/tests/__init__.py
  sale_order_whole_delivered_invoiceability/tests/test_sale_order_whole_delivered_invoiceability.py
  sale_order_whole_delivered_invoiceability/views/res_partner_view.xml
  sale_order_whole_delivered_invoiceability/views/sale_order_view.xml
  setup/sale_order_whole_delivered_invoiceability/odoo/addons/sale_order_whole_delivered_invoiceability
  setup/sale_order_whole_delivered_invoiceability/setup.py
Labels: bot is merging ⏳

#1792 [15.0][ADD] sale_order_type_whole_delivered_invoiceability: Add new module
  sale_order_type_whole_delivered_invoiceability/README.rst
  sale_order_type_whole_delivered_invoiceability/__init__.py
  sale_order_type_whole_delivered_invoiceability/__manifest__.py
  sale_order_type_whole_delivered_invoiceability/models/__init__.py
  sale_order_type_whole_delivered_invoiceability/models/sale_order.py
  sale_order_type_whole_delivered_invoiceability/models/sale_order_type.py
  sale_order_type_whole_delivered_invoiceability/readme/CONFIGURE.rst
  sale_order_type_whole_delivered_invoiceability/readme/CONTRIBUTORS.rst
  sale_order_type_whole_delivered_invoiceability/readme/DESCRIPTION.rst
  sale_order_type_whole_delivered_invoiceability/readme/USAGE.rst
  sale_order_type_whole_delivered_invoiceability/static/description/icon.png
  sale_order_type_whole_delivered_invoiceability/static/description/index.html
  sale_order_type_whole_delivered_invoiceability/tests/__init__.py
  sale_order_type_whole_delivered_invoiceability/tests/test_sale_order_type_whole_delivered_invoiceability.py
  sale_order_type_whole_delivered_invoiceability/views/sale_order_type_views.xml
  setup/sale_order_type_whole_delivered_invoiceability/odoo/addons/sale_order_type_whole_delivered_invoiceability
  setup/sale_order_type_whole_delivered_invoiceability/setup.py
Labels: bot is merging ⏳

#1777 [FIX] account_invoice_pricelist: Added copy attribute in the pricelist_id field
  account_invoice_pricelist/models/account_move.py
Labels: approved, ready to merge, bot is merging ⏳

#1368 [16.0][ADD] account_tax_one_vat_sale
  account_tax_one_vat_sale/README.rst
  account_tax_one_vat_sale/__init__.py
  account_tax_one_vat_sale/__manifest__.py
  account_tax_one_vat_sale/i18n/account_tax_one_vat_sale.pot
  account_tax_one_vat_sale/models/__init__.py
  account_tax_one_vat_sale/models/sale_order_line.py
  account_tax_one_vat_sale/readme/CONTRIBUTORS.rst
  account_tax_one_vat_sale/readme/DESCRIPTION.rst
  account_tax_one_vat_sale/static/description/index.html
  account_tax_one_vat_sale/tests/__init__.py
  account_tax_one_vat_sale/tests/test_account_tax_one_vat_sale.py
  setup/account_tax_one_vat_sale/odoo/addons/account_tax_one_vat_sale
  setup/account_tax_one_vat_sale/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#1796 [16.0][ADD] account_tax_one_vat_sale
  account_tax_one_vat_sale/README.rst
  account_tax_one_vat_sale/__init__.py
  account_tax_one_vat_sale/__manifest__.py
  account_tax_one_vat_sale/i18n/account_tax_one_vat_sale.pot
  account_tax_one_vat_sale/models/__init__.py
  account_tax_one_vat_sale/models/sale_order_line.py
  account_tax_one_vat_sale/readme/CONTRIBUTORS.rst
  account_tax_one_vat_sale/readme/DESCRIPTION.rst
  account_tax_one_vat_sale/static/description/index.html
  account_tax_one_vat_sale/tests/__init__.py
  account_tax_one_vat_sale/tests/test_account_tax_one_vat_sale.py
  setup/account_tax_one_vat_sale/odoo/addons/account_tax_one_vat_sale
  setup/account_tax_one_vat_sale/setup.py
Labels: bot is merging ⏳

#1801 [FIX] account_invoice_discount_display_amount: hide discount amount on invoice line
  account_invoice_discount_display_amount/README.rst
  account_invoice_discount_display_amount/readme/CONTRIBUTORS.rst
  account_invoice_discount_display_amount/readme/DESCRIPTION.rst
  account_invoice_discount_display_amount/readme/USAGE.rst
  account_invoice_discount_display_amount/static/description/index.html
  account_invoice_discount_display_amount/views/account_move_views.xml
Labels: needs review, approved, bot is merging ⏳

#1769 [16.0][MIG] sale_order_invoicing_queued: Migration to 16.0
  sale_order_invoicing_queued/README.rst
  sale_order_invoicing_queued/__init__.py
  sale_order_invoicing_queued/__manifest__.py
  sale_order_invoicing_queued/data/job_queue.xml
  sale_order_invoicing_queued/i18n/ca.po
  sale_order_invoicing_queued/i18n/es.po
  sale_order_invoicing_queued/i18n/it.po
  sale_order_invoicing_queued/i18n/sale_order_invoicing_queued.pot
  sale_order_invoicing_queued/i18n/zh_CN.po
  sale_order_invoicing_queued/models/__init__.py
  sale_order_invoicing_queued/models/sale_order.py
  sale_order_invoicing_queued/readme/CONFIGURE.rst
  sale_order_invoicing_queued/readme/CONTRIBUTORS.rst
  sale_order_invoicing_queued/readme/DESCRIPTION.rst
  sale_order_invoicing_queued/readme/HISTORY.rst
  sale_order_invoicing_queued/readme/INSTALL.rst
  sale_order_invoicing_queued/readme/USAGE.rst
  sale_order_invoicing_queued/static/description/icon.png
  sale_order_invoicing_queued/static/description/index.html
  sale_order_invoicing_queued/tests/__init__.py
  sale_order_invoicing_queued/tests/test_sale_order_invoicing_queued.py
  sale_order_invoicing_queued/views/queue_job_views.xml
  sale_order_invoicing_queued/views/sale_order_views.xml
  sale_order_invoicing_queued/wizards/__init__.py
  sale_order_invoicing_queued/wizards/sale_advance_payment_inv.py
  sale_order_invoicing_queued/wizards/sale_advance_payment_inv_views.xml
  setup/sale_order_invoicing_queued/odoo/addons/sale_order_invoicing_queued
  setup/sale_order_invoicing_queued/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#1780 [16.0][MIG] sale_invoicing_date_selection: Backport from 17.0
  sale_invoicing_date_selection/README.rst
  sale_invoicing_date_selection/__init__.py
  sale_invoicing_date_selection/__manifest__.py
  sale_invoicing_date_selection/i18n/es.po
  sale_invoicing_date_selection/i18n/sale_invoicing_date_selection.pot
  sale_invoicing_date_selection/models/__init__.py
  sale_invoicing_date_selection/models/sale_order.py
  sale_invoicing_date_selection/pyproject.toml
  sale_invoicing_date_selection/readme/CONTRIBUTORS.md
  sale_invoicing_date_selection/readme/DESCRIPTION.md
  sale_invoicing_date_selection/readme/USAGE.md
  sale_invoicing_date_selection/static/description/icon.png
  sale_invoicing_date_selection/static/description/index.html
  sale_invoicing_date_selection/tests/__init__.py
  sale_invoicing_date_selection/tests/test_sale_invoicing_date_selection.py
  sale_invoicing_date_selection/wizard/__init__.py
  sale_invoicing_date_selection/wizard/sale_advance_payment_inv.py
  sale_invoicing_date_selection/wizard/sale_make_invoice_advance_views.xml
  setup/sale_invoicing_date_selection/odoo/addons/sale_invoicing_date_selection
  setup/sale_invoicing_date_selection/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#1595 [15.0][MIG] account_move_substate
  account_move_substate/README.rst
  account_move_substate/__init__.py
  account_move_substate/__manifest__.py
  account_move_substate/data/account_move_substate_data.xml
  account_move_substate/data/account_move_substate_mail_template_data.xml
  account_move_substate/demo/account_move_substate_demo.xml
  account_move_substate/models/__init__.py
  account_move_substate/models/account_move.py
  account_move_substate/readme/CONTRIBUTORS.rst
  account_move_substate/readme/DESCRIPTION.rst
  account_move_substate/readme/USAGE.rst
  account_move_substate/static/description/icon.png
  account_move_substate/static/description/index.html
  account_move_substate/tests/__init__.py
  account_move_substate/tests/test_account_move_substate.py
  account_move_substate/views/account_move_views.xml
  setup/account_move_substate/odoo/addons/account_move_substate
  setup/account_move_substate/setup.py
Labels: approved, ready to merge, bot is merging ⏳
