Repository OCA/account-invoicing, pull requests merged in 2025-07, with the labels that each got.

#1496 [15.0][MIG] account_move_original_partner: Migration to 15.0
  account_move_original_partner/README.rst
  account_move_original_partner/__init__.py
  account_move_original_partner/__manifest__.py
  account_move_original_partner/hooks.py
  account_move_original_partner/i18n/account_move_original_partner.pot
  account_move_original_partner/i18n/ca.po
  account_move_original_partner/models/__init__.py
  account_move_original_partner/models/account_move.py
  account_move_original_partner/readme/CONTRIBUTORS.rst
  account_move_original_partner/readme/CREDITS.rst
  account_move_original_partner/readme/DESCRIPTION.rst
  account_move_original_partner/static/description/icon.png
  account_move_original_partner/static/description/index.html
  account_move_original_partner/views/account_move.xml
  setup/account_move_original_partner/odoo/addons/account_move_original_partner
  setup/account_move_original_partner/setup.py
Labels: approved, ready to merge, bot is merging ⏳, stale

#1311 [14.0][MIG] account_invoice_origin_link & account_invoice_sale_origin_link
  account_invoice_origin_link/README.rst
  account_invoice_origin_link/__init__.py
  account_invoice_origin_link/__manifest__.py
  account_invoice_origin_link/i18n/account_invoice_origin_link.pot
  account_invoice_origin_link/models/__init__.py
  account_invoice_origin_link/models/account_move.py
  account_invoice_origin_link/readme/CONTRIBUTORS.rst
  account_invoice_origin_link/readme/DESCRIPTION.rst
  account_invoice_origin_link/static/description/icon.png
  account_invoice_origin_link/static/description/index.html
  account_invoice_origin_link/views/account_move_views.xml
  account_invoice_sale_origin_link/README.rst
  account_invoice_sale_origin_link/__init__.py
  account_invoice_sale_origin_link/__manifest__.py
  account_invoice_sale_origin_link/i18n/account_invoice_sale_origin_link.pot
  account_invoice_sale_origin_link/models/__init__.py
  account_invoice_sale_origin_link/models/account_move.py
  account_invoice_sale_origin_link/readme/CONTRIBUTORS.rst
  account_invoice_sale_origin_link/readme/DESCRIPTION.rst
  account_invoice_sale_origin_link/static/description/icon.png
  account_invoice_sale_origin_link/static/description/index.html
  account_invoice_sale_origin_link/tests/__init__.py
  account_invoice_sale_origin_link/tests/test_account_invoice_sale_origin_link.py
  setup/account_invoice_origin_link/odoo/addons/account_invoice_origin_link
  setup/account_invoice_origin_link/setup.py
  setup/account_invoice_sale_origin_link/odoo/addons/account_invoice_sale_origin_link
  setup/account_invoice_sale_origin_link/setup.py
Labels: bot is merging ⏳, no stale

#1732 [FIX] 14.0 account_invoice_fixed_discount: fixed using discount_fixed on free account move line
  account_invoice_fixed_discount/models/account_move.py
  account_invoice_fixed_discount/tests/test_account_fixed_discount.py
Labels: approved, ready to merge, bot is merging ⏳

#1764 [MIG] backport account_invoice_warn_message from v. 15.0 to v. 14.0
  account_invoice_warn_message/README.rst
  account_invoice_warn_message/__init__.py
  account_invoice_warn_message/__manifest__.py
  account_invoice_warn_message/i18n/account_invoice_warn_message.pot
  account_invoice_warn_message/i18n/es.po
  account_invoice_warn_message/models/__init__.py
  account_invoice_warn_message/models/account_move.py
  account_invoice_warn_message/readme/CONTRIBUTORS.rst
  account_invoice_warn_message/readme/DESCRIPTION.rst
  account_invoice_warn_message/static/description/icon.png
  account_invoice_warn_message/static/description/index.html
  account_invoice_warn_message/tests/__init__.py
  account_invoice_warn_message/tests/test_account_invoice_warn_message.py
  account_invoice_warn_message/views/account_move_views.xml
  setup/account_invoice_warn_message/odoo/addons/account_invoice_warn_message
  setup/account_invoice_warn_message/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#2056 [18][FIX] account_invoice_show_currency_rate: ensure compute currency rate
  account_invoice_show_currency_rate/models/account_move.py
Labels: bot is merging ⏳

#2000 [FIX] account_invoice_pricelist: add new calculate discount condition
  account_invoice_pricelist/models/account_move.py
  account_invoice_pricelist/tests/test_account_move_pricelist.py
Labels: approved, bot is merging ⏳

#1973 [18.0][MIG] sale_credit_note_reversal: Migration to 18.0
  sale_credit_note_reversal/README.rst
  sale_credit_note_reversal/__init__.py
  sale_credit_note_reversal/__manifest__.py
  sale_credit_note_reversal/i18n/it.po
  sale_credit_note_reversal/i18n/sale_credit_note_reversal.pot
  sale_credit_note_reversal/models/__init__.py
  sale_credit_note_reversal/models/account_move.py
  sale_credit_note_reversal/pyproject.toml
  sale_credit_note_reversal/readme/CONTRIBUTORS.md
  sale_credit_note_reversal/readme/DESCRIPTION.md
  sale_credit_note_reversal/readme/ROADMAP.md
  sale_credit_note_reversal/static/description/icon.png
  sale_credit_note_reversal/static/description/index.html
  sale_credit_note_reversal/tests/__init__.py
  sale_credit_note_reversal/tests/test_sale_credit_note_reversal.py
  sale_credit_note_reversal/views/account_move_views.xml
  sale_credit_note_reversal/wizard/account_move_reversal_views.xml
Labels: approved, ready to merge, bot is merging ⏳

#1942 [18.0][MIG] stock_picking_invoicing: Migration to 18.0
  stock_picking_invoicing/README.rst
  stock_picking_invoicing/__init__.py
  stock_picking_invoicing/__manifest__.py
  stock_picking_invoicing/demo/stock_picking_demo.xml
  stock_picking_invoicing/i18n/ca.po
  stock_picking_invoicing/i18n/de.po
  stock_picking_invoicing/i18n/es.po
  stock_picking_invoicing/i18n/fr.po
  stock_picking_invoicing/i18n/hr.po
  stock_picking_invoicing/i18n/it.po
  stock_picking_invoicing/i18n/pt_BR.po
  stock_picking_invoicing/i18n/sl.po
  stock_picking_invoicing/i18n/stock_picking_invoicing.pot
  stock_picking_invoicing/models/__init__.py
  stock_picking_invoicing/models/account_move.py
  stock_picking_invoicing/models/stock_invoice_state_mixin.py
  stock_picking_invoicing/models/stock_move.py
  stock_picking_invoicing/models/stock_picking.py
  stock_picking_invoicing/models/stock_picking_type.py
  stock_picking_invoicing/models/stock_rule.py
  stock_picking_invoicing/pyproject.toml
  stock_picking_invoicing/readme/CONTRIBUTORS.md
  stock_picking_invoicing/readme/DESCRIPTION.md
  stock_picking_invoicing/readme/HISTORY.md
  stock_picking_invoicing/readme/INSTALL.md
  stock_picking_invoicing/readme/USAGE.md
  stock_picking_invoicing/security/ir.model.access.csv
  stock_picking_invoicing/static/description/icon.png
  stock_picking_invoicing/static/description/index.html
  stock_picking_invoicing/tests/__init__.py
  stock_picking_invoicing/tests/common.py
  stock_picking_invoicing/tests/test_picking_invoicing.py
  stock_picking_invoicing/tests/test_stock_rule.py
  stock_picking_invoicing/views/stock_move_views.xml
  stock_picking_invoicing/views/stock_picking_type_views.xml
  stock_picking_invoicing/views/stock_picking_views.xml
  stock_picking_invoicing/wizards/__init__.py
  stock_picking_invoicing/wizards/stock_invoice_onshipping.py
  stock_picking_invoicing/wizards/stock_invoice_onshipping_view.xml
  stock_picking_invoicing/wizards/stock_return_picking.py
  stock_picking_invoicing/wizards/stock_return_picking_view.xml
Labels: approved, bot is merging ⏳

#2061 [16.0][Fix] account_billing test_create_billing_from_selected_invoices
  account_billing/tests/test_account_billing.py
Labels: approved, ready to merge, bot is merging ⏳
