Repository OCA/account-invoicing, pull requests merged in 2025-04, with the labels that each got.

#1921 [18.0][MIG] account_move_tier_validation:Migration to 18
  account_move_cancel_confirm/model/account_move.py
  account_move_cancel_confirm/tests/test_account_move_cancel_confirm.py
  account_move_tier_validation/README.rst
  account_move_tier_validation/__init__.py
  account_move_tier_validation/__manifest__.py
  account_move_tier_validation/i18n/account_move_tier_validation.pot
  account_move_tier_validation/i18n/ca.po
  account_move_tier_validation/i18n/es.po
  account_move_tier_validation/i18n/es_PA.po
  account_move_tier_validation/i18n/fr.po
  account_move_tier_validation/i18n/hr.po
  account_move_tier_validation/i18n/it.po
  account_move_tier_validation/i18n/sv.po
  account_move_tier_validation/i18n/zh_CN.po
  account_move_tier_validation/models/__init__.py
  account_move_tier_validation/models/account_move.py
  account_move_tier_validation/models/tier_definition.py
  account_move_tier_validation/pyproject.toml
  account_move_tier_validation/readme/CONFIGURE.md
  account_move_tier_validation/readme/CONTRIBUTORS.md
  account_move_tier_validation/readme/DESCRIPTION.md
  account_move_tier_validation/readme/INSTALL.md
  account_move_tier_validation/readme/USAGE.md
  account_move_tier_validation/static/description/icon.png
  account_move_tier_validation/static/description/index.html
  account_move_tier_validation/tests/__init__.py
  account_move_tier_validation/tests/test_tier_validation.py
  account_move_tier_validation/views/account_move_view.xml
Labels: needs fixing, approved, bot is merging ⏳

#1978 [18.0][MIG] account_invoice_date_due: Migration to 18.0
  account_invoice_date_due/README.rst
  account_invoice_date_due/__init__.py
  account_invoice_date_due/__manifest__.py
  account_invoice_date_due/i18n/account_invoice_date_due.pot
  account_invoice_date_due/i18n/ca.po
  account_invoice_date_due/i18n/de.po
  account_invoice_date_due/i18n/es.po
  account_invoice_date_due/i18n/fr.po
  account_invoice_date_due/i18n/fr_FR.po
  account_invoice_date_due/i18n/it.po
  account_invoice_date_due/models/__init__.py
  account_invoice_date_due/models/account_move.py
  account_invoice_date_due/pyproject.toml
  account_invoice_date_due/readme/CONFIGURE.md
  account_invoice_date_due/readme/CONTRIBUTORS.md
  account_invoice_date_due/readme/DESCRIPTION.md
  account_invoice_date_due/readme/USAGE.md
  account_invoice_date_due/security/security.xml
  account_invoice_date_due/static/description/icon.png
  account_invoice_date_due/static/description/index.html
  account_invoice_date_due/tests/__init__.py
  account_invoice_date_due/tests/test_account_invoice_date_due.py
  account_invoice_date_due/views/account_move_date_due.xml
Labels: approved, bot is merging ⏳

#1980 [18.0][MIG] sale_order_invoicing_qty_percentage: Migration to 18.0
  sale_order_invoicing_qty_percentage/README.rst
  sale_order_invoicing_qty_percentage/__init__.py
  sale_order_invoicing_qty_percentage/__manifest__.py
  sale_order_invoicing_qty_percentage/i18n/es.po
  sale_order_invoicing_qty_percentage/i18n/it.po
  sale_order_invoicing_qty_percentage/i18n/sale_order_invoicing_qty_percentage.pot
  sale_order_invoicing_qty_percentage/models/__init__.py
  sale_order_invoicing_qty_percentage/models/sale_order.py
  sale_order_invoicing_qty_percentage/pyproject.toml
  sale_order_invoicing_qty_percentage/readme/CONTRIBUTORS.md
  sale_order_invoicing_qty_percentage/readme/DESCRIPTION.md
  sale_order_invoicing_qty_percentage/readme/ROADMAP.md
  sale_order_invoicing_qty_percentage/readme/USAGE.md
  sale_order_invoicing_qty_percentage/static/description/icon.png
  sale_order_invoicing_qty_percentage/static/description/index.html
  sale_order_invoicing_qty_percentage/tests/__init__.py
  sale_order_invoicing_qty_percentage/tests/test_sale_order_invoicing_qty_percentage.py
  sale_order_invoicing_qty_percentage/wizards/__init__.py
  sale_order_invoicing_qty_percentage/wizards/sale_advance_payment_inv.py
  sale_order_invoicing_qty_percentage/wizards/sale_advance_payment_inv_views.xml
Labels: approved, ready to merge, bot is merging ⏳

#1948 [14.0][ADD] account_invoice_purchase_picking_selection: New module to auto-…
  account_invoice_purchase_picking_selection/README.rst
  account_invoice_purchase_picking_selection/__init__.py
  account_invoice_purchase_picking_selection/__manifest__.py
  account_invoice_purchase_picking_selection/i18n/account_invoice_purchase_picking_selection.pot
  account_invoice_purchase_picking_selection/i18n/es.po
  account_invoice_purchase_picking_selection/models/__init__.py
  account_invoice_purchase_picking_selection/models/account_move.py
  account_invoice_purchase_picking_selection/models/stock_move.py
  account_invoice_purchase_picking_selection/models/stock_picking.py
  account_invoice_purchase_picking_selection/readme/CONTRIBUTORS.rst
  account_invoice_purchase_picking_selection/readme/DESCRIPTION.rst
  account_invoice_purchase_picking_selection/readme/USAGE.rst
  account_invoice_purchase_picking_selection/static/description/index.html
  account_invoice_purchase_picking_selection/tests/__init__.py
  account_invoice_purchase_picking_selection/tests/test_invoice_picking_selection.py
  account_invoice_purchase_picking_selection/views/account_move_views.xml
  setup/account_invoice_purchase_picking_selection/odoo/addons/account_invoice_purchase_picking_selection
  setup/account_invoice_purchase_picking_selection/setup.py
Labels: approved, ready to merge, bot is merging ⏳
