Repository OCA/account-invoicing, pull requests merged in 2025-06, with the labels that each got.

#1854 [17.0][mig]stock_account_move_reset_to_draft
  stock_account_move_reset_to_draft/README.rst
  stock_account_move_reset_to_draft/__init__.py
  stock_account_move_reset_to_draft/__manifest__.py
  stock_account_move_reset_to_draft/i18n/es.po
  stock_account_move_reset_to_draft/i18n/it.po
  stock_account_move_reset_to_draft/i18n/stock_account_move_reset_to_draft.pot
  stock_account_move_reset_to_draft/models/__init__.py
  stock_account_move_reset_to_draft/models/account_move.py
  stock_account_move_reset_to_draft/pyproject.toml
  stock_account_move_reset_to_draft/readme/CONTEXT.md
  stock_account_move_reset_to_draft/readme/CONTRIBUTORS.md
  stock_account_move_reset_to_draft/readme/DESCRIPTION.md
  stock_account_move_reset_to_draft/readme/USAGE.md
  stock_account_move_reset_to_draft/static/description/icon.png
  stock_account_move_reset_to_draft/static/description/index.html
  stock_account_move_reset_to_draft/tests/__init__.py
  stock_account_move_reset_to_draft/tests/test_stock_account_move_reset_to_draft.py
Labels: approved, ready to merge, bot is merging ⏳

#2018 [16.0][ADD] account_invoice_partner_reference
  account_invoice_partner_reference/README.rst
  account_invoice_partner_reference/__init__.py
  account_invoice_partner_reference/__manifest__.py
  account_invoice_partner_reference/models/__init__.py
  account_invoice_partner_reference/models/account_move.py
  account_invoice_partner_reference/readme/CONTRIBUTORS.rst
  account_invoice_partner_reference/readme/DESCRIPTION.rst
  account_invoice_partner_reference/readme/USAGE.rst
  account_invoice_partner_reference/static/description/icon.png
  account_invoice_partner_reference/static/description/index.html
  account_invoice_partner_reference/static/img/readme/partner_reference.png
  account_invoice_partner_reference/static/img/readme/partner_reference_invoice_tree.png
  account_invoice_partner_reference/views/account_move_views.xml
  setup/account_invoice_partner_reference/odoo/addons/account_invoice_partner_reference
  setup/account_invoice_partner_reference/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#2017 [16.0] [MIG] account_invoice_google_document_ai: Migration to 16.0
  account_invoice_google_document_ai/README.rst
  account_invoice_google_document_ai/__init__.py
  account_invoice_google_document_ai/__manifest__.py
  account_invoice_google_document_ai/i18n/account_invoice_google_document_ai.pot
  account_invoice_google_document_ai/i18n/it.po
  account_invoice_google_document_ai/models/__init__.py
  account_invoice_google_document_ai/models/account_move.py
  account_invoice_google_document_ai/models/account_move_google_document_ai.py
  account_invoice_google_document_ai/models/res_company.py
  account_invoice_google_document_ai/models/res_config_settings.py
  account_invoice_google_document_ai/readme/CONFIGURE.rst
  account_invoice_google_document_ai/readme/CONTRIBUTORS.rst
  account_invoice_google_document_ai/readme/DESCRIPTION.rst
  account_invoice_google_document_ai/static/description/icon.png
  account_invoice_google_document_ai/static/description/index.html
  account_invoice_google_document_ai/tests/__init__.py
  account_invoice_google_document_ai/tests/result.json
  account_invoice_google_document_ai/tests/test_google_document_ai.py
  account_invoice_google_document_ai/views/account_move.xml
  account_invoice_google_document_ai/views/res_config_settings.xml
  requirements.txt
  setup/account_invoice_google_document_ai/odoo/addons/account_invoice_google_document_ai
  setup/account_invoice_google_document_ai/setup.py
Labels: approved, bot is merging ⏳

#1832 [18.0][MIG] account_invoice_section_sale_order: Migration to 18.0
  account_invoice_section_sale_order/README.rst
  account_invoice_section_sale_order/__init__.py
  account_invoice_section_sale_order/__manifest__.py
  account_invoice_section_sale_order/i18n/account_invoice_section_sale_order.pot
  account_invoice_section_sale_order/i18n/es.po
  account_invoice_section_sale_order/i18n/it.po
  account_invoice_section_sale_order/models/__init__.py
  account_invoice_section_sale_order/models/account_move.py
  account_invoice_section_sale_order/models/res_company.py
  account_invoice_section_sale_order/models/res_config_settings.py
  account_invoice_section_sale_order/models/res_partner.py
  account_invoice_section_sale_order/models/sale_order.py
  account_invoice_section_sale_order/pyproject.toml
  account_invoice_section_sale_order/readme/CONFIGURATION.rst
  account_invoice_section_sale_order/readme/CONTRIBUTORS.md
  account_invoice_section_sale_order/readme/CREDITS.md
  account_invoice_section_sale_order/readme/DESCRIPTION.md
  account_invoice_section_sale_order/security/res_groups.xml
  account_invoice_section_sale_order/static/description/icon.png
  account_invoice_section_sale_order/static/description/index.html
  account_invoice_section_sale_order/tests/__init__.py
  account_invoice_section_sale_order/tests/common.py
  account_invoice_section_sale_order/tests/test_access_rights.py
  account_invoice_section_sale_order/tests/test_invoice_group_by_sale_order.py
  account_invoice_section_sale_order/views/res_config_settings.xml
  account_invoice_section_sale_order/views/res_partner.xml
Labels: approved, ready to merge, bot is merging ⏳

#2014 [16.0][ADD] partner_last_invoice_date
  partner_last_invoice_date/README.rst
  partner_last_invoice_date/__init__.py
  partner_last_invoice_date/__manifest__.py
  partner_last_invoice_date/hooks.py
  partner_last_invoice_date/i18n/es.po
  partner_last_invoice_date/i18n/partner_last_invoice_date.pot
  partner_last_invoice_date/models/__init__.py
  partner_last_invoice_date/models/res_partner.py
  partner_last_invoice_date/readme/CONTRIBUTORS.rst
  partner_last_invoice_date/readme/DESCRIPTION.rst
  partner_last_invoice_date/static/description/index.html
  partner_last_invoice_date/tests/__init__.py
  partner_last_invoice_date/tests/test_partner_last_invoice_date.py
  partner_last_invoice_date/views/res_partner_views.xml
  setup/partner_last_invoice_date/odoo/addons/partner_last_invoice_date
  setup/partner_last_invoice_date/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#1822 [16.0][IMP] account_invoice_discount_display_amount: Show undiscounted amount in report
  account_invoice_discount_display_amount/report/report_invoice.xml
  account_invoice_discount_display_amount/tests/common.py
  account_invoice_discount_display_amount/tests/test_account_move.py
Labels: approved, ready to merge, bot is merging ⏳

#1996 [18.0] [MIG] portal_account_personal_data_only: Migration to 18.0
  portal_account_personal_data_only/README.rst
  portal_account_personal_data_only/__init__.py
  portal_account_personal_data_only/__manifest__.py
  portal_account_personal_data_only/hooks.py
  portal_account_personal_data_only/i18n/es.po
  portal_account_personal_data_only/i18n/it.po
  portal_account_personal_data_only/i18n/portal_account_personal_data_only.pot
  portal_account_personal_data_only/pyproject.toml
  portal_account_personal_data_only/readme/CONTRIBUTORS.md
  portal_account_personal_data_only/readme/DESCRIPTION.md
  portal_account_personal_data_only/readme/USAGE.md
  portal_account_personal_data_only/security/security.xml
  portal_account_personal_data_only/static/description/icon.png
  portal_account_personal_data_only/static/description/index.html
  portal_account_personal_data_only/tests/__init__.py
  portal_account_personal_data_only/tests/test_partner_access.py
Labels: needs review, approved, migration, bot is merging ⏳
