Repository OCA/account-invoicing, pull requests merged in 2025-02, with the labels that each got.

#1687 [17.0][MIG] account_global_discount: Migration to 17.0
  account_global_discount/README.rst
  account_global_discount/__init__.py
  account_global_discount/__manifest__.py
  account_global_discount/hooks.py
  account_global_discount/i18n/.empty
  account_global_discount/i18n/account_global_discount.pot
  account_global_discount/i18n/es.po
  account_global_discount/i18n/it.po
  account_global_discount/i18n/nl_NL.po
  account_global_discount/i18n/pt.po
  account_global_discount/models/__init__.py
  account_global_discount/models/account_move.py
  account_global_discount/models/global_discount.py
  account_global_discount/pyproject.toml
  account_global_discount/readme/CONFIGURE.md
  account_global_discount/readme/CONTRIBUTORS.md
  account_global_discount/readme/DESCRIPTION.md
  account_global_discount/readme/ROADMAP.md
  account_global_discount/readme/USAGE.md
  account_global_discount/report/__init__.py
  account_global_discount/report/account_invoice_report.py
  account_global_discount/security/ir.model.access.csv
  account_global_discount/security/security.xml
  account_global_discount/static/description/icon.png
  account_global_discount/static/description/icon.svg
  account_global_discount/static/description/index.html
  account_global_discount/tests/__init__.py
  account_global_discount/tests/test_global_discount.py
  account_global_discount/views/account_invoice_views.xml
  account_global_discount/views/global_discount_views.xml
  account_global_discount/views/report_account_invoice.xml
Labels: approved, ready to merge, bot is merging ⏳

#1901 [16.0][FIX] account_invoice_show_currency_rate: do not round currency rate
  account_invoice_show_currency_rate/models/account_move.py
Labels: approved, bot is merging ⏳

#1857 [16.0][MIG][sale_stock_picking_invoicing]
  sale_stock_picking_invoicing/README.rst
  sale_stock_picking_invoicing/__init__.py
  sale_stock_picking_invoicing/__manifest__.py
  sale_stock_picking_invoicing/demo/sale_order_demo.xml
  sale_stock_picking_invoicing/i18n/sale_stock_picking_invoicing.pot
  sale_stock_picking_invoicing/models/__init__.py
  sale_stock_picking_invoicing/models/res_company.py
  sale_stock_picking_invoicing/models/res_config_settings.py
  sale_stock_picking_invoicing/models/sale_order.py
  sale_stock_picking_invoicing/models/sale_order_line.py
  sale_stock_picking_invoicing/models/stock_move.py
  sale_stock_picking_invoicing/models/stock_picking.py
  sale_stock_picking_invoicing/readme/CONFIGURE.rst
  sale_stock_picking_invoicing/readme/CONTRIBUTORS.rst
  sale_stock_picking_invoicing/readme/CREDITS.rst
  sale_stock_picking_invoicing/readme/DESCRIPTION.rst
  sale_stock_picking_invoicing/readme/HISTORY.rst
  sale_stock_picking_invoicing/readme/INSTALL.rst
  sale_stock_picking_invoicing/readme/ROADMAP.rst
  sale_stock_picking_invoicing/readme/USAGE.rst
  sale_stock_picking_invoicing/static/description/icon.png
  sale_stock_picking_invoicing/static/description/index.html
  sale_stock_picking_invoicing/tests/__init__.py
  sale_stock_picking_invoicing/tests/test_sale_stock.py
  sale_stock_picking_invoicing/views/res_company_view.xml
  sale_stock_picking_invoicing/views/res_config_settings_view.xml
  sale_stock_picking_invoicing/wizards/__init__.py
  sale_stock_picking_invoicing/wizards/stock_invoice_onshipping.py
  sale_stock_picking_invoicing/wizards/stock_invoice_onshipping_view.xml
  setup/sale_stock_picking_invoicing/odoo/addons/sale_stock_picking_invoicing
  setup/sale_stock_picking_invoicing/setup.py
Labels: bot is merging ⏳

#1907 [FIX] account_invoice_tax_note: Fix test
  account_invoice_tax_note/tests/test_account_invoice.py
Labels: approved, bot is merging ⏳

#1906 [14.0][REF] sale_stock_picking_invoicing: Allow other modules inform Fields that should not be used from Sale 'prepare' methods
  sale_stock_picking_invoicing/wizards/stock_invoice_onshipping.py
Labels: approved, bot is merging ⏳

#1644 [16.0][MIG] account_billing
  account_billing/README.rst
  account_billing/__init__.py
  account_billing/__manifest__.py
  account_billing/data/account_billing_sequence.xml
  account_billing/data/server_action.xml
  account_billing/i18n/account_billing.pot
  account_billing/i18n/es.po
  account_billing/i18n/fr_FR.po
  account_billing/i18n/nl_NL.po
  account_billing/i18n/zh_CN.po
  account_billing/models/__init__.py
  account_billing/models/account_billing.py
  account_billing/models/account_move.py
  account_billing/readme/CONTRIBUTORS.rst
  account_billing/readme/DESCRIPTION.rst
  account_billing/readme/USAGE.rst
  account_billing/report/report.xml
  account_billing/report/report_billing.xml
  account_billing/security/ir.model.access.csv
  account_billing/static/description/icon.png
  account_billing/static/description/index.html
  account_billing/static/src/img/icon.png
  account_billing/tests/__init__.py
  account_billing/tests/test_account_billing.py
  account_billing/views/account_billing_views.xml
  account_billing/views/account_move_views.xml
  setup/account_billing/odoo/addons/account_billing
  setup/account_billing/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#1908 [17.0][ADD] account_invoice_subscription_per_contact: New module
  account_invoice_subscription_per_contact/README.rst
  account_invoice_subscription_per_contact/__init__.py
  account_invoice_subscription_per_contact/__manifest__.py
  account_invoice_subscription_per_contact/data/mail_message_subtype_data.xml
  account_invoice_subscription_per_contact/i18n/account_invoice_subscription_per_contact.pot
  account_invoice_subscription_per_contact/i18n/es.po
  account_invoice_subscription_per_contact/models/__init__.py
  account_invoice_subscription_per_contact/models/account_move.py
  account_invoice_subscription_per_contact/pyproject.toml
  account_invoice_subscription_per_contact/readme/CONTRIBUTORS.md
  account_invoice_subscription_per_contact/readme/DESCRIPTION.md
  account_invoice_subscription_per_contact/readme/USAGE.md
  account_invoice_subscription_per_contact/static/description/icon.png
  account_invoice_subscription_per_contact/static/description/index.html
  account_invoice_subscription_per_contact/tests/__init__.py
  account_invoice_subscription_per_contact/tests/test_account_invoice_subscription_per_contact.py
Labels: approved, ready to merge, bot is merging ⏳

#1873 [18.0][MIG] account_invoice_show_currency_rate
  account_invoice_show_currency_rate/README.rst
  account_invoice_show_currency_rate/__init__.py
  account_invoice_show_currency_rate/__manifest__.py
  account_invoice_show_currency_rate/i18n/account_invoice_show_currency_rate.pot
  account_invoice_show_currency_rate/i18n/es.po
  account_invoice_show_currency_rate/i18n/it.po
  account_invoice_show_currency_rate/models/__init__.py
  account_invoice_show_currency_rate/models/account_move.py
  account_invoice_show_currency_rate/pyproject.toml
  account_invoice_show_currency_rate/readme/CONFIGURE.md
  account_invoice_show_currency_rate/readme/CONTRIBUTORS.md
  account_invoice_show_currency_rate/readme/DESCRIPTION.md
  account_invoice_show_currency_rate/readme/USAGE.md
  account_invoice_show_currency_rate/static/description/icon.png
  account_invoice_show_currency_rate/static/description/index.html
  account_invoice_show_currency_rate/tests/__init__.py
  account_invoice_show_currency_rate/tests/test_account_move.py
  account_invoice_show_currency_rate/views/account_move_view.xml
Labels: approved, ready to merge, bot is merging ⏳

#1781 [16.0][MIG] account_invoice_customer_no_autofollow
  account_invoice_customer_no_autofollow/README.rst
  account_invoice_customer_no_autofollow/__init__.py
  account_invoice_customer_no_autofollow/__manifest__.py
  account_invoice_customer_no_autofollow/i18n/account_invoice_customer_no_autofollow.pot
  account_invoice_customer_no_autofollow/models/__init__.py
  account_invoice_customer_no_autofollow/models/account_move.py
  account_invoice_customer_no_autofollow/models/res_config_settings.py
  account_invoice_customer_no_autofollow/readme/CONFIGURE.rst
  account_invoice_customer_no_autofollow/readme/CONTRIBUTORS.rst
  account_invoice_customer_no_autofollow/readme/DESCRIPTION.rst
  account_invoice_customer_no_autofollow/static/description/icon.png
  account_invoice_customer_no_autofollow/static/description/index.html
  account_invoice_customer_no_autofollow/tests/__init__.py
  account_invoice_customer_no_autofollow/tests/common.py
  account_invoice_customer_no_autofollow/tests/test_no_autofollow_disabled.py
  account_invoice_customer_no_autofollow/tests/test_no_autofollow_enabled.py
  account_invoice_customer_no_autofollow/views/res_config_settings.xml
  setup/account_invoice_customer_no_autofollow/odoo/addons/account_invoice_customer_no_autofollow
  setup/account_invoice_customer_no_autofollow/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#1840 [16.0] [REF] account_invoice_triple_discount Consolidate discount in std field (Follow-up of #1638)
  .copier-answers.yml
  .github/workflows/test.yml
  account_global_discount/__manifest__.py
  account_global_discount/static/description/index.html
  account_global_discount/tests/test_global_discount.py
  account_invoice_fixed_discount/__manifest__.py
  account_invoice_fixed_discount/static/description/index.html
  account_invoice_supplierinfo_update_discount/__manifest__.py
  account_invoice_supplierinfo_update_discount/models/account_move_line.py
  account_invoice_supplierinfo_update_discount/static/description/index.html
  account_invoice_triple_discount/README.rst
  account_invoice_triple_discount/__init__.py
  account_invoice_triple_discount/__manifest__.py
  account_invoice_triple_discount/hooks.py
  account_invoice_triple_discount/migrations/16.0.2.0.0/pre-migrate.py
  account_invoice_triple_discount/models/__init__.py
  account_invoice_triple_discount/models/account_move.py
  account_invoice_triple_discount/models/account_move_line.py
  account_invoice_triple_discount/readme/CONTRIBUTORS.rst
  account_invoice_triple_discount/report/invoice.xml
  account_invoice_triple_discount/static/description/index.html
  account_invoice_triple_discount/tests/test_invoice_triple_discount.py
  account_invoice_triple_discount/views/account_move.xml
Labels: approved, bot is merging ⏳

#1919 [16.0][REF] sale_stock_picking_invoicing: Allow other modules inform Fields that should not be used from Sale 'prepare' methods, FWD 1906
  sale_stock_picking_invoicing/wizards/stock_invoice_onshipping.py
Labels: approved

#1922 [18.0][MIG] sale_order_invoicing_grouping_criteria: Migration to version 18.0
  sale_order_invoicing_grouping_criteria/README.rst
  sale_order_invoicing_grouping_criteria/__init__.py
  sale_order_invoicing_grouping_criteria/__manifest__.py
  sale_order_invoicing_grouping_criteria/i18n/ca.po
  sale_order_invoicing_grouping_criteria/i18n/de.po
  sale_order_invoicing_grouping_criteria/i18n/es.po
  sale_order_invoicing_grouping_criteria/i18n/fr.po
  sale_order_invoicing_grouping_criteria/i18n/it.po
  sale_order_invoicing_grouping_criteria/i18n/sale_order_invoicing_grouping_criteria.pot
  sale_order_invoicing_grouping_criteria/models/__init__.py
  sale_order_invoicing_grouping_criteria/models/res_company.py
  sale_order_invoicing_grouping_criteria/models/res_config_settings.py
  sale_order_invoicing_grouping_criteria/models/res_partner.py
  sale_order_invoicing_grouping_criteria/models/sale_invoicing_grouping_criteria.py
  sale_order_invoicing_grouping_criteria/models/sale_order.py
  sale_order_invoicing_grouping_criteria/pyproject.toml
  sale_order_invoicing_grouping_criteria/readme/CONFIGURE.md
  sale_order_invoicing_grouping_criteria/readme/CONTRIBUTORS.md
  sale_order_invoicing_grouping_criteria/readme/DESCRIPTION.md
  sale_order_invoicing_grouping_criteria/readme/USAGE.md
  sale_order_invoicing_grouping_criteria/security/ir.model.access.csv
  sale_order_invoicing_grouping_criteria/static/description/icon.png
  sale_order_invoicing_grouping_criteria/static/description/index.html
  sale_order_invoicing_grouping_criteria/tests/__init__.py
  sale_order_invoicing_grouping_criteria/tests/test_sale_order_invoicing_group_criteria.py
  sale_order_invoicing_grouping_criteria/views/res_config_settings_views.xml
  sale_order_invoicing_grouping_criteria/views/res_partner_views.xml
  sale_order_invoicing_grouping_criteria/views/sale_invoicing_grouping_criteria_views.xml
Labels: approved, bot is merging ⏳

#1924 [16.0][FIX] account_invoice_refund_link: Post-install test + fallback to load CoA
  account_invoice_refund_link/tests/test_invoice_refund_link.py
Labels: bot is merging ⏳

#1926 [16.0][FIX] sale_order_invoicing_grouping_criteria: Post-install test + fallback to load CoA
  sale_order_invoicing_grouping_criteria/tests/test_sale_order_invoicing_group_criteria.py
Labels: bot is merging ⏳

#1802 [15.0][FW] account_invoice_section_sale_order: multiple ports from 14.0
  account_invoice_section_sale_order/__manifest__.py
  account_invoice_section_sale_order/models/__init__.py
  account_invoice_section_sale_order/models/account_move.py
  account_invoice_section_sale_order/models/res_company.py
  account_invoice_section_sale_order/models/res_config_settings.py
  account_invoice_section_sale_order/models/res_partner.py
  account_invoice_section_sale_order/models/sale_order.py
  account_invoice_section_sale_order/readme/CONFIGURATION.rst
  account_invoice_section_sale_order/readme/CONTRIBUTORS.rst
  account_invoice_section_sale_order/readme/DESCRIPTION.rst
  account_invoice_section_sale_order/security/res_groups.xml
  account_invoice_section_sale_order/tests/test_invoice_group_by_sale_order.py
  account_invoice_section_sale_order/views/res_config_settings.xml
  account_invoice_section_sale_order/views/res_partner.xml
Labels: approved, bot is merging ⏳

#1851 [18.0][MIG] account_move_cancel_confirm: Migration to 18.0
  account_move_cancel_confirm/README.rst
  account_move_cancel_confirm/__init__.py
  account_move_cancel_confirm/__manifest__.py
  account_move_cancel_confirm/i18n/account_move_cancel_confirm.pot
  account_move_cancel_confirm/i18n/it.po
  account_move_cancel_confirm/model/__init__.py
  account_move_cancel_confirm/model/account_move.py
  account_move_cancel_confirm/model/account_payment.py
  account_move_cancel_confirm/pyproject.toml
  account_move_cancel_confirm/readme/CONTRIBUTORS.md
  account_move_cancel_confirm/readme/DESCRIPTION.md
  account_move_cancel_confirm/static/description/icon.png
  account_move_cancel_confirm/static/description/index.html
  account_move_cancel_confirm/tests/__init__.py
  account_move_cancel_confirm/tests/test_account_move_cancel_confirm.py
Labels: approved, bot is merging ⏳
