Repository OCA/account-invoicing, pull requests merged in 2025-01, with the labels that each got.

#1858 [MIG] [16.0] account_invoice_clearing
  account_invoice_clearing/README.rst
  account_invoice_clearing/__init__.py
  account_invoice_clearing/__manifest__.py
  account_invoice_clearing/i18n/account_invoice_clearing.pot
  account_invoice_clearing/i18n/es.po
  account_invoice_clearing/models/__init__.py
  account_invoice_clearing/models/account_move.py
  account_invoice_clearing/readme/CONTRIBUTORS.rst
  account_invoice_clearing/readme/CREDITS.rst
  account_invoice_clearing/readme/DESCRIPTION.rst
  account_invoice_clearing/readme/ROADMAP.rst
  account_invoice_clearing/readme/USAGE.rst
  account_invoice_clearing/security/ir.model.access.csv
  account_invoice_clearing/static/description/icon.png
  account_invoice_clearing/static/description/index.html
  account_invoice_clearing/tests/__init__.py
  account_invoice_clearing/tests/test_clearing_wizard.py
  account_invoice_clearing/views/account_move_view.xml
  account_invoice_clearing/wizards/__init__.py
  account_invoice_clearing/wizards/account_invoice_clearing_wizard.py
  account_invoice_clearing/wizards/account_invoice_clearing_wizard_views.xml
  setup/account_invoice_clearing/odoo/addons/account_invoice_clearing
  setup/account_invoice_clearing/setup.py
Labels: needs review, approved, bot is merging ⏳

#1888 [17.0][FIX] account_invoice_section_sale_order: fix tax amount in test
  account_invoice_section_sale_order/tests/test_invoice_group_by_sale_order.py
Labels: approved, bot is merging ⏳

#1886 [16.0] [MIG] account_invoice_discount_date
  account_invoice_discount_date/README.rst
  account_invoice_discount_date/__init__.py
  account_invoice_discount_date/__manifest__.py
  account_invoice_discount_date/i18n/account_invoice_discount_date.pot
  account_invoice_discount_date/i18n/es.po
  account_invoice_discount_date/models/__init__.py
  account_invoice_discount_date/models/account_move.py
  account_invoice_discount_date/readme/CONTEXT.md
  account_invoice_discount_date/readme/CONTRIBUTORS.md
  account_invoice_discount_date/readme/DESCRIPTION.md
  account_invoice_discount_date/readme/USAGE.md
  account_invoice_discount_date/static/description/icon.png
  account_invoice_discount_date/static/description/index.html
  account_invoice_discount_date/tests/__init__.py
  account_invoice_discount_date/tests/test_account_invoice_discount_date.py
  account_invoice_discount_date/views/account_move_line_view.xml
  account_invoice_discount_date/views/account_move_view.xml
  setup/account_invoice_discount_date/odoo/addons/account_invoice_discount_date
  setup/account_invoice_discount_date/setup.py
Labels: approved, bot is merging ⏳

#1838 [13.0][IMP] account_invoice_show_currency_rate: add journal item rate and consider journal item balance for credit amounts
  account_invoice_show_currency_rate/models/account_move.py
  account_invoice_show_currency_rate/tests/test_account_move.py
  account_invoice_show_currency_rate/views/account_move_view.xml
Labels: approved, ready to merge, bot is merging ⏳

#1887 [17.0][IMP]: account_invoice_section_sale_order add option to always …
  account_invoice_section_sale_order/models/res_company.py
  account_invoice_section_sale_order/models/res_config_settings.py
  account_invoice_section_sale_order/models/sale_order.py
  account_invoice_section_sale_order/views/res_config_settings.xml
Labels: approved, bot is merging ⏳

#1883 [17.0][MIG] account_manual_currency
  account_manual_currency/README.rst
  account_manual_currency/__init__.py
  account_manual_currency/__manifest__.py
  account_manual_currency/data/decimal_data.xml
  account_manual_currency/i18n/account_manual_currency.pot
  account_manual_currency/models/__init__.py
  account_manual_currency/models/account_move.py
  account_manual_currency/pyproject.toml
  account_manual_currency/readme/CONTRIBUTORS.md
  account_manual_currency/readme/DESCRIPTION.md
  account_manual_currency/readme/USAGE.md
  account_manual_currency/static/description/icon.png
  account_manual_currency/static/description/index.html
  account_manual_currency/tests/__init__.py
  account_manual_currency/tests/test_account_manual_currency.py
  account_manual_currency/views/account_move_view.xml
  account_manual_currency/wizard/__init__.py
  account_manual_currency/wizard/account_payment_register.py
  account_manual_currency/wizard/account_payment_register_views.xml
  setup/account_manual_currency/odoo/addons/account_manual_currency
  setup/account_manual_currency/setup.py
Labels: approved, bot is merging ⏳
