Repository OCA/account-invoicing, pull requests merged in 2025-05, with the labels that each got.

#1871 [17.0][FIX] account_invoice_section_sale_order: FWD port and fix test-case
  account_invoice_section_sale_order/models/sale_order.py
  account_invoice_section_sale_order/tests/__init__.py
  account_invoice_section_sale_order/tests/common.py
  account_invoice_section_sale_order/tests/test_access_rights.py
  account_invoice_section_sale_order/tests/test_invoice_group_by_sale_order.py
Labels: approved, bot is merging ⏳

#1999 [14.0][FIX] account_invoice_purchase_picking_selection: Use commercial_partner_id instead of partner_id
  account_invoice_purchase_picking_selection/views/account_move_views.xml
Labels: bot is merging ⏳

#1389 [14.0][ADD] account_invoice_google_document_ai
  account_invoice_google_document_ai/README.rst
  account_invoice_google_document_ai/__init__.py
  account_invoice_google_document_ai/__manifest__.py
  account_invoice_google_document_ai/models/__init__.py
  account_invoice_google_document_ai/models/account_move.py
  account_invoice_google_document_ai/models/account_move_google_document_ai.py
  account_invoice_google_document_ai/models/res_company.py
  account_invoice_google_document_ai/models/res_config_settings.py
  account_invoice_google_document_ai/readme/CONFIGURE.rst
  account_invoice_google_document_ai/readme/CONTRIBUTORS.rst
  account_invoice_google_document_ai/readme/DESCRIPTION.rst
  account_invoice_google_document_ai/static/description/icon.png
  account_invoice_google_document_ai/tests/__init__.py
  account_invoice_google_document_ai/tests/result.json
  account_invoice_google_document_ai/tests/test_google_document_ai.py
  account_invoice_google_document_ai/views/account_move.xml
  account_invoice_google_document_ai/views/res_config_settings.xml
  account_invoice_google_document_ai_purchase/README.rst
  account_invoice_google_document_ai_purchase/__init__.py
  account_invoice_google_document_ai_purchase/__manifest__.py
  account_invoice_google_document_ai_purchase/models/__init__.py
  account_invoice_google_document_ai_purchase/models/account_move_google_document_ai.py
  account_invoice_google_document_ai_purchase/readme/CONTRIBUTORS.rst
  account_invoice_google_document_ai_purchase/readme/DESCRIPTION.rst
  account_invoice_google_document_ai_purchase/static/description/icon.png
  account_invoice_google_document_ai_purchase/tests/__init__.py
  account_invoice_google_document_ai_purchase/tests/result.json
  account_invoice_google_document_ai_purchase/tests/test_google_document_ai.py
  requirements.txt
  setup/account_invoice_google_document_ai/odoo/addons/account_invoice_google_document_ai
  setup/account_invoice_google_document_ai/setup.py
  setup/account_invoice_google_document_ai_purchase/odoo/addons/account_invoice_google_document_ai_purchase
  setup/account_invoice_google_document_ai_purchase/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#1893 [17.0][MIG] account invoice mass sending
  account_invoice_mass_sending/README.rst
  account_invoice_mass_sending/__init__.py
  account_invoice_mass_sending/__manifest__.py
  account_invoice_mass_sending/data/queue_job.xml
  account_invoice_mass_sending/i18n/account_invoice_mass_sending.pot
  account_invoice_mass_sending/i18n/de.po
  account_invoice_mass_sending/i18n/es.po
  account_invoice_mass_sending/i18n/fr.po
  account_invoice_mass_sending/i18n/it.po
  account_invoice_mass_sending/models/__init__.py
  account_invoice_mass_sending/models/account_move.py
  account_invoice_mass_sending/pyproject.toml
  account_invoice_mass_sending/readme/CONFIGURE.md
  account_invoice_mass_sending/readme/CONTRIBUTORS.md
  account_invoice_mass_sending/readme/DESCRIPTION.md
  account_invoice_mass_sending/readme/USAGE.md
  account_invoice_mass_sending/static/description/icon.png
  account_invoice_mass_sending/static/description/index.html
  account_invoice_mass_sending/tests/__init__.py
  account_invoice_mass_sending/tests/test_account_invoice_mass_sending.py
  account_invoice_mass_sending/views/account_invoice_views.xml
  account_invoice_mass_sending/wizards/__init__.py
  account_invoice_mass_sending/wizards/account_move_send.py
  account_invoice_mass_sending/wizards/account_move_send.xml
Labels: approved, bot is merging ⏳

#2006 [REF] account_invoice_triple_discount : integrate triple.discount.mixin, previously in purchase_triple_discount module. (OCA/purchase-workflow)
  account_invoice_triple_discount/models/__init__.py
  account_invoice_triple_discount/models/account_move_line.py
  account_invoice_triple_discount/models/triple_discount_mixin.py
Labels: approved, bot is merging ⏳

#1885 [18.0][MIG] account_manual_currency
  account_manual_currency/README.rst
  account_manual_currency/__init__.py
  account_manual_currency/__manifest__.py
  account_manual_currency/data/decimal_data.xml
  account_manual_currency/i18n/account_manual_currency.pot
  account_manual_currency/models/__init__.py
  account_manual_currency/models/account_move.py
  account_manual_currency/pyproject.toml
  account_manual_currency/readme/CONTRIBUTORS.md
  account_manual_currency/readme/DESCRIPTION.md
  account_manual_currency/readme/USAGE.md
  account_manual_currency/static/description/icon.png
  account_manual_currency/static/description/index.html
  account_manual_currency/tests/__init__.py
  account_manual_currency/tests/test_account_manual_currency.py
  account_manual_currency/views/account_move_view.xml
  account_manual_currency/wizard/__init__.py
  account_manual_currency/wizard/account_payment_register.py
  account_manual_currency/wizard/account_payment_register_views.xml
Labels: approved, bot is merging ⏳

#1877 [17.0][MIG] sale_order_whole_delivered_invoiceability: Migration to version 17.0
  sale_order_whole_delivered_invoiceability/README.rst
  sale_order_whole_delivered_invoiceability/__init__.py
  sale_order_whole_delivered_invoiceability/__manifest__.py
  sale_order_whole_delivered_invoiceability/i18n/es.po
  sale_order_whole_delivered_invoiceability/i18n/sale_order_whole_delivered_invoiceability.pot
  sale_order_whole_delivered_invoiceability/models/__init__.py
  sale_order_whole_delivered_invoiceability/models/res_partner.py
  sale_order_whole_delivered_invoiceability/models/sale_order.py
  sale_order_whole_delivered_invoiceability/pyproject.toml
  sale_order_whole_delivered_invoiceability/readme/CONFIGURE.md
  sale_order_whole_delivered_invoiceability/readme/CONTRIBUTORS.md
  sale_order_whole_delivered_invoiceability/readme/DESCRIPTION.md
  sale_order_whole_delivered_invoiceability/readme/USAGE.md
  sale_order_whole_delivered_invoiceability/static/description/icon.png
  sale_order_whole_delivered_invoiceability/static/description/index.html
  sale_order_whole_delivered_invoiceability/tests/__init__.py
  sale_order_whole_delivered_invoiceability/tests/test_sale_order_whole_delivered_invoiceability.py
  sale_order_whole_delivered_invoiceability/views/res_partner_view.xml
  sale_order_whole_delivered_invoiceability/views/sale_order_view.xml
Labels: approved, ready to merge, bot is merging ⏳

#2013 [16.0][FIX]account_invoice_triple_discount: Unfilled ‘discount1’ field on the invoice
  account_invoice_triple_discount/models/triple_discount_mixin.py
Labels: approved, bot is merging ⏳
