Repository OCA/account-invoicing, pull requests merged in 2025-03, with the labels that each got.

#1248 [14.0][ADD] account_invoice_qr_code_sepa_payconiq
  account_invoice_qr_code_sepa_payconiq/README.rst
  account_invoice_qr_code_sepa_payconiq/__init__.py
  account_invoice_qr_code_sepa_payconiq/__manifest__.py
  account_invoice_qr_code_sepa_payconiq/models/__init__.py
  account_invoice_qr_code_sepa_payconiq/models/res_company.py
  account_invoice_qr_code_sepa_payconiq/models/res_config_settings.py
  account_invoice_qr_code_sepa_payconiq/models/res_partner_bank.py
  account_invoice_qr_code_sepa_payconiq/readme/CONFIGURE.rst
  account_invoice_qr_code_sepa_payconiq/readme/CONTRIBUTORS.rst
  account_invoice_qr_code_sepa_payconiq/readme/DESCRIPTION.rst
  account_invoice_qr_code_sepa_payconiq/readme/ROADMAP.rst
  account_invoice_qr_code_sepa_payconiq/readme/USAGE.rst
  account_invoice_qr_code_sepa_payconiq/static/description/icon.png
  account_invoice_qr_code_sepa_payconiq/static/description/index.html
  account_invoice_qr_code_sepa_payconiq/tests/__init__.py
  account_invoice_qr_code_sepa_payconiq/tests/test_payconiq_qr.py
  account_invoice_qr_code_sepa_payconiq/views/res_config_settings.xml
  setup/account_invoice_qr_code_sepa_payconiq/odoo/addons/account_invoice_qr_code_sepa_payconiq
  setup/account_invoice_qr_code_sepa_payconiq/setup.py
  test-requirements.txt
Labels: approved, bot is merging ⏳

#1694 [16.0][MIG] account_invoice_validation_queued
  account_invoice_validation_queued/README.rst
  account_invoice_validation_queued/__init__.py
  account_invoice_validation_queued/__manifest__.py
  account_invoice_validation_queued/data/queue_job.xml
  account_invoice_validation_queued/i18n/account_invoice_validation_queued.pot
  account_invoice_validation_queued/i18n/ca.po
  account_invoice_validation_queued/i18n/es.po
  account_invoice_validation_queued/models/__init__.py
  account_invoice_validation_queued/models/account_move.py
  account_invoice_validation_queued/readme/CONFIGURE.rst
  account_invoice_validation_queued/readme/CONTRIBUTORS.rst
  account_invoice_validation_queued/readme/DESCRIPTION.rst
  account_invoice_validation_queued/readme/USAGE.rst
  account_invoice_validation_queued/static/description/icon.png
  account_invoice_validation_queued/static/description/index.html
  account_invoice_validation_queued/tests/__init__.py
  account_invoice_validation_queued/tests/test_account_invoice_validation_queued.py
  account_invoice_validation_queued/views/account_invoice_views.xml
  account_invoice_validation_queued/views/queue_job_views.xml
  account_invoice_validation_queued/wizards/__init__.py
  account_invoice_validation_queued/wizards/validate_account_move.py
  account_invoice_validation_queued/wizards/validate_account_move_view.xml
  setup/account_invoice_validation_queued/odoo/addons/account_invoice_validation_queued
  setup/account_invoice_validation_queued/setup.py
Labels: approved, bot is merging ⏳

#1931 [18.0][MIG] stock_picking_return_refund_option: Migration to 18.0
  stock_picking_return_refund_option/README.rst
  stock_picking_return_refund_option/__init__.py
  stock_picking_return_refund_option/__manifest__.py
  stock_picking_return_refund_option/i18n/ca.po
  stock_picking_return_refund_option/i18n/es.po
  stock_picking_return_refund_option/i18n/it.po
  stock_picking_return_refund_option/i18n/stock_picking_return_refund_option.pot
  stock_picking_return_refund_option/models/__init__.py
  stock_picking_return_refund_option/models/stock_move.py
  stock_picking_return_refund_option/models/stock_picking.py
  stock_picking_return_refund_option/pyproject.toml
  stock_picking_return_refund_option/readme/CONTRIBUTORS.md
  stock_picking_return_refund_option/readme/DESCRIPTION.md
  stock_picking_return_refund_option/readme/INSTALL.md
  stock_picking_return_refund_option/readme/USAGE.md
  stock_picking_return_refund_option/static/description/icon.png
  stock_picking_return_refund_option/static/description/index.html
  stock_picking_return_refund_option/tests/__init__.py
  stock_picking_return_refund_option/tests/test_stock_picking_return_refund_options.py
  stock_picking_return_refund_option/views/stock_picking_view.xml
Labels: approved, bot is merging ⏳

#1808 [16.0][ADD] sale_credit_note_reversal: module to create reversals from sales credit notes
  sale_credit_note_reversal/README.rst
  sale_credit_note_reversal/__init__.py
  sale_credit_note_reversal/__manifest__.py
  sale_credit_note_reversal/models/__init__.py
  sale_credit_note_reversal/models/account_move.py
  sale_credit_note_reversal/readme/CONTRIBUTORS.rst
  sale_credit_note_reversal/readme/DESCRIPTION.rst
  sale_credit_note_reversal/readme/ROADMAP.rst
  sale_credit_note_reversal/static/description/icon.png
  sale_credit_note_reversal/static/description/index.html
  sale_credit_note_reversal/tests/__init__.py
  sale_credit_note_reversal/tests/test_sale_credit_note_reversal.py
  sale_credit_note_reversal/views/account_move_views.xml
  setup/sale_credit_note_reversal/odoo/addons/sale_credit_note_reversal
  setup/sale_credit_note_reversal/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#1933 [16.0][FIX] sale_order_invoicing_qty_percentage: Post-install test + fallback to load CoA
  sale_order_invoicing_qty_percentage/tests/test_sale_order_invoicing_qty_percentage.py
Labels: bot is merging ⏳

#1937 [16.0][FIX] account_invoice_pricelist + sale_timesheet_invoice_description: Post-install test + fallback to load CoA
  account_invoice_pricelist/tests/test_account_move_pricelist.py
  sale_timesheet_invoice_description/tests/test_sale_timesheet_description.py
Labels: bot is merging ⏳

#1936 [16.0][FIX] stock_account_move_reset_to_draft: Post-install test + fallback to load CoA
  stock_account_move_reset_to_draft/tests/test_stock_account_move_reset_to_draft.py
Labels: bot is merging ⏳

#1938 [16.0][FIX] account invoice triple discount report after refactoring
  account_invoice_triple_discount/report/invoice.xml
Labels: approved, bot is merging ⏳

#1898 [17.0][MIG] account_move_cancel_confirm: Migration to 17.0
  account_move_cancel_confirm/README.rst
  account_move_cancel_confirm/__init__.py
  account_move_cancel_confirm/__manifest__.py
  account_move_cancel_confirm/i18n/account_move_cancel_confirm.pot
  account_move_cancel_confirm/i18n/it.po
  account_move_cancel_confirm/model/__init__.py
  account_move_cancel_confirm/model/account_move.py
  account_move_cancel_confirm/model/account_payment.py
  account_move_cancel_confirm/pyproject.toml
  account_move_cancel_confirm/readme/CONTRIBUTORS.md
  account_move_cancel_confirm/readme/DESCRIPTION.md
  account_move_cancel_confirm/static/description/icon.png
  account_move_cancel_confirm/static/description/index.html
  account_move_cancel_confirm/tests/__init__.py
  account_move_cancel_confirm/tests/test_account_move_cancel_confirm.py
Labels: approved, ready to merge, bot is merging ⏳

#1594 [14.0][ADD] account_move_substate
  account_move_substate/README.rst
  account_move_substate/__init__.py
  account_move_substate/__manifest__.py
  account_move_substate/data/account_move_substate_data.xml
  account_move_substate/data/account_move_substate_mail_template_data.xml
  account_move_substate/demo/account_move_substate_demo.xml
  account_move_substate/models/__init__.py
  account_move_substate/models/account_move.py
  account_move_substate/readme/CONTRIBUTORS.rst
  account_move_substate/readme/DESCRIPTION.rst
  account_move_substate/readme/USAGE.rst
  account_move_substate/static/description/icon.png
  account_move_substate/static/description/index.html
  account_move_substate/tests/__init__.py
  account_move_substate/tests/test_account_move_substate.py
  account_move_substate/views/account_move_views.xml
  oca_dependencies.txt
  setup/account_move_substate/odoo/addons/account_move_substate
  setup/account_move_substate/setup.py
Labels: approved, ready to merge, bot is merging ⏳, stale

#1833 [18.0][MIG] partner_invoicing_mode: Migration to 18.0.
  partner_invoicing_mode/README.rst
  partner_invoicing_mode/__init__.py
  partner_invoicing_mode/__manifest__.py
  partner_invoicing_mode/data/ir_cron.xml
  partner_invoicing_mode/data/queue_job_data.xml
  partner_invoicing_mode/i18n/es.po
  partner_invoicing_mode/i18n/it.po
  partner_invoicing_mode/i18n/partner_invoicing_mode.pot
  partner_invoicing_mode/models/__init__.py
  partner_invoicing_mode/models/account_invoice.py
  partner_invoicing_mode/models/queue_job.py
  partner_invoicing_mode/models/res_company.py
  partner_invoicing_mode/models/res_config_settings.py
  partner_invoicing_mode/models/res_partner.py
  partner_invoicing_mode/models/sale_order.py
  partner_invoicing_mode/pyproject.toml
  partner_invoicing_mode/readme/CONTRIBUTORS.md
  partner_invoicing_mode/readme/CREDITS.md
  partner_invoicing_mode/readme/DESCRIPTION.md
  partner_invoicing_mode/readme/USAGE.md
  partner_invoicing_mode/static/description/icon.png
  partner_invoicing_mode/static/description/index.html
  partner_invoicing_mode/tests/__init__.py
  partner_invoicing_mode/tests/common.py
  partner_invoicing_mode/tests/test_invoice_mode.py
  partner_invoicing_mode/views/res_config_settings.xml
  partner_invoicing_mode/views/res_partner.xml
  partner_invoicing_mode/views/sale_order.xml
Labels: approved, ready to merge, bot is merging ⏳

#1884 [18.0][MIG] product_form_account_move_line_link
  product_form_account_move_line_link/README.rst
  product_form_account_move_line_link/__init__.py
  product_form_account_move_line_link/__manifest__.py
  product_form_account_move_line_link/i18n/es.po
  product_form_account_move_line_link/i18n/it.po
  product_form_account_move_line_link/i18n/product_form_account_move_line_link.pot
  product_form_account_move_line_link/i18n/pt_BR.po
  product_form_account_move_line_link/models/__init__.py
  product_form_account_move_line_link/models/product_product.py
  product_form_account_move_line_link/models/product_template.py
  product_form_account_move_line_link/pyproject.toml
  product_form_account_move_line_link/readme/CONTRIBUTORS.md
  product_form_account_move_line_link/readme/DESCRIPTION.md
  product_form_account_move_line_link/readme/USAGE.md
  product_form_account_move_line_link/static/description/icon.png
  product_form_account_move_line_link/static/description/index.html
  product_form_account_move_line_link/tests/__init__.py
  product_form_account_move_line_link/tests/test_product_product.py
  product_form_account_move_line_link/views/account_move_line_views.xml
  product_form_account_move_line_link/views/product_product_views.xml
  product_form_account_move_line_link/views/product_template_views.xml
Labels: approved, ready to merge, bot is merging ⏳

#1581 [16.0][MIG] sale_line_refund_to_invoice_qty_skip_anglo_saxon
  sale_line_refund_to_invoice_qty_skip_anglo_saxon/README.rst
  sale_line_refund_to_invoice_qty_skip_anglo_saxon/__init__.py
  sale_line_refund_to_invoice_qty_skip_anglo_saxon/__manifest__.py
  sale_line_refund_to_invoice_qty_skip_anglo_saxon/i18n/sale_line_refund_to_invoice_qty_skip_anglo_saxon.pot
  sale_line_refund_to_invoice_qty_skip_anglo_saxon/readme/CONTRIBUTORS.rst
  sale_line_refund_to_invoice_qty_skip_anglo_saxon/readme/DESCRIPTION.rst
  sale_line_refund_to_invoice_qty_skip_anglo_saxon/static/description/icon.png
  sale_line_refund_to_invoice_qty_skip_anglo_saxon/static/description/index.html
  sale_line_refund_to_invoice_qty_skip_anglo_saxon/tests/__init__.py
  sale_line_refund_to_invoice_qty_skip_anglo_saxon/tests/test_sale_line_refund_to_invoice_qty_skip_anglo_saxon.py
  sale_line_refund_to_invoice_qty_skip_anglo_saxon/wizard/__init__.py
  sale_line_refund_to_invoice_qty_skip_anglo_saxon/wizard/account_move_reversal.py
  sale_line_refund_to_invoice_qty_skip_anglo_saxon/wizard/account_move_reversal_view.xml
  setup/sale_line_refund_to_invoice_qty_skip_anglo_saxon/odoo/addons/sale_line_refund_to_invoice_qty_skip_anglo_saxon
  setup/sale_line_refund_to_invoice_qty_skip_anglo_saxon/setup.py
Labels: approved, bot is merging ⏳

#1447 [16.0][MIG] account_invoice_date_due: Migration to 16.0
  account_invoice_date_due/README.rst
  account_invoice_date_due/__init__.py
  account_invoice_date_due/__manifest__.py
  account_invoice_date_due/i18n/account_invoice_date_due.pot
  account_invoice_date_due/i18n/ca.po
  account_invoice_date_due/i18n/de.po
  account_invoice_date_due/i18n/es.po
  account_invoice_date_due/i18n/fr.po
  account_invoice_date_due/i18n/fr_FR.po
  account_invoice_date_due/models/__init__.py
  account_invoice_date_due/models/account_move.py
  account_invoice_date_due/readme/CONFIGURE.rst
  account_invoice_date_due/readme/CONTRIBUTORS.rst
  account_invoice_date_due/readme/DESCRIPTION.rst
  account_invoice_date_due/readme/USAGE.rst
  account_invoice_date_due/security/security.xml
  account_invoice_date_due/static/description/icon.png
  account_invoice_date_due/static/description/index.html
  account_invoice_date_due/tests/__init__.py
  account_invoice_date_due/tests/test_account_invoice_date_due.py
  account_invoice_date_due/views/account_move_date_due.xml
  setup/account_invoice_date_due/odoo/addons/account_invoice_date_due
  setup/account_invoice_date_due/setup.py
Labels: bot is merging ⏳

#1947 [16.0] [MIG] account_invoice_check_picking_date: Migration to 16.0
  account_invoice_check_picking_date/README.rst
  account_invoice_check_picking_date/__init__.py
  account_invoice_check_picking_date/__manifest__.py
  account_invoice_check_picking_date/i18n/account_invoice_check_picking_date.pot
  account_invoice_check_picking_date/i18n/es.po
  account_invoice_check_picking_date/models/__init__.py
  account_invoice_check_picking_date/models/account_move.py
  account_invoice_check_picking_date/readme/CONTRIBUTORS.rst
  account_invoice_check_picking_date/readme/DESCRIPTION.rst
  account_invoice_check_picking_date/readme/INSTALL.rst
  account_invoice_check_picking_date/readme/USAGE.rst
  account_invoice_check_picking_date/security/ir.model.access.csv
  account_invoice_check_picking_date/static/description/icon.png
  account_invoice_check_picking_date/static/description/index.html
  account_invoice_check_picking_date/tests/__init__.py
  account_invoice_check_picking_date/tests/test_account_invoice_check_picking_date.py
  account_invoice_check_picking_date/wizards/__init__.py
  account_invoice_check_picking_date/wizards/invoice_stock_picking_date_wiz.py
  account_invoice_check_picking_date/wizards/invoice_stock_picking_date_wiz.xml
  setup/account_invoice_check_picking_date/odoo/addons/account_invoice_check_picking_date
  setup/account_invoice_check_picking_date/setup.py
Labels: needs review, approved, bot is merging ⏳

#1953 [15.0][FIX] account_invoice_anglo_saxon_no_cogs_deferral: tests
  account_invoice_anglo_saxon_no_cogs_deferral/tests/test_account_invoice_anglo_saxon_no_cogs_deferral.py
Labels: approved, bot is merging ⏳

#1941 [REM] account_invoice_fiscal_position_update: Remove code from account_invoice_fiscal_position_update as is not longer required
  account_invoice_fiscal_position_update/README.rst
  account_invoice_fiscal_position_update/__init__.py
  account_invoice_fiscal_position_update/models/__init__.py
  account_invoice_fiscal_position_update/models/account_move.py
  account_invoice_fiscal_position_update/readme/DESCRIPTION.md
  account_invoice_fiscal_position_update/static/description/icon.png
  account_invoice_fiscal_position_update/static/description/index.html
  account_invoice_fiscal_position_update/tests/__init__.py
  account_invoice_fiscal_position_update/tests/test_inv_fiscal_pos_update.py
Labels: approved, bot is merging ⏳

#1949 [18.0][MIG] account_invoice_fixed_discount: Migration to 18.0
  account_invoice_fixed_discount/README.rst
  account_invoice_fixed_discount/__init__.py
  account_invoice_fixed_discount/__manifest__.py
  account_invoice_fixed_discount/i18n/account_invoice_fixed_discount.pot
  account_invoice_fixed_discount/i18n/ca.po
  account_invoice_fixed_discount/i18n/de.po
  account_invoice_fixed_discount/i18n/es.po
  account_invoice_fixed_discount/i18n/it.po
  account_invoice_fixed_discount/i18n/pt_BR.po
  account_invoice_fixed_discount/models/__init__.py
  account_invoice_fixed_discount/models/account_move_line.py
  account_invoice_fixed_discount/models/account_tax.py
  account_invoice_fixed_discount/pyproject.toml
  account_invoice_fixed_discount/readme/CONTRIBUTORS.md
  account_invoice_fixed_discount/readme/DESCRIPTION.md
  account_invoice_fixed_discount/readme/INSTALL.md
  account_invoice_fixed_discount/readme/USAGE.md
  account_invoice_fixed_discount/reports/report_account_invoice.xml
  account_invoice_fixed_discount/security/res_groups.xml
  account_invoice_fixed_discount/static/description/icon.png
  account_invoice_fixed_discount/static/description/index.html
  account_invoice_fixed_discount/tests/__init__.py
  account_invoice_fixed_discount/tests/test_account_fixed_discount.py
  account_invoice_fixed_discount/views/account_move_view.xml
Labels: approved, ready to merge, bot is merging ⏳

#1955 [17.0][MIG] account_invoice_date_due: Migration to 17.0
  account_invoice_date_due/README.rst
  account_invoice_date_due/__init__.py
  account_invoice_date_due/__manifest__.py
  account_invoice_date_due/i18n/account_invoice_date_due.pot
  account_invoice_date_due/i18n/ca.po
  account_invoice_date_due/i18n/de.po
  account_invoice_date_due/i18n/es.po
  account_invoice_date_due/i18n/fr.po
  account_invoice_date_due/i18n/fr_FR.po
  account_invoice_date_due/i18n/it.po
  account_invoice_date_due/models/__init__.py
  account_invoice_date_due/models/account_move.py
  account_invoice_date_due/pyproject.toml
  account_invoice_date_due/readme/CONFIGURE.md
  account_invoice_date_due/readme/CONTRIBUTORS.md
  account_invoice_date_due/readme/DESCRIPTION.md
  account_invoice_date_due/readme/USAGE.md
  account_invoice_date_due/security/security.xml
  account_invoice_date_due/static/description/icon.png
  account_invoice_date_due/static/description/index.html
  account_invoice_date_due/tests/__init__.py
  account_invoice_date_due/tests/test_account_invoice_date_due.py
  account_invoice_date_due/views/account_move_date_due.xml
Labels: approved, bot is merging ⏳

#1952 [15.0][OU-FIX] account_invoice_supplier_self_invoice: Fix Migration script
  account_invoice_supplier_self_invoice/migrations/15.0.1.0.1/post-migration.py
Labels: approved, ready to merge, bot is merging ⏳
